### ISSUE TITLE
Omitted file extension for part files (.xml)

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#101]
Currently, this library does not add an extension for part-files. This might have to be added.

This issue was also filed in Spark, https://issues.apache.org/jira/browse/SPARK-13766.

**Comment by jijosg** [comment]
I would like to work on this issue ,but need some guidance. I read through the issue filed in spark. Are we waiting for completion of [SPARK-8000](https://issues.apache.org/jira/browse/SPARK-8000) ?

**Comment by srowen** [comment]
I think this is about writing, not reading, so no don't think so.
