### ISSUE TITLE
Create a way to exclude rootTag when saving file

### ISSUE THREAD

**Issue by ksteffe** [databricks/spark-xml#102]
If I create an RDD with multiple slices, then I end up with a file for each slice.  Each file includes a rootTag in it, so that if I use Hadoop to merge the files I end up with a resulting file like so...

```
<animals>
  <animal>
    <name>cat</name>
  </animal>
  <animal>
    <name>dog</name>
  </animal>
</animals>
<animals>
  <animal>
    <name>fish</name>
  </animal>
  <animal>
    <name>bird</name>
  </animal>
</animals>
```

If I set the rootTag option to null I end up with:

```
<null>
  <animal>
    <name>cat</name>
  </animal>
  <animal>
    <name>dog</name>
  </animal>
</null>
<null>
  <animal>
    <name>fish</name>
  </animal>
  <animal>
    <name>bird</name>
  </animal>
</null>
```

If I could exclude the rootTag option, then I can surround the merged file in the root tag myself after all processing is complete.  This would be similar to the option in spark-csv where you can exclude the CSV header.

Ideally if the root tag and closing tag could go in their own partitioned files (at the beginning and end respectively) then I wouldn't have to perform the additional file manipulation.

Or perhaps I'm doing something wrong?

**Comment by HyukjinKwon** [comment]
Hm.. I see. Let me take a look deeper. 

For a temporary workaround, you might be able to do this `coalesce(1)` if the file is not big. If the size of the input is big, then it will degrade performance a lot but I think this might be an workaround to make the output as singlefile surrounded with single root tag.

**Comment by HyukjinKwon** [comment]
Hm.. for the reason here, https://github.com/databricks/spark-csv/pull/318#issuecomment-215065563, I think it might make senses to include those..

**Comment by HyukjinKwon** [comment]
Let me label this `won't fix` until data sources in Spark changes their behaviour.

**Comment by HyukjinKwon** [comment]
I am closing this for now because I think we should not support this for now.
