### ISSUE TITLE
Incorrect data loading when using custom schema with multiple struct fields

### ISSUE THREAD

**Issue by joostfarla** [databricks/spark-xml#113]
When defining multiple struct fields in a custom schema, the latter fields do not get loaded correctly. The following Python example can be used to reproduce the issue. Consider this XML document:

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <element>
    <struct1>
      <property>123</property>
    </struct1>
    <struct2>
      <property>345</property>
    </struct2>
  </element>
</root>
```

If I would want to load just the second struct element (`<struct2>`), I would define the following schema:

```
schema = StructType([ \
        StructField('struct2', StructType([ \
            StructField('property', StringType()) \
        ])) \
    ])

sqlContext.read \
        .format('com.databricks.spark.xml') \
        .options(rowTag='element') \
        .load(SOME_PATH, schema=schema) \
        .show()
```

This results in:

```
+-------+
|struct2|
+-------+
|   null|
+-------+
```

The value is `null`, which is not correct. When defining both struct fields (or just the first) in the schema, the data is loaded successfully:

```
schema = StructType([ \
        StructField('struct1', StructType([ \
            StructField('property', StringType()) \
        ])), \
        StructField('struct2', StructType([ \
            StructField('property', StringType()) \
        ])) \
    ])
```

Now, the result is:

```
+-------+-------+
|struct1|struct2|
+-------+-------+
|  [123]|  [345]|
+-------+-------+
```

**Comment by HyukjinKwon** [comment]
@joostfarla Thanks for your codes and data. I will try to reproduce this first.

**Comment by HyukjinKwon** [comment]
@joostfarla Hm.. for me it sounds like the support for partial schema (or filtering by this). I think if we can support https://github.com/databricks/spark-xml/issues/42, it will be able to load the XML data as above rather than directly supporting this.

**Comment by joostfarla** [comment]
@HyukjinKwon this could definitely be related! I would be happy to perform some tests on my real datasets once this is supported.

**Comment by HyukjinKwon** [comment]
Let me mark this as a duplicated (although this issue is slightly different with #42 I think they can be closed together).

I would get rid of the duplicated tag if you strongly feel it is a different issue anyway.

**Comment by HyukjinKwon** [comment]
Let me close this for now. We have #42 which will cover this issue. Please feel free to reopen or request opening if anyone feels differently.
