### ISSUE TITLE
Will it support the creating dateframe from existing RDDs?

### ISSUE THREAD

**Issue by TYoung1221** [databricks/spark-xml#114]
For example. if I have one existing rdd,
`val lines = sc.textFile("/home/spark/new.xml")`
 how can I create the dataframe based on this rdd?

**Comment by HyukjinKwon** [comment]
Yes it does. It has the [API](https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/XmlReader.scala#L96-L103) (although this should be deprecated)

For example, this will work:

```scala
new XmlReader()
      .withRowTag("book")
      .xmlRdd(sqlContext, rdd)
```

But I recently noticed there is a problem, that is, the RDD as an argument should contain each XML document for each record, meaning `sc.textFile(...)` with well-formed xml documents would not work. The RDD might have to be created as below:

```scala
val location = "path-to-file"
sc.newAPIHadoopFile(location,
        classOf[XmlInputFormat],
        classOf[LongWritable],
        classOf[Text]).map(pair => new String(pair._2.getBytes, 0, pair._2.getLength))
```

**Comment by HyukjinKwon** [comment]
I am going to close this. Please feel free to reopen if you think it is not solved.

**Comment by TYoung1221** [comment]
Sorry for the late reply. Sure, thanks!

**Comment by MaciejGajewski** [comment]
Hi ,

I'm using python 3.5.2 and spark 1.6.2 and getting
AttributeError: 'SQLContext' object has no attribute '_get_object_id'
when trying to call 
XmlReader().withRowTag("CstmrCdtTrfInitn").xmlRdd(context, rdd) function.

Is it the too old version of spark issue. Appreciate your help

Thanks
Maciej
