### ISSUE TITLE
Improve performance of XML schema inference's compatibleType method

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#115]
This issue is similar with [SPARK-14972](https://issues.apache.org/jira/browse/SPARK-14972).

According to the PR description, it looks this fix brings a high performance improvement ("a 2x-4x speedup").

Since XML data source resembles merging types at JSON data source for type inference, this patch can be similarly applied to this library as well.

**Comment by BioQwer** [comment]
really needed optimisation

delete treeagregate
https://github.com/apache/spark/pull/12750
