### ISSUE TITLE
Register your spark package

### ISSUE THREAD

**Issue by MasseGuillaume** [databricks/spark-xml#116]
You have a dependency on Apache Spark. You can register your package at 
http://spark-packages.org/register.
It's "[a] community index of packages for Apache Spark."

**Comment by HyukjinKwon** [comment]
My original repository of this was registered in http://spark-packages.org/package/HyukjinKwon/spark-xml but it seems I can't upload this one. I see one of the requirements for a Spark package

>Its content must be hosted by GitHub in a public repo **under the owner's account.**

I am not the owner of this package but a collaborator. 

cc @rxin

**Comment by BioQwer** [comment]
@HyukjinKwon  maybe close this
