### ISSUE TITLE
No value in nested struct causes arrayIndexOutOfBounds

### ISSUE THREAD

**Issue by lokm01** [databricks/spark-xml#117]
Hi,

I found a problem (not sure if this is more related to spark-xml or spark itself), but I was able to fix it with small change in the code of spark-xml.

The issue is with nested structs, namely when one of them is missing.

We have large XML documents similar to:
```xml
<?xml version="1.0" ?>
<root>
	<item>
		<a>a</a>
		<b>
			<c>c</c>
			<d>0.4</d>
			<es>
				<e>
					<ee>1</ee>
				</e>
				<e>
					<ee>2</ee>
					<eee>3</eee>
				</e>
			</es>
		</b>
		<f>f</f>
	</item>
		<item>
		<a>a</a>
		<b>
			<c>c</c>
			<d>0.4</d>
			<es></es>
		</b>
		<f>f</f>
	</item>
</root>
```
As you can see, the `<es>` element in the second record is null.

When doing any action on the dataframe, I get ArrayOutOfBoundsException.

    val df = sqlc.read
      .format("com.databricks.spark.xml")
      .option("rowTag", "item")
      .load("sample.xml")
    df.write.parquet("testout")  

Will produce:

> 16/04/29 12:22:49 ERROR DefaultWriterContainer: Aborting task.
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.genericGet(rows.scala:226)
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getAs(rows.scala:34)
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.isNullAt(rows.scala:35)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.isNullAt(rows.scala:220)

From the stack trace, you see that the parquet writer is calling isNull on a non-existing item in the Row. I guess it assumes from schema that the Row is non-empty.
Spark-xml however produces an empty row in such a case.

I was able to fix this by building spark-xml locally and changing the StaxXmlParser.scala, namely the  convertRow function so that it checks whether the Row is empty and return null in such a case:

    val res = Row.fromSeq(row)
    if(res.size == 0) null else res

Would it be possible to fix this in the next release? It is kind of a blocker for us at the moment.

Thanks!

**Comment by lokm01** [comment]
Forgot to mention that the exception is thrown in Spark 1.5.2. 1.6.1 seems to fix the issue when writing, but selects on the nested structures still fail

**Comment by HyukjinKwon** [comment]
@lokm01 This one is merged. Do you mind closing this?

**Comment by HyukjinKwon** [comment]
I am closing this. Feel free to reopen if this is still happening!
