### ISSUE TITLE
Save as string Dataframe or RDD

### ISSUE THREAD

**Issue by paritosh-gupta** [databricks/spark-xml#127]
Is it possible to write xml as string rows to a dataframe-column or rdd?
I have some legacy python elementree parsing implementation that would require a some effort to convert to a spark implementation. I was hoping to write out dataframe rows  as xml string into a new column and then map it with my existing python code.

**Comment by paritosh-gupta** [comment]
Hey so I tried to do this by modifying the scala code however If I compile from source I get the error shown below. For some reason it is unable to find the load function. I stashed my changes and did a build from master and latest release commit version too same error. Any ideas?
```
py4j.protocol.Py4JJavaError: An error occurred while calling o29.load.
: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
        at com.databricks.spark.xml.XmlOptions.<init>(XmlOptions.scala:26)
        at com.databricks.spark.xml.XmlOptions$.apply(XmlOptions.scala:48)
        at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:58)
        at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:44)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by davidtambjss** [comment]
Hello I am also looking for a way to do something similar.  Basically what I need is a mapper function that takes in a Row object in spark dataframe and convert each Row into xml string.

If you can point me in the right direction I am happy to make the change.  I think it just need some conversion / adaptation to [StaxXmlGenerator.scala](https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala) ?

**Comment by Bertrandbenj** [comment]
I think [package.scala ](https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/package.scala)shows how it happens : 

val xmlRDD = dataFrame.rdd.mapPartitions .... 

Im not sure how it all get invoked but there is a lot of things in that class that I need to change/override.
that is where it creates

- IndentingXMLStreamWriter which is cool but not always necessary 
- It sets the start and end tag which I need to remove 
- It invokes the saveAsTextFile which I believe is what you want to replace and just return the RDD itself or the string representation of it (I personally believe its better to keep it as RDD than a string you need to parse later on) 
- Im also a little curious on how I can feed a string to it from the driver and convert that into RDD cause I don't want to use the file system as intermediate.

**Comment by davidtambjss** [comment]
Thanks @Bertrandbenj yes this is exactly what I need.  Although after more thoughts I am not sure how I can reuse this.
And yes I agree ultimately it will be kept as RDD of String, however in my case what I really need is RDD[key, xml] where key is a column (or string from function on columns).

Thanks again - I will see what I can do next.

**Comment by Bertrandbenj** [comment]
df.toJavaRDD().map(r -> RowFactory.create("SomeKeyString", XMLdataFrame))

**Comment by HyukjinKwon** [comment]
@Bertrandbenj Meanwhile, I think both points below are worth being considered to handle within this library.

> - IndentingXMLStreamWriter which is cool but not always necessary
> - It sets the start and end tag which I need to remove

**Comment by davidtambjss** [comment]
Thanks @HyukjinKwon @Bertrandbenj 
I actually thought that I have got something working (it runs perfectly in my unit test) but the horror came when I tried to compile:
`com.sun.xml.internal.txw2.output.IndentingXMLStreamWriter`
Is giving me loads of grief, as it doesnt compile and gives me:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project persist: Compilation failure: Compilation failure:
[ERROR] mycode.java:[7,40] package com.sun.xml.internal.txw2.output does not exist
[ERROR] mycode.java:[56,17] cannot find symbol
```
Can the StaxXmlGenerator be changed to use for example:
`com.sun.xml.txw2.output.IndentingXMLStreamWriter`
that is part of jaxv-impl perhaps?

I am on java 8 and maven unfortunately...

**Comment by Bertrandbenj** [comment]
Can you share your code please, Im trying to implement my own map partition function similarly but I indeed got in a similar problem, the StaxXMLGenerator is unfortunately tuned for the IndentingXMLStreamWriter. my suggestion would be to define StaxXMLGenerator with a XMLStreamWriter which should be the higher level so that we can pass it our own StreamWriter.

Also in my case all I need is the following 
             
>    StaxXmlGenerator(
>                   rowSchema,
>                   indentingXmlWriter,
>                   options)(iter.next())
>                 writer.toString
>               }
>               writer.reset()


I dont want first row, last row, which I believe can easily be set as options: in package.scala when declaring them 
      new Iterator[String] {
          var firstRow: Boolean = true && !options.isEntireDataFrame 
          var lastRow: Boolean = true && !options.isEntireDataFrame 

or even better as the comment in the same class explain, have some code to figure out whether this is an Array or a struct as input. Which we can do since we got the schema given

**Comment by HyukjinKwon** [comment]
I was surprised that a builtin library breaks Java version compatibility without deprecation warnnings. I will take a look soon as well!

**Comment by HyukjinKwon** [comment]
I see. I run travis tests with Oracle JDK 8 but it seems passed, https://travis-ci.org/HyukjinKwon/spark-xml-1. However, it seems those library should not be used directly (assuming from this Java bug report, http://bugs.java.com/bugdatabase/view_bug.do;jsessionid=1711ee4eae3ff10565fc7a212018?bug_id=6778491). I don't understand why they are public though. 

After looking into this deeper, I will maybe try to switch this to another one compatible across all Java.

**Comment by davidtambjss** [comment]
@Bertrandbenj unfortunately I am not allowed to use scala in my current work environment.
My code is simply this (in java):

    static String toXMLMessage(Row row)  {
        final XMLOutputFactory factory = XMLOutputFactory.newInstance();
        final XmlOptions options = XmlOptions.apply(
                toScalaMap(ImmutableMap.of("rowTag", "aMessage"))
        );

        try (CharArrayWriter writer = new CharArrayWriter()) {
            try {
                IndentingXMLStreamWriter indentingXmlWriter = new IndentingXMLStreamWriter(factory.createXMLStreamWriter(writer));
                StaxXmlGenerator.apply(row.schema(), indentingXmlWriter, options, row);
                indentingXmlWriter.flush();
                indentingXmlWriter.setIndentStep("");
            } catch (XMLStreamException e) {
                throw new XYZRuntimeException("Error when flushing xml to buffer", e) {
                };
            }
            return writer.toString();
        }
    }




I think if scala is allowed in my work place I can perhaps duplicate StaxXmlGenerator and use
`com.sun.xml.txw2.output.IndentingXMLStreamWriter`
instead.

I tried 
`-XDignore.symbol.file`
but it doesn't work.

In the end I have implemented StaxXmlGenerator partially (for what I need only, StaxXmlGenerator do more) in java, which isn't to hard but it would be nice to not re-invent the wheel.

**Comment by davidtambjss** [comment]
@HyukjinKwon thank you much appreciate as I say it maybe just a matter of  changing import from:
`com.sun.xml.internal.txw2.output.IndentingXMLStreamWriter`
to
`com.sun.xml.txw2.output.IndentingXMLStreamWriter`

or even better the partial function should take in XMLStreamWriter instead (you can still pass in IndentingXMLStreamWriter which is a child of XMLStreamWriter I think).

Cheers!!

**Comment by HyukjinKwon** [comment]
@davidtambjss Actually, I originally used `com.sun.xml.txw2.output.IndentingXMLStreamWriter` but I changed this to `com.sun.xml.internal.txw2.output.IndentingXMLStreamWriter` because it was failed in some Java versions but maybe I was wrong. 

I will change this to `com.sun.xml.txw2.output.IndentingXMLStreamWriter` if I https://travis-ci.org/HyukjinKwon/spark-xml-1 gives me all passes. If not, I will switch this to an equivalent one.

Thanks again!
