### ISSUE TITLE
Bypassing rootTag and rowTag

### ISSUE THREAD

**Issue by Bertrandbenj** [databricks/spark-xml#128]
Hi, I would like to get rid of the RowTag and RootTag when writing out XML 

I'm trying to generate an XML that looks as follow : 

<myRoot withTimestamp="date">
    <MetadataA>someTextString<MetadataA>
    <MetadataB>someOtherTextString<MetadataB>
    <RowOfData attribute="huhu">
       <NestedStruct>withValue</NestedStruct>
       <AnotherNestedStruct>1234</AnotherNestedStruct>
    </RowOfData>
    <RowOfData attribute="huhu">
       <NestedStruct>withValue</NestedStruct>
       <AnotherNestedStruct>1234</AnotherNestedStruct>
    </RowOfData>
</myRoot>

problem is this package was created to serialize table originally and not hierarchical data. Yet again these two are conflicting.

In this example there is 2 different issues: first of all the attributes for rowTag and rootTag, there is no way I can set an attribute there.

Second problem is my table's top level node contains some elements (Potentially structures) that are not rows but static.

How can I possibly have the following in my XML output
    <MetadataA>someTextString<MetadataA>
    <MetadataB>someOtherTextString<MetadataB>

I think the RootTag RowTag is a problem for my use case but considering the inputs and outputs I see at my workplace I dont see a single use case where those are useful to me. if I have to output a table I certainly wont serialize to XML and if I have to write an XML its very unlikely this will be a table, at least not at the top level. 

So my question is how can I bypass rootTag and rowTag.

**Comment by HyukjinKwon** [comment]
Hi @Bertrandbenj , I agree writing XML via this library is not flexible much with `rowTag` and `rootTag`.
I think this definitely should be improved. Originally I focused on the roundtrip in writing and reading XML data.

Currently, It won't be able to just skip both. Maybe, we should think a better way to support this flexibly.

**Comment by Bertrandbenj** [comment]
The concept seems to be quite generic to hierarchical data, so maybe there is ideas to be taken from the JSON api unless it has the same issue and was also design to load flat files. 
There are two ideas : 

- To handle XML in heavily parallelized way wouldn't become effective to build an RDD like RDD<Tuple<AbsoluteXPath, valueAsTypeX>>  It's memory greedy, I know, but there may be ways to filter out unnecessary nodes, the transformations are rather straightforwards to code and we can create hooks to the DataFrameAPI while also having the freedom to play with hierarchical structures, extracting an Element is a simple filter, creating a node is appending. You have probably thought of it more than I did but let me know if you think its worth drafting something.

- I tried to look at how I could implement my own DataFrameReader, DataFrameWriter cause Im also stuck with loading and writing from file by using the SQLContext. is it possible to load an XML/CSV/JSON from an InputStream or even a string directly. Lets say one of my RDD contains a String as a row and that string is nothing else than a full encoded XML. I can decode it using Base64 but then have no other options than dropping it as file and load it again. If there is such custom implementation of DataFrameWriter/Reader could you point me to it.

- One last questions more practical this time. 

How do you nest a DataFrame into Another. 

lets say I have a DataFrame A 

+------------+---------------------------+
|    key       |  values                       |
+------------+---------------------------+
|  1234      | DataFrame B placeholder   |

DataFrame B is some XML loaded DataFrame but if I join it it create a new row in DF A for each row in DF B

**Comment by davemoyers** [comment]
I would also like to provide a comment that knowing the rootTag and rowTag up front is not very practical. In an application that must handle several types of XML content, it would require a significant amount of up-front effort to pre-parse the data and then organize it so that a Spark job can be generalized to handle different formats. If that much effort is required, then it may be better, in many situations, just to perform an XML to JSON conversion, then create the DataFrame based upon the JSON data. For that reason, I would urge finding a way to avoid the use of rowTag and rootTag as being mandatory.

**Comment by HyukjinKwon** [comment]
It seems related with https://github.com/databricks/spark-xml/issues/127#issuecomment-225759676. Maybe we need some options to disable the tags and `IndentingXMLStreamWriter`.

**Comment by HyukjinKwon** [comment]
I took a look for this and seems not quite easy to support this since we're not going to support read it back. Let's don't fix it.
