### ISSUE TITLE
Reading all dataframes from each rowTag at once.

### ISSUE THREAD

**Issue by bigdataamdi** [databricks/spark-xml#131]
Hi,

I am currently loading multiple dataframes by reading different rowTags from a single Xml file which is very small. Is there a way to load data from all rowTags into a single dataframe at once and take it from there?

Thanks!

**Comment by HyukjinKwon** [comment]
Hm.. I think it might be possible as below although I haven't tested this yet:

```scala
import com.databricks.spark.xml.XmlReader

val path = "path-to-files"
val rdd = sc.wholeTextFiles(path)
val df = new XmlReader().xmlRdd(sqlContext, rdd)
df.show()
```

Maybe I will update this on this weekend after testing this.

**Comment by HyukjinKwon** [comment]
I am closing this for now. Please feel free to reopen if you still face this issue.
