### ISSUE TITLE
woodstox conflict 

### ISSUE THREAD

**Issue by Bertrandbenj** [databricks/spark-xml#132]
I'm tempted to say this library wears its name accurately :-) after hours of debugging why my XMLs output ended truncated (if any content at all), I figured [this library](https://mvnrepository.com/artifact/org.codehaus.woodstox/woodstox-core-asl/4.4.1) specifically the 4.4 version was screwing my build. I'm using ivy, Spark 1.5.2 / 1.6.1 (pre build including hadoop 2.6)  and of course spark-xml 0.3.3.

I'm not sure where, not sure how but I thought its worth documenting that.

**Comment by HyukjinKwon** [comment]
Thanks for opening this! I will take a look soon!

**Comment by srowen** [comment]
This may be a stale issue. However this issue tracks a different issue with woodstox 5.0.2 and Hadoop 2.9: https://github.com/databricks/spark-xml/issues/338
