### ISSUE TITLE
How to use the library with Spark Streaming?

### ISSUE THREAD

**Issue by wpoosanguansit** [databricks/spark-xml#135]
Hi,

Is there an example of using the library with Spark Streaming?  I am new to both Spark and the library.  Any pointer is appreciated.  Thanks.

**Comment by HyukjinKwon** [comment]
This library has not been tested against 2.0 yet and I guess this should implement `FileFormat` in 2.0 anyway. I will let you know if I start to work on this.

**Comment by wpoosanguansit** [comment]
Thanks for your help.

**Comment by HyukjinKwon** [comment]
Let me just mark this as duplicated and I will summarize related updates in https://github.com/databricks/spark-xml/issues/137.

**Comment by HyukjinKwon** [comment]
I will retarget this for 0.5.0.

**Comment by paulcarey** [comment]
I might have some time to work on this if you're interested, and could outline how you think it should be done?

**Comment by wpoosanguansit** [comment]
Thank you for your help.  However, we have long moved on to other works and not using Spark at all at the moment.  Thanks again.

**Comment by HyukjinKwon** [comment]
Yeap, but we should fix this for other users :). Good to know someone is interested in this. Will try to give you some outlines here at my best soon.

**Comment by HyukjinKwon** [comment]
Hi @paulcarey, we should extend `org.apache.spark.sql.execution.datasources.FileFormat` instead of [`PrunedScan`](http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.sources.PrunedScan) or [`TableScan`](http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.sources.TableScan) in the current implementation.

Please take a look at CSV/JSON datasource implementation. We could implement this similarly with them (in https://github.com/apache/spark/tree/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources)

**Comment by shiv2994** [comment]
Hi @HyukjinKwon.
Is the latest version of the library compatible with file-streaming? I am trying to stream XML files from a kafka/local source ( depending on the requirement/availability ) for analysis, and DataFrames seem like the best option for that. However, I am unable to convert the Dstream genertaed from the streamed XML files into a DataFrame.
Thanks.

**Comment by nkarpovdb** [comment]
@shiv2994 

In case anyone ends up here, this works :) YMMV

```
inputStream.writeStream.foreachBatch { (batchDF: DataFrame, batchId: Long) =>
    
    var parameters = collection.mutable.Map.empty[String, String]
    var schema: StructType = null
  
    val rdd:RDD[String] = batchDF.as[String].rdd
  
    val relation = XmlRelation(
      () => rdd,
      None,
      parameters.toMap,
      schema)(spark.sqlContext)
  
    spark.baseRelationToDataFrame(relation)
      .write.format("delta")
      .mode("append")
      .saveAsTable("default.catalog_sink")
  
}.start()
```
