### ISSUE TITLE
valueTag and attributePrefix not honored when specifying a Schema

### ISSUE THREAD

**Issue by slowenthal** [databricks/spark-xml#136]
If I specify valueTag, attributePrefix, and a schema, the attributePrefix and valueTag are ignored.  This make it very difficult to use with the DataSets API as I can't create case classes with field names such as @id.

Let me know if there is a way to easily use DataSets with the XML parser.

**Comment by HyukjinKwon** [comment]
I will try this on this weekend and fix this if it is a problem. Thanks for reporting this. Do you mind sharing some codes and your sample data maybe?  I would like to reproduce.

**Comment by slowenthal** [comment]
Probably my fault - didn't fix the @ sign in the schema

**Comment by HyukjinKwon** [comment]
Thanks for having interests in this :).
