### ISSUE TITLE
auto-detect new files

### ISSUE THREAD

**Issue by hghina0** [databricks/spark-xml#138]
Hello,

Can this library auto-detect new xml files on HDFS and provide DStream out of it? Similar to  `streamingContext.textFileStream("hdfs:///tempDir")`

Thanks

**Comment by HyukjinKwon** [comment]
I guess this is related with https://github.com/databricks/spark-xml/issues/137 and https://github.com/databricks/spark-xml/issues/135. I will check this out soon.

**Comment by HyukjinKwon** [comment]
Let me just mark this as duplicated and I will summarize related updates in https://github.com/databricks/spark-xml/issues/137.

**Comment by HyukjinKwon** [comment]
I will retarget this for 0.5.0.
