### ISSUE TITLE
Disable scientific notation 

### ISSUE THREAD

**Issue by amitdubey766** [databricks/spark-xml#139]
Hi,
If tag contains integer value with spaces , it is converted to scientific notation in dataframe . 
for eg :  <V1>42451267 </V1>   is converted to 4.2451267E7

Is there any way to disable scientific notation or any workaround ?
for more information you follow this link
http://stackoverflow.com/questions/38196739/how-to-disable-scientific-notation-in-spark-dataframe

**Comment by HyukjinKwon** [comment]
It seems your data was loaded as double. How about setting a schema explicitly if your data structure is not super complicated? It would be not really good in production to use schema inference anyway.

**Comment by HyukjinKwon** [comment]
https://github.com/databricks/spark-xml/issues/223#issuecomment-269300526 here I wrote some workrounds. I will close this for now because it seems #223 covers this issue.

**Comment by HyukjinKwon** [comment]
Please feel free to reopen if you think we should leave this open.
