### ISSUE TITLE
How to parse a dataframe containing xml strings?

### ISSUE THREAD

**Issue by parix** [databricks/spark-xml#140]
Hi,

I have a dataframe here:

```
+------+--------------------+
|  id  |               xml  |
+------+--------------------+
| 6723 |<?xml version="1....|
| 6741 |<?xml version="1....|
| 6774 |<?xml version="1....|
| 6735 |<?xml version="1....|
| 6828 |<?xml version="1....|
| 6764 |<?xml version="1....|
| 6732 |<?xml version="1....|
| 6792 |<?xml version="1....|
| 6754 |<?xml version="1....|
| 6833 |<?xml version="1....|
+------+--------------------+
```

Is it possible to parse the xml string inside this dataframe using spark xml?

Thanks!

**Comment by HyukjinKwon** [comment]
Hm.. I think you might better just use normal XML parser  for each row since it seems your data is already loaded into data frame.

**Comment by skamkar** [comment]
So to be clear, is it possible to use spark-xml to parse dataframes (or rdds) in memory, or is it just not recommended? There is some key functionality that spark-xml provides over normal XML python parsers (like xmltodict), so I'd like to use it if possible.

Thanks!

**Comment by HyukjinKwon** [comment]
Yes, we can create another dataframe from rdd here, https://github.com/databricks/spark-xml/issues/114#issuecomment-215301575

I would like to make this similar with Spark's existing APIs. For example, without `XmlReader` but `spark.read.xml(rdd)` if possible.

**Comment by ayseyo** [comment]
Hi @HyukjinKwon :)
Firstly I'm really glad that you've suggested spark.read.xml(rdd) above, it would be awesome. 

at #114 you have mentioned that XMLReader.scala will be deprecated. Is this still on the table? Will this api be deprecated soon?

Actually I need to analyse a json file which might include xml as json attributes. Since I don't want to save this attribute as intermediate xml files, I guess I need to create dataframe from RDD[String]. 
So do you recommend below usage? 

this is a dummy example of json - daily.log:
{
	"dest_content": "<?xml version=\"1.0\"?><soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope/\" soap:encodingStyle=\"http://www.w3.org/2003/05/soap-encoding\"><soap:Body><m:GetPriceResponse xmlns:m=\"http://www.w3schools.com/prices\"><m:Price>1.90</m:Price></m:GetPriceResponse></soap:Body></soap:Envelope>",
	"text": "Adventures With Coffee, Code, and Writing.",
}

this is my Java code : 

        DataFrame sampleFile = sqlContext.jsonFile("daily.log");
        sampleFile.registerTempTable("sampleTable");
        DataFrame destinationDF = sqlContext.sql("SELECT dest_content FROM sampleTable");

        JavaRDD<String> destinationXMLRDD = destinationDF.toJavaRDD().map(new Function<Row, String>() { public String call(Row row) {
            return row.getString(0); }});

        **DataFrame dataFrame = (new XmlReader()).xmlRdd(sqlContext, destinationXMLRDD.rdd());**
        DataFrame encod = dataFrame.select("@encodingStyle");

**Comment by syepes** [comment]
Hope we get a final solution to this one.

**Comment by bhagya-gj** [comment]
I have a similar requirement, where i need to get the xml fromt he input file , and parse certain fields in the input file and need to load them into a table . can we use explode on a dataframe to parse the xml loaded into a dataframe

**Comment by nicku123** [comment]
i also have same issues, i am reading a hive table where one of the column contains a XML string. When i read it to a dataframe it is as the hive table . I wanted to parse this XML ?
Any suggestions?

**Comment by srowen** [comment]
I suppose you can strip the XML header from each row, add a first and last row with enclosing top level tag, then write the whole thing as text and read it back with spark-xml. I think it's easier probably to parse well-formed XML with native tools; not sure what's in Python but the JVM side has very good XML parsing.

If I'm not mistaken XmlReader.xmlRdd is an option too. That part isn't deprecated right now.

**Comment by AmolKakade** [comment]
Hi Team, I have same scenario and I want to use withRowTag() as well on one element from xml column but not able to do so.
Lets say in above xml column, we have 'people' element which I want to use in withRowTag("people"), so output of this is dataframe should only contain elements under 'people', but not from entire xml.

**Comment by anisbehlim** [comment]
@nicku123 Did you find the solution ?

**Comment by uradhakrishna** [comment]
@parix : How did you finally concluded , many people are looking for the resolutions.

Appreciate your response.

**Comment by srowen** [comment]
This is all covered in comments above. This isn't a use case for spark-xml; just read the rows as text and apply an XML parser to each. You can also use spark-xml if you strip the XML header from each row first. This is about two lines of code.
