### ISSUE TITLE
Dataframe is null when parent and child tag names are same

### ISSUE THREAD

**Issue by AshwaniGaur** [databricks/spark-xml#148]
Following valid XML returns a null Dataframe:
&lt;Parent&gt;
  &lt;Child&gt;&lt;/Child&gt;
  &lt;Parent&gt;&lt;/Parent&gt;
&lt;/Parent&gt;

when row-tag is given as &lt;Parent&gt;

**Comment by HyukjinKwon** [comment]
Yea, this is an issue. Thanks!

**Comment by HyukjinKwon** [comment]
This is fixed in #161
