### ISSUE TITLE
Spark 2.0 - databricks xml 2.11:0.3.3 not working

### ISSUE THREAD

**Issue by Esteban-De-la-Sexface** [databricks/spark-xml#154]
Hello, 

I have spark 2.0 running, built with scala 2.11.8. It seems this is not compatible with any version of the spark-xml library. 

I keep getting NotImplemented errors for Decimal type? any idea if this is or should be supported?

**Comment by HyukjinKwon** [comment]
Yup, I just submitted a PR here, https://github.com/databricks/spark-xml/pull/150 
I will release 0.4.0 as soon as possible.

BTW, please let me mark this as a duplicated with https://github.com/databricks/spark-xml/issues/137 so that I can manage them all together!

**Comment by Esteban-De-la-Sexface** [comment]
Thanks @HyukjinKwon,
