### ISSUE TITLE
PrintSchema is not generating XML Schema 

### ISSUE THREAD

**Issue by anayyar82** [databricks/spark-xml#158]
I am loading XML file but that xml file having some space and \n character in between , when i 
 df.printSchema()  :::  print the schema it's not printing any thing. 

Can you please help for this type of xml how to pass. when i using library and giving rowtag "ns:test1 " it just showing the xml like 

WARN InferSchema$: Dropping malformed row: <ns:test1>	<ns:test11 Target=\"Cert\">	</ns:test11>\n	<ns:test2 Target=\"Prod\">	</ns:test2></ns:test1>

root

XML Example :  

{"outer":{"string":"webservice}, "body":"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n 
  <ns:test1>
        <ns:test11 Target=\"Cert\">
        </ns:test11>\n
        <ns:test2 Target=\"Prod\">
        </ns:test2>
</ns:test1>
}

**Comment by HyukjinKwon** [comment]
Thanks for pointing this out. I will take a look on this weekend!

**Comment by anayyar82** [comment]
Proper XML for your testing : 


`{"outer":{"string":"GMVHOS"}, "body":"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n
  <ns:test1>
        <ns:test11 Target=\"Cert\">
        </ns:test11>\n
        <ns:test2 Target=\"Prod\">
        </ns:test2>
</ns:test1>
}`

**Comment by HyukjinKwon** [comment]
Hm.. I see it seems it is not a XML standard format due to escaping `"` with `\`.
