### ISSUE TITLE
Reading XML data from Avro table

### ISSUE THREAD

**Issue by anayyar82** [databricks/spark-xml#162]
Is there any way we can read a string column as xml input. 

We have load method which takes path as string, is there any way i can give string in load path.

**Comment by HyukjinKwon** [comment]
Myabe I think you can do this as below:

```scala
val rdd: RDD[String] = results.rdd.map(r => r.toSeq.head.toString)
val dataFrame = new XmlReader()
  .withRowTag("...")
  .xmlRdd(sqlContext, rdd)
```

**Comment by HyukjinKwon** [comment]
Do you mind if I close this @anayyar82 ?
