### ISSUE TITLE
I love the great work and effort put in... thanks! But the solution is sooo unfriendly in terms of practical implemantation

### ISSUE THREAD

**Issue by rajabhathor** [databricks/spark-xml#163]

**Comment by HyukjinKwon** [comment]
Could you close this and be more specific for the issues you faced? I can't resolve this issue because I can't reproduce anything and even I can't guess what's so unfriendly.

**Comment by HyukjinKwon** [comment]
Can you fill up the description of this issue so that we can know what's so unfriendly? Is there a suggestion for that? Also  could you please fix the title to be more specific?

**Comment by HyukjinKwon** [comment]
I am closing this. Please open another issue.

**Comment by rajabhathor** [comment]
Thanks for the response.
I hope I can help make this evolving area more popular for wider use by the developer community
