### ISSUE TITLE
Perhaps spark-xml should ignore prefixes?

### ISSUE THREAD

**Issue by mattroberts297** [databricks/spark-xml#168]
Given a schema like this:

``` xml
<?xml version="1.0"?>
<xs:schema xmlns="urn:xsd:people" targetNamespace="urn:xsd:people" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="People" type="People"/>
    <xs:complexType name="People">
        <xs:sequence>
            <xs:element name="Person" type="Person" minOccurs="1" maxOccurs="10000"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Person">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Age" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
```

Then all of the following are valid instances:

``` xml
<People xmlns="urn:xsd:people" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:xsd:people People.xsd">
  <Person><Name>Alice</Name> <Age>20</Age> </Person>
  <Person><Name>Bob</Name><Age>30</Age></Person>
  <Person><Name>Charlie</Name><Age>40</Age></Person>
</People>
```

``` xml
<a:People xmlns:a="urn:xsd:people" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:xsd:people People.xsd">
  <a:Person><a:Name>Alice</a:Name><a:Age>20</a:Age></a:Person>
  <a:Person><a:Name>Bob</a:Name><a:Age>30</a:Age></a:Person>
  <a:Person><a:Name>Charlie</a:Name><a:Age>40</a:Age></a:Person>
</a:People>
```

``` xml
<b:People xmlns:b="urn:xsd:people" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:xsd:people People.xsd">
  <b:Person><b:Name>Alice</b:Name><b:Age>20</b:Age></b:Person>
  <b:Person><b:Name>Bob</b:Name><b:Age>20</b:Age></b:Person>
  <b:Person><b:Name>Charlie</b:Name><b:Age>20</b:Age></b:Person>
</b:People>
```

At the moment, each xml file would have to be read with a different configuration. Unfortunately, according to the xml specification the prefix is user-defined and can be redefined at any element. For these reasons, client code would have to read the entire file and determine all prefixes ahead of time before configuring spark-xml (perhaps multiple times). Given that spark-xml does not support namespaces, and never can without performance implications by virtue of the xml specification, then perhaps it should ignore the prefix?

For example, given a start element `<Person>` then `<Person>`, `<a:Person>`, `<b:Person>`, `<foo:Person>` etc. would all match.

**Comment by HyukjinKwon** [comment]
I see. I think this is a reasonable suggestion. Maybe we can add an option to deal with this. Thanks for your kind and detailed explanation.

**Comment by mattroberts297** [comment]
Ah yes adding an option is a very good idea. Then we don't break previous behaviour.

**Comment by HyukjinKwon** [comment]
Hm, I guess https://github.com/databricks/spark-xml/issues/74 is related. I will leave this command as a reminder.

**Comment by anayyar82** [comment]
If we add below logic,  i feel can resolve the problem.

import scala.xml._
val a = <a xmlns:ns1="www.ns1"><b/><b/><b/><ns1:b/></a>

A standard query would return simply all b elements:

a \ "b"
res0: scala.xml.NodeSeq = NodeSeq(<b xmlns:ns1="www.ns1"/>, <b xmlns:ns1="www.ns1"/>, <b xmlns:ns1="www.ns1"/>, <ns1:b xmlns:ns1="www.ns1"/>)

To query for the specific namespace, two options are possible. The first option:

a \ "b" filter (e => e.namespace == "www.ns1")

**Comment by VladAntropov** [comment]
I have this very specific issue now - every new file can arrive with a different namespace prefix. Ignoring the prefix would solve the problem for me, but in general the row tag may be appear in different namespaces only one of which defines a record. Then this approach will lead to an error. What about using an XML parser to find records? It could be given an XPath expression with namespace URI and thus remove the dependency on a prefix.

**Comment by NoOrdInaryGuy** [comment]
I've been thinking about this, and realise ignoring the prefix may not be as straightforward as it seems.

Despite the fact the [W3C XML Recommendation ](https://www.w3.org/TR/2008/REC-xml-20081126/#sec-common-syn) states that the colon character should not be used except for namespace purposes, column _is_ still an allowed character for element names in the XML spec.

I think this means you still need knowledge of which namespaces have been registered further up in the hierarchy for each record, in order to be able to correctly ignore namespaces. Otherwise you will introduce a tiny edge case in documents which have colon being used as an element name character. Of course, it's a pretty weird thing to do - this edge case could be deemed acceptable and dealt with by documentation.

**Comment by anayyar82** [comment]
Do we have any updates with Name space, or should we use custom XPATH expression. 

Please suggest.

**Comment by janbhanijai** [comment]
Hi, is this issue fixed?

**Comment by impandey** [comment]
Placing back tick is a may be a temporary solution 
suppose we read a xml through spark-xml api and got  element/column <ns0:Item> in dataframe then use column name as  `ns0:Item`
for example spark.sql("select `ns0:Item` from table")

**Comment by anujwalia** [comment]
Hi, Is this issue resolved ? using Java

**Comment by srowen** [comment]
I'm not sure it's an issue. The same tag names with different prefixes are different elements, and it seems correct to treat them as such. You can freely rename the resulting columns in Spark.

**Comment by anujwalia** [comment]
yes, but there could be a scenario where there are thousands of xmls being published from 100 different publisher systems, each having a different namespace alias. Having said that, they are all same xml's with root or child tag

**Comment by anujwalia** [comment]
> I'm not sure it's an issue. The same tag names with different prefixes are different elements, and it seems correct to treat them as such. You can freely rename the resulting columns in Spark.

yes, but there could be a scenario where there are thousands of xmls being published from 100 different publisher systems, each having a different namespace alias. Having said that, they are all same xml's with root or child tag

**Comment by tolomaus** [comment]
I'm having the same issue. 

I process large xml files with hundreds of fields. the prefix is usually the same but in a small percentage of the cases many different prefixes are used. My fallback solution is currently to use regexes to replace (most of) the unsupported namespaces in those xml files that were rejected by the initial spark run and process them in a second spark run.

Having an ability to ignore the namespaces would be highly appreciated.

**Comment by srowen** [comment]
Got it - "same" field just under different namespaces. What you could do now is just rename the columns, dropping the "_namespace_:" prefix if it exists

**Comment by tolomaus** [comment]
Thanks for the suggestion

I forgot to mention though that I apply a predefined schema to the spark read process that only knows about the fields with the main prefix. In principle I could duplicate the fields in the schema for each possible prefix and rename the columns in spark but - if I remember well - having a much larger predefined schema would incur a performance hit and secondly since the fields are hierarchic/nested renaming them may not be trivial. Therefore I currently do the renaming step with a simple regex outside of spark and xml

**Comment by srowen** [comment]
I get it, OK this seems like a reasonable option. Are you in a position to work on a PR? I can probably look at it too, just may take a bit to get to.

**Comment by tolomaus** [comment]
Yes I should free up some time for it. If you have any advice as to where to relevant code is and what edge cases etc to keep in mind feel free to let me know

**Comment by srowen** [comment]
In the course of figuring out where to point you, I just investigated. So, one weird thing is, the code already ignores namespaces! But, the XML parser is set to ignore namespaces too. So it puts any namespace prefixes into the element name as if they're part of the name and not namespace. Hence the current behavior.

One quick fix is simply to make the XML parser namespace-aware. That makes it work as you intend, I believe. (Ironic: making it namespace aware enables the code to ignore the namespaces.)

There's a catch though, when made namespace-aware, the parser will demand to know the namespace declarations in any XML fragment it sees. So you'd have to re-declare the namespace on every row tag, or somewhere within it. I don't think that matches anyone's use case here?

If not, then, I fall back to having the code manually ignore namespaces, which, again ironically means leaving the XML parser as namespace-unaware and then trying to snip them out in the code. This may be a better solution anyway - not much code and preserves current behavior.

**Comment by tolomaus** [comment]
Hi Sean, good to see the code is already mostly there!

Indeed, in my own use case the namespaces are only declared at the top level of the xml document, they are not declared within the row tags. (Btw even my row tag has a namespace that can hopefully be ignored). 

So I agree with your fallback solution: ignoring namespaces then simply means that 1) we don't have to declare the possible namespaces anywhere and 2) the namespaces are stripped from the field names before matching them to the predefined schema.

Many thanks!

**Comment by srowen** [comment]
(Anyone,) Let me know if the change in #501 seems to work for you, if you can build and test it.

**Comment by tolomaus** [comment]
Cool I will test it, probably somewhere this weekend

**Comment by tolomaus** [comment]
Hi Sean,

I tested #501 on my project and it works as expected on first sight. I noticed that I had quite some logic to work around this namespace issue so I will happily remove these lines as soon as the fix is released :-)

Two issues I noticed: you already mention in the docs that the rowTag is not supported, and since my rowTag has a namespace I will have to keep some of the pre-spark regex replacement logic. Secondly attribute namespaces are not yet stripped either.

**Comment by srowen** [comment]
Good point, I added support for handling attribute namespaces too.
Yeah, handling the rowTag is harder unfortunately. That part of the code is buried in the Hadoop InputFormat where it's scanning text pretty manually to pick out XML to even parse with a parser. It's _possible_ I'm sure, just complicated. I might at least merge this much for now.

**Comment by tolomaus** [comment]
Agreed, the current solution (without support for the rowTag) should cover most of the needs so it makes sense to release a new version already.

Many thanks to get this implemented!

**Comment by anujwalia** [comment]
@srowen Thanks for the implementation. Are we also releasing this version to Maven Central repo ?

**Comment by srowen** [comment]
Yes I think there are enough small changes to justify a new release this week.

**Comment by srowen** [comment]
I just put out 0.11.0 with this change. https://github.com/databricks/spark-xml/releases/tag/v0.11.0
Should show up in Maven shortly.

**Comment by anujwalia** [comment]
Thanks @srowen

**Comment by tolomaus** [comment]
Many thanks @srowen ! I upgraded my code base to 0.11.0 and all seems to work as expected. A huge simplification of my code base and hopefully a improvement in speed as well since the schema is only half the size now.
