### ISSUE TITLE
XmlInputFormat produces duplicate rows in large files

### ISSUE THREAD

**Issue by lokm01** [databricks/spark-xml#171]
There's a bug in the XmlInputFormat which causes duplicate rows to be produced when the input file spans over more input splits (for plain text and splittable compression format) in cases, where there is no whitespace between closing and opening row tags.

How to reproduce:
1) Use large XML file (e.g the protein file from http://www.cs.washington.edu/research/xmldatasets/www/repository.html#pir )
2) Modify to remove whitespace between the closing and opening row tags (e.g </ProteinEntry><ProteinEntry id="CCCZ" > )
3) See that the rows are duplicated

This is due to the fact that the condition which checks the end of the file position isn't reached as the check of the start tag returns true before getting to that point.

**Comment by HyukjinKwon** [comment]
I will try to reproduce this soon. Thanks for reporting this.

**Comment by lokm01** [comment]
This seems to be fixed by #161 
There is however another bug which appeared after this PR on the same data when using compression codecs.

`
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 123.0 failed 1 times, most recent failure: Lost task 1.0 in stage 123.0 (TID 131, localhost): java.lang.ArrayIndexOutOfBoundsException: 65536
[info] 	at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.hbCreateDecodeTables(CBZip2InputStream.java:666)
[info] 	at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.createHuffmanDecodingTables(CBZip2InputStream.java:793)
[info] 	at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.recvDecodingTables(CBZip2InputStream.java:765)
[info] 	at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.getAndMoveToFrontDecode(CBZip2InputStream.java:801)
[info] 	at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.initBlock(CBZip2InputStream.java:504)
[info] 	at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.changeStateToProcessABlock(CBZip2InputStream.java:333)
[info] 	at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.read(CBZip2InputStream.java:399)
[info] 	at org.apache.hadoop.io.compress.BZip2Codec$BZip2CompressionInputStream.read(BZip2Codec.java:483)
[info] 	at org.apache.hadoop.io.compress.BZip2Codec$BZip2CompressionInputStream.read(BZip2Codec.java:502)
[info] 	at com.databricks.spark.xml.XmlRecordReader.readUntilEndElement(XmlInputFormat.scala:194)
[info] 	at com.databricks.spark.xml.XmlRecordReader.next(XmlInputFormat.scala:143)
[info] 	at com.databricks.spark.xml.XmlRecordReader.nextKeyValue(XmlInputFormat.scala:128)

`

**Comment by HyukjinKwon** [comment]
Let's make a separate issue. I would appreciate if you open anither issue for this.

**Comment by lokm01** [comment]
Sure, no problem
