### ISSUE TITLE
scala.MatchError: for some node names but not others?

### ISSUE THREAD

**Issue by leokall** [databricks/spark-xml#175]
Hi, I am trying to parse a xml something like:

```
  1 <a>
  2   <b>
  3     <c1>201601010100Z</c1>
  4     <c2>1000</c2>
  5     <c3>string1</c3>
  6     <c3>string2</c3>
  7     <c3>string3</c3>
  8     <c3>string4</c3>
  9   </b>
 10 </a>
 11 <a>
 12   <b>
 13     <c1>201601010100Z</c1>
 14     <c2>1000</c2>
 15     <c3>string5</c3>
 16     <c3>string6</c3>
 17     <c3>string7</c3>
 18     <c4>
 19        <d1>ABCD_15</d1>
 20        <d2>1</d2>
 21        <d2>2</d2>
 22        <d2>3</d2>
 23     </c4>
 24   </b>
 25 </a>
```

This works:
```
import org.apache.spark.sql.types.{StructType, StructField, StringType, DoubleType, IntegerType, ArrayType, LongType};
val cSchema = StructType(Array(
    StructField("d1", StringType, nullable = true),
    StructField("d2", ArrayType(IntegerType, false), nullable=true)
    ))
    
val bSchema = StructType(Array(
    StructField("c1", StringType, nullable = true),
    StructField("c2", StringType, nullable = true),
    StructField("c3", ArrayType(StringType, false), nullable=true),
    StructField("c4", ArrayType(cSchema, false), nullable=true)
    ))
    
val Schema = StructType(Array(
    StructField("b", ArrayType(bSchema, false), nullable = true)
    ))
    
val df = sqlContext.read
    .format("com.databricks.spark.xml")
    .option("rowTag", "a")
    .schema(Schema)
    .load(path)

df.printSchema
df.show(2)
```

However, changing for example "c2" in the xml and schemas to "whatever" gives me an error. I cannot understand why this is happening (I get the same error in my original xml as well). 

`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 47.0 failed 4 times, most recent failure: Lost task 0.3 in stage 47.0: scala.MatchError:`

**Comment by HyukjinKwon** [comment]
@leokall Hm, do you mean changing

```scala
...
val bSchema = StructType(Array(
    StructField("c1", StringType, nullable = true),
    StructField("c2", StringType, nullable = true),
...
```

to

```scala
...
val bSchema = StructType(Array(
    StructField("c1", StringType, nullable = true),
    StructField("whatever", StringType, nullable = true),
...
```

?

It seems it works okay with master branch. Could you please confirm it is okay with master branch?

I am about to release a new one so it'd be great if we can make sure everything is fine :)

**Comment by HyukjinKwon** [comment]
I think this might be related with this https://github.com/databricks/spark-xml/issues/125 if it does not work. There was an issue about column ordering when users specify the schema. Could you maybe try with the schema below ?

```scala
val bSchema = StructType(Array(
    StructField("c1", StringType, nullable = true),
    StructField("c3", ArrayType(StringType, false), nullable=true),
    StructField("c4", ArrayType(cSchema, false), nullable=true),
   StructField("whatever", StringType, nullable = true)
    ))
```

**Comment by leokall** [comment]
Thanks! I've been stuck with this for a long while now. It works if I define the nodes in my schema in alphabetic order. This should really be in the documentation though, hard error to catch.

**Comment by HyukjinKwon** [comment]
@leokall Indeed, this should be documented. I am about to release a new one including several bug fixes soon. Thanks for reporting this!
