### ISSUE TITLE
Read nested XML tags

### ISSUE THREAD

**Issue by mmartsen** [databricks/spark-xml#183]
Hi,
Is it possible to somehow read xml structure with nested tags like
`<book>
    <id>1</id>
    <book>
      <id>2</id>
    </book>
    <book>
      <id>3</id>
    </book>
</book>`

Specifying xpath would be great option.. Or maybe some additional parameters like level or rootTag for read function?

Thanks!

**Comment by HyukjinKwon** [comment]
Yeap, this'd be an option. Maybe it'd be great if we have this support in a clean and sensible way.

**Comment by HyukjinKwon** [comment]
Now, it's fixed. This can be read and manually filtered by DataFrame operations.

**Comment by srowen** [comment]
Yes you can select things like "book.id" although not XPath expressions
