### ISSUE TITLE
Try parser XML

### ISSUE THREAD

**Issue by luissantanayh** [databricks/spark-xml#185]
**I have this schema:**

root
 |-- _Id: string (nullable = true)
 |-- _versao: double (nullable = true)
 |-- autXML: struct (nullable = true)
 |    |-- CNPJ: long (nullable = true)
 |-- dest: struct (nullable = true)
 |    |-- CNPJ: long (nullable = true)
 |    |-- IE: long (nullable = true)
 |    |-- enderDest: struct (nullable = true)
 |    |    |-- CEP: long (nullable = true)
 |    |    |-- UF: string (nullable = true)
 |    |    |-- cMun: long (nullable = true)
 |    |    |-- cPais: long (nullable = true)
 |    |    |-- fone: long (nullable = true)
 |    |    |-- nro: string (nullable = true)
 |    |    |-- xBairro: string (nullable = true)
 |    |    |-- xLgr: string (nullable = true)
 |    |    |-- xMun: string (nullable = true)
 |    |    |-- xPais: string (nullable = true)
 |    |-- indIEDest: long (nullable = true)
 |    |-- xNome: string (nullable = true)
 |-- det: struct (nullable = true)
 |    |-- _nItem: long (nullable = true)
 |    |-- imposto: struct (nullable = true)
 |    |    |-- COFINS: struct (nullable = true)
 |    |    |    |-- COFINSAliq: struct (nullable = true)
 |    |    |    |    |-- CST: long (nullable = true)
 |    |    |    |    |-- pCOFINS: double (nullable = true)
 |    |    |    |    |-- vBC: double (nullable = true)
 |    |    |    |    |-- vCOFINS: double (nullable = true)
 |    |    |-- ICMS: struct (nullable = true)
 |    |    |    |-- ICMS40: struct (nullable = true)
 |    |    |    |    |-- CST: long (nullable = true)
 |    |    |    |    |-- orig: long (nullable = true)
 |    |    |-- PIS: struct (nullable = true)
 |    |    |    |-- PISAliq: struct (nullable = true)
 |    |    |    |    |-- CST: long (nullable = true)
 |    |    |    |    |-- pPIS: double (nullable = true)
 |    |    |    |    |-- vBC: double (nullable = true)
 |    |    |    |    |-- vPIS: double (nullable = true)
 |    |-- prod: struct (nullable = true)
 |    |    |-- CFOP: long (nullable = true)
 |    |    |-- NCM: long (nullable = true)
 |    |    |-- cEAN: string (nullable = true)
 |    |    |-- cEANTrib: string (nullable = true)
 |    |    |-- cProd: long (nullable = true)
 |    |    |-- indTot: long (nullable = true)
 |    |    |-- nItemPed: long (nullable = true)
 |    |    |-- qCom: double (nullable = true)
 |    |    |-- qTrib: double (nullable = true)
 |    |    |-- uCom: string (nullable = true)
 |    |    |-- uTrib: string (nullable = true)
 |    |    |-- vProd: double (nullable = true)
 |    |    |-- vUnCom: double (nullable = true)
 |    |    |-- vUnTrib: double (nullable = true)
 |    |    |-- xProd: string (nullable = true)
 |-- emit: struct (nullable = true)
 |    |-- CNPJ: long (nullable = true)
 |    |-- CRT: long (nullable = true)
 |    |-- IE: long (nullable = true)
 |    |-- enderEmit: struct (nullable = true)
 |    |    |-- CEP: long (nullable = true)
 |    |    |-- UF: string (nullable = true)
 |    |    |-- cMun: long (nullable = true)
 |    |    |-- cPais: long (nullable = true)
 |    |    |-- fone: long (nullable = true)
 |    |    |-- nro: long (nullable = true)
 |    |    |-- xBairro: string (nullable = true)
 |    |    |-- xLgr: string (nullable = true)
 |    |    |-- xMun: string (nullable = true)
 |    |    |-- xPais: string (nullable = true)
 |    |-- xNome: string (nullable = true)
 |-- ide: struct (nullable = true)
 |    |-- NFref: struct (nullable = true)
 |    |    |-- refNFe: double (nullable = true)
 |    |-- cDV: long (nullable = true)
 |    |-- cMunFG: long (nullable = true)
 |    |-- cNF: long (nullable = true)
 |    |-- cUF: long (nullable = true)
 |    |-- dhEmi: string (nullable = true)
 |    |-- dhSaiEnt: string (nullable = true)
 |    |-- finNFe: long (nullable = true)
 |    |-- idDest: long (nullable = true)
 |    |-- indFinal: long (nullable = true)
 |    |-- indPag: long (nullable = true)
 |    |-- indPres: long (nullable = true)
 |    |-- mod: long (nullable = true)
 |    |-- nNF: long (nullable = true)
 |    |-- natOp: string (nullable = true)
 |    |-- procEmi: long (nullable = true)
 |    |-- serie: long (nullable = true)
 |    |-- tpAmb: long (nullable = true)
 |    |-- tpEmis: long (nullable = true)
 |    |-- tpImp: long (nullable = true)
 |    |-- tpNF: long (nullable = true)
 |    |-- verProc: double (nullable = true)
 |-- infAdic: struct (nullable = true)
 |    |-- infCpl: string (nullable = true)
 |-- total: struct (nullable = true)
 |    |-- ICMSTot: struct (nullable = true)
 |    |    |-- vBC: double (nullable = true)
 |    |    |-- vBCST: double (nullable = true)
 |    |    |-- vCOFINS: double (nullable = true)
 |    |    |-- vDesc: double (nullable = true)
 |    |    |-- vFrete: double (nullable = true)
 |    |    |-- vICMS: double (nullable = true)
 |    |    |-- vICMSDeson: double (nullable = true)
 |    |    |-- vII: double (nullable = true)
 |    |    |-- vIPI: double (nullable = true)
 |    |    |-- vNF: double (nullable = true)
 |    |    |-- vOutro: double (nullable = true)
 |    |    |-- vPIS: double (nullable = true)
 |    |    |-- vProd: double (nullable = true)
 |    |    |-- vST: double (nullable = true)
 |    |    |-- vSeg: double (nullable = true)
 |-- transp: struct (nullable = true)
 |    |-- modFrete: long (nullable = true)

**from this command:**

``` python
df = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='infNFe').load(file_name)
```

**So df is:**

``` xml
+--------------------+-------+----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------+
|                 _Id|_versao|          autXML|                dest|                 det|                emit|                 ide|             infAdic|               total|transp|
+--------------------+-------+----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------+
|NFe31160918761791...|    3.1|[11561877000178]|[76295344000137,8...|[1,[[[1,7.6,45.5,...|[18761791000138,3...|[[4.1160276295344...|[Trib aprox R$: 6...|[[45.5,0.0,3.46,0...|   [0]|
+--------------------+-------+----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------+
```

**but when I do:**

``` python
newDF = df.select(df.autXML)
newDF.show()
```

**Appear this with null value:**

``` xml
+------+
|autXML|
+------+
|  null|  
+------+
```

**but the XML has content in the tag.** 

``` xml
<NFe xmlns="http://www.portalfiscal.inf.br/nfe">
    <infNFe Id="NFed12345678" versao="3.10">
        <ide>
            <cUF>31</cUF>
            <cNF>07875824</cNF>
            <natOp>6202/6411 DEVOLUÇAO DE COMPRA F/UF</natOp>
            <indPag>0</indPag>
            <mod>55</mod>
            <serie>1</serie>
            <nNF>1417</nNF>
            <dhEmi>2016-09-23T10:14:00-03:00</dhEmi>
            <dhSaiEnt>2016-09-23T10:14:00-03:00</dhSaiEnt>
            <tpNF>1</tpNF>
            <idDest>2</idDest>
            <cMunFG>3157807</cMunFG>
            <tpImp>1</tpImp>
            <tpEmis>1</tpEmis>
            <cDV>6</cDV>
            <tpAmb>1</tpAmb>
            <finNFe>4</finNFe>
            <indFinal>0</indFinal>
            <indPres>9</indPres>
            <procEmi>0</procEmi>
            <verProc>3.10</verProc>
            <NFref>
                <refNFe>342352345234</refNFe>
            </NFref>
        </ide>
        <emit>
            <CNPJ>15235123512234</CNPJ>
            <xNome>TESTE</xNome>
            <enderEmit>
                <xLgr>AV. TESTE</xLgr>
                <nro>1121</nro>
                <xBairro>VILA TESTE</xBairro>
                <cMun>3157807</cMun>
                <xMun>TESE</xMun>
                <UF>TESTE</UF>
                <CEP>33234234</CEP>
                <cPais>12342</cPais>
                <xPais>BRASIL</xPais>
                <fone>12344556</fone>
            </enderEmit>
            <IE>23541234</IE>
            <CRT>3</CRT>
        </emit>
        <dest>
            <CNPJ>5234523452345</CNPJ>
            <xNome>TESTE</xNome>
            <enderDest>
                <xLgr>TESTE</xLgr>
                <nro>SN</nro>
                <xBairro>TESTE</xBairro>
                <cMun>23452345</cMun>
                <xMun>TESTE</xMun>
                <UF>TESTE</UF>
                <CEP>21341234</CEP>
                <cPais>1058</cPais>
                <xPais>BRASIL</xPais>
                <fone>123415678</fone>
            </enderDest>
            <indIEDest>1</indIEDest>
            <IE>1243512341</IE>
        </dest>
        <autXML>
            <CNPJ>123412341234</CNPJ>
        </autXML>
        <det nItem="1">
            <prod>
                <cProd>000066</cProd>
                <cEAN/>
                <xProd>AJ RORATO TANQUE FIBRA SIMPLES 60X60 PRETO</xProd>
                <NCM>68109900</NCM>
                <CFOP>6411</CFOP>
                <uCom>PC</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>45.5000000000</vUnCom>
                <vProd>45.50</vProd>
                <cEANTrib/>
                <uTrib>PC</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>45.5000000000</vUnTrib>
                <indTot>1</indTot>
                <nItemPed>0</nItemPed>
            </prod>
            <imposto>
                <ICMS>
                    <ICMS40>
                        <orig>0</orig>
                        <CST>40</CST>
                    </ICMS40>
                </ICMS>
                <PIS>
                    <PISAliq>
                        <CST>01</CST>
                        <vBC>45.50</vBC>
                        <pPIS>1.65</pPIS>
                        <vPIS>0.75</vPIS>
                    </PISAliq>
                </PIS>
                <COFINS>
                    <COFINSAliq>
                        <CST>01</CST>
                        <vBC>45.50</vBC>
                        <pCOFINS>7.60</pCOFINS>
                        <vCOFINS>3.46</vCOFINS>
                    </COFINSAliq>
                </COFINS>
            </imposto>
        </det>
        <total>
            <ICMSTot>
                <vBC>45.50</vBC>
                <vICMS>8.19</vICMS>
                <vICMSDeson>0.00</vICMSDeson>
                <vBCST>0.00</vBCST>
                <vST>0.00</vST>
                <vProd>45.50</vProd>
                <vFrete>0.00</vFrete>
                <vSeg>0.00</vSeg>
                <vDesc>0.00</vDesc>
                <vII>0.00</vII>
                <vIPI>0.00</vIPI>
                <vPIS>0.75</vPIS>
                <vCOFINS>3.46</vCOFINS>
                <vOutro>0.00</vOutro>
                <vNF>45.50</vNF>
            </ICMSTot>
        </total>
        <transp>
            <modFrete>0</modFrete>
        </transp>
        <infAdic>
            <infCpl>Trib aprox R$: 6,12 Federal e 5,46 Estadual Fonte: IBPT Ar5Fr7 MD-5: 4E10BF61E02969CD2D7D040F67E4AC38</infCpl>
        </infAdic>
    </infNFe>
</NFe>
```

Why doesn't work with:

``` python
newDF = df.select(df.autXML.CNPJ)
newDF.show()
```

**or**

``` python
newDF = df.select(df.autXML)
newDF.show()
```

?

**Comment by HyukjinKwon** [comment]
It seems critical. I just took a look and this case is possible in some cases when we should skip whole child elements. I will submit a PR now.

**Comment by luissantanayh** [comment]
Thank you very much for your answer. If you need something and I can to help. I am here.

Best regards.

**Comment by dennisthegitmenace** [comment]
I think [the issue](https://github.com/databricks/spark-xml/issues/193) i just created is very similar to this one.

**Comment by HyukjinKwon** [comment]
I am closing this. Please feel free to reopen if this is not resolved and you still face this issue. Thanks again!

**Comment by luissantanayh** [comment]
Is this correct fix in the library from databricks?  The version in databricks is spark-xml_2.11-0.4.1. 

Thank you

**Comment by nihalseethi** [comment]
Hi, I ran into this very same issue today.
I'm using Python API, getting NULL for some columns which actually has data.  
This is happening for a struct type which has further array type within same tag. Similar tags are being handled correctly but for  one tag I'm running into this issue. 
If i print the schema, i can see everything(all the tags,attributes within that tag) being inferred properly , but when i do any transformation, it's reflected as null.
Sorry that at this point i cannot share the schema but any thoughts on this is much appreciated

Thank you.
