### ISSUE TITLE
how can I access  column xml???????? Please help me is urgent

### ISSUE THREAD

**Issue by shermilaguerra** [databricks/spark-xml#188]
I have simples xml file 
I dont get the xml elements or xml column 

I read the xml:
dgrem = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='provenance').load("file:///home/cloudera/Dataframe/Reconciliador-Sts2remoções.xml")
dgrem.show()

+--------------------+--------------------+
|                edit|              remove|
+--------------------+--------------------+
|[[null,15:16:23@1...|[[null,15:16:23@1...|
+--------------------+--------------------+

dgrem.printSchema()

root
 |-- edit: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- #VALUE: string (nullable = true)
 |    |    |-- @date: string (nullable = true)
 |    |    |-- @objectName: string (nullable = true)
 |    |    |-- @sourceContext: string (nullable = true)
 |    |    |-- @sourceKeySet: string (nullable = true)
 |    |    |-- @sourceMetadata: string (nullable = true)
 |    |    |-- @sourceOwner: string (nullable = true)
 |    |    |-- @sourceValue: string (nullable = true)
 |    |    |-- @status: string (nullable = true)
 |    |    |-- @targetContext: string (nullable = true)
 |    |    |-- @targetKeySet: string (nullable = true)
 |    |    |-- @targetMetadata: string (nullable = true)
 |    |    |-- @targetOwner: string (nullable = true)
 |    |    |-- @targetValue: string (nullable = true)
 |-- remove: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- #VALUE: string (nullable = true)
 |    |    |-- @date: string (nullable = true)
 |    |    |-- @objectName: string (nullable = true)
 |    |    |-- @sourceContext: string (nullable = true)
 |    |    |-- @sourceKeySet: string (nullable = true)
 |    |    |-- @sourceMetadata: string (nullable = true)
 |    |    |-- @sourceOwner: string (nullable = true)
 |    |    |-- @sourceValue: string (nullable = true)
 |    |    |-- @status: string (nullable = true)
 |    |    |-- @targetContext: string (nullable = true)
 |    |    |-- @targetKeySet: string (nullable = true)
 |    |    |-- @targetMetadata: string (nullable = true)
 |    |    |-- @targetOwner: string (nullable = true)
 |    |    |-- @targetValue: string (nullable = true)

how can I access @sourceOwner column xml????????

Any thoughts?
Very Thank for your help.

**Comment by HyukjinKwon** [comment]
You can access to them via wrapping the fields with backquotes.

If it is the problem with array, you might better take a look for `exclude()` function. Please see https://github.com/databricks/spark-xml/issues/141#issuecomment-234835577

**Comment by shermilaguerra** [comment]
I try it: dgrem.selectExpr("explode(edit) as e").select("e.*").show()
but it show
 ++
||
++
||
||
||
||
++
how to do two explode?????

**Comment by HyukjinKwon** [comment]
```scala
dgrem.selectExpr("explode(edit) as e").selectExpr("e.*").show()
```

Hm, could you try this one?

**Comment by HyukjinKwon** [comment]
If that does still not work, I guess that is related with https://github.com/databricks/spark-xml/issues/185. It seems a critical bug and I have a plan to bump up the version as soon as possible.

**Comment by shermilaguerra** [comment]
I try 
dgrem.selectExpr("explode(edit) as e").selectExpr("e.*").show()
++
||
++
||
||
||
||
++

**Comment by HyukjinKwon** [comment]
Do you mind if I ask your data if possible?

**Comment by shermilaguerra** [comment]
My data is simples:
<provenance>
 <remove objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="Nome para Citação" targetOwner="Adalberto Panobianco Bergamasco" targetValue="CORDARO, P." sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="Ordem de autoria" targetOwner="Adalberto Panobianco Bergamasco" targetValue="2" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <remove objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="Nome para Citação" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="Ordem de autoria" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
</provenance>

**Comment by shermilaguerra** [comment]
<provenance>
 <remove objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="Nome para Citação" targetOwner="Adalberto Panobianco Bergamasco" targetValue="CORDARO, P." sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="Ordem de autoria" targetOwner="Adalberto Panobianco Bergamasco" targetValue="2" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <remove objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="Nome para Citação" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="Ordem de autoria" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
</provenance>

**Comment by shermilaguerra** [comment]
My data is simple
`<provenance>
 <remove objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="Nome para Citação" targetOwner="Adalberto Panobianco Bergamasco" targetValue="CORDARO, P." sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=Paulo CORDARO" sourceValue="" targetMetadata="Ordem de autoria" targetOwner="Adalberto Panobianco Bergamasco" targetValue="2" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <remove objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="Nome para Citação" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
 <edit objectName="Autor" targetContext="Título=Globally Hypoelliptic Systems Of Vector Fields;Ano=1993;Revista=Journal of Functional Analysis" status="" sourceContext="" sourceMetadata="" sourceOwner="" targetKeySet="Nome=" sourceValue="" targetMetadata="Ordem de autoria" targetOwner="Adalberto Panobianco Bergamasco" targetValue="" sourceKeySet="" date="15:16:23@14/10/2016"/>
</provenance>
`

**Comment by HyukjinKwon** [comment]
I will test this and be back tomorrow.

**Comment by shermilaguerra** [comment]
Thank you so much for  your interest.  Best regards.

**Comment by shermilaguerra** [comment]
Hi HyukjinKwon,  i get the  column xml in pyspark this ay:
dgrem.selectExpr("explode(edit) as e").selectExpr("e.@date").show()
Very thank you so much for all. Best regards.

**Comment by HyukjinKwon** [comment]
Could you please close this if everything is fine?
