### ISSUE TITLE
Exception while tag is not found in xml 

### ISSUE THREAD

**Issue by anshsachdeva** [databricks/spark-xml#191]
I am extracting some tags from xml, but if that tag or hierarchy is not present in an xml, Is it possible to get null ? This Issue is not related to Issue 117 .. As  tag is present in xml schema but in my case this tag or hierarchy is not present in xml then not in xml schema ..

Appreciate for your Help.

Thanks
Ansh

**Comment by HyukjinKwon** [comment]
Could I please ask your sample codes and output maybe?

**Comment by anshsachdeva** [comment]
![image](https://cloud.githubusercontent.com/assets/22814152/19637289/dbda8380-99eb-11e6-9275-92b02014389e.png)

**Comment by anshsachdeva** [comment]
Any Luck ?

**Comment by HyukjinKwon** [comment]
I am sorry. I think I didn't understand the issue clearly. So, you set `rowTag` to, for example, `ABC` for the XML you gave but you want to produce `null` for each `Address`?

**Comment by anshsachdeva** [comment]
Ok , I will make you understand again.  While filling address by user, user address can be completed in two lines and another user filled it in three lines.

User1 Xml 
![image](https://cloud.githubusercontent.com/assets/22814152/19918036/674132f8-a0ee-11e6-86ae-d2fb8ba94950.png)

user2 xml 
![image](https://cloud.githubusercontent.com/assets/22814152/19918047/7d80ffc6-a0ee-11e6-8f06-962375916ec0.png)

But my query i generic, It should handle both the case. But for second xml I am getting line3 is not found
sqlcontext.sql("select address.line1,address.line2,address.line3 from table").show();

Thanks
Ansh

**Comment by fpousserot** [comment]
define schema manually.. If you infer the schema automaticaly, the lib may not detect the line3 tag
