### ISSUE TITLE
Values for some columns are read as NULLs

### ISSUE THREAD

**Issue by dennisthegitmenace** [databricks/spark-xml#193]
Currently i am facing this issue with Spark 2.0 built with Scala 2.11 and I am 100% sure it is a bug, because I ran the same code with Spark 1.6 (and respective version of spark-xml) and to an extent it worked fine.

I read my XML into a dataframe like so:
`df = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='dealer').load('file.xml')
df.printSchema()

> root
>  |-- address: string (nullable = true)
>  |-- cars: struct (nullable = true)
>  |    |-- value: array (nullable = true)
>  |    |    |-- element: struct (containsNull = true)
>  |    |    |    |-- brand: string (nullable = true)
>  |    |    |    |-- car_url: string (nullable = true)
>  |    |    |    |-- circulation_date: string (nullable = true)
>  |    |    |    |-- consommation_mixte: string (nullable = true)
>  |    |    |    |-- dpt: string (nullable = true)
>  |    |    |    |-- emission: string (nullable = true)
>  |    |    |    |-- energie: string (nullable = true)
>  |    |    |    |-- exterior_color: string (nullable = true)
>  |    |    |    |-- fiscale: string (nullable = true)
>  |    |    |    |-- freight: long (nullable = true)
>  |    |    |    |-- interior: string (nullable = true)
>  |    |    |    |-- mileage: string (nullable = true)
>  |    |    |    |-- model: string (nullable = true)
>  |    |    |    |-- options_equipments: struct (nullable = true)
>  |    |    |    |    |-- autre: struct (nullable = true)
>  |    |    |    |    |    |-- value: array (nullable = true)
>  |    |    |    |    |    |    |-- element: string (containsNull = true)
>  |    |    |    |    |-- exterieur_et_chassis: struct (nullable = true)
>  |    |    |    |    |    |-- value: array (nullable = true)
>  |    |    |    |    |    |    |-- element: string (containsNull = true)
>  |    |    |    |    |-- interieur: struct (nullable = true)
>  |    |    |    |    |    |-- value: array (nullable = true)
>  |    |    |    |    |    |    |-- element: string (containsNull = true)
>  |    |    |    |    |-- securite: struct (nullable = true)
>  |    |    |    |    |    |-- value: array (nullable = true)
>  |    |    |    |    |    |    |-- element: string (containsNull = true)
>  |    |    |    |    |-- securite_suite_: struct (nullable = true)
>  |    |    |    |    |    |-- value: string (nullable = true)
>  |    |    |    |-- photos: struct (nullable = true)
>  |    |    |    |    |-- value: array (nullable = true)
>  |    |    |    |    |    |-- element: string (containsNull = true)
>  |    |    |    |-- price: string (nullable = true)
>  |    |    |    |-- puissance_din: string (nullable = true)
>  |    |    |    |-- transmission: string (nullable = true)
>  |    |    |    |-- version: string (nullable = true)
>  |    |    |    |-- volume_coffre: string (nullable = true)
>  |    |    |    |-- warranty: string (nullable = true)
>  |    |    |    |-- year: long (nullable = true)
>  |-- dealer_url: string (nullable = true)
>  |-- financial_data: string (nullable = true)
>  |-- name: string (nullable = true)
>  |-- phone: struct (nullable = true)
>  |    |-- value: long (nullable = true)
>  |-- vehicle_count: struct (nullable = true)
>  |    |-- value: array (nullable = true)
>  |    |    |-- element: string (containsNull = true)

`

So in the xml there are `dealers`. and each `dealer`has a list of `cars`, which consists of multiple `value` elements.  Now, any of the top-level columns such as `dealer_url`, `name`, `financial_data` are never empty in the above mentioned file. However, when try to get those columns, the results are as follows (all columns except for the `name`are null): 

```
 df.select(df.name,df.financial_data,df.dealer_url).show()
name       financial_data     dealer_url
name_a   null                     null
name_b   null                     null
```

I played with XML structure for a while and found out that if I get rid of all the nested elements - then the top-level column values are read fine.

P.S. Defining an explicit schema didn't help.

As i mentioned before the same code works well on Spark 1.6.

Could you please help me out?

**Comment by HyukjinKwon** [comment]
It'd be certainly a regression if something does work after upgrading. I appreciate it if you are able to share a bit of data and codes if possible.

Could I please ask if you are able to test that with the master branch one? Actually, #185 is fixed in the master (not in branch-0.3 yet).

**Comment by HyukjinKwon** [comment]
BTW, I will release a new one within this week if that also fixes this issue.

**Comment by dennisthegitmenace** [comment]
Attached is a sample data from a file i am working with. There are two dealer nodes. In one of them i removed the `cars` node on purpose - to see if it affects the way the code works
[2_dealers_xml.txt](https://github.com/databricks/spark-xml/files/552932/2_dealers_xml.txt)
. I was using `pyspark --packages com.databricks:spark-xml_2.11:0.4.0` when firing up the spark console, it seems to be the master version, right?

And the code is something along the lines:

df = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='dealer').load('file.xml')
df.printSchema()
df.select(df.name,df.financial_data,df.dealer_url).show()

**Comment by HyukjinKwon** [comment]
Ah, I meant the one in master branch (after manually building). Never mind. I will try to reproduce it and be back soon.

**Comment by dennisthegitmenace** [comment]
Unfortunately i do not know how to build it from the master branch. What should i read on the topic? I would love to try

**Comment by HyukjinKwon** [comment]
Oh, there is a (little) documentation in https://github.com/databricks/spark-xml#building-from-source :). Thanks for reporting this.

**Comment by dennisthegitmenace** [comment]
Awesome. Thank you :)

**Comment by dennisthegitmenace** [comment]
If you could give me a hint on how to do it - i will surely try doing that
myself. (Unfortunately i do not know how to do it :( )

**Comment by dennisthegitmenace** [comment]
I learned how to build a code from a master branch and ran the above code with above data but the result was the same. Do you get the same behavior?

**Comment by HyukjinKwon** [comment]
Hm, it seems it works fine in my local.

I ran the codes below:

```scala
val df = sqlContext.read.format("xml").option("rowTag", "dealer").load("file.xml")
df.select("name","financial_data","dealer_url").show()
```

```
+-----------+--------------------+--------------------+
|       name|      financial_data|          dealer_url|
+-----------+--------------------+--------------------+
|   Absolute|91940 LES ULIS SI...|http://pros.lacen...|
|Zen Auto 33|                null|                null|
+-----------+--------------------+--------------------+
```

**Comment by HyukjinKwon** [comment]
Let me try to validate this with Python API too. I am pretty sure this issue is related with https://github.com/databricks/spark-xml/issues/185.

**Comment by dennisthegitmenace** [comment]
Yes. Otherwise will have to learn Scala ;)

**Comment by HyukjinKwon** [comment]
Oh yes, I just found a bug. Thanks! will fix and then release another one. I just verified this via Python API. 

```
+-----------+--------------------+--------------------+
|       name|      financial_data|          dealer_url|
+-----------+--------------------+--------------------+
|   Absolute|91940 LES ULIS SI...|http://pros.lacen...|
|Zen Auto 33|33460 ARSAC - SIR...|http://pros.lacen...|
+-----------+--------------------+--------------------+
```

**Comment by dennisthegitmenace** [comment]
Cool. Thank you :)

**Comment by dennisthegitmenace** [comment]
Whoop whoop, seems to work now :) Thank you 🎱

**Comment by HyukjinKwon** [comment]
Thank you for reporting this!

**Comment by HyukjinKwon** [comment]
I am closing this. Please reopen if this is not resolved and you still face this issue. Thanks again!
