### ISSUE TITLE
failing with "blank" and nested values

### ISSUE THREAD

**Issue by tonizzz** [databricks/spark-xml#194]
I'm having issues to process a file when under the structure it has a blank (**<![CDATA[]]>**). It doesn't work either, when providing schema or not. The schema identified is not correct , as it doesn't create an array and only maps the first picture. If i create a schema and use my schema to to the load, then, when reading the object pictures, it throws exception.

```
<ad>
<id><![CDATA[15406]]></id>
<pictures>
    <picture><![CDATA[]]>
        <picture_url><![CDATA[http://www.mysite.com/0.jpg]]></picture_url>
        <picture_title><![CDATA[my site picture 0]]></picture_title>
    </picture>
    <picture><![CDATA[]]>
        <picture_url><![CDATA[http://www.mysite.com/1.jpg]]></picture_url>
        <picture_title><![CDATA[my site picture 1]]></picture_title>
    </picture>
</pictures>
</ad>
```

if we remove from the file the blank value **<![CDATA[]]>** within picture, then it works fine and the structure is generated fine. As below.

```
<ad>
<id><![CDATA[15406]]></id>
<pictures>
    <picture>
        <picture_url><![CDATA[http://www.mysite.com/0.jpg]]></picture_url>
        <picture_title><![CDATA[my site picture 0]]></picture_title>
    </picture>
    <picture>
        <picture_url><![CDATA[http://www.mysite.com/1.jpg]]></picture_url>
        <picture_title><![CDATA[my site picture 1]]></picture_title>
    </picture>
</pictures>
</ad>
```

in spark-shell this is what I get for both examples. The first example the structure generated is not correct, it doesn't identify the pictures element as an array and it actually picks up only the first picture. The second example, with no blanks (<![CDATA[]]>) after picture, works fine and the structure is identified properly.

Same issue is happening when providing schema generated by case class. i haven't been able to map the first file successfully. 

```
scala> val badDF = sqlContext.read.format("com.databricks.spark.xml").option("charset", "UTF-8").option("rowTag", "ad").load("xml_bad.xml")
badDF: org.apache.spark.sql.DataFrame = [id: bigint, picture: string ... 3 more fields]

scala> badDF.printSchema
root
 |-- id: long (nullable = true)
 |-- picture: string (nullable = true)
 |-- picture_title: string (nullable = true)
 |-- picture_url: string (nullable = true)
 |-- pictures: struct (nullable = true)
 |    |-- picture: string (nullable = true)
 |    |-- picture_title: string (nullable = true)
 |    |-- picture_url: string (nullable = true)

scala> val goodDF = sqlContext.read.format("com.databricks.spark.xml").option("charset", "UTF-8").option("rowTag", "ad").load("xml_good.xml")
goodDF: org.apache.spark.sql.DataFrame = [id: bigint, pictures: struct<picture: array<struct<picture_title:string,picture_url:string>>>]

scala> goodDF.printSchema
root
 |-- id: long (nullable = true)
 |-- pictures: struct (nullable = true)
 |    |-- picture: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- picture_title: string (nullable = true)
 |    |    |    |-- picture_url: string (nullable = true)

```

Do you think this is a potential bug or would you be able to help with a case class to provide generate a schema with so I can use the library to map my files with first format also?

Attached "good" and "bad" xml files.

[example-xmls.zip](https://github.com/databricks/spark-xml/files/555589/example-xmls.zip)

Thanks

**Comment by HyukjinKwon** [comment]
Thanks for reporting this. Will try this one and other issues as well on this weekend.

**Comment by HyukjinKwon** [comment]
Indeed, it seems suspicious. I will try to take a closer look.

**Comment by tonizzz** [comment]
Thanks for looking at this!

If we get the schema from the "good" case and open the "bad" XML providing the schema manually, when trying to read the Dataframe (specifically the "pictures" field), it gives the exception below:

```
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at com.databricks.spark.xml.parsers.StaxXmlParser$.convertField(StaxXmlParser.scala:134)
	at com.databricks.spark.xml.parsers.StaxXmlParser$.convertObjectWithAttributes(StaxXmlParser.scala:219)
	at com.databricks.spark.xml.parsers.StaxXmlParser$.com$databricks$spark$xml$parsers$StaxXmlParser$$convertObject(StaxXmlParser.scala:274)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$parse$1$$anonfun$apply$4.apply(StaxXmlParser.scala:84)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$parse$1$$anonfun$apply$4.apply(StaxXmlParser.scala:73)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithKeys$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tonizzz** [comment]
I have been playing around with the library over the weekend and I think i found something interesting... I changed the filter within the parser to filter the blank CDATA elements and seem to work with my files BUT only when inferring the schema. I have to test more extensively anyway. but in any case I'll share the code I modified with you as I'm very sure you'll come across with a much better solution :) Thanks!

```
val filter = new EventFilter {
        override def accept(event: XMLEvent): Boolean =
          // Ignore comments. This library does not treat comments.
          Try(event.getEventType != XMLStreamConstants.COMMENT &&
            // added to skip blank CDATA
            !( event.getEventType == XMLStreamConstants.CDATA &&
                event.asCharacters().getData == "<![CDATA[]]>"  ||
                event.asCharacters().getData.length == 0
              )
          ).getOrElse(true)
      }
```

**Comment by HyukjinKwon** [comment]
Yea, I think the approach seems okay although we should avoid relying on try/catch handling within critical path as possible as we can. I instantly think we might should avoid to deal with CDATA completely for now. Then we could make the condition simplified as below:

``````scala
...
event.getEventType != XMLStreamConstants.COMMENT && 
event.getEventType != XMLStreamConstants.CDATA
...
```

My instant feeling is, it seems okay to ignore all CDATA but I think we should look into this deeper. Would you be interested in opening a PR for this after researching whether it is okay to ignore CDATA completely?

**Comment by tonizzz** [comment]
I agree with you, I also didn't like much the approach with Try. I'll give it a try anyway now that you are OK to do the change in the filter to give it a good solution and will open the PR as you suggest. Will try to have it done this week.
Thanks!

**Comment by HyukjinKwon** [comment]
Yea, but I think we might have to look into this first in order to check if it is really okay to completely ignore them.. I worry if this affects any existing usage cases and breaks backwards compatibility due to this change. Of course, we can talk in the PR if you will open first :).

**Comment by tonizzz** [comment]
This is what I need to test. I think the idea is to ignore CDATA only when it doesn't contain any data . My initial approach is doing that , ignoring all CDATA i think it's too much - we want the CDATA when they contain data.

**Comment by HyukjinKwon** [comment]
Hm.. let me look into CDATA and how it is parsed deeper and be back!

**Comment by tonizzz** [comment]
Hey, did you look at it already or want me to proceed with the PR?

**Comment by HyukjinKwon** [comment]
I am sorry for late response.. I was busy for Spark testing stuff and preparing a presentation/demo for my company...  Could you please give a shot if you are okay?

**Comment by Wei-1** [comment]
```
   java.util.NoSuchElementException: head of empty list
    at scala.collection.immutable.Nil$.head(List.scala:420)
    at scala.collection.immutable.Nil$.head(List.scala:417)
    at com.databricks.spark.xml.parsers.StaxXmlParser$.convertField(StaxXmlParser.scala:134)
```

I just got the same error message with my data while it is not CDATA but some HL7 related structure.

Do we have any follow up on this or workaround?

**Comment by Wei-1** [comment]
Because the HL7 file is above 1MB, it is hard to track the elements that cause the error.
But I had checked that there is no value started with `<!`  in the document.

**Comment by Wei-1** [comment]
@HyukjinKwon can you help to check if this is the caused?
https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala#L157

**Comment by srowen** [comment]
I'm pretty sure this is the same issue as https://github.com/databricks/spark-xml/issues/415 which has some more discussion. It's the existence of a non-whitespace element of any type mixed in with the structure.
