### ISSUE TITLE
How to extract all  elements in column with "minus" please is urgent

### ISSUE THREAD

**Issue by shermilaguerra** [databricks/spark-xml#195]
Please help me, i read the xml in pySpark
F1 = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ARTIGOS-PUBLICADOS').load("file:///home/cloudera/BigPrInt/Fontes/AnaPaulaPeron.xml")
F1.show()
+--------------------+
|    ARTIGO-PUBLICADO|
+--------------------+
|[[2,[[null,Matem�...|
+--------------------+
F1.selectExpr("explode(ARTIGO-PUBLICADO) as e")
exeption: AnalysisException: cannot resolve 'ARTIGO' given input columns ARTIGO-PUBLICADO;

any ideas
Best regards!!

**Comment by HyukjinKwon** [comment]
Can you try `F1.selectExpr("explode(`ARTIGO-PUBLICADO`) as e")` instead?

**Comment by shermilaguerra** [comment]
I  try: F1.selectExpr("explode(ARTIGO-PUBLICADO) as e")

it show exeption: AnalysisException: cannot resolve 'ARTIGO' given input columns ARTIGO-PUBLICADO;
it not recognize  "-" as letter it imagine as a minus sign.

**Comment by HyukjinKwon** [comment]
Oh, it seems the mark-down went wrong. I meant, 

```scala
F1.selectExpr("explode(`ARTIGO-PUBLICADO`) as e")
```

**Comment by shermilaguerra** [comment]
How to include these special characters, does explode function not recognized as a string?

**Comment by HyukjinKwon** [comment]
quoting the fields having special characters with `` will properly work fine.

**Comment by shermilaguerra** [comment]
Please can you show me an example? How to include  "-", it to be  recognized as a string.

**Comment by shermilaguerra** [comment]
but whem i do with underscore not has problem.
the problem is    whem i  work  with "-" betwen  the string ARTIGO-PUBLICADO .
F1.selectExpr("explode(`ARTIGO-PUBLICADO`) as e") it has quoting the fields having special characters 
with `` . grata. Shermila.
