### ISSUE TITLE
Getting "null" when selecting second or futher columns

### ISSUE THREAD

**Issue by someonehere15** [databricks/spark-xml#196]
Hi,

so I have e.g. the following XML file:
```
<root>
  <first>
    <a>textA</a>
  </first>
  <second>
    <b>textB</b>
  </second>
  <third>
    <c>textC</c>
  </third>
</root>
```
I load it into Spark through the DataBricks XML package, and everything looks good and loaded correctly.
When I try to select `first `or `first.a`, then I get the result correctly.

But if I try to get `second` or `second.b`, or `third` or `third.c`, then I get `null`.

I tried with a direct query, select function, everything, I don't know what the problem is.
The rowTag is root.
Any ideas?

**Comment by HyukjinKwon** [comment]
This should be fixed in the master I believe.

**Comment by someonehere15** [comment]
It's working now, thanks.

**Comment by HyukjinKwon** [comment]
Thank you for reporting this!
