### ISSUE TITLE
Get filename when loading whole folder

### ISSUE THREAD

**Issue by someonehere15** [databricks/spark-xml#203]
I couldn't find any option or solution to get the source filename when I load a complete folder.
Would this be possible without iterating separately every file manually?

**Comment by HyukjinKwon** [comment]
Maybe, it sounds like you are looking for `input_file_name` function?

**Comment by someonehere15** [comment]
wow, great, yes. Thanks, and I'm very sorry for the apparently stupid question.
BTW, I have to say, you are the best developer ever, always ready to help, and quickly answer for that matter. I'm new to spark and python and you helped me a lot. Thanks again.

The function works, however I am having a few consequent issues, if you have time to take a look:

1. I want to get only the filename, not the path. For this I created a function with the path as input, and filename as output, which I then registered to the sql session and call it in the column selection. But I am getting an empty column in the output. The function registering and calling works (have other functions too), the function itself works (tried directly returning the input string), and I even tried to create a new `dataframe.withColumn('filename',input_file_name())`, and then call the `function(filename)`, but still returns empty.

2. Now just discussing here, so I hope it doesn't sound stupid. Depending on the columns I select to output in the end, I also get some rows kind of repeated, with e.g. one row with all columns, the other has a column with a null value. From what I noticed, this happens if I have exploded multiple levels of parent elements, where some child element may not be present in each parent element. This is related to the other issue I opened with the flattening of nested XML, and the fact that multiple-levels of arrays cannot be accessed. So at the moment, I solved it by iteratively going through the path, and exploding arrays. I guess if spark-xml can directly flatten when reading would be better performing, so I'm hoping to see it as an option, but anyway. 
So, if I have this:
```
<root>
  <tag>
    <A>
      <textA>1</textA>
    </A>
    <A>
      <textA>2</textA>
    </A>
    <B>
      <textB>3</textB>
    </B>
  </tag>
  <tag>
    <B>
      <textB>4</textB>
    </B>
  </tag>
</root>
```
Since from what I saw, spark doesn't support exploding nested columns and preserving the path to it, it needs to create a completely new unnested column with the exploded entries. So in order to get to `root.tag.A.textA`, I need to explode `tag` and `A`. However, by exploding iteratively and getting new columns for each explosion, I would also get new rows for tags that may not be present in a parent, e.g. I would get a row for `root.tag.B.textB`, where the column for `root.tag.A.textA` would be `null`. It is an expected behavior if I were to flatten the table completely, and of course each tag would have a column and tags that are not present would be null. But I don't want to flatten the whole table.  I just want to eliminate arrays, thus exploding same name tags, but keep the nested column structure generally. And since nested columns are still there, this would allow me to get only the elements I need, e.g. `root.tag.A.textA`, while no `root.tag.B.textB` are retrieved, and thus eliminating null columns.
I'm not sure, but I guess this would be achievable if spark-xml directly stores same name tags as separate entries, eliminating arrays, and at the same time, keeping the nested structure.  Is there anything I can do here, or is there any chance this will be added as an option soon in spark-xml?

Sorry for the long text, and thanks a lot for you help until now.

**Comment by HyukjinKwon** [comment]
@someonehere15 Oh, IIRC, that should work fine from 1.6.3. Otherwise, that would return empty strings. BTW, nothing sounds stupid here really :). For the 2. i will take a look closely soon.

**Comment by someonehere15** [comment]
Thanks for answering.

I managed to create a function that iteratively explodes the columns. The one I posted on the other issue page was wrong, but I fixed it and it is working fine for now, until hopefully you can fix it directly in spark-xml.

I am still having problems with extracting the filename though. I have spark 2.1.0 and the latest build from spark-xml. If I call` input_file_name() `directly, it works, but if I try to use another function on top of it as described earlier, it is empty.

**Comment by HyukjinKwon** [comment]
@someonehere15 It sounds like a bug in Spark. Could I please ask the code snippet? I will try as well.

**Comment by someonehere15** [comment]
I tried even with a simple return and no processing:
```
def filename(path):
    return path
```
and I save it as a udf:
```
sourceFile = udf(filename, StringType())
df = df.withColumn('filename', sourceFile(input_file_name()))
```
and then select the filename column, and comes empty.
I also tried registering it:
`session.udf.register('filename',filename)`
but same thing.

To be honest I am trying this on Windows, so maybe that's a problem?
But then why would the `input_file_name()` function work separately but is not usable anywhere else?

**Comment by HyukjinKwon** [comment]
I will try to take a look deeper on this weekend.

**Comment by HyukjinKwon** [comment]
@someonehere15 Yeap, I just tried and I was able to reproduce this as below:

```python
from pyspark.sql.functions import *
from pyspark.sql.types import *

def filename(path):
    return path

sourceFile = udf(filename, StringType())
spark.read.json("tmp.json").select(sourceFile(input_file_name())).show()
```

```bash
+---------------------------+
|filename(input_file_name())|
+---------------------------+
|                           |
+---------------------------+
```

```python
spark.read.json("tmp.json").select(input_file_name()).show()
```

```bash
+--------------------+
|   input_file_name()|
+--------------------+
|file:///Users/hyu...|
+--------------------+
```

I believe this is an issue in Spark itself. I will take a look deeper and leave a comment here with a JIRA.

**Comment by HyukjinKwon** [comment]
BTW, it seems it is PySpark-specified problem.

```scala
import org.apache.spark.sql.functions.udf
import spark.implicits._

val path = "tmp.json"
val filename = (path: String) => path
val filenameUDF = udf(filename)

spark.read.json(path).select(filenameUDF(input_file_name())).show()
```

```
+----------------------+
|UDF(input_file_name())|
+----------------------+
|  file:///Users/hyu...|
+----------------------+
```

**Comment by someonehere15** [comment]
Good to know. thanks.

**Comment by someonehere15** [comment]
Just FYI, I added on the JIRA ticket that I continue to have the same problem on pySpark 2.1.0, and some additional issues.

**Comment by someonehere15** [comment]
Hello again,

just FYI,  I posted on the JIRA ticket from above that the problem is still present specifically when using spark-xml.

**Comment by HyukjinKwon** [comment]
Thank you for your update.
