### ISSUE TITLE
Trying to select values based off a condition

### ISSUE THREAD

**Issue by davidcrossland** [databricks/spark-xml#204]
I have a column with the following schema

|-- FuelHeader: struct (nullable = true)
 |    |-- AdditionalFuels: struct (nullable = true)
 |    |    |-- AdditionalFuel: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- CaptainCheck: string (nullable = true)
 |    |    |    |    |-- Duration: struct (nullable = true)
 |    |    |    |    |    |-- Value: string (nullable = true)
 |    |    |    |    |-- EstimatedWeight: struct (nullable = true)
 |    |    |    |    |    |-- Value: struct (nullable = true)
 |    |    |    |    |    |    |-- _VALUE: double (nullable = true)
 |    |    |    |    |    |    |-- _unit: string (nullable = true)
 |    |    |    |    |-- _reason: string (nullable = true)

Im trying to figure out how i can select a subset of values from the entire AdditionalFuel array based on _reason and assumed something like the following should work.
  
df.where("FuelHeader.AdditionalFuels.AdditionalFuel._reason == 'MinimumReserve'").select("`FuelHeader.AdditionalFuels.AdditionalFuel.EstimatedWeight.Value._VALUE`")

Ultimately  i plan to add the result to an existing dataframe using .withColumn, however i get the following error that i cant figure out..

cannot resolve '(`FuelHeader`.`AdditionalFuels`.`AdditionalFuel`.`_reason` = CAST('MinimumReserve' AS DOUBLE))' due to data type mismatch: differing types in '(`FuelHeader`.`AdditionalFuels`.`AdditionalFuel`.`_reason` = CAST('MinimumReserve' AS DOUBLE))' (array<string> and double).; line 1 pos 0
org.apache.spark.sql.AnalysisException: cannot resolve '(`FuelHeader`.`AdditionalFuels`.`AdditionalFuel`.`_reason` = CAST('MinimumReserve' AS DOUBLE))' due to data type mismatch: differing types in '(`FuelHeader`.`AdditionalFuels`.`AdditionalFuel`.`_reason` = CAST('MinimumReserve' AS DOUBLE))' (array<string> and double).; line 1 pos 0

is this a bug?

**Comment by HyukjinKwon** [comment]
Hi @davidcrossland, would https://github.com/databricks/spark-xml/issues/141#issuecomment-234835577 be helpful maybe?

**Comment by srowen** [comment]
Looks like more of a Spark SQL question. You can access array elements with `[n]` syntax
