### ISSUE TITLE
Disable inferSchema and keep everything as String

### ISSUE THREAD

**Issue by someonehere15** [databricks/spark-xml#205]
Would it be possible to add an option to disable type detection and save all parsed values as a string datatype?

**Comment by HyukjinKwon** [comment]
It is not. Thank you for a suggestion.

**Comment by someonehere15** [comment]
So I just wanted to add a follow-up question here: Can I disable inferSchema, as is possible on spark-csv, and leave everything as a String?

**Comment by jvmlet** [comment]
Have you tried to apply your schema explicitly ?

**Comment by HyukjinKwon** [comment]
Yea, the best way is to give the schema explicitly. BTW. If we want to avoid only type inference, then it seems it goes in a problem in some cases like `inferSchema` option in CSV datasource.

**Comment by someonehere15** [comment]
Same as OP of #223 , I also have a complex XML dataset and a dynamic schema on each run, so passing  a Schema explicitly is not an option for me. Creating a function as shown in #223 would require to load the files twice, which is a problem in my case because there are a lot of files. On the other hand, I would also need to adapt it for python, which I'm not sure exactly how to do it from the scala example (If anyone could help me there I could try it though despite the performance).

I understand it is going to be added, but in the meantime, is there anything I can change myself to the spark-xml source code to disable inferSchema or force everything to String, or is there going to be a new release soon?

**Comment by HyukjinKwon** [comment]
I think we need this, at least, per use cases reported so far. I think it is not going to release soon though. Let me try to fix these and try to make a release at my best.

**Comment by someonehere15** [comment]
Thank you very much, it would help me a lot.
I was thinking to change the inferSchema code to always return StringType or something like that, but if you could provide a better release, I would really appreciate it. Thanks again.

**Comment by schoi99** [comment]
Just asking for a follow up, this thread has been open for a while. 
Is there any work around that could solve this issue temporally, or did I miss a release with a fix?
If any, some help would be greatly appreciated. Thank you

**Comment by srowen** [comment]
You can just rewrite the schema to specify StringType in place of what is inferred, as a workaround. Read the file to infer the schema, then write a little code to map the primitive types to StringType, then reparse as string.

If the point is to avoid inference, yeah that won't help.
If the point is to just get string values out, you could call .toString on the values? cast them in the DataFrame?

**Comment by blbradley** [comment]
@srowen That doesn't workfor columns that are integers but get inferred as doubles.

**Comment by schoi99** [comment]
Yeah that was the issue. So here's my workaround. 

Infer the schema once with whatever you got. Alter the schema to have all string data type and run your process against the new schema. 

There is some sacrifice, but it works for my case. If you have to inferschema a lot this wouldn't be ideal.

**Comment by blbradley** [comment]
Yes, that is possible. But, I'm working with a large deeply nested XML conversion and my schema is about 100 lines long. It was very inconvenient for one field.

**Comment by srowen** [comment]
Yeah OK that's a reasonable thing to implement, especially if you're interested in trying it. Probably a flag that just causes it to not look at the actual data type and always return StringType

**Comment by blbradley** [comment]
Hey, cool! Thank you.

I'm not sure when, but I could cook up a change for this.

**Comment by Wei-1** [comment]
This feature will be very helpful since the current parser seems to change 0010 to 10.

**Comment by blbradley** [comment]
@Wei-1 You can also explicitly define your schema; that will allow you to parse 0010 to a StringType which will preserve the structure.

**Comment by Wei-1** [comment]
I know but
We don't really know the schema before running it. so a possible solution is to run spark-xml to get the schema, and change the schema to StringType and run spark-xml again. (which we will want to avoid if possible since spark-xml will take 10 minutes just to load all xml files that we got in an hour)

**Comment by HyukjinKwon** [comment]
One workaround is:

```scala
val path = "..."
val schema = spark.read.format("xml").load(path)
val stringSchema = schema .. // transform types you guys want to string types
spark.read.format("xml").schema(schema).load(path)
```

**Comment by yjhyjhyjh0** [comment]
We’ve encountered this issue.
Our use case is some XML column contains text like “00010”.
We like to treat it as String but parser automatically parses it as IntegerType when using inferring.
The data become 10 while processing which this means we can’t recover original data “00010”.

We would like to keep using infer columns to take advantage of no predefined schema.
This might imply custom column infer strategy would be a good enhancement.

I’ve submitted pull request to add inferring interface along with new with allString infer strategy.
There is an example unit test of this use case at the pull request.
Please let me know if there is any feedback on this improvement.
Thanks.

**Comment by srowen** [comment]
Should be resolved by https://github.com/databricks/spark-xml/commit/0ff88df9e3ab5fb9304f598aa1c05f8aba7a3817
