### ISSUE TITLE
DataFrameReader  object has no attribute 'select'

### ISSUE THREAD

**Issue by alexisaraya** [databricks/spark-xml#207]
I am trying to follow the example, but it gives me the following error
I load xml from Hadoop

`>>> df.select("author", "@id").write().format("com.
.option("rowTag", "book").save("newbooks.xml");`

`  File "<stdin>", line 1, in <module>
AttributeError: 'DataFrameReader' object has no attribute 'select'`

S.O Windows 7
Hadoop 2.7.1
Spark 1.6.4

Tranks for your help

**Comment by HyukjinKwon** [comment]
It seems you forgot to call `load(...)` :) ?

**Comment by alexisaraya** [comment]
HyukjinKwon brote. :

```
df2 = sqlContext.read.format('com.databricks.spark.xml')
df2.options(rowTag='book')
```
**pyspark.sql.readwriter.DataFrameReader object at 0x02853050>**
`df2.load('hdfs://localhost:9000/xml/books.xml')`
**DataFrame[@id: string, author: string, description: string, genre: string, price: double, publish_da
te: string, title: string]**
`df2.select("autor")`
**Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'DataFrameReader' object has no attribute 'select'**



Tranks

**Comment by HyukjinKwon** [comment]
Could you try this?

```python
df2 = df2.load('hdfs://localhost:9000/xml/books.xml')
df.select("autor")
```

BTW, there are some critical bugs in lower versions. If possible, I would like to recommand to use higher one like 0.3.4

**Comment by HyukjinKwon** [comment]
I think this was mistake ;). Please feel free to reopen this if you still face this issue. I am closing this for now.
