### ISSUE TITLE
How to Ignore XML comments like this

### ISSUE THREAD

**Issue by tanxinz** [databricks/spark-xml#208]
It still loads , not ignore.How can I do .Thanks
```xml
<?xml version="1.0"?>
<ROWSET>
   <!-- 
    <ROW>
        <year>2115</year>
        <make>aaaaChevy</make>
        <model>Volaaaat</model>
        <comment>Noaaa</comment>
   </ROW>
   -->
 
</ROWSET>
```

**Comment by HyukjinKwon** [comment]
Could I please ask the codes you tried?

**Comment by tanxinz** [comment]
I change cars.xml like this .
<?xml version="1.0"?>
<ROWSET>
    <ROW>
        <year>2012</year>
        <make>Tesla</make>
        <model>S</model>
        <comment>No comment</comment>
    </ROW>
    <ROW>
        <year>1997</year>
        <make>Ford</make>
        <model>E350</model>
        <comment>Go get one now they are going fast</comment>
    </ROW>
    <ROW>
        <year>2015</year>
        <make>Chevy</make>
        <model>Volt</model>
        <comment>No</comment>
    </ROW>
   
</ROWSET>

Here is my python code:
./pyspark --master local[2] \
 --conf spark.driver.memory=2G \
 --packages com.databricks:spark-xml_2.11:0.4.1


from pyspark.sql import SQLContext
from pyspark.sql import functions
from pyspark.sql.functions import *
sqlContext = SQLContext(sc)
df_cars = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ROW').load('file:///home/etl/tcz/cars.xml')
df_cars.show(100,truncate=False)
+----------------------------------+---------+--------+----+
|comment                           |make     |model   |year|
+----------------------------------+---------+--------+----+
|No comment                        |Tesla    |S       |2012|
|Go get one now they are going fast|Ford     |E350    |1997|
|No                                |Chevy    |Volt    |2015|
|Noaaa                             |aaaaChevy|Volaaaat|2115|
+----------------------------------+---------+--------+----+

**Comment by tanxinz** [comment]
I change cars.xml like this :
<?xml version="1.0"?>
<ROWSET>
    <ROW>
        <year>2012</year>
        <make>Tesla</make>
        <model>S</model>
        <comment>No comment</comment>
    </ROW>
    <ROW>
        <year>1997</year>
        <make>Ford</make>
        <model>E350</model>
        <comment>Go get one now they are going fast</comment>
    </ROW>
    <ROW>
        <year>2015</year>
        <make>Chevy</make>
        <model>Volt</model>
        <comment>No</comment>
    </ROW>
   
</ROWSET>


Here is my python code:
./pyspark --master local[2]
--conf spark.driver.memory=2G
--packages com.databricks:spark-xml_2.11:0.4.1

from pyspark.sql import SQLContext
from pyspark.sql import functions
from pyspark.sql.functions import *
sqlContext = SQLContext(sc)
df_cars = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ROW').load('file:///home/etl/tcz/cars.xml')
df_cars.show(100,truncate=False)
+----------------------------------+---------+--------+----+
|comment |make |model |year|
+----------------------------------+---------+--------+----+
|No comment |Tesla |S |2012|
|Go get one now they are going fast|Ford |E350 |1997|
|No |Chevy |Volt |2015|
|Noaaa |aaaaChevy|Volaaaat|2115|
+----------------------------------+---------+--------+----+

**Comment by tanxinz** [comment]
I change cars.xml like this :
<?xml version="1.0"?>
<ROWSET>
    <ROW>
        <year>2012</year>
        <make>Tesla</make>
        <model>S</model>
        <comment>No comment</comment>
    </ROW>
    <ROW>
        <year>1997</year>
        <make>Ford</make>
        <model>E350</model>
        <comment>Go get one now they are going fast</comment>
    </ROW>
    <ROW>
        <year>2015</year>
        <make>Chevy</make>
        <model>Volt</model>
        <comment>No</comment>
    </ROW>
   
</ROWSET>


Here is my python code:
./pyspark --master local[2]
--conf spark.driver.memory=2G
--packages com.databricks:spark-xml_2.11:0.4.1

from pyspark.sql import SQLContext
from pyspark.sql import functions
from pyspark.sql.functions import *
sqlContext = SQLContext(sc)
df_cars = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ROW').load('file:///home/etl/tcz/cars.xml')
df_cars.show(100,truncate=False)
+----------------------------------+---------+--------+----+
|comment |make |model |year|
+----------------------------------+---------+--------+----+
|No comment |Tesla |S |2012|
|Go get one now they are going fast|Ford |E350 |1997|
|No |Chevy |Volt |2015|
|Noaaa |aaaaChevy|Volaaaat|2115|
+----------------------------------+---------+--------+----+

**Comment by tanxinz** [comment]
I change cars.xml like this :
|   <?xml version="1.0"?>
|   <ROWSET>
|       <ROW>
|           <year>2012</year>
|           <make>Tesla</make>
|           <model>S</model>
|           <comment>No comment</comment>
|       </ROW>
|       <ROW>
|           <year>1997</year>
|           <make>Ford</make>
|           <model>E350</model>
|           <comment>Go get one now they are going fast</comment>
|       </ROW>
|       <ROW>
|           <year>2015</year>
|           <make>Chevy</make>
|           <model>Volt</model>
|           <comment>No</comment>
|       </ROW>
|      
|   </ROWSET>


Here is my python code:
./pyspark --master local[2]
--conf spark.driver.memory=2G
--packages com.databricks:spark-xml_2.11:0.4.1

from pyspark.sql import SQLContext
from pyspark.sql import functions
from pyspark.sql.functions import *
sqlContext = SQLContext(sc)
df_cars = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ROW').load('file:///home/etl/tcz/cars.xml')
df_cars.show(100,truncate=False)
+----------------------------------+---------+--------+----+
|comment |make |model |year|
+----------------------------------+---------+--------+----+
|No comment |Tesla |S |2012|
|Go get one now they are going fast|Ford |E350 |1997|
|No |Chevy |Volt |2015|
|Noaaa |aaaaChevy|Volaaaat|2115|
+----------------------------------+---------+--------+----+

**Comment by tanxinz** [comment]
I change cars.xml like this :
`<?xml version="1.0"?>
<ROWSET>
    <ROW>
        <year>2012</year>
        <make>Tesla</make>
        <model>S</model>
        <comment>No comment</comment>
    </ROW>
    <ROW>
        <year>1997</year>
        <make>Ford</make>
        <model>E350</model>
        <comment>Go get one now they are going fast</comment>
    </ROW>
    <ROW>
        <year>2015</year>
        <make>Chevy</make>
        <model>Volt</model>
        <comment>No</comment>
    </ROW>
   
</ROWSET>`

Here is my python code:
./pyspark --master local[2]
--conf spark.driver.memory=2G
--packages com.databricks:spark-xml_2.11:0.4.1

`from pyspark.sql import SQLContext
from pyspark.sql import functions
from pyspark.sql.functions import *
sqlContext = SQLContext(sc)
df_cars = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ROW').load('file:///home/etl/tcz/cars.xml')
df_cars.show(100,truncate=False)
+----------------------------------+---------+--------+----+
|comment |make |model |year|
+----------------------------------+---------+--------+----+
|No comment |Tesla |S |2012|
|Go get one now they are going fast|Ford |E350 |1997|
|No |Chevy |Volt |2015|
|Noaaa |aaaaChevy|Volaaaat|2115|
+----------------------------------+---------+--------+----+
`

**Comment by tanxinz** [comment]
I change cars.xml like this :
```xml
<?xml version="1.0"?>
<ROWSET>
    <ROW>
        <year>2012<!--A comment within tags--></year>
        <make>Tesla</make>
        <model>S</model>
        <comment>No comment</comment>
    </ROW>
    <ROW>
        <year>1997</year><!--A comment within elements-->
        <make>Ford</make>
        <model>E350</model>
        <comment><!--A comment before a value-->Go get one now they are going fast</comment>
    </ROW>
    <ROW>
        <year>2015</year>
        <make>Chevy</make>
        <model>Volt</model>
        <comment>No</comment>
    </ROW>
   <!-- 
    <ROW>
        <year>2115</year>
        <make>aaaaChevy</make>
        <model>Volaaaat</model>
        <comment>Noaaa</comment>
   </ROW>
   -->
</ROWSET>
```

Here is my python code:
./pyspark --master local[2]
--conf spark.driver.memory=2G
--packages com.databricks:spark-xml_2.11:0.4.1
```python
from pyspark.sql import SQLContext
from pyspark.sql import functions
from pyspark.sql.functions import *
sqlContext = SQLContext(sc)
df_cars = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ROW').load('file:///home/etl/tcz/cars.xml')
df_cars.show(100,truncate=False)
+----------------------------------+---------+--------+----+
|comment |make |model |year|
+----------------------------------+---------+--------+----+
|No comment |Tesla |S |2012|
|Go get one now they are going fast|Ford |E350 |1997|
|No |Chevy |Volt |2015|
|Noaaa |aaaaChevy|Volaaaat|2115|
+----------------------------------+---------+--------+----+
```

**Comment by tanxinz** [comment]
@HyukjinKwon 
I am using spark2.0.2 and spark-xml_2.11:0.4.1
Regards

**Comment by HyukjinKwon** [comment]
Thank you for details!

**Comment by srowen** [comment]
Yeah this is kinda hard as XmlInputFormat is doing the work to locate the row tags, but we're trying not to make it a full-on XML parser. It doesn't know about comments. I think it's possible, not terribly hard, to add comment awareness.

**Comment by ajanuskevicius** [comment]
Hi @srowen !

Seems like we have very similar issue with comments in xml.

Please see the examples bellow.

I wanted to ask maybe something has changed during the years? We're using 0.12.0.

I've been playing with those options "rootTag", "rowTag" on Payload, but none of that helped.

Is there a more elegant way to solve this other than substring the actual data without the comments from Payload?

We were parsing Payload element like this:
`df.withColumn("parsedPayload", from_xml($"Data.Storage.Payload", payloadAvroSchema, Map("mode" -> "FAILFAST")))`

It works just fine with xml like that:
```
<AMP version="4.0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Data>
    <Storage>
      <Payload>
        <![CDATA[<Document xmlns="http://www.six-interbank-clearing.com/de/pacs.002.001.03.ch.01">                                                                               
          <FIToFIPmtStsRpt>The data I need</FIToFIPmtStsRpt>                                                              
            </Document>]]>
      </Payload>
    </Storage>
  </Data>                                                               
</AMP>
```

With xml like that, it throws exception:
```
<AMP version="4.0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Data>
    <Storage>
      <Payload>
        <![CDATA[Some meta data about Payload element and data it contains
          <Document xmlns="http://www.six-interbank-clearing.com/de/pacs.002.001.03.ch.01">                                                                               
            <FIToFIPmtStsRpt>The data I need</FIToFIPmtStsRpt>                                                              
              </Document>Some other comments here, as well]]>
      </Payload>
    </Storage>
  </Data>                                                               
</AMP>
```

The exception looks like that:
```
Caused by: java.lang.RuntimeException: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 'R' (code 82) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
```

**Comment by srowen** [comment]
What is your row tag here, and where do you think the "R" is that it complains about? I think this is the same sort of issue, but yeah this is CDATA not a comment.

**Comment by ajanuskevicius** [comment]
Up to this moment I wasn't using any rowTag to parse the Payload element. Only "AMP" as the rowTag to read the whole XML file.

```
val df = spark.read.format("com.databricks.spark.xml")
  .option("mode", "FAILFAST")
  .option("rowValidationXSDPath", baseSchemaName)
  .option("rowTag", "AMP")
  .load(inputPath)

df.withColumn("parsedPayload", from_xml($"Data.Storage.Payload", payloadAvroSchema, Map("mode" -> "FAILFAST")))
```

"R" is the first char after "<Payload><![CDATA[". I just didn't want to expose it. So with this example, it would be "S".

So I was playing with rowTag, like "Payload" or "Document", or "FIToFIPmtStsRpt" when parsing Payload element with function from_xml(), but none of that helped.

**Comment by srowen** [comment]
OK this is slightly different. Here, yes, there is no rowTag involved, right, you are passing XML from a column. That entire XML fragment is parsed as a document. Here it starts with a CDATA section, but, that's not legal XML - it's trying to read it as an XML prolog and it doesn't work.

I'm not quite sure why the first example works differently though. Maybe it figures it out?

In any event, I think you really want to pass the XML starting at `<Payload>`, including that tag, not just its contents. It needs to be one XML element at the root
