### ISSUE TITLE
Are the parsed elements ordered on the DataFrame?

### ISSUE THREAD

**Issue by someonehere15** [databricks/spark-xml#210]
Just like the title says, I wanted to check if the parsed elements from the XML file are saved in the same order on the DataFrame as the order of the tags on the XML, especially in the case of Arrays.

From what I checked myself manually, they appear to be ordered, but I wanted to ask here to be completely sure. So, is it safe to assume the elements (e.g. in a WrappedArray) have the same order as in the XML source file?

**Comment by HyukjinKwon** [comment]
Yes, they are. It saves each element as the parse meets. So, it follows the natural order. However, my gut tells me it might not be a good idea to rely on the natural order in most cases of batch processing though.

**Comment by someonehere15** [comment]
Thank you very much for the answer. I completely agree with you. But I have a very difficult xml structure to work with,  and the order of the tags are important for some reason. It is bad but it is what it is. 

Anyway, this saves me a lot of work, so thanks.

**Comment by dariuszjezierski** [comment]
Hi,
You can apply monotonically_increasing_id() function within partition of dataset.

**Comment by srowen** [comment]
I think this issue is about whether something like...
```
<tag>foo</tag>
<tag>bar</tag>
```
definitely results in an array with "foo" and then "bar".  Not rows within a DataFrame.
