### ISSUE TITLE
Unable to read the xml

### ISSUE THREAD

**Issue by rahultumane** [databricks/spark-xml#212]
Hi,
I followed the same steps as you had mentioned, but was unable to get any output.
The code that I used is as follows:

./spark-2.0.2/bin/spark-shell --packages com.databricks:spark-xml_2.11:0.4.1

val sqlContext = SQLContext(sc)
val df = sqlContext.read.format("com.databricks.spark.xml").option("rowTag", "project").load("/path/abc.xml")
df.printSchema()

The Output I got is: 
root

Kindly look into it.

**Comment by HyukjinKwon** [comment]
Do you mind if I ask your sample data please? I would like to reproduce this.

**Comment by rahultumane** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<Transaction xmlns:xsi="http://www.w3.org/2001/XMLSchema-CJCGCGCNNCNJCGinstance" xsi:noNamespaceSchemaLocation="3yfhPFFGSL_IS.xsd" >
	<UserID>targeedvmhvhed<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<Transaction xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="3PLgxgmxhxfxhx_IS.xsd" >
	<UserID>getJCJxml</UserID>
	<Password>rggdgetxml01</Password>
	<MerchantID>Tarvehkbhkvfget.com</MerchantID>
	<TransactionReferenceNumber>OHXHXHL2016101502050277158</TransactionReferenceNumber>
	<TransactionType>InventorxdfxhcgcySyncH</TransactionType>
	<_3PLReferenceNumber>884877158</_3PLReferenceNumber>
	<EventDate>2016.10.15 02:05:02 CDT</EventDate>
	<_3PLID>ODFGHL</_3PLID>
	<MessageCount>8043</MessageCount>
	<Products>
		<Product>
			<ProdID>10158555272</ProdID>
			<WarehouseID>94774678</WarehouseID>
			<InStockQty>0</InStockQty>
			<ReservedQty/>
			<AvailableQty>0</AvailableQty>
			<OnOrderQty/>
			<DamagedQty>0</DamagedQty>
			<QualityQty>0</QualityQty>
			<RTVQty>0</RTVQty>
		</Product>
		<Product>
			<ProdID>10266678865319</ProdID><WarehouseID>94897658977</WarehouseID><InStockQty>10</InStockQty><ReservedQty/><AvailableQty>10</AvailableQty><OnOrderQty/><DamagedQty>0</DamagedQty><QualityQty>0</QualityQty><RTVQty>0</RTVQty>
		</Product>
	</Products>
</Transaction>

**Comment by rahultumane** [comment]
Above mentioned data is a just a small part of the file. Hope it will suffice your need.

**Comment by rahultumane** [comment]
Please suggest something. I can't move forward without parsing this xml.

**Comment by masud-technope** [comment]
I have these XML file:

`<?xml version="1.0">
<comments>
  <row>one</row>
  <row>two</row>
  <row>three</row>
  <row>one</row>
    <row>two</row>
  <row>three</row>
  <row>one</row>
    <row>two</row>
  <row>three</row>
  <row>one</row>
    <row>two</row>
  <row>three</row>
  <row>one</row>
    <row>two</row>
  <row>three</row>
  <row>one</row>
    <row>two</row>
</comments>`

Now, I am trying to read it using this code
`Dataset df = sqlContext.read().format("com.databricks.spark.xml")
				.option("rowTag", "row").load(xmlFile);
		df.printSchema();
		df.show();`

And the output I get
`17/12/05 18:29:02 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
17/12/05 18:29:02 INFO NewHadoopRDD: Input split: file:/F:/MyWorks/Thesis Works/BigDataWorks/Corpus/xml/comments-small.xml:0+371
17/12/05 18:29:03 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.util.NoSuchElementException
	at com.sun.xml.internal.stream.EventFilterSupport.nextEvent(EventFilterSupport.java:79)
	at com.databricks.spark.xml.parsers.StaxXmlParserUtils$.checkEndElement(StaxXmlParserUtils.scala:31)
	at com.databricks.spark.xml.util.InferSchema$.com$databricks$spark$xml$util$InferSchema$$inferObject(InferSchema.scala:208)
	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:101)
	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:89)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)`

What does this library do? I am shocked! Any suggestions?

**Comment by srowen** [comment]
In this case you need to specify a custom schema. Inference isn't working, and various issues with inference are already tracked elsewhere.
