### ISSUE TITLE
Load the whole xml as a row

### ISSUE THREAD

**Issue by donderom** [databricks/spark-xml#213]
Is there any way to load the whole XML without specifying the `rowTag`?

**Comment by HyukjinKwon** [comment]
I haven't tested this yet but I guess this works.

```
import com.databricks.spark.xml.XmlReader

val path = "path-to-files"
val rdd = sc.wholeTextFiles(path)
val df = new XmlReader().xmlRdd(sqlContext, rdd)
df.show()
```

BTW, we might need an option for this.

**Comment by donderom** [comment]
Thanks, it works without specifying the `rowTag` explicitly however it does not include the top level element. For example (where `books` is the top level tag):

```scala
import com.databricks.spark.xml.XmlReader

val rdd = sc.parallelize(Seq("<books><book>book1</book><book>book2</book></books>"))
val df = new XmlReader().xmlRdd(spark.sqlContext, rdd)
df.show

+--------------+
|          book|
+--------------+
|[book1, book2]|
+--------------+

df.printSchema

root
 |-- book: array (nullable = true)
 |    |-- element: string (containsNull = true)
```

The general idea is it to be similar to how json works in Spark:

```scala
val rdd = sc.parallelize(Seq("""{"books": { "book": ["book1", "book2"]}}"""))
val df = spark.read.json(rdd)
df.show

+--------------------+
|               books|
+--------------------+
|[WrappedArray(boo...|
+--------------------+

df.printSchema

root
 |-- books: struct (nullable = true)
 |    |-- book: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
```
Any ideas how to overcome it?

**Comment by HyukjinKwon** [comment]
Hm, yea, I understand it is a bit awkward. I ended up with doing as above, for example, due to the case below:

```json
{
  "a": {
    "b": "book1"
  },
  "b": 1
}
```

In this case, we can't convert this to ..

```xml
<a>
  <b>book1</b>
</a>
<b>1</b>
```

because as you see there are two separate root XML documents. It seems they are not directly compatible so it seems it had to have such a limitation.

If we have an option to deal with this case (assuming each file is each XML), we could deal with this I think.

BTW, I can;t think of other automatic workarounds for this for now. Maybe we can at least do this something like ...

```scala
val rdd = sc.parallelize(Seq("<books><book>book1</book><book>book2</book></books>"))
val df = new XmlReader().xmlRdd(spark.sqlContext, rdd)
df.selectExpr("struct(book) as books")
```

I will be back if I can come up with a better idea.

**Comment by donderom** [comment]
Do you think adding a new option for such behaviour would be ok?

**Comment by HyukjinKwon** [comment]
I am not too sure because it would break the current behaviour. BTW, I am just curious of your usecase and why the root element is needed. Maybe, we can build up a concrete reason to support to add the option with some reasonable usecases.

**Comment by donderom** [comment]
One of the use cases is that the type of the XML message can be known only from its top level element, like the following: `<DeviceType><...></DeviceType>`. The inner structure of the message can be the same but the top level `DeviceType` tag can be different and it's crucial for business logic.

**Comment by HyukjinKwon** [comment]
BTW, I just came up with a weird workaround as below:

```scala
import com.databricks.spark.xml.XmlReader

val path = "path-to-files"
val rdd = sc.wholeTextFiles(path)
val wrapped = rdd.map(xml => s"""<a>$xml</a>""")
val df = new XmlReader().xmlRdd(sqlContext, wrapped)
df.show()
```

**Comment by donderom** [comment]
This trick would work, thanks!

**Comment by sbumesh** [comment]
How do I specify a schema for this

import com.databricks.spark.xml.XmlReader

val path = "path-to-files"
val rdd = sc.wholeTextFiles(path)
val wrapped = rdd.map(xml => s"""<a>$xml</a>""")
val df = new XmlReader().xmlRdd(sqlContext, wrapped)
df.show()

**Comment by srowen** [comment]
Yeah, if you really only have one type of top level element, it _is_ the row tag. If it differs, you have (possibly) different schemas and can read for the different top-level elements separately. Otherwise, yes, wrap everything in an artifical top level element so you can treat the various possible children as optional struct elements.

**Comment by itachi-sharingan** [comment]
anyone any idea how we can do the same(read xml without rowtag) from python, this is what I am currently trying:-
spark=SparkSession.builder.appname('test').getOrCreate()
pyRdd=spark.read.text("xml-file-path", wholetext=True)
df=spark._jvm.com.databricks.spark.xml.XmlReader().xmlRdd(spark._jsparkSession.sqlContext(),pyRdd.rdd)
Unfortunately getting error:-
RDD object has no attribute '_get_object_id'

P.S - I also tried converting python rdd to java rdd but then it could not find a function with that signature
