### ISSUE TITLE
Write XML from data frame.. not able to create array in datafram

### ISSUE THREAD

**Issue by naveenreddy2811** [databricks/spark-xml#214]
`val final_df = sqlContext.sql("select _xmlns, Date_Crt, Creator, struct(_ngr, _region, SetofValues) as Station from (select _xmlns, Date_Crt, Creator, _ngr, _region, struct(_dataType, _period, Value) as SetofValues  from (select _xmlns, Date_Crt, Creator, _ngr, _region, _dataType, _period, struct(_VALUE, _time) as Value from df_h a left outer join df_ds b on a.batchId = b.batchId left outer join df_dsv c on b.batchId = c.batchId left outer join df_nv d on c.batchId = d.batchId))")
`
Above line returns schema as below

`root
 |-- _xmlns: string (nullable = true)
 |-- Date_Crt: string (nullable = true)
 |-- Creator: string (nullable = true)
 |-- Station: struct (nullable = false)
 |    |-- _ngr: string (nullable = true)
 |    |-- _region: string (nullable = true)
 |    |-- SetofValues: struct (nullable = false)
 |    |    |-- _dataType: string (nullable = true)
 |    |    |-- _period: string (nullable = true)
 |    |    |-- Value: struct (nullable = false)
 |    |    |    |-- _VALUE: double (nullable = true)
 |    |    |    |-- _time: string (nullable = true)`

`final_df.repartition(1).write.format("xml").option("rowTag","NewTag").save(output_path)
[xml_issue.txt](https://github.com/databricks/spark-xml/files/628716/xml_issue.txt)
`

when I am trying to save dataframe as XML using above command getting XML file as below.

`<ROWS>
    <NewTag xmlns="testing">
        <Date_Crt>2016-10-30</Date_Crt>
        <Creator>USER_1</Creator>
        <Station ngr="123456" region="North East">
            <SetofValues dataType="Total" period="15 min">
                <Value 3.509" time="05:30:00"></Value>
            </SetofValues>
        </Station>
    </NewTag>
    <NewTag xmlns="testing">
        <Date_Crt>2016-10-30</Date_Crt>
        <Creator>USER_1</Creator>
        <Station ngr="123456" region="North East">
            <SetofValues dataType="Total" period="15 min">
                <Value 2.6" time="05:45:00"></Value>
            </SetofValues>
        </Station>
    </NewTag>
    <NewTag xmlns="testing">
        <Date_Crt>2016-10-30</Date_Crt>
        <Creator>USER_1</Creator>
        <Station ngr="123456" region="North East">
            <SetofValues dataType="Total" period="15 min">
                <Value 1.111" time="06:00:00"></Value>
            </SetofValues>
        </Station>
    </NewTag>
</ROWS>
`

Output I am expecting is as below

`<NewTag xmlns="testing">
	<Date_Crt>2016-10-30</Date_Crt>
	<Creator>USER_1</Creator>
	<Station ngr="123456" region="North East">
		<SetofValues dataType="Total" period="15 min">
			<Value time="05:30:00">3.509</Value>
			<Value time="05:45:00">2.6</Value>
			<Value time="06:00:00">1.111</Value>
		</SetofValues>
	</Station>
</NewTag>
`

**Comment by naveenreddy2811** [comment]
XML format is noy coming correctly so attached the description along with XML format

**Comment by naveenreddy2811** [comment]
@HyukjinKwon can you have a look at this and let me know where i am doing wrong..

**Comment by anshsachdeva** [comment]
I am not sure we can do this directly with spark-xml library itself. But i have found alternate solution(Hive UDF) by which i can make list of struct as what is your requirements

UDF (CollectUDAF) : [https://github.com/klout/brickhouse]

Thanks
Ansh
