### ISSUE TITLE
Computed values using UDF and  standard functions

### ISSUE THREAD

**Issue by jvmlet** [databricks/spark-xml#215]
Hi
Is the  subject supported ? 
This feature, besides other advantages, would help to resolve the issue with no-standard  date formats

**Comment by HyukjinKwon** [comment]
As this is just a third-party library, I believe you could use all the functionalities in Spark.

**Comment by HyukjinKwon** [comment]
I am closing this for now. Please feel free to reopen this if you can't use Spark's UDF and etc.

**Comment by jvmlet** [comment]
I'll provide more details and let you decide if you want to have  this feature built-in, or not.
I'm using the `spark-xml` with provided schema to disable the schema auto-discovery and gain performance. One field of the schema has `TimestampType` type, but the value uses non-standard format, example : `2016-05-16T14:14:02`.
Out-of-the-box invocation fails with complain that value `2016-05-16T14:14:02` can't be translated to date time, so to overcome this I have to tweak the schema (replace `TimestampType` with `StringType` ), load the  dataframe and then use UDF to parse the string to TimeStamp:

````
df.withColumn(dateTimeColumn, callUDF(parseTimestamp, DataTypes.TimestampType, col(dateTimeColumn)) )
````

My suggestion is to have some kind of configuration/expression that should be used when loading and parsing the data, example :

````
sqlContext.udf.register("parseTimestamp",parseTimestamp);

dfReader.format("com.databricks.spark.xml")
.option("rowTag", "LogMessage")
.option("column.%name%.exp", "callUDF(parseTimestamp)")
````

or via Schema's DataField metadata :

````
StructType
  field.name = 'dateTimeColumn'
  field.type = DataTypes.TimestampType
  field.metadata= {"exp":"callUDF(parseTimestamp)"}
  
````
