### ISSUE TITLE
How to write Value in an element that has no child elements but attributes and Value.. valueTag

### ISSUE THREAD

**Issue by naveenreddy2811** [databricks/spark-xml#218]
When i am trying to write DataFrame using XML, new attribute is being created for element that has no child elements but attributes and Value. In below example.

I am getting below output
`<Values VALUE="0.56" date="2015-11-25" time="16:15:00"></Values>`

Where as i am expecting as below.

`<Values date="2015-11-25" time="16:15:00">0.56</Values>`

which option need to be used for this? 
does using "valueTag" option works, if so let me what is the correct way to use it?

**Comment by HyukjinKwon** [comment]
Ah, yes. it is related with `valueTag`.

You could do a roundtrip in reading and writing with the data below:

```xml
<ROWS>
    <ROW>
      <Values date="2015-11-25" time="16:15:00">0.56</Values>
    </ROW>
</ROWS>
```

with the codes below:

```scala
val path = "path-your-file"
val df = sqlContext.read.format("xml").option("valueTag", "#VALUE").load(path)
df.write.format("xml").option("valueTag", "#VALUE").save("/tmp/test1234")
```

or

```scala
val path = "path-your-file"
val df = sqlContext.read.format("xml").option("attributePrefix", "__").load(carsFile)
df.write.format("xml").option("attributePrefix", "__").save("/tmp/test1234")
```

It seems the default value of `attributePrefix` conflicts with `valueTag`'s `_`.

**Comment by naveenreddy2811** [comment]
Thanks @HyukjinKwon , it helped..

**Comment by HyukjinKwon** [comment]
@naveenreddy2811 I will try to make a PR to prevent the conflicts. Thank you for reporting this.
