### ISSUE TITLE
attribute names case sensitive?

### ISSUE THREAD

**Issue by tonizzz** [databricks/spark-xml#221]
Hi ,

Seems like attribute names are case sensitive. I have an XML with below "Company" as first in capital and my case class attributes are all lower case and "company" attribute is mapped as null.

`<Company><![CDATA[My Company]]></Company>`

I can't find configuration related to define the xml attributes as case insensitive. Do you think is there a way?

thanks!

**Comment by HyukjinKwon** [comment]
Yea, It is case sensitive. Actually, let me take out enhancement tag for now because I am not too sure if they should be supported or not. In Spark, JSON datasource also does not take care of if up to my understanding whereas CSV does.
