### ISSUE TITLE
is there any way to refer XSD as a schema reference to process xml messages ?

### ISSUE THREAD

**Issue by skm235** [databricks/spark-xml#224]

**Comment by HyukjinKwon** [comment]
Currently, it does not have a functionality for it. Feel free to open a PR for this.

**Comment by skm235** [comment]
I am sorry. Don't know how to do it.

**Comment by Sokrates80** [comment]
that will be great actually.

**Comment by MaciejGajewski** [comment]
I am also looking for this feature as I'm working with pretty big XMLs with plenty of optional tags. Would like to provide generic schema beforehand and have XML messages read into this schema (instead of infering the individual message schema) and have optional elements filled with nulls.

**Comment by marshackVB** [comment]
Just curious if there is an update on this. If not, any tips on how to approach the problem posed above by MacieGajewski would be much appreciated.

**Comment by srowen** [comment]
Someone would need to write a converter from XSD schema to a StructType for Spark. I'm not sure anyone is going to work on this, so it's open to those who want to submit a pull request for it.

**Comment by akshaygehi** [comment]
**I was thinking of using a two step approach of solving this problem without code changes:**

- Use a library to generate from an XSD its sample XMLs including optional attributes. For example XSInstance allows you to do this. You could alternatively use online generators or desktop tools such as LiquidXML to do this. 

- Once you have the sample XML, create a dataframe from this and export the schema into a JSON file. 

Now you can use this exported structure file during the actual parsing i.e. with the actual XML files

**Comment by srowen** [comment]
Maybe, as a general approach, though that seems kind of outside the scope of this library. Note that this can't work in the general case because XML and XSDs can follow schemas that don't conform to a tabular form.

**Comment by akshaygehi** [comment]
I agree with you. It will be outside the scope of the library and will only work as a workaround. Can you elaborate what you mean by general case? Are you pointing at some limitation in Spark DataFrame which would restrict having complex structures or something else?

**Comment by srowen** [comment]
No, simply that all DataFrames are tabular, and XML is not at all tabular.

**Comment by developeratkiit** [comment]
I am also looking for such function where i need to transform the dataframe to xsd and then write it as  XML file.

**Comment by srowen** [comment]
One thing I think we can do is simply validate the XML rows according to an XSD. It would still infer the schema separately, not from the XSD, but, presumably those are consistent if parsing succeeds.

**Comment by developeratkiit** [comment]
Thanks for response.

I have got a requirement where i have to read the schema frok XSD file and
then convert the input DataFrame as per schema and write the xml
accordingly.

Could you please suggest is there any provision for this.

**Comment by srowen** [comment]
That's the harder thing, defining the schema by XSD, and no it's not what I'm suggesting. Not all XML/XSDs make sense as tabular data of course, but more specifically, I can imagine that for some XML that _can_ have a schema inferred and validate against some XSD, that the XSD is hard or impossible to parse into the same schema.

But in your case, doesn't sound like you need a transformation - you just need validation. That much is easy. The idea is that the schema would still be separately inferred, but, presumably, the schema that is inferred for the XML is consistent with the XSD if it passes XSD validation.

You could think of it as a way to express additional validation that isn't possible just by checking that everything follows the same schema. I'm thinking of things like validating there are at most 3 repeating elements in some field, or that the values are in a range.
