### ISSUE TITLE
Input filename for files in archives

### ISSUE THREAD

**Issue by someonehere15** [databricks/spark-xml#226]
If I load the XML files from a folder, I get the source filename for each row through `input_file_name()`, but if I load the XML files from an archive (bz2 in my case), I get the same archive name for all the entries. Would it be possible for `input_file_name()` to show the source filenames from inside the archive here too, just like as if it was loading from a folder?

**Comment by HyukjinKwon** [comment]
I don't think it is possible.. let me update you if I get a better answer.

**Comment by srowen** [comment]
Here I think you'd just have to unpack the .bz2 archive.
