### ISSUE TITLE
How to Encode UTF-8 for Dataframe

### ISSUE THREAD

**Issue by shermilaguerra** [databricks/spark-xml#229]
Hi!
please, maybe you can help me.
How to encoding output to UTF-8, there are wrong values.

`coDf=Df.selectExpr("explode(copy)` as e").select("e._sourceOwner", "e._targetOwner","e._sourceKeySet", "e._targetKeySet", "e._sourceMetadata", "e._targetMetadata", "e._sourceValue", `"e._targetValue").show()`

> +---------------+--------------------+--------------------+--------------------+------------------+------------------+--------------------+--------------------+

|   _sourceOwner|        _targetOwner|       _sourceKeySet|       _targetKeySet|   _sourceMetadata|   _targetMetadata|        _sourceValue|        _targetValue|
+---------------+--------------------+--------------------+--------------------+------------------+------------------+--------------------+--------------------+
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|              Pais|              Pais|      Estados Unidos|      Estados Unidos|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|  Local publica��o|  Local publica��o|                    |      Estados Unidos|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|   Palavra-chave 1|   Palavra-chave 1|Positive definite...|   positive definite|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|   Palavra-chave 2|   Palavra-chave 2|Strict positive d...|Strictly Positive...|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|   Palavra-chave 3|   Palavra-chave 3|             Spheres|     complex spheres|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|   Palavra-chave 4|   Palavra-chave 4|    Disk polynomials|    disk polynomials|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|            T�tulo|            T�tulo|Generalized inter...|Generalized inter...|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|               Ano|               Ano|                1997|                1997|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|              Pais|              Pais|      Estados Unidos|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|Meio de divulga��o|Meio de divulga��o|            IMPRESSO|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|            Idioma|            Idioma|              Ingl�s|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|          Natureza|          Natureza|            COMPLETO|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|           Revista|           Revista|Numerical Functio...|Numerical Functio...|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|    P�gina inicial|    P�gina inicial|                 189|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|      P�gina final|      P�gina final|                 200|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|              ISSN|              ISSN|            01630563|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|            Volume|            Volume|                  18|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|             S�rie|             S�rie|                    |                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|         Fasc�culo|         Fasc�culo|                 1&2|                    |
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|  Local publica��o|  Local publica��o|                    |                    |

> +---------------+--------------------+--------------------+--------------------+------------------+------------------+--------------------+--------------------+
Very thranks, 
Sher

**Comment by shermilaguerra** [comment]
Hi!!! please can you help me,
I've been trying to process a textfile with Python.  
I've tried to fix this bug for 3 hours, but haven't found anything really useful. 
Can anyone tell me why the decode function not works?
my code is:
import os, sys
import codecs
reload(sys)
sys.setdefaultencoding('utf-8')

coDf=Df.selectExpr("explode(copy) as e").select("e._sourceOwner", "e._targetOwner",("e._sourceKeySet").encode("utf-8"), "e._targetKeySet", ("e._sourceMetadata").encode("utf-8"), "e._targetMetadata", "e._sourceValue", "e._targetValue").show()
+---------------+--------------------+--------------------+--------------------+------------------+------------------+--------------------+--------------------+
|   _sourceOwner|        _targetOwner|       _sourceKeySet|       _targetKeySet|   _sourceMetadata|   _targetMetadata|        _sourceValue|        _targetValue|
+---------------+--------------------+--------------------+--------------------+------------------+------------------+--------------------+--------------------+
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|              Pais|              Pais|      Estados Unidos|      Estados Unidos|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|  Local publica��o|  Local publica��o|                null|      Estados Unidos|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|   Palavra-chave 1|   Palavra-chave 1|Positive definite...|   positive definite|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|   Palavra-chave 2|   Palavra-chave 2|Strict positive d...|Strictly Positive...|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|   Palavra-chave 3|   Palavra-chave 3|             Spheres|     complex spheres|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Strict pos...|T�tulo=Strict pos...|   Palavra-chave 4|   Palavra-chave 4|    Disk polynomials|    disk polynomials|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|            T�tulo|            T�tulo|Generalized inter...|Generalized inter...|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|               Ano|               Ano|                1997|                1997|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|              Pais|              Pais|      Estados Unidos|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|Meio de divulga��o|Meio de divulga��o|            IMPRESSO|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|            Idioma|            Idioma|              Ingl�s|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|          Natureza|          Natureza|            COMPLETO|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|           Revista|           Revista|Numerical Functio...|Numerical Functio...|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|    P�gina inicial|    P�gina inicial|                 189|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|      P�gina final|      P�gina final|                 200|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|              ISSN|              ISSN|            01630563|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|            Volume|            Volume|                  18|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|             S�rie|             S�rie|                null|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|         Fasc�culo|         Fasc�culo|                 1&2|                null|
|Ana Paula Peron|Valdir Antonio Me...|T�tulo=Generalize...|T�tulo=Generalize...|  Local publica��o|  Local publica��o|                null|                null|
+---------------+--------------------+--------------------+--------------------+------------------+------------------+--------------------+--------------------+

very thrank,

**Comment by HyukjinKwon** [comment]
I guess you could have a good answer if you ask this to Spark user mailing list. It seems related with `.encode("utf-8")` functionality in Spark.

**Comment by shermilaguerra** [comment]
Maybe you can tell me the group?

**Comment by HyukjinKwon** [comment]
Here, https://spark.apache.org/community.html there are mailing lists.

**Comment by srowen** [comment]
I'm not sure this is even a Spark issue.. perhaps your console isn't set to display unicode glyphs. That is, the `<?>` chars may just be a cosmetic issue with your display.
