### ISSUE TITLE
How to save a dataframe in xml format?

### ISSUE THREAD

**Issue by shermilaguerra** [databricks/spark-xml#233]
Hi!!
How to save a pyspark sql DataFrame in xml format
I read xml  data in  pyspark. it transform in dataframe,  then in it made a transformation.
 Now I want to save it as xml format. 
How can I do this? 
Solution for directly saving the pyspark sql dataframe in xml.
 Thanks in advance. 
sher

**Comment by HyukjinKwon** [comment]
You could do something like the one below I guess

```python
df.select("author", "_id").write \
    .format('com.databricks.spark.xml') \
    .options(rowTag='book', rootTag='books') \
    .save('newbooks.xml')
```

**Comment by MaciejGajewski** [comment]
Hi,

I have similar issue however above saves dataframe to a folder named newbooks.xml with part* files inside rather to a single files newbooks.xml?
I've read about using Hadoop copyMerge to merge those files afterwards but is there a way to create files with specific names based e.g. on df column or input file name? Let's say I want to read 100 xml files with their specific names, transform them and write with same names (with suffix) so I end up also with 100 files.

Thanks
Maciej

**Comment by HyukjinKwon** [comment]
Thanks, @BioQwer. Let me leave this closed.
