### ISSUE TITLE
error to apply  explode  array  in xml 

### ISSUE THREAD

**Issue by shermilaguerra** [databricks/spark-xml#234]
In the first level when using "explode" in "ARTIGO_PUBLICADO" it works(please see schema).
When I use "explode" with the column "AUTORES" also it works.
But when I want to use it in the other columns it does not work, it show: due to data type mismatch: input to function explode should be array or map type, not StructType

dfx_2 = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ARTIGOS_PUBLICADOS', nullValue="").load("file:///home/cloudera/BigPrInt/Fontes/AnaPaulaPeron_v1.xml")

root
 |-- ARTIGO_PUBLICADO: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- AREAS_DO_CONHECIMENTO: struct (nullable = true)
 |    |    |    |-- AREA_DO_CONHECIMENTO_1: struct (nullable = true)
 |    |    |    |    |-- _NOME_DA_AREA_DO_CONHECIMENTO: string (nullable = true)
 |    |    |    |    |-- _NOME_DA_ESPECIALIDADE: string (nullable = true)
 |    |    |    |    |-- _NOME_DA_SUB_AREA_DO_CONHECIMENTO: string (nullable = true)
 |    |    |    |    |-- _NOME_GRANDE_AREA_DO_CONHECIMENTO: string (nullable = true)
 |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |    |-- AREA_DO_CONHECIMENTO_2: struct (nullable = true)
 |    |    |    |    |-- _NOME_DA_AREA_DO_CONHECIMENTO: string (nullable = true)
 |    |    |    |    |-- _NOME_DA_ESPECIALIDADE: string (nullable = true)
 |    |    |    |    |-- _NOME_DA_SUB_AREA_DO_CONHECIMENTO: string (nullable = true)
 |    |    |    |    |-- _NOME_GRANDE_AREA_DO_CONHECIMENTO: string (nullable = true)
 |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |-- AUTORES: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- _NOME_COMPLETO_DO_AUTOR: string (nullable = true)
 |    |    |    |    |-- _NOME_PARA_CITACAO: string (nullable = true)
 |    |    |    |    |-- _ORDEM_DE_AUTORIA: long (nullable = true)
 |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |-- DADOS_BASICOS_DO_ARTIGO: struct (nullable = true)
 |    |    |    |-- _ANO_DO_ARTIGO: long (nullable = true)
 |    |    |    |-- _DOI: string (nullable = true)
 |    |    |    |-- _FLAG_RELEVANCIA: string (nullable = true)
 |    |    |    |-- _HOME_PAGE_DO_TRABALHO: string (nullable = true)
 |    |    |    |-- _IDIOMA: string (nullable = true)
 |    |    |    |-- _MEIO_DE_DIVULGACAO: string (nullable = true)
 |    |    |    |-- _NATUREZA: string (nullable = true)
 |    |    |    |-- _PAIS_DE_PUBLICACAO: string (nullable = true)
 |    |    |    |-- _TITULO_DO_ARTIGO: string (nullable = true)
 |    |    |    |-- _TITULO_DO_ARTIGO_INGLES: string (nullable = true)
 |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |-- DETALHAMENTO_DO_ARTIGO: struct (nullable = true)
 |    |    |    |-- _FASCICULO: string (nullable = true)
 |    |    |    |-- _ISSN: string (nullable = true)
 |    |    |    |-- _LOCAL_DE_PUBLICACAO: string (nullable = true)
 |    |    |    |-- _PAGINA_FINAL: long (nullable = true)
 |    |    |    |-- _PAGINA_INICIAL: long (nullable = true)
 |    |    |    |-- _SERIE: long (nullable = true)
 |    |    |    |-- _TITULO_DO_PERIODICO_OU_REVISTA: string (nullable = true)
 |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |    |-- _VOLUME: long (nullable = true)
 |    |    |-- INFORMACOES_ADICIONAIS: struct (nullable = true)
 |    |    |    |-- _DESCRICAO_INFORMACOES_ADICIONAIS: string (nullable = true)
 |    |    |    |-- _DESCRICAO_INFORMACOES_ADICIONAIS_INGLES: string (nullable = true)
 |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |-- PALAVRAS_CHAVE: struct (nullable = true)
 |    |    |    |-- _PALAVRA_CHAVE_1: string (nullable = true)
 |    |    |    |-- _PALAVRA_CHAVE_2: string (nullable = true)
 |    |    |    |-- _PALAVRA_CHAVE_3: string (nullable = true)
 |    |    |    |-- _PALAVRA_CHAVE_4: string (nullable = true)
 |    |    |    |-- _PALAVRA_CHAVE_5: string (nullable = true)
 |    |    |    |-- _PALAVRA_CHAVE_6: string (nullable = true)
 |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |-- SETORES_DE_ATIVIDADE: struct (nullable = true)
 |    |    |    |-- _SETOR_DE_ATIVIDADE_1: string (nullable = true)
 |    |    |    |-- _SETOR_DE_ATIVIDADE_2: string (nullable = true)
 |    |    |    |-- _SETOR_DE_ATIVIDADE_3: string (nullable = true)
 |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |-- _SEQUENCIA_PRODUCAO: long (nullable = true)

dfx_2_ap=dfx_2.selectExpr("explode(ARTIGO_PUBLICADO) as e").select("e.*")
dfx_2_ap.printSchema()
dfx_2_ap.show()

dfx_2_ap_ac=dfx_2_ap.selectExpr("explode(AREAS_DO_CONHECIMENTO) as e2").select("e2.*")

cannot resolve 'explode(AREAS_DO_CONHECIMENTO)' due to data type mismatch: input to function explode should be array or map type, not StructType(StructField(AREA_DO_CONHECIMENTO_1,StructType(StructField(_NOME_DA_AREA_DO_CONHECIMENTO,StringType,true), StructField(_NOME_DA_ESPECIALIDADE,StringType,true), StructField(_NOME_DA_SUB_AREA_DO_CONHECIMENTO,StringType,true), StructField(_NOME_GRANDE_AREA_DO_CONHECIMENTO,StringType,true), StructField(_VALUE,StringType,true)),true))

**Comment by HyukjinKwon** [comment]
It seems the error as said,

```
cannot resolve 'explode(AREAS_DO_CONHECIMENTO)' due to data type mismatch: input to function explode should be array or map type, not 
```

It seems `AREAS_DO_CONHECIMENTO` is `StructType`. It seems `explode` should be applied with `ArrayType` or `MapType`.

**Comment by shermilaguerra** [comment]
hi,
for struct to use explode. For array element that:
ArtPublicadodf.select(ArtPublicadodf.AUTORES._NOME_COMPLETO_DO_AUTOR).show()
there are another way?
best regards!
Sher

**Comment by shermilaguerra** [comment]
Why when I retrieve data from an array, it shows me in the brackets?

dAna2=dfArtPublicadosA.select(dfArtPublicadosA.AUTORES._NOME_COMPLETO_DO_AUTOR, dfArtPublicadosA.AUTORES._NOME_PARA_CITACAO, dfArtPublicadosA.AUTORES._ORDEM_DE_AUTORIA).collect()
 

	NOME_COMPLETO_DO_AUTOR 	NOME_PARA_CITACAO 	ORDEM_DE_AUTORIA
0 	[Valdir Antonio Menegatto, Ana Paula Peron] 	[MENEGATTO, V. A., PERON, A. P.;Peron, Ana P.] 	[1, 2]
1 	[Valdir Antonio Menegatto, Ana Paula Peron] 	[MENEGATTO, V. A., PERON, A. P.;Peron, Ana P.] 	[1, 2]
2 	[Valdir Antonio Menegatto, Ana Paula Peron] 	[MENEGATTO, V. A., PERON, A. P.;Peron, Ana P.] 	[1, 2]
3 	[Valdir Antonio Menegatto, Ana Paula Peron] 	[MENEGATTO, V. A., PERON, A. P.;Peron, Ana P.] 	[1, 2]
4 	[V A Menegatto, Ana Paula Peron] 	[MENEGATTO, V A, PERON, A. P.;Peron, Ana P.] 	[1, 2]
5 	[V A Menegatto, C P Oliveira, Ana Paula Peron] 	[MENEGATTO, V A, OLIVEIRA, C P, PERON, A. P.;P... 	[1, 2, 3]
6 	[Valdir A Menegatto, C P Oliveira, Ana Paula P... 	[MENEGATTO, Valdir A, OLIVEIRA, C P, PERON, A.... 	[1, 2, 3]
7 	[Valdir A Menegatto, C P Oliveira, Ana Paula P... 	[MENEGATTO, Valdir A, OLIVEIRA, C P, PERON, A.... 	[1, 2, 3]
8 	[Valdir Antonio Menegatto, Oliveira, C. P., An... 	[MENEGATTO, V. A., Oliveira, C. P., Peron, Ana... 	[1, 2, 3]
9 	[Claudinei, V A Menegatto, Ana Paula Peron] 	[FERREIRA, JOSÉ CLAUDINEI, MENEGATTO, V A, PER... 	[1, 2, 3]
10 	[V A Menegatto, Oliveira, C. P., Ana Paula Peron] 	[MENEGATTO, V A, Oliveira, C. P., PERON, A. P.] 	[1, 2, 3]
