### ISSUE TITLE
The fields with extra whitespaces have correctly passed through the XML validation against their correct types (xsd:double, xsd:dateTime, etc) but fail during parsing in spark-xml

### ISSUE THREAD

**Issue by kkaduk** [databricks/spark-xml#236]
Elements in xml document for example  &lt; tagA &gt; 12.33  &lt; /tagA &gt; (trailing or leading spaces ) are not correctly converted with exception:
java.lang.NumberFormatException: For input string: "  12.33   "
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)

Also kills the spark executor and fails the entire Spark job.

**Comment by HyukjinKwon** [comment]
Thanks for reporting this.

**Comment by HyukjinKwon** [comment]
Fixed in #237
