### ISSUE TITLE
Failing accessing to nested values. 

### ISSUE THREAD

**Issue by carloallocca** [databricks/spark-xml#238]
Dear All, 

I would like to report an issue when parsing an XML file. 

More specifically: given the following XML data structure:

xocs:doc
 |-- xocs:item: struct (nullable = true)
 |    |-- bibrecord: struct (nullable = true)
 |    |    |-- head: struct (nullable = true)
 |    |    |    |-- abstracts: struct (nullable = true)
 |    |    |    |    |-- abstract: struct (nullable = true)
 |    |    |    |    |    |-- _original: string (nullable = true)
 |    |    |    |    |    |-- _lang: string (nullable = true)
 |    |    |    |    |    |-- ce:para: string (nullable = true) 

CASE 1:

String rowTag="abstracts”; 
Dataset<Row> df = (new XmlReader()).withAttributePrefix("_").withRowTag(rowTag).xmlFile(sqlContext, localxml);
df.select(df.col("abstract.ce:para"), df.col("abstract._original"),df.col("abstract._lang") ).show();

I got the right values. 

CASE 2:

String rowTag="xocs:doc";
Dataset<Row> df = (new XmlReader()).withAttributePrefix("_").withRowTag(rowTag).xmlFile(sqlContext, localxml);
df.select(df.col("xocs:item.item.bibrecord.head.abstracts.abstract.ce:para")).show();

I got null values.

My question is: How Can I get it right to use String rowTag="xocs:doc”; and get the right values for  ….abstract.ce:para, etc? what am I doing wrong? 

Many Thanks in advance.
Best Regards,
Carlo

=== This is the code I have been using 

public static void main(String arr[]) {
            String localxml = "/Users/carloallocca/Desktop/Spark Material/63449138399.xml";
            String rowTag="xocs:doc";
            SparkSession spark = SparkSession
                .builder()
                .master("local[2]")
                .appName("DatasetForCaseNew")
                .getOrCreate();
            SQLContext sqlContext = new SQLContext(spark);

            Dataset<Row> df = (new XmlReader()).withAttributePrefix("_").withRowTag(rowTag).xmlFile(sqlContext, localxml);
            df.show();
        
            df.printSchema();
        
//        df.select(df.col("xocs:item.item.bibrecord.head.abstracts.abstract.ce:para")).show();
//        df.select(df.col("abstract.ce:para"), df.col("abstract._original"),df.col("abstract._lang") ).show();
        
        df.select(df.col("abstracts.abstract.ce:para")).show();
        
        //df.select(df.col("abstracts.abstract.ce:para"), df.col("abstracts.abstract._original"),df.col("abstracts.abstract._lang") ).show();

**Comment by HyukjinKwon** [comment]
Thanks for reporting this. Let me take a look soon.

**Comment by HyukjinKwon** [comment]
@carloallocca, are you maybe able to share `/Users/carloallocca/Desktop/Spark Material/63449138399.xml` file or the sample of it?

**Comment by HyukjinKwon** [comment]
Let me try to test with  ...

```xml
<xocs:doc>
  <xocs:item>
     <item>
       <bibrecord>
         <head>
    <abstracts>
       <abstract original="y" xml:lang="eng”>
 <ce:para>
  ...
```

but please let me know this is different.

**Comment by carloallocca** [comment]
Uhhh..I cannot share it here as it is, unfortunately. I am  happy to send a version of it with fake data but with the same complexity. The xml file contains many nested, it is quite complex one. 
[63449138399fake.xml.zip](https://github.com/databricks/spark-xml/files/785324/63449138399fake.xml.zip)

**Comment by carloallocca** [comment]
Hi Hyukjin,  
Thanks. The structure is a bit different. I sent you a zip file containing the right one. I had to change it and put some fake data. 
This is the level on nesting to get the abstract: 
xocs:doc/xocs:item/item/bibrecord/head/abstracts/abstract/ce:para

Many Thanks,Best Regards,Carlo 
Please, let me know if you received it. 

    Il Sabato 18 Febbraio 2017 18:31, Hyukjin Kwon <notifications@github.com> ha scritto:
 

 Let me try to test with ...<xocs:doc>
  <xocs:item>
     <item>
       <bibrecord>
         <head>
    <abstracts>
       <abstract original="y" xml:lang="eng”>
 <ce:para>
  ...but please let me know this is different.—

**Comment by carloallocca** [comment]
This is the new path

xocs:doc/xocs:item/item/bibrecord/head/abstracts/abstract/ce:para

**Comment by HyukjinKwon** [comment]
Thank you!

**Comment by HyukjinKwon** [comment]
Hi @carloallocca, it seems working okay in the master

```java
(new XmlReader()).withAttributePrefix("_").withRowTag("xocs:doc").xmlFile(sqlContext, path)
  .select(df.col("xocs:item.item.bibrecord.head.abstracts.abstract.ce:para")).show();
```

```
+--------------------+
|             ce:para|
+--------------------+
|This paper presen...|
+--------------------+
```

Do you mind if I ask which version you are using?

**Comment by carloallocca** [comment]
Many Thanks Hyukjin, 
I am using the following:
<dependency>            <groupId>elsevierlabs-os</groupId>            <artifactId>spark-xml-utils</artifactId>            <version>1.4.0</version>        </dependency>

What about you?Please, could you let me know?
Many Thanks in advance.Carlo 

    Il Domenica 19 Febbraio 2017 8:19, Hyukjin Kwon <notifications@github.com> ha scritto:
 

 Hi @carloallocca, it seems working okay in the master(new XmlReader()).withAttributePrefix("_").withRowTag("xocs:doc").xmlFile(sqlContext, path)
  .select(df.col("xocs:item.item.bibrecord.head.abstracts.abstract.ce:para")).show();+--------------------+
|             ce:para|
+--------------------+
|This paper presen...|
+--------------------+
Do you mind if I ask which version you are using?—

**Comment by carloallocca** [comment]
sorry this one:
<dependency>            <groupId>com.databricks</groupId>            <artifactId>spark-xml_2.10</artifactId>            <version>0.4.0</version>        </dependency> 

    Il Domenica 19 Febbraio 2017 12:42, Carlo Allocca <carloallocca@yahoo.it> ha scritto:
 

 Many Thanks Hyukjin, 
I am using the following:
<dependency>            <groupId>elsevierlabs-os</groupId>            <artifactId>spark-xml-utils</artifactId>            <version>1.4.0</version>        </dependency>

What about you?Please, could you let me know?
Many Thanks in advance.Carlo 

    Il Domenica 19 Febbraio 2017 8:19, Hyukjin Kwon <notifications@github.com> ha scritto:
 

 Hi @carloallocca, it seems working okay in the master(new XmlReader()).withAttributePrefix("_").withRowTag("xocs:doc").xmlFile(sqlContext, path)
  .select(df.col("xocs:item.item.bibrecord.head.abstracts.abstract.ce:para")).show();+--------------------+
|             ce:para|
+--------------------+
|This paper presen...|
+--------------------+
Do you mind if I ask which version you are using?—

**Comment by carloallocca** [comment]
I have just realised that the note above is not readable.
The version that I am using is the following:

<dependency>
            <groupId>com.databricks</groupId>
            <artifactId>spark-xml_2.10</artifactId>
            <version>0.4.0</version>
        </dependency>

**Comment by carloallocca** [comment]
which version did you use for your test?if you do not mind

**Comment by HyukjinKwon** [comment]
Maybe are you able to test this with 0.4.1?
