### ISSUE TITLE
How I can to generalize xml reading in pySpark

### ISSUE THREAD

**Issue by shermilaguerra** [databricks/spark-xml#242]
Hi!!
Please maybe you can help me. 
I would like to rewrite this function, it is  in scala to PySpark. 

def children(colname: String, df: DataFrame) = {
  val parent = df.schema.fields.filter(_.name == colname).head
  val fields = parent.dataType match {
    case x: StructType => x.fields
    case _ => Array.empty[StructField]
  }
  fields.map(x => col(s"$colname.${x.name}"))
}

 in pyspark  i dont fin DATATYPE Property 

df_1.selectExpr("explode(ARTIGO_PUBLICADO.DADOS_BASICOS_DO_ARTIGO) as e").head  
bound method DataFrame.head of DataFrame[e: struct<_ANO_DO_ARTIGO:bigint,_DOI:string,_FLAG_RELEVANCIA:string,_HOME_PAGE_DO_TRABALHO:string,_IDIOMA:string,_MEIO_DE_DIVULGACAO:string,_NATUREZA:string,_PAIS_DE_PUBLICACAO:string,_TITULO_DO_ARTIGO:string,_TITULO_DO_ARTIGO_INGLES:string,_VALUE:string>]>

aaa=df_1.selectExpr("explode(ARTIGO_PUBLICADO.DADOS_BASICOS_DO_ARTIGO) as e").head

aaa.dataType
AttributeError                            Traceback (most recent call last)
<ipython-input-70-68a23dc973eb> in <module>()
----> 1 aaa.dataType

AttributeError: 'function' object has no attribute 'dataType'

Best regards.
Shermila.

**Comment by HyukjinKwon** [comment]
Hm.. I think you want

```
df_1.selectExpr("explode(ARTIGO_PUBLICADO.DADOS_BASICOS_DO_ARTIGO) as e").schema.head
```

...?
