### ISSUE TITLE
XML will not parse when reading from Kafka unless rowTag is the highest-level tag

### ISSUE THREAD

**Issue by harrisonmebane** [databricks/spark-xml#244]
We noticed this when reading XML from Kafka where `rowTag` was set to a tag other than the highest tag in the document.  For example, in
```xml
<topLevel>
  <nextLevel>
    <value>val</value>
  </nextLevel>
<topLevel>
```
If we set the `rowTag` to `topLevel`, everything parses fine.  If we instead set it to `nextLevel`, we get a DataFrame with a single null value.

We do not notice this behavior when reading from files, only reading from RDD (from Kafka).  We are using Spark 2.0, spark-xml 0.4.1, and Kafka 0.10.0 (using the new Kafka010 API to read from Kafka).

**Comment by HyukjinKwon** [comment]
Hm... it seems working okay.

```scala
spark.read.format("xml").option("rowTag", "nextLevel").load("path").show()
```

```
+-----+
|value|
+-----+
|  val|
+-----+
```

Do you mind if I ask some more contexts? Let me try to reproduce that.

**Comment by harrison-sbry** [comment]
Sure, I apologize I'm not able to isolate the issue more myself.  Whatever is happening is buried in our application code.  I only noticed this issue after our upgrade to Spark 2.0, Kafka 10.  And to reiterate, we _only_ see this when reading from Kafka, so it's hard to reproduce without a full environment.  There is no issue when reading from a file.  I cannot guarantee that this is an issue with `spark-xml`, but I thought I should report it, just in case.

**Comment by harrisonmebane** [comment]
Sure, I apologize I'm not able to isolate the issue more myself. Whatever is happening is buried in our application code. I only noticed this issue after our upgrade to Spark 2.0, Kafka 10. And to reiterate, we only see this when reading from Kafka, so it's hard to reproduce without a full environment. There is no issue when reading from a file. I cannot guarantee that this is an issue with spark-xml, but I thought I should report it, just in case.

**Comment by HyukjinKwon** [comment]
Yea, definitely good to report this. Thank you. Let me maybe try to do several things by myself.

**Comment by harrisonmebane** [comment]
Never mind, it was something I was doing in the code.  Apologies for the false alarm, and thanks for looking into it!  Closing this now.

**Comment by harrisonmebane** [comment]
I would no longer classify this an issue, but it might be helpful to be aware of the problem I was running into.  We have an application that takes a configuration file that specifies tables to be created from XML.  Our code parses this configuration into a Spark schema for the XML document and passes it to the XML parser.  When the rowTag in the configuration file is not the highest-level tag, our generated schema knows about the rowTag but not any higher-level tags.  This appears to be okay when reading from a file, but the xmlRDD code appears to handle this differently and can't read a document with a schema that starts at the rowTag and doesn't contain the higher-level tags.

Let me know if that doesn't make sense.
