### ISSUE TITLE
Converting named properties to tags

### ISSUE THREAD

**Issue by bolau** [databricks/spark-xml#248]
Hi all,
I've got close to a million XML files that have a structure like this:
```
<root>
  <property key="name">
    [content data]
  </property>
  <property key="address">
    [content data]
  </property>
  ...
</root>
```

There are many different property keys, and only some of them are present in each file. The resulting schema and data structures are not nice, since the properties are converted to arrays with many nones.
I would highly prefer the kind of schema I get from an input like this:

```
<root>
  <name>
    [content data]
  </name>
  <address>
    [content data]
  </address>
  ...
</root>
```

What's the best way to deal with this? Is there a feature to convert values of attributes like "key" to tags for given tags like "property" during parsing? Does it make sense if I implement this, or is it easier to do it in a pre- or postprocessing step?

Thanks for any help
Boris

**Comment by HyukjinKwon** [comment]
I don't think it's currently possible in this library..

**Comment by srowen** [comment]
Yeah, as you say, this will already parse `property` directly as an array of pairs of attribute and values. That's a good literal interpretation of the XML schema into a table-like DataFrame. Assuming you can't change your XML, you can manipulate the DataFrame into what you want. For sake of argument let's say you also had an ID column, then:

- explode the property array
- pivot on the key-values to make the keys into columns

```
df.withColumn("e", explode(col("property"))).groupBy("id").pivot("e._key").agg(first("e._VALUE"))
```

For that reason I'd say we maybe don't need to add special handling of this in this library.
