### ISSUE TITLE
unable to read xml file in spark standalone mode

### ISSUE THREAD

**Issue by pmakkena** [databricks/spark-xml#249]
hi,
I am using spark 2.1.0(scala 2.11.8) in windows stand-alone mode. I followed your instructions and started the spark shell using command
%SPARK_HOME%/spark-shell --packages com.databricks:spark-xml_2.11:0.4.1. Then I got this output.

Ivy Default Cache set to: C:\Users\SONY\.ivy2\cache
The jars for the packages stored in: C:\Users\SONY\.ivy2\jars
:: loading settings :: url = jar:file:/C:/Users/SONY/Desktop/SPARK/jars/ivy2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-xml_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
        found com.databricks#spark-xml_2.11;0.4.1 in central
:: resolution report :: resolve 768ms :: artifacts dl 0ms
        :: modules in use:
        com.databricks#spark-xml_2.11;0.4.1 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
        confs: [default]
        0 artifacts copied, 1 already retrieved (0kB/31ms)

**After spark-shell opened I run these commands**

import org.apache.spark.sql.SQLContext
val sqlContext = new SQLContext(sc)
val df = sqlContext.read.format("com.databricks.spark.xml").option("rowtag","Id").load("C:\\Users\\SONY\\Desktop\\Posts.small.xml")

Then I got the following error:
java.lang.ClassNotFoundException: Failed to find data source: com.databricks.spark.xml. Please find packages at http://spark.apache.org/third-party-projects.html
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:569)     
                                                                                                                                                                        
 -----------------------------------
Caused by: java.lang.ClassNotFoundException: com.databricks.spark.xml.DefaultSource
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:62)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)                                                                             
  -------------.
I am not able to find what is the problem and I have gone through previous issues with a similar problem.

**Comment by HyukjinKwon** [comment]
It sounds like a Windows specific issue within Spark. Could you try out if the codes below work too if possible?

```
--packages com.databricks:spark-avro_2.11:3.2.0
```

and 

```scala
import com.databricks.spark.avro._
import org.apache.spark.sql.SparkSession

val spark = SparkSession.builder().master("local").getOrCreate()

val df = spark.createDataFrame(
  Seq(
    (2012, 8, "Batman", 9.8),
    (2012, 8, "Hero", 8.7),
    (2012, 7, "Robot", 5.5),
    (2011, 7, "Git", 2.0))
  ).toDF("year", "month", "title", "rating")

df.toDF.write.partitionBy("year", "month").avro("/tmp/output")
```

**Comment by pmakkena** [comment]
The above code is also not working in windows stand alone mode. 
Now I installed centos on my VM and both the codes mentioned above are working fine.

**Comment by HyukjinKwon** [comment]
I will try this out in Windows soon.

**Comment by srowen** [comment]
This is ultimately something to do with Spark, Windows and `--packages` in the shell, rather than this project
