### ISSUE TITLE
input_file_name not working in spark-xml

### ISSUE THREAD

**Issue by thiru-incedo** [databricks/spark-xml#251]
Hi, I'm trying to add input file name for every row when loading xml file through com.databricks.spark.xml format. But it is returning empty column for filename.. Below is the code snippet. I'm using input_file_name function

sqlContext.read.format("com.databricks.spark.xml").
option("rowTag", "BO_RECORD").
load("file:///<**path**>/*").
withColumn("filename",input_file_name()).show()

+------------+-----------+---------------+--------+
|TicketRefund|TicketsSold|_corrupt_record|filename|
+------------+-----------+---------------+--------+
|           0|          3|           null|        |
|           0|          1|           null|        |
|           0|         18|           null|        |
|           0|         22|           null|        |
|           0|          3|           null|        |
+------------+-----------+---------------+--------+

I tried with different ways, but still it returns empty filename when using com.databricks.spark.xml. 

sqlContext.read.format("com.databricks.spark.xml").
option("rowTag", "BO_RECORD").
load("file:///<**path**>/*").select(input_file_name()).show()

However it works good when doing a normal data-frame load for text files.Kindly help.

**Comment by HyukjinKwon** [comment]
It was an issue within spark. Please refer https://github.com/databricks/spark-xml/issues/203.

**Comment by thiru-incedo** [comment]
Hi @HyukjinKwon , Thanks for looking into. Issue #203 refers that input_file_name() does not work when used within UDF. But the issue I posted, I'm not using in UDF, but directly adding it as a column (using withColumn) which is returning empty records. 

Could you please check that ? Pardon me if my understanding is wrong.

**Comment by HyukjinKwon** [comment]
Do you mind if I ask version informations for Spark and spark-xml please? let me try it. Is it Python?

**Comment by thiru-incedo** [comment]
@HyukjinKwon I'm using Spark 1.6.1 With Scala 2.11.8 and spark-xml_2.10:0.4.1

**Comment by HyukjinKwon** [comment]
Ah, could you try this with 0.3.5? 0.4.x is for Spark 2.x.x.

**Comment by thiru-incedo** [comment]
@HyukjinKwon tried 0.3.5, still the same issue.
spark-shell --packages com.databricks:spark-xml_2.10:0.3.5

**Comment by HyukjinKwon** [comment]
I see. Let me try this out soon.

**Comment by thiru-incedo** [comment]
@HyukjinKwon , yes please. I need this function very badly, as there is a requirement based on this. Do you suggest any alternate ways till then ?

**Comment by simond** [comment]
This is an issue for me too. I am trying to parse over 2.5 million xml files and it seems that I wont be able to log which ones fail due to malformed XML if I cant get the file name. Is there a workaround for this or is it in the pipeline to be fixed?

**Comment by Vijayatagore** [comment]
org.apache.spark.sql.AnalysisException: cannot resolve '`tablename.input__file__name`' given input columns: [col1, col2, col3-------------so on]; line 1 pos 805;
'Project [*]
+- 'SubqueryAlias viewname, `dbname`.`viewname`
   +- 'Project ['col1 AS col1#374, 'col2 AS col2#375, 'col3 AS col3#376, 'so on]
      +- 'SubqueryAlias dbname.view_name
         +- 'Project [version AS col#373, so on 'tablename.input__file__name, date#387]
            +- MetastoreRelation dbname, tablename

getting problem in reading view. getting input__file__name exception

**Comment by wangxisea** [comment]
any updates on this one?

**Comment by catherine-drivin** [comment]
I'd also like to know if there are any updates?

**Comment by HyukjinKwon** [comment]
Guys, this should really be a problem within Spark. Mind double checking if this thing only happens with Spark XML thirdparty library?
