### ISSUE TITLE
Include option to remove non valid characters in host language for attribute and element names

### ISSUE THREAD

**Issue by mtrivolli** [databricks/spark-xml#252]
Some characters like "-" or "." are not valid as part of an identifier in Java or Scala. As a consequence, XML files including these characters as part of attribute or element names have limited possibilities of using the schema provided by encoders. The following example shows the problem:
```xml
<root>
     <person id="xxx" first-name="John" last-name="Ford"/>
</root>
```
```scala
case class Person(id: String, first-name: String, last-name: String)
 val df = spark.read
      .format("com.databricks.spark.xml")
      .option("rowTag", "person")
      .schema(Encoders.product[Person].schema)
```
Since first-name or last-name are not valid Scala identifiers, the code above will not compile. One possible approach is to include a new option to discard certain characters, similar to "attributePrefix":
```scala
case class Person(id: String, firstname: String, lastname: String)
 val df = spark.read
      .format("com.databricks.spark.xml")
      .option("rowTag", "person")
      .option("excludeTagCharacters", "-")
      .schema(Encoders.product[Person].schema)
```

**Comment by HyukjinKwon** [comment]
Probably, we could just rename it after loading it as a workaround and the workaround looks pretty easy. I am not sure if we need this yet of this.

**Comment by mtrivolli** [comment]
Would you mind if I prepare a PR?

**Comment by HyukjinKwon** [comment]
Hm... I am not too sure if we really need this as an option yet. I have been trying only to add an option for the case that could not be easily worked around or that is pretty much common/reasonable. This case I guess could be easily worked around.

**Comment by mtrivolli** [comment]
What would you suggest as a workaround? My point is to facilitate the use of case classes as schema input for the reader as in the example above, but also to transform data:
```scala
 val output = input.as[Record].rdd.map(r => r.firstname + " " + r.lastname)
```
This is an elegant approach that takes advantage of Scala type system.

**Comment by srowen** [comment]
This is a case where you'd build the schema manually, or else get a schema from your case class (with some variant of the identifiers that are valid in Scala) and map the names in the schema.
