### ISSUE TITLE
If all column values for Row is null or empty , an empty row is returned

### ISSUE THREAD

**Issue by KenpachiRules** [databricks/spark-xml#254]
Say for example an XML schema ?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="part">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="P_PARTKEY" type="xs:int" />
					<xs:element name="P_NAME" type="xs:string" />
					<xs:element name="P_CONTAINER" type="xs:string" />
					<xs:element name="P_RETAILPRICE" type="xs:decimal" />
					<xs:element name="P_COMMENT" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

if all the values for the columns come empty or null , an Row with no column values are returned . Shouldnt there be an option to drop a record whose columns contains no data?.

**Comment by srowen** [comment]
I think that's correct behavior. If the tag exists but is empty, is should be a Row with nulls. See https://github.com/databricks/spark-xml/pull/355
