### ISSUE TITLE
How can I write null dataframe?

### ISSUE THREAD

**Issue by Jimmyst** [databricks/spark-xml#255]
Hello!
I have a problem with saving dataframe.
My xml's based on xsd scheme, and I use this global scheme to parse my xml's (I just created full xml, read it and use dataframe's generated scheme)
The problems begins, when one of my xml's does't have specific filed - it couse the reason why my dataframe become empty (but with correct scheme). When I want to save this dataframe to file - I expected to have a "null"'s? but I have nothing - just empty file.

How can I save empty dataframe with fields filld as nulls?

**Comment by HyukjinKwon** [comment]
So, the problem is unable to write out nulls. I think there is no way to do this for now. I guess this is the same issue with JSON one in Spark. I am currently not sure yet of how much common it would be though.
