### ISSUE TITLE
content of fields in array are swapped

### ISSUE THREAD

**Issue by smailio** [databricks/spark-xml#258]
I have this job with which I'm trying to parse xml. 
    
    import lombok.Data;
    import org.apache.spark.sql.*;
    import org.apache.spark.sql.types.*;
    import java.util.List;
    import static org.apache.spark.sql.types.DataTypes.StringType;
    import static org.apache.spark.sql.types.DataTypes.createArrayType;

    public class Job {
    
        public static void main(String[] args) {
    
            SparkSession session = SparkSession.builder().appName("SandBoxJob").master("local[*]").getOrCreate();
            final StructType InpiIMRInstanceCourtXML = struct( //
                    field("_siren"), //
                    field("_dat_donnees"), //
                    field("_num_gestion"), //
                    field("reps", struct(//
                            array("rep", //
                                    field("qual"), //
                                    field("nom_denom") //
                            ) //
                        ) //
                    ) //
            );
    
            SQLContext sqlContext = new SQLContext(session);
            Dataset<Row> rows = sqlContext
                    .read()
                    .format("com.databricks.spark.xml")
                    .option("rowTag", "societe")
                    .schema(InpiIMRInstanceCourtXML)
                    .load("path/small_sample.xml");
    
            rows.as(Encoders.bean(CompanyRow.class)).foreach(row -> System.out.println(row));
        }
    
        private static StructField field(String name) {
            return new StructField(name, StringType, true, Metadata.empty());
        }
    
        private static StructType struct(StructField... fieldList) {
            return DataTypes.createStructType(fieldList);
        }
    
        private static StructField array(String name, StructField... fieldList) {
            return field(name, createArrayType(struct(fieldList)));
        }
    
        private static StructField field(String name, DataType dataType) {
            return new StructField(name, dataType, true, Metadata.empty());
        }
    
        @Data
        public static class CompanyRow{
            private String _siren;
            private String _dat_donnees;
            private String _num_gestion;
            private Reps reps;
        }
    
        @Data
        public static class Rep{
            private String qual;
            private String nom_denom;
        }
    
        @Data
        public static class Reps{
            private List<Rep> rep;
        }
    }
  
---
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <fichier type="RCS" version="1.2">
        <grf cod="9721">
            <societe dat_donnees="20170427" num_gestion="1974B00079" siren="303184345">
                <reps>
                    <rep>
                        <qual>0600</qual>
                        <nom_denom>NADJAT</nom_denom>
                    </rep>
                    <rep>
                        <qual>0600</qual>
                        <nom_denom>VERLOCHE Jean</nom_denom>
                    </rep>
                    <rep>
                        <qual>0120</qual>
                        <nom_denom>RENARD</nom_denom>
                    </rep>
                    <rep>
                        <qual>0600</qual>
                        <nom_denom>CAYARD</nom_denom>
                    </rep>
                    <rep>
                        <qual>0110</qual>
                        <nom_denom>BARAT</nom_denom>
                    </rep>
                    <rep>
                        <qual>1400</qual>
                        <nom_denom>BUSCHER</nom_denom>
                    </rep>
                    <rep>
                        <qual>1500</qual>
                        <nom_denom>ASSIE</nom_denom>
                    </rep>
                </reps>
            </societe>
        </grf>
    </fichier>
---
this is the output produced, as you can see the content of the fields qual and nom_denom are swapped.  

     Job.CompanyRow(_siren=303184345, _dat_donnees=20170427, _num_gestion=1974B00079,    reps=Job.Reps(rep=[Job.Rep(qual=NADJAT, nom_denom=0600), Job.Rep(qual=VERLOCHE Jean, nom_denom=0600), Job.Rep(qual=RENARD, nom_denom=0120), Job.Rep(qual=CAYARD, nom_denom=0600), Job.Rep(qual=BARAT, nom_denom=0110), Job.Rep(qual=BUSCHER, nom_denom=1400), Job.Rep(qual=ASSIE, nom_denom=1500)]))

I am using the java api with spark-xml_2.11 0.4.1 and spark 2.0.2

**Comment by smailio** [comment]
It works well when I put my fields in this order 

            final StructType InpiIMRInstanceCourtXML = struct( //
                    field("_dat_donnees"), //
                    field("_num_gestion"), //
                    field("_siren"), //
                    field("reps", struct(//
                            array("rep", //
                                    field("nom_denom"), //
                                    field("qual") //
                            ) //
                        ) //
                    ) //
            );

**Comment by HyukjinKwon** [comment]
Sounds like a bug. Will take a look soon. Thanks for reporting this.

**Comment by srowen** [comment]
I can't reproduce this. In Scala:

```
case class Rep(var qual: String, nom_denom: String) {
  override def toString(): String = s"Rep[qual:$qual, nom_denom:$nom_denom]"
}

case class Reps(var rep: Array[Rep])

case class CompanyRow(var _siren: String,
                      var _dat_donnees: String,
                      var _num_gestion: String,
                      var reps: Reps)

val repsType = StructType(Array(
      StructField("rep", ArrayType(StructType(Array(
        StructField("qual", StringType, true),
        StructField("nom_denom", StringType, true)
      )), true), true)))
    val InpiIMRInstanceCourtXML = StructType(Array(
      StructField("_siren", StringType, true),
      StructField("_dat_donnees", StringType, true),
      StructField("_num_gestion", StringType, true),
      StructField("reps", repsType)))

    val df = spark.read
      .option("rowTag", "societe")
      .schema(InpiIMRInstanceCourtXML)
      .xml("src/test/resources/fichier.xml")

    df.as(Encoders.product[CompanyRow]).foreach { c =>
      println(c.reps.rep.mkString(","))
    }
```

yields:

```
Rep[qual:0600, nom_denom:NADJAT],Rep[qual:0600, nom_denom:VERLOCHE Jean],Rep[qual:0120, nom_denom:RENARD],Rep[qual:0600, nom_denom:CAYARD],Rep[qual:0110, nom_denom:BARAT],Rep[qual:1400, nom_denom:BUSCHER],Rep[qual:1500, nom_denom:ASSIE]
```

That appears correct. Maybe it was fixed previously already. In any event the issue would be in translating the DF to a bean via Encoder; it seems like the DF had correctly parsed the XML?
