### ISSUE TITLE
Cannot load XML with embedded binary data

### ISSUE THREAD

**Issue by thaivinhnguyen** [databricks/spark-xml#259]
Hi all,

I have an XML file exported from SQL Server that embeds a field of binary data. 

I use spark-xml to load this XML file, but the result is just an empty DataFrame. 

Any suggestion how to deal with such file? 

Thanks.

**Comment by HyukjinKwon** [comment]
Would you mind share your codes?

**Comment by thaivinhnguyen** [comment]
This is the code I wrote to load the xml file:

```spark
val fn = "test.xml"
val xml_data = spark.read
    .format("com.databricks.spark.xml")
    .option("rowTag", "Record")
    .load(fn)
```

and the content of **test.xml** file

```xml
<Record><Id>1</Id><Data>H4sIAAAAAAAAC7PxCPH1sbPxcHV0sbMJ8QzxcbULzSvJLMlJTbHRh/BtgkMigZSBjT6EYaMPUe3k7xJpx8tlE2AXkpGqkJZfoZCYl6JQAmSn5+enKKQXJRakFuvZ6AdAFAGNCfL3c7dzB0rqgcwC84iQttEH2wS0FuRUAMzGgnKxAAAA</Data></Record>
```

**Comment by thaivinhnguyen** [comment]
I just run the code again and the result is no longer an empty DataFrame. 

This is quite strange. What happened here was that I copy the content of the xml file exported from SQL Server and paste to another file, then everything seems to work. 

My guess is that the binary data is encoded in to string while copying-pasting into the SubLime Text editor.

**Comment by HyukjinKwon** [comment]
Hm.. I tried few times but I could not reproduce. Will probably take another look soon when I have some time.

**Comment by thaivinhnguyen** [comment]
I resolved this problem. What I need to do was setting the option 'charset' to 'UTF-16BE' or 'UTF-16LE'. Then, I can load the xml file correctly to spark. 
```
val fn = "test.xml"
val xml_data = spark.read
    .format("com.databricks.spark.xml")
    .option("rowTag", "Record")
    .option("charset", "UTF-16BE")
    .load(fn)

The other encoding (UTF-8 or UTF-16) didn't work.
