### ISSUE TITLE
Connection refused: pyspark --packages com.databricks:spark-xml_2.11:0.4.1

### ISSUE THREAD

**Issue by rfad** [databricks/spark-xml#265]
I have a case to extract XML data into a relational structure in Hive/Impala. Have come across this Spark package: 
https://github.com/databricks/spark-xml

When i run this command: pyspark --packages com.databricks:spark-xml_2.11:0.4.1

I get these warnings and errors. Is there something wrong that i am doing: 
My proxy settings are okay on the server.

:::: WARNINGS
                module not found: com.databricks#spark-xml_2.11;0.2.0

        ==== local-m2-cache: tried

          file:/root/.m2/repository/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.pom

          -- artifact com.databricks#spark-xml_2.11;0.2.0!spark-xml_2.11.jar:

          file:/root/.m2/repository/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.jar

        ==== local-ivy-cache: tried

          /root/.ivy2/local/com.databricks/spark-xml_2.11/0.2.0/ivys/ivy.xml

        ==== central: tried

          https://repo1.maven.org/maven2/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.pom

          -- artifact com.databricks#spark-xml_2.11;0.2.0!spark-xml_2.11.jar:

          https://repo1.maven.org/maven2/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.jar

        ==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.pom

          -- artifact com.databricks#spark-xml_2.11;0.2.0!spark-xml_2.11.jar:

          http://dl.bintray.com/spark-packages/maven/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: com.databricks#spark-xml_2.11;0.2.0: not found

                ::::::::::::::::::::::::::::::::::::::::::::::

:::: ERRORS
        Server access error at url https://repo1.maven.org/maven2/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.pom (java.net.ConnectException: Connection refused)

        Server access error at url https://repo1.maven.org/maven2/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.jar (java.net.ConnectException: Connection refused)

        Server access error at url http://dl.bintray.com/spark-packages/maven/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.pom (java.net.ConnectException: Connection refused)

        Server access error at url http://dl.bintray.com/spark-packages/maven/com/databricks/spark-xml_2.11/0.2.0/spark-xml_2.11-0.2.0.jar (java.net.ConnectException: Connection refused)

**Comment by HyukjinKwon** [comment]
Hm, can you check out path or conf? Looks it tries to search 0.2.0. I guess it is not an issue of this library anyway ... let me leave this resolve but probably you could ask to Spark's mailing list.
