### ISSUE TITLE
Dataframe is null when parent and child tag names are same and parent and child tag are in different partition

### ISSUE THREAD

**Issue by AshwaniGaur** [databricks/spark-xml#266]
Had raised this issue #148, which was linked to #160 and fixed in #161. However, we still face the issue when the content is large enough to split parent and child tag in different partition. In such case, child tag is treated as parent tag and everything goes haywire. Could there be a solution where a schema could be provided with xml, which would help create the dataframe.

**Comment by HyukjinKwon** [comment]
Would you mind providing reproducer? Let me take a look.
