### ISSUE TITLE
How to set attributes on the root tag when writing an XML file?

### ISSUE THREAD

**Issue by tacareyNBC** [databricks/spark-xml#268]
How does one set attributes on the root tag when writing XML?

**Comment by HyukjinKwon** [comment]
You could do this as below:

```scala
Seq(("1", "b")).toDF("_id", "value").write.format("xml").option("attributePrefix", "_").save("foo")
```

```
cat foo/*
```

```xml
<ROWS>
    <ROW id="1">
        <value>b</value>
    </ROW>
</ROWS>
```

**Comment by vinothkumarsubbu** [comment]
Hi HyukjinKwon,
I think the Question and answer are not relevant, Here he has raised the question of adding attributes to Root Tag but the answer is for adding the attribute to row tag.


`<ROWS id="1">
    <ROW>
        <value>b</value>
    </ROW>
	<ROW>
        <value>c</value>
    </ROW>
</ROWS>`


So, can we reopen this?

**Comment by andrecamillo** [comment]
It is an old and closed topic but specifying the attributes on the **rootTag** option like below did work for me. (Tested on Spark 1.6.0 with with jar spark-xml_2.10, version:  0.3.5)

`dataframe.write.format("com.databricks.spark.xml").option("rootTag", """MyRootTag SomeAttribute="Value123" """).save("hdfs://my_path/")`

**Comment by gasparda** [comment]
Hi, will this be reopened? We have the same usecase.

**Comment by srowen** [comment]
Hm, what happens if you set `rowTag` to something like `root foo="bar"`? I think it might just work, even though it looks weird.

**Comment by srowen** [comment]
Oh wait, that won't work because it'll put that in the close tag. Well it would be easy enough to just use the leading non-whitespace chars as the root close tag, which would make this hack work. I could try it.

**Comment by gasparda** [comment]
Thanks a lot!

**Comment by srowen** [comment]
Should work in the next version, after https://github.com/databricks/spark-xml/pull/470
