### ISSUE TITLE
How to read a encoded/decoded data in xml format using pyspark?

### ISSUE THREAD

**Issue by khwajabhai** [databricks/spark-xml#269]
from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)

df1 = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='data').load('/sample.xml')
df1.show()

I am using the above  code.  But i am unable to do so and also i am using spark-xml_2.11-0.4.1.jar with 2.1 Spark version.

**Comment by HyukjinKwon** [comment]
I think you could use `charset` option like `options(charset='...')`.

**Comment by srowen** [comment]
Not clear what the question is ...
