### ISSUE TITLE
How to read dynamic xml as string type with out specifying schema.

### ISSUE THREAD

**Issue by mytramesh** [databricks/spark-xml#271]
Since my xml files are dynamic and nested  from different  sources I am not able to specify schema, it automatically inferring the schema and changing my data.
Sample file
-------
<xml>
  <Id>0001<Id>
</xml>

After reading with out specifing schema
<xml>
  <Id>1<Id> . // Data got changed 
</xml>
It treating as number and removing my prefixed zeros.  while processing strictly I should not change the data.

Please guide me is there is way How to read xml file with specifying Schema type and  should treat everything string type?

**Comment by srowen** [comment]
You can't read data of differing schemas together; they wouldn't make sense in a DataFrame. If you just mean that some fields are optional, you can specify a schema that marks those fields as optional. You can also parse different XML files with different schemas separately. The library does some basic schema inference already.
