### ISSUE TITLE
Process one large XML file

### ISSUE THREAD

**Issue by hongjiedai** [databricks/spark-xml#273]
I try to use the following code to process a large XML file from 
https://ftp.ncbi.nlm.nih.gov/pubmed/baseline/medline17n0001.xml.gz

```
var sparkConf = new SparkConf();
sparkConf.SetAppName("XML example");
var sparkContext = new SparkContext(sparkConf);
var sqlContext = new SqlContext(sparkContext);
var MedlineCitation = new StructField("MedlineCitation", new StructType(new List<StructField>() { 
new StructField("PMID", new LongType()) }));
var PubmedArticle = new StructType(new List<StructField>() { MedlineCitation });
var pubmedDataFrame =
                sqlContext.Read()
                    .Format("com.databricks.spark.xml")
                    .Options(new Dictionary<string, string>() { 
                        {"rowTag", "PubmedArticle"},
                        {"excludeAttribute", "true"}
                    }).Schema(PubmedArticle)
                    .Load("medline17n0001.xml");
Console.WriteLine(pubmedDataFrame.Count());

```
It works fine if I read from a small XML file containing the first record I want to extract from the XML file, but fails when loading from the original XML file.
Is it the limitation of the tool or anything I am wrong?

**Comment by HyukjinKwon** [comment]
Would you mind if I ask to share the error message?

**Comment by HyukjinKwon** [comment]
Oh, thing is, this is .gz. It is not splittable so it'd probably throw an OOM. I think you should use splittable ones, for example, bz2.

**Comment by hongjiedai** [comment]
I have extracted the xml file from the gz file.
It shows 0 without any error messages.

I also try to show the scheme and it show an empty result. But if I only use top20 elements in the file, it can be successfully parsed and show the scheme and counts..

**Comment by HyukjinKwon** [comment]
Will try to reproduce and take a look soon.

**Comment by hongjiedai** [comment]
Is there any update about the issue?

**Comment by AnandMariappan** [comment]
I am using your jar to process a complex XML file of 4GB size.
File size of 100MB  are getting processed without issues. But when I want to process files in GBs I get 'lost executor' errors. I tried to set the below values which are reasonable. But I could not avoid the executor lost errors. I could not get much help from other sources.

Any help would be really appreciated.

This is how I invoke the spark-shell.

spark-shell \
--master yarn \
--num-executors 100 \
--executor-memory 10G \
--conf spark.driver.memory=8G \
--conf spark.driver.am.memory=8G \
--conf spark.yarn.am.memoryOverhead=4096 \
--conf spark.yarn.am.cores=2 \
--conf spark.shuffle.compress=true \
--conf spark.network.timeout=1200s \
--conf spark.executor.heartbeatInterval=1200s \
--conf spark.sql.broadcastTimeout=1900 \
--conf spark.shuffle.spill.compress=true \
--conf spark.sql.inMemoryColumnarStorage.compressed=true \
--conf spark.sql.inMemoryColumnarStorage.batchSize=10000 \
--conf spark.sql.shuffle.partitions=100 \
--conf spark.sql.tungsten.enabled=true \
--driver-java-options -Dlog4j.configuration=file:log4j.properties \
--conf spark.sql.autoBroadcastJoinThreshold=-1 \
--executor-cores 4 \
--jars  spark-xml_2.10-0.4.1.jar

scala> val xml_dt = "source.xml" 

scala> val xml_ld = sqlContext.read.format("com.databricks.spark.xml").option("rowTag","Package").load(xml_dt)
[STage 0:===============================> (33+1) / 34]180/04/26 16:31:32 ERROR cluster.YarnScheduler: Lost executor 29 on hostname. Container marked as failed. Exit status 143. Diagnostics: Container killed on request.
Killed by external signal

**Comment by srowen** [comment]
I think these are Spark and memory resource errors, not specific to this library.
