### ISSUE TITLE
in pyspark how should I read the type: array the struct, after reading the xml?

### ISSUE THREAD

**Issue by shermilaguerra** [databricks/spark-xml#274]
Hi Hyukjin !
in pyspark how  I can to read the data type: array, struct type, after reading the xml? My xml has no fixed structure. Sometimes is Array in another xml is struct?

df_xml = spark.read.format('com.databricks.spark.xml').options(rowTag='ARTIGOS_PUBLICADOS', nullValue="", ).load(path_long)
best regards!!

**Comment by HyukjinKwon** [comment]
I think we should avoid the schema inference and set the explicit schema. There should be a limitation as XML is semi-structured data ...
