### ISSUE TITLE
how to explode nested array ?

### ISSUE THREAD

**Issue by shermilaguerra** [databricks/spark-xml#277]
Hi  Hyukjin!
Please, 
df_o1 = spark.read.format('com.databricks.spark.xml').options(rowTag='sort_by_timestamp',nullValue="",` ).load(path)
`df_o1.printSchema()`
root
 |-- remove: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- _date: string (nullable = true)
 |    |    |-- _objectName: string (nullable = true)
 |    |    |-- _status: string (nullable = true)
 |    |    |-- _targetContext: string (nullable = true)
 |    |    |-- _targetKeySet: string (nullable = true)
 |    |    |-- _targetOwner: string (nullable = true)
 |    |    |-- edit: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |    |    |-- _date: string (nullable = true)
 |    |    |    |    |-- _objectName: string (nullable = true)
 |    |    |    |    |-- _sourceValue: string (nullable = true)
 |    |    |    |    |-- _status: string (nullable = true)
 |    |    |    |    |-- _targetContext: string (nullable = true)
 |    |    |    |    |-- _targetKeySet: string (nullable = true)
 |    |    |    |    |-- _targetMetadata: string (nullable = true)
 |    |    |    |    |-- _targetOwner: string (nullable = true)
 |    |    |    |    |-- _targetValue: string (nullable = true)

`df_o1.selectExpr("explode(remove)` as e").count()
520

df_o1.selectExpr("explode(remove.edit)

 as e").select("e.*" ).collect()
df_o1.selectExpr("explode(remove.edit) as e").count()
520

df_o1.selectExpr("explode(remove.edit) as e").take(1)

[Row(e=[Row(_VALUE=None, _date='11:22:44@15/05/2017', _objectName='Autor', _sourceValue=None, _status='Editing', _targetContext='Título=A Support System for Content-Based Medical Image Retrieval in Object-Oriented Databases;Ano=1997;Revista=Journal of Medical Systems', _targetKeySet='Nome=Caetano Traina Jr', _targetMetadata='Nome para Citação', _targetOwner='Agma Juci Machado Traina', _targetValue='TRAINA JR, Caetano'), Row(_VALUE=None, _date='11:22:44@15/05/2017', _objectName='Autor', _sourceValue=None, _status='Editing', _targetContext='Título=A Support System for Content-Based Medical Image Retrieval in Object-Oriented Databases;Ano=1997;Revista=Journal of Medical Systems', _targetKeySet='Nome=Caetano Traina Jr', _targetMetadata='Ordem de autoria', _targetOwner='Agma Juci Machado Traina', _targetValue='1')])]

The problem is that it doubles the result. It should show only as an answer [x] but it is showing [x, x] when I do df_o1.selectExpr("explode(remove.edit) as e").take(1)

I’m very grateful to you for helping me

**Comment by BioQwer** [comment]
Hello @shermilaguerra .
I tryed repeat your example, with example data.
I think you need second `explode`.
Maybe my example will be helpfull for you

```xml
<myRoot>
    <elem>
        <a>Something a</a>
        <somethingelse>
            <mySomething>
                <id>0</id>
                <arr>
                    <elem>1</elem>
                    <elem>2</elem>
                </arr>
            </mySomething>
            <mySomething>
                <id>1</id>
                <arr>
                    <elem>3</elem>
                    <elem>4</elem>
                </arr>
            </mySomething>
        </somethingelse>
    </elem>
</myRoot>
```

```scala 
    val df = sqlContext.read.format("xml")
      .option("excludeAttribute", "false")
      .option("rowTag", "elem")
      .xml("src/test/resources/example.xml")

    df.printSchema()

    df.selectExpr("explode(somethingelse.mySomething.arr) as e")
      .selectExpr("explode(e.elem) as e")
      .select("e").show(100)
```

```
root
 |-- a: string (nullable = false)
 |-- somethingelse: struct (nullable = false)
 |    |-- mySomething: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- arr: struct (nullable = true)
 |    |    |    |    |-- elem: array (nullable = true)
 |    |    |    |    |    |-- element: long (containsNull = true)
 |    |    |    |-- id: long (nullable = true)

+---+
|  e|
+---+
|  1|
|  2|
|  3|
|  4|
+---+
```

**Comment by HyukjinKwon** [comment]
Let me leave this closed. Thanks for the output @BioQwer.

**Comment by Buyannemekh** [comment]
Hello, I'd like to extend this and include the ID to get an output like this:

+---+---+
|  e   |   id | 
+---+---+
|  1    |   0 | 
|  2   |   0  | 
|  3   |   1  | 
|  4   |   1  | 
+---+---+

How would I achieve this? Thank you.

**Comment by srowen** [comment]
This isn't related to spark-xml per se; you just need to use the Spark `explode` function on an array.

**Comment by kumarks1122** [comment]
@Buyannemekh you can achieve this by selecting both columns after `explode`
FYI:
```
df.selectExpr("explode(somethingelse.mySomething.arr) as e", "explode(somethingelse.mySomething.arr) as e", "explode(somethingelse.mySomething.id) as id")
      .selectExpr("explode(e.elem) as e", "id")
      .select("e", "id").show(100)
```
