### ISSUE TITLE
How to write with xml tag at the first line of file?

### ISSUE THREAD

**Issue by ichakid** [databricks/spark-xml#278]
I have written xml file from dataframe using write. But the xml file does not contain any xml tag like: 
`<?xml version="1.0"?>`
How do I add this tag when writing dataframe into xml?

**Comment by feryandi** [comment]
Does anyone know how to do this properly?

**Comment by HyukjinKwon** [comment]
It's not supported yet. Probably we would need this option from a very quick look.

**Comment by HyukjinKwon** [comment]
Dueplicate of #74
