### ISSUE TITLE
Detecting malformed XMLs not matching custom schema

### ISSUE THREAD

**Issue by MaciejGajewski** [databricks/spark-xml#280]
Hi,

Is there a way to detect and rejetct/mark as corrupted XMLs which are not matching with custom schema provided (e.g. some tag names are different).

Thanks
Maciej

**Comment by HyukjinKwon** [comment]
It's not supported. We could ignore the mismatched fields or throw an error on this. Maybe we can provide more option for it but it kinda needs a quite big effort and good design. Not sure yet if it's worth (to me). Please go ahead with a PR if you have a concrete idea and patch.

**Comment by srowen** [comment]
Permissive mode sort of does this, right? it can ignore bad rows and put them in a separate column.
