### ISSUE TITLE
Spark version conflict issue

### ISSUE THREAD

**Issue by Joongho** [databricks/spark-xml#281]
When I run in DBR3.5 ( spark2.2.1) , it failed
java.lang.ClassNotFoundException: com.databricks.spark.xml.util.InferSchema$

But run OK in Spark2.1 cluster. 
Looks like it's spark version conflict.

Can you build using spark2.2.1 ?

**Comment by HyukjinKwon** [comment]
It sounds just simply because the jar file was not found in your new cluster .. are you sure that's a problem from this library?

**Comment by srowen** [comment]
That doesn't sound like a Spark version conflict, but that the spark-xml library was missing or the wrong version.
