### ISSUE TITLE
[BUG] Array of structs drops elements

### ISSUE THREAD

**Issue by lokm01** [databricks/spark-xml#284]
This issue was observed both on 0.4.1 and master with Spark 2.2.1 (after fixing dependencies)
`
<myRoot>
	<elem>
		<a>Something a</a>
		<mySomethings>
			<mySomething>
				<id>0</id>
				<b>blahblah</b>
				<c>abc</c>
			</mySomething>
			<mySomething>
				<id>1</id>
				<b>blahblah2</b>
				<c>abc2</c>
			</mySomething>
		</mySomethings>
		<somethingelse>xyz</somethingelse>
	</elem>
</myRoot>
`

`
    val schema = StructType(Seq(
    	StructField("a", StringType),
    	StructField("mySomethings", ArrayType(
    		StructType(Seq(
    		    StructField("mySomething", StructType(Seq(
      			  StructField("id", IntegerType),
    			    StructField("b", StringType),
    			    StructField("c", StringType)  		        
    		    )))
    		))
    	)),
    	StructField("somethingelse", StringType)
    ))
`
`
    val df = sqlContext.read.format("xml").schema(schema).option("rowTag", "elem").load("src/test/resources/array-object.xml")
    
    df.show(false) 
`
Produces:
+-----------+----------------------+-------------+
|a          |mySomethings          |somethingelse|
+-----------+----------------------+-------------+
|Something a|[[[1,blahblah2,abc2]]]|xyz          |
+-----------+----------------------+-------------+

I.e drops the first array element.

**Comment by lokm01** [comment]
Hmmm... Should this be a bug? Looking at the implementation and it seems that for

`<as>
   <a>..</a>
   <a>..</a>
</as>
`

<as> is a struct of ArrayType <a> rather than the other way around... To us this seems counter intuitive

**Comment by lokm01** [comment]
Nevermind, I guess this is a problem with loosely typed formats like XML...

**Comment by lokm01** [comment]
Actually maybe we could produce a warning when we rewrite an existing element in the Row object so that it doesn't drop array elements completely quietly when someone's got the manual schema wrong??

**Comment by BioQwer** [comment]
@lokm01 hello.
I tryed make flatten your example, and doesn't see error.
```scala
    val df = sqlContext.read.format("xml")
      .option("excludeAttribute", "false")
      .option("rowTag", "elem")
      .xml("src/test/resources/example-284.xml")

    df.printSchema()
    df.show(1000)

    df.select("mySomethings").collect().foreach(println)
```

```
root
 |-- a: string (nullable = false)
 |-- mySomethings: struct (nullable = false)
 |    |-- mySomething: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- b: string (nullable = true)
 |    |    |    |-- c: string (nullable = true)
 |    |    |    |-- id: long (nullable = true)
 |-- somethingelse: string (nullable = false)

+-----------+--------------------+-------------+
|          a|        mySomethings|somethingelse|
+-----------+--------------------+-------------+
|Something a|[WrappedArray([bl...|          xyz|
+-----------+--------------------+-------------+

[[WrappedArray([blahblah,abc,0], [blahblah2,abc2,1])]]
```

**Comment by HyukjinKwon** [comment]
@BioQwer, you are my hero.
