### ISSUE TITLE
spark xml creation issue with JAVARDD

### ISSUE THREAD

**Issue by Siddendra** [databricks/spark-xml#287]
We are trying to create the xml file in spark job with javaRDD and Dataframes in java language. we have defile the custom StructType to supporting our xml elements code is like below

```
JavaRDD<Row> rowRdd =FeedAttributes.map(attribute ->RowFactory.create(
                            attribute.getProducts()));finalStructTypestruct=DataTypes.createStructType(fields);StructType st3 =newStructType(newStructField[]{newStructField("productName",DataTypes.StringType,true,null),newStructField("instock",DataTypes.IntegerType,true,null)});finalDataFrame df2 =this.sqlCon.createDataFrame(rowRdd, st3);finalHdfsReader reader =newHdfsReader(conf);
            df2.repartition(1).write().mode(SaveMode.Overwrite).format("com.databricks.spark.xml").option("rootTag","CATALOG").save(folder.toString());

```

Bean is 
```
public class FeedAttributes implements Serializable{
private final List<ProductAttributes> products;

}
```
We are facing the below exception, please suggest us the best way to generate the xml file org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 4, localhost): scala.MatchError: (StringType,[ProductAttributes(productName=Bed, instock=1)]) (of class scala.Tuple2) at com.databricks.spark.xml.parsers.stax.StaxXmlGenerator$$anonfun$com$databricks$spark$xml$parsers$stax$StaxXmlGenerator$$writeElement$1$1.apply(StaxXmlGenerator.scala:38) at com.databricks.spark.xml.parsers.stax.StaxXmlGenerator$$anonfun$com$databricks$spark$xml$parsers$stax$StaxXmlGenerator$$writeElement$1$1.apply(StaxXmlGenerator.scala:38) at com.databricks.spark.xml.parsers.stax.StaxXmlGenerator$$anonfun$com$databricks$spark$xml$parsers$stax$StaxXmlGenerator$$writeElement$1$1$$anonfun$apply$3.apply(StaxXmlGenerator.scala:86) at com.databricks.spark.xml.parsers.stax.StaxXmlGenerator$$anonfun$com$databricks$spark$xml$parsers$stax$StaxXmlGenerator$$writeElement$1$1$$anonfun$apply$3.apply(StaxXmlGenerator.scala:74) at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108) at com.databricks.spark.xml.parsers.stax.StaxXmlGenerator$$anonfun$com$databricks$spark$xml$parsers$stax$StaxXmlGenerator$$writeElement$1$1.apply(StaxXmlGenerator.scala:74) at com.databricks.spark.xml.parsers.stax.StaxXmlGenerator$$anonfun$com$databricks$spark$xml$parsers$stax$StaxXmlGenerator$$writeElement$1$1.apply(StaxXmlGenerator.scala:38) at com.databricks.spark.xml.parsers.stax.StaxXmlGenerator$.apply(StaxXmlGenerator.scala:92) at com.databricks.spark.xml.package$XmlSchemaRDD$$anonfun$5$$anon$1.next(package.scala:106) at com.databricks.spark.xml.package$XmlSchemaRDD$$anonfun$5$$anon$1.next(package.scala:93) at scala.collection.Iterator$$anon$11.next(Iterator.scala:328) at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply$mcV$sp(PairRDDFunctions.scala:1109) at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply(PairRDDFunctions.scala:1108) at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply(PairRDDFunctions.scala:1108) at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1285)

**Comment by srowen** [comment]
You're making a Row directly, with types that aren't allowed in a row, like your custom class.
