### ISSUE TITLE
Small files 

### ISSUE THREAD

**Issue by geoHeil** [databricks/spark-xml#296]
How do you handle the hdfs small files problem? 
Is https://github.com/ZuInnoTe/hadoopoffice/wiki/Improve-performance-for-processing-a-lot-of-small-Office-files-with-Hadoop-Archives-(HAR) also working?

**Comment by HyukjinKwon** [comment]
Spark itself has a mechanism to merge small files into fewer partitions, for internal datasources. For datasource version 1 which currently Spark-XML uses, it's not. I think this issue should be more specific to Spark itself. Let me leave it resolved.

**Comment by geoHeil** [comment]
But how do you handle this problem currently? Do you concatenate  to sequence files or do you simply ignore it and do not face a hefty performance penalty after all?
