### ISSUE TITLE
How to parse a dataframe containing xml strings?

### ISSUE THREAD

**Issue by bhagya-gj** [databricks/spark-xml#297]
I need help with this problem where i have an input .dat file containing pipe delimited data.
One of the column will contain an XML.
I need to parse the XML on each row and load the parsed data into relevant tables.

I was able to split the file and extract the XML column alone and was able to load the XML column alone into a Dataframe. but i am not sure if i can use explode functions directly on a dataframe to parse the data.
Please let me know any pointers.

I looked into this thread but unclear about any solution
https://github.com/databricks/spark-xml/issues/140

**Comment by HyukjinKwon** [comment]
Shall we talk in #140? I think https://github.com/databricks/spark-xml/issues/140#issuecomment-268326368 works from a very quick look.

**Comment by DivyaJain84** [comment]
Same issue...when i am trying to explode xml string using XMLReader getting below exception
Caused by: java.lang.ClassCastException: com.sun.xml.internal.stream.events.StartDocumentEvent cannot be cast to javax.xml.stream.events.StartElement

Any help is highly appreciated

**Comment by uradhakrishna** [comment]
#297 is resolved ? becoz #140 is not clear about the conclusion

**Comment by uradhakrishna** [comment]
> I need help with this problem where i have an input .dat file containing pipe delimited data.
> One of the column will contain an XML.
> I need to parse the XML on each row and load the parsed data into relevant tables.
> 
> I was able to split the file and extract the XML column alone and was able to load the XML column alone into a Dataframe. but i am not sure if i can use explode functions directly on a dataframe to parse the data.
> Please let me know any pointers.
> 
> I looked into this thread but unclear about any solution
> #140

I too have similar problem , could you please let me know finally whats the resolution ?
