### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jameswinegar** [databricks/spark-xml#307]
With the latest commit https://github.com/databricks/spark-xml/commit/f3772b296d77a5a92ae4e714f3f8cb9940f1f0f9 which has a pretty large fix for me personally, is there a plan to publish a new version to Maven anytime soon?

**Comment by HyukjinKwon** [comment]
Was waiting for other PRs to be get in but probably I think we should do this soon.

**Comment by jameswinegar** [comment]
Which PRs? I might work on them since a lot of them look like a lot of them have low commitment.

**Comment by HyukjinKwon** [comment]
https://github.com/databricks/spark-xml/pull/293 one. Seems he got stuck. Would you be willing to take over this? I think the only things is just to address comments and clean up.
