### ISSUE TITLE
Complex XML docs with dynamic structures can lead to JaninoRuntimeException

### ISSUE THREAD

**Issue by cartershanklin** [databricks/spark-xml#309]
Version 0.4.1

Attempting to process data from the "IRS 990 returns" dataset at: https://aws.amazon.com/blogs/publicsector/irs-990-filing-data-now-available-as-an-aws-public-data-set/ which includes 1 million+ XML files.

To start out easy I tried it on 20 files and was successful.

Next I tried it on 50 files and it fails:

Caused by: org.codehaus.janino.JaninoRuntimeException: Constant pool for class org.apache.spark.sql.catalyst.expressions.GeneratedClass$Specifi
cSafeProjection has grown past JVM limit of 0xFFFF

There error also includes a dump of 342890 lines of generated code. I can make this error available if it helps but probably you can just pick any 50 files at random from the dataset and reproduce the error.

Relevant code options I used were:

```
    val df = sqlContext.read.format("com.databricks.spark.xml")
        .option("rowTag", "Return")
        .option("rootTag", "Return")
        .load("mypath")
```

In case it helps:
Others have noted they would like the ability to turn off schema inference, which I strongly support as well for a variety of reasons. If it would avoid code generation issues like this, that would be an excellent option to have IMO. The problem with using a low sampling ratio is this dataset has a lot of fields which are usually numbers but sometimes strings and a low ratio may result in runtime non-deterministic behavior.

**Comment by srowen** [comment]
This is ultimately a Spark issue, and I'd try version 2.4.x, as janino generation has been improved a lot in recent versions. I don't know if schema inference is the issue here, but yes that's on the list of feature requests.
