### ISSUE TITLE
.load() doesn't seem to support lists

### ISSUE THREAD

**Issue by jpmorris** [databricks/spark-xml#310]
DataFrame reader supports a list for load:

[https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=load#pyspark.sql.DataFrameReader.load](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=load#pyspark.sql.DataFrameReader.load)

But when I try the same on spark 2.3.0 (on Databricks) with spark-xml 2.11-0.4.1:

sqlContext.read.format('xml').load([file1, file2])

i get the error:

'path' must be specified for XML data

**Comment by HyukjinKwon** [comment]
It should be an issue in Spark ...

**Comment by rfibigr** [comment]
Did you have more information about this issue ?
