### ISSUE TITLE
Generate XML root element with attribute for XML in Spark(scala) using databricks

### ISSUE THREAD

**Issue by vinothkumarsubbu** [databricks/spark-xml#312]
I wanted to create a nested XML from CSV/DataFrame in scala spark. I am using Databricks spark-XML library for converting the DataFrame to XML format.

I was trying to create an output like below, but unable to achieve it

    <rows version="1"> 
    <row>
    <name id=10>Mahashree</name>
    </row>
    </rows>

I have tried with struct

    {"_VALUE":"Mahashree","@id":10,"__version":1}

but resulted as below 

    <rows> 
    <row>
    <name id=10>Mahashree
    <__version>1</__version>
    </name>
    </row>
    </rows>

 can anyone help to make the attribute in the root element?

Thanks in Advance

**Comment by punithmailme** [comment]
Hi @vinothkumarsubbu i am facing an issue where i cannot generate a xml with spark 2.1.2 and spark-xml 0.4.1.. when i run it as a main program i can generate it. but when i submit it as a spark job it fails with XMLStreamException... Can you please help. Here is the sample code https://github.com/punithmailme/spark-xml-new

**Comment by srowen** [comment]
If you're just asking about the attribute on the root element `rows`, no you can't do that. I am not sure if there's a great use case for it? this is really about outputting rows as XML. You could possibly omit the root tag, and prepend/append the desired root to the resulting file?
