### ISSUE TITLE
Cannot distinguish between empty and non-existent nodes

### ISSUE THREAD

**Issue by elibus** [databricks/spark-xml#314]
Hi,
I have an XML as below:

```xml
<items>
	<Ntr>
		<Othr>NORE</Othr>
	</Ntr>
	<Ntr>
		<NFI>
		</NFI>
		<Othr>NORE</Othr>
	</Ntr>
	<Ntr>
		<NFI>
                    <VAL>some<VAL>
		</NFI>
		<Othr>NORE</Othr>
	</Ntr>
</items>
```

I can parse correctly the structure above, however I am not able to tell whether the NFI node is present and empty or is not present at all because, in both cases for the first and the second NFI elements above the parser returns NULL.

What I would expect as behavior is the parser to:

- return NULL if the NFI element does not exist at all. (Element 1 of the XML)
- return a complex empty struct if the element exists but is empty. (Element 2 of the XML)
- return a complex struct filled with one element

Would that be reasonable?

**Comment by elibus** [comment]
Linked to #117

**Comment by HyukjinKwon** [comment]
@elibus, does this happen in the master branch too?

**Comment by elibus** [comment]
@HyukjinKwon we are using branch 0.3 however, if I am not mistaken, the code responsible for this behaviour should be this one: https://github.com/databricks/spark-xml/blob/f3772b296d77a5a92ae4e714f3f8cb9940f1f0f9/src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala#L218 which is identical in both 0.3 and 0.4 branches and introduced to fix #117 .

**Comment by elibus** [comment]
Hi,
below an example XML and an explanation of the expected behaviour.

```xml
<root>
  <item>
    <!-- Issue 314 - We expect [null]
               The node exists but is empty
    -->
    <b>
    </b>
  </item>
  <item>
    <b>
      <!-- Issue 314 - We expect [[null,null]]
                   The <es> node exists and can have two nested elements, both null
      -->
      <es></es>
    </b>
  </item>
  <item>
    <b>
      <es>
        <!-- Issue 314 - We expect [[E,null]]
                       The <es> node exists and can have two nested elements, E and null
        -->
        <e>E</e>
      </es>
    </b>
  </item>
  <item>
    <b>
      <es>
        <!-- Issue 314 - We expect [[E,null]]
                       The <es> node exists and can have two nested elements, E and " "
        -->
        <e>E</e>
        <f> </f>
      </es>
    </b>
  </item>
  <item>
    <b>
      <es>
        <!-- Issue 314 - We expect [[E,null]]
                       The <es> node exists and can have two nested elements, E and ""
        -->
        <e>E</e>
        <f></f>
      </es>
    </b>
  </item>
</root>
```

The current version of spark-xml will give the following result.
```scala
scala> result.printSchema
root
 |-- b: struct (nullable = true)
 |    |-- es: struct (nullable = true)
 |    |    |-- e: string (nullable = true)
 |    |    |-- f: string (nullable = true)
scala> result.show
+----------+
|         b|
+----------+
|      null|
|    [null]|
|[[E,null]]|
|   [[E, ]]|
|[[E,null]]|
+----------+
```

Note that:

- the first row is `null`, the expected behaviour would be to have `[null]` as `<b>` exists has not text nor children
- the second row is `[null]`, the expected behaviour would be to have `[[null,null]]` as `<es>` exists has no text and can have two children but has none
- the third row is `[[E,null]]`, this is expected as  as `<e>` exists and has a text while `<f>` does not
- the fourth row is `[[E, ]]`, this is expected as  as `<e>` exists and has a text while `<f>` has blank and `treatEmptyValuesAsNulls ` is false
- the fifth row is `[[E,null]]`, the expected behaviour would be to have `[[E,]]` as  as `<e>` exists and has a text while `<f>` has an empty string and `treatEmptyValuesAsNulls ` is false

The expected behaviour is shown below:
```scala
scala> result.show
+-------------+
|            b|
+-------------+
|       [null]|
|[[null,null]]|
|   [[E,null]]|
|      [[E, ]]|
|      [[E,]]|
+-------------+
```
Setting `treatEmptyValuesAsNulls ` to true would give instead:
```scala
scala> result.show
+-------------+
|            b|
+-------------+
|       [null]|
|[[null,null]]|
|   [[E,null]]|
|      [[E,null]]|
|      [[E,null]]|
+-------------+
```

**Comment by srowen** [comment]
Resolved by https://github.com/databricks/spark-xml/pull/355
