### ISSUE TITLE
Numeric value automatically changing parsing time

### ISSUE THREAD

**Issue by rudrashis** [databricks/spark-xml#318]
hi ,
In my xml file there is a value like:2018031406301852565547890,when i am parsing this value and creating dataframe, I am getting 2.01803140630185227E24 with data type long.I am parsing this using pyspark,IDE (pycharm).
what is the possible reason an how i can get the atcual value.

**Comment by srowen** [comment]
It's being parsed as a long because it looks like a long, and what you are citing is just how Python is printing the large value. It should work as a long. If you want a string, convert it to a string or manually specify a schema that says this field is a string.
