### ISSUE TITLE
Extract xml data from Dataframe and process the xml in to a separate Dataframe

### ISSUE THREAD

**Issue by rakiuday** [databricks/spark-xml#331]
I have a Dataframe and it has been imported from mysql

```
dataframe_mysql.show()
+----+---------+---------------------------------------------------+
|  id|accountid|                                            xmldata|
+----+---------+---------------------------------------------------+
|1001|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
|1002|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
|1003|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
|1004|    12347|<AccountSetup xmlns:xsi="test"><Customers test="...|
+----+---------+---------------------------------------------------+
```

In the xmldata column there is xml tags inside, I need to parse it in a structured data in a seperate dataframe.

Previously I had the xml file alone in a text file, and loaded in a spark dataframe using "com.databricks.spark.xml"
```
 spark-shell --packages com.databricks:spark-xml_2.10:0.4.1,  com.databricks:spark-csv_2.10:1.5.0
 val sqlContext = new org.apache.spark.sql.SQLContext(sc)
 val df = sqlContext.read.format("com.databricks.spark.xml").option("rowTag","Account")
 .load("mypath/Account.xml")
```
the final output I got as structured one
```
df.show()
+----------+--------------------+--------------------+--------------+--------------------+-------+....
|   AcctNbr|         AddlParties|           Addresses|ApplicationInd|       Beneficiaries|ClassCd|....
+----------+--------------------+--------------------+--------------+--------------------+-------+....
|AAAAAAAAAA|[[cccccccccc Amer...|[WrappedArray([D,...|             T|[WrappedArray([11...|     35|....
+----------+--------------------+--------------------+--------------+--------------------+-------+....
```
Please advice how to achieve the this when I have the xml content inside a dataframe.
I am new to spark and scala.

**Comment by BioQwer** [comment]
Hello, @rakiuday @hina1234 
Please see this test [test("DSL test schema (object) inferred correctly")](https://github.com/databricks/spark-xml/blob/f3772b296d77a5a92ae4e714f3f8cb9940f1f0f9/src/test/scala/com/databricks/spark/xml/XmlSuite.scala#L570)

i make prints in test
```scala
test("DSL test schema (object) inferred correctly") {
    val results = sqlContext.read.format("xml")
      .option("rowTag", booksTag)
      .load(booksNestedObjectFile)
    results.show()
    assert(results.schema == StructType(List(
      StructField(s"${DEFAULT_ATTRIBUTE_PREFIX}id", StringType, nullable = true),
      StructField("author", StringType, nullable = true),
      StructField("description", StringType, nullable = true),
      StructField("genre", StringType, nullable = true),
      StructField("price", DoubleType, nullable = true),
      StructField("publish_dates", StructType(
        List(StructField("publish_date", StringType))), nullable = true),
      StructField("title", StringType, nullable = true))
    ))
    results.printSchema()

    results.select("publish_dates.publish_date").show()

    assert(results.collect().size === numBooks)
  }
```
In this test you will see that schema already resolve correctly
One element
```xml
<book id="bk101">
      <author>Gambardella, Matthew</author>
      <title>XML Developer's Guide</title>
      <genre>Computer</genre>
      <price>44.95</price>
      <publish_dates>
         <publish_date>2000-10-01</publish_date>
      </publish_dates>
      <description>An in-depth look at creating applications 
      with XML.</description>
   </book>
```
schema
```
root
 |-- _id: string (nullable = true)
 |-- author: string (nullable = true)
 |-- description: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- price: double (nullable = true)
 |-- publish_dates: struct (nullable = true)
 |    |-- publish_date: string (nullable = true)
 |-- title: string (nullable = true)
```
`show()` wrap your inner objects 
```
+-----+--------------------+--------------------+---------------+-----+-------------+--------------------+
|  _id|              author|         description|          genre|price|publish_dates|               title|
+-----+--------------------+--------------------+---------------+-----+-------------+--------------------+
|bk101|Gambardella, Matthew|An in-depth look ...|       Computer|44.95| [2000-10-01]|XML Developer's G...|
|bk102|          Ralls, Kim|A former architec...|        Fantasy| 5.95| [2000-12-16]|       Midnight Rain|
|bk112|         Galos, Mike|Microsoft Visual ...|       Computer|49.95| [2001-04-16]|Visual Studio 7: ...|
+-----+--------------------+--------------------+---------------+-----+-------------+--------------------+
```
In spark you have 2 option
1 you can use `results.select("publish_dates.publish_date").show()` for get your element 
2 create `case class` for your struct and transform to dataset `results.as[YourCaseClass]`
```
+------------+
|publish_date|
+------------+
|  2000-10-01|
|  2000-12-16|
|  2000-11-17|
|  2001-03-10|
|  2001-09-10|
|  2000-09-02|
|  2000-11-02|
|  2000-12-06|
|  2000-11-02|
|  2000-11-02|
|  2000-12-01|
|  2001-04-16|
+------------+
```

**Comment by HyukjinKwon** [comment]
Thanks, @BioQwer. Let me leave this closed.

**Comment by christianb7** [comment]
Hi, apologies for replying to this closed thread.  I have the same requirement also, but I don't understand from @BioQwer response how to read the XML from a column in a dataframe.  Are you able to explain how this can be acheived please? I currently understand that it isn't possible and we can only use spark xml from an xml formatted file.  I am more than happy to be wrong.

Thanks,
Chris

**Comment by BioQwer** [comment]
Hi @christianb7 
I read about this question with more attention 
```
dataframe_mysql.show()
+----+---------+---------------------------------------------------+
|  id|accountid|                                            xmldata|
+----+---------+---------------------------------------------------+
|1001|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
|1002|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
|1003|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
|1004|    12347|<AccountSetup xmlns:xsi="test"><Customers test="...|
+----+---------+---------------------------------------------------+
```

If you mean parse column `xmldata` directly in DF, at now `from the box` spark xml not do it
as i know

**Comment by christianb7** [comment]
> Hi @christianb7
> I read about this question with more attention
> 
> ```
> dataframe_mysql.show()
> +----+---------+---------------------------------------------------+
> |  id|accountid|                                            xmldata|
> +----+---------+---------------------------------------------------+
> |1001|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
> |1002|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
> |1003|    12346|<AccountSetup xmlns:xsi="test"><Customers test="...|
> |1004|    12347|<AccountSetup xmlns:xsi="test"><Customers test="...|
> +----+---------+---------------------------------------------------+
> ```
> 
> If you mean parse column `xmldata` directly in DF, at now `from the box` spark xml not do it
> as i know

Thanks. I did find this [https://github.com/databricks/spark-xml/pull/334] but looks like it is incomplete with outstanding comments. It is a shame as I imagine it would be quite well used and not require the current approach of saving raw xml and loading again..

**Comment by BioQwer** [comment]
> It is a shame as I imagine it would be quite well used and not require the current approach of saving raw xml and loading again..

i'm not completely understand(

**Comment by srowen** [comment]
You don't need spark-xml at all here. You just apply an XML parser to the values in `xmldata`, parse them, extract the values you want as a list of values, and give the result new column names. Something roughly like this (probably not 100% correct, off the top of my head, but you get the idea)...

```
myDataFrame.select("xmldata").as[String].map { xmldata =>
  ... parse the XML with JAXB or something ...
  [ customerName, test, etc... ]
}.toDF("customerName", "test", ...)
```

**Comment by sshadoop** [comment]
from pyspark.sql.column import Column, _to_java_column
from pyspark.sql.types import _parse_datatype_json_string
import pyspark.sql.functions as F


def ext_from_xml(xml_column, schema, options={}):
    java_column = _to_java_column(xml_column.cast('string'))
    java_schema = spark._jsparkSession.parseDataType(schema.json())
    scala_map = spark._jvm.org.apache.spark.api.python.PythonUtils.toScalaMap(options)
    jc = spark._jvm.com.databricks.spark.xml.functions.from_xml(
        java_column, java_schema, scala_map)
    return Column(jc)

def ext_schema_of_xml_df(df, options={}):
    assert len(df.columns) == 1

    scala_options = spark._jvm.PythonUtils.toScalaMap(options)
    java_xml_module = getattr(getattr(
        spark._jvm.com.databricks.spark.xml, "package$"), "MODULE$")
    java_schema = java_xml_module.schema_of_xml_df(df._jdf, scala_options)
    return _parse_datatype_json_string(java_schema.json())

use above defenition to achive

payloadSchema = ext_schema_of_xml_df(dataframe_mysql.select("XMLData"))
parsed_dataframe = dataframe_mysql.withColumn("parsed", ext_from_xml(F.col("XMLData"), payloadSchema))

**Comment by sshadoop** [comment]
@BioQwer 
'from pyspark.sql.column import Column, _to_java_column
from pyspark.sql.types import _parse_datatype_json_string
import pyspark.sql.functions as F


def ext_from_xml(xml_column, schema, options={}):
    java_column = _to_java_column(xml_column.cast('string'))
    java_schema = spark._jsparkSession.parseDataType(schema.json())
    scala_map = spark._jvm.org.apache.spark.api.python.PythonUtils.toScalaMap(options)
    jc = spark._jvm.com.databricks.spark.xml.functions.from_xml(
        java_column, java_schema, scala_map)
    return Column(jc)

def ext_schema_of_xml_df(df, options={}):
    assert len(df.columns) == 1

    scala_options = spark._jvm.PythonUtils.toScalaMap(options)
    java_xml_module = getattr(getattr(
        spark._jvm.com.databricks.spark.xml, "package$"), "MODULE$")
    java_schema = java_xml_module.schema_of_xml_df(df._jdf, scala_options)
    return `_parse_datatype_json_string(java_schema.json())

payloadSchema = ext_schema_of_xml_df(XMLData_mysql.select("XMLDataCol"))
parsed = XMLData_mysql.withColumn("parsed", ext_from_xml(F.col("XMLDataCol"), payloadSchema))'
parsed is final data frame  parsed based on XML nodes


u can
