### ISSUE TITLE
Not able to parse object of System.Collections.Generic.List`1[System.Single]

### ISSUE THREAD

**Issue by Kaviylu** [databricks/spark-xml#332]
I faced an issue that one tag is of type System.Collections.Generic.List`1[System.Single].  String "System.Collections.Generic.List`1[System.Single]" is parsed as value instead of the <data> tag.

Attached  is the sample source file - 
[xml_source_test.txt](https://github.com/databricks/spark-xml/files/2399136/xml_source_test.txt)

**Comment by srowen** [comment]
That looks like .NET code, and not related to this project?
