### ISSUE TITLE
How to parse the XML into Flattened one

### ISSUE THREAD

**Issue by sparksha** [databricks/spark-xml#333]
I have this XML
```
<?xml version="1.0" encoding="UTF-8"?>
<security_master v="46.7">
	<header>
		<type>update</type>
		<timestamp>2017-11-04T00:31:17Z</timestamp>
	</header>
	<payload>
		<instrument id="123456789">
			<master_information>
				<instrument_xref>
					<xref type="ISIN" type_id="2">US123456UU11</xref>
					<xref type="BANK Global Id" type_id="20" unique_id="M1234567" bsid=" " ticker="FN" id_bb_sec_num="FN BJ1234" pricing_source="N.A." market_sector="Mtge" security_typ="MBS 30yr" security_typ2="" exch_code=" ">BBG00J4TWFY4</xref>
				</instrument_xref>
			</master_information>
		</instrument>
		<instrument id="123456790">
			<master_information>
				<instrument_xref>
					<xref type="ISIN" type_id="2">US123456UU12</xref>
				</instrument_xref>
			</master_information>
		</instrument>
	</payload> 
</security_master>
```

```
dfx1 = sqlContext.read.format("com.databricks.spark.xml")\
      .option("excludeAttribute", "false")\
	  .option("rowTag", "security_master")\
	  .load("C:\\test\\xml_db_New.xml")
dfx1.selectExpr("explode(payload.instrument.arr) as e").selectExpr("explode(e.xref) as e").select("e").show(100)
df.printSchema()
root
 |-- _v: double (nullable = true)
 |-- header: struct (nullable = true)
 |    |-- timestamp: string (nullable = true)
 |    |-- type: string (nullable = true)
 |-- payload: struct (nullable = true)
 |    |-- instrument: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- _id: long (nullable = true)
 |    |    |    |-- master_information: struct (nullable = true)
 |    |    |    |    |-- instrument_xref: struct (nullable = true)
 |    |    |    |    |    |-- xref: array (nullable = true)
 |    |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |    |    |    |    |    |-- _bsid: string (nullable = true)
 |    |    |    |    |    |    |    |-- _exch_code: string (nullable = true)
 |    |    |    |    |    |    |    |-- _id_bb_sec_num: string (nullable = true)
 |    |    |    |    |    |    |    |-- _market_sector: string (nullable = true)
 |    |    |    |    |    |    |    |-- _pricing_source: string (nullable = true)
 |    |    |    |    |    |    |    |-- _security_typ: string (nullable = true)
 |    |    |    |    |    |    |    |-- _security_typ2: string (nullable = true)
 |    |    |    |    |    |    |    |-- _ticker: string (nullable = true)
 |    |    |    |    |    |    |    |-- _type: string (nullable = true)
 |    |    |    |    |    |    |    |-- _type_id: long (nullable = true)
 |    |    |    |    |    |    |    |-- _unique_id: string (nullable = true)
```

I want to flatten the XML ? Pls help me with the explode and selectExpr command thanks

**Comment by sparksha** [comment]
2.	On the given XML file on printSchema, I can able to explore till master information, but the values after its not showing up
root
|-- _v: double (nullable = true)
|-- header: struct (nullable = true)
|    |-- timestamp: string (nullable = true)
|    |-- type: string (nullable = true)
|-- payload: struct (nullable = true)
|    |-- instrument: array (nullable = true)
|    |    |-- element: struct (containsNull = true)
|    |    |    |-- _id: long (nullable = true)
|    |    |    |-- master_information: struct (nullable = true)
|    |    |    |    |-- instrument_xref: struct (nullable = true)
|    |    |    |    |    |-- xref: array (nullable = true)
|    |    |    |    |    |    |-- element: struct (containsNull = true)
|    |    |    |    |    |    |    |-- _VALUE: string (nullable = true)
|    |    |    |    |    |    |    |-- _bsid: string (nullable = true)
|    |    |    |    |    |    |    |-- _exch_code: string (nullable = true)
|    |    |    |    |    |    |    |-- _id_bb_sec_num: string (nullable = true)
|    |    |    |    |    |    |    |-- _market_sector: string (nullable = true)
|    |    |    |    |    |    |    |-- _pricing_source: string (nullable = true)
|    |    |    |    |    |    |    |-- _security_typ: string (nullable = true)
|    |    |    |    |    |    |    |-- _security_typ2: string (nullable = true)
|    |    |    |    |    |    |    |-- _ticker: string (nullable = true)
|    |    |    |    |    |    |    |-- _type: string (nullable = true)
|    |    |    |    |    |    |    |-- _type_id: long (nullable = true)
|    |    |    |    |    |    |    |-- _unique_id: string (nullable = true)

See the output below, and please try to explode this values. When we try to explode this values we are getting exception. (see the below in RED)
>>> df=dfx1.selectExpr("explode(instrument) as ins").select("ins._id","ins.master_information").show(100)
+---------+--------------------+
|      _id|  master_information|
+---------+--------------------+
|145966938|[[WrappedArray([U...|
|145967107|[[WrappedArray([U...|
+---------+--------------------+
>>> df=dfx1.selectExpr("explode(instrument) as ins").select("ins._id","ins._bsid").show(100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\spark-2.0.2-bin-hadoop2.7\python\pyspark\sql\dataframe.py", line 861, in select
    jdf = self._jdf.select(self._jcols(*cols))
  File "C:\Python27\lib\site-packages\py4j\java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "C:\spark-2.0.2-bin-hadoop2.7\python\pyspark\sql\utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: u'No such struct field _bsid in _id, master_information;'

**Comment by srowen** [comment]
This looks like maybe a typo in your SQL. _bsid appears to be under instrument_xref, not instrument
