### ISSUE TITLE
Spark Streaming XML messages from Kafka topic and push it into Hive table

### ISSUE THREAD

**Issue by Rahumathulla** [databricks/spark-xml#335]
Hi All,

I have an XML file in hand which needs to be streamed using spark from Kafka topic and ingested into Hive table. The xml contains 4 transactions enclosed in <txnf:Transaction> which contains one or more line items inside the tag <txnf:ItemDetails>.  I need to get this data streamed and saved into Hive table.

Note: The line item information can either be stored in Struct format or as a separate table with relationship using <txnf:ReceiptNumber>

============XML==============
<?xml version="1.0" encoding="UTF-8"?>
<tns:TransactionData
  xmlns:tns="http://www.hm.com/POS/POSLog/5.0.0-Build06"
  xmlns:txnf="http://www.nrf-arts.org/IXRetail/namespace/"
  xmlns:cct="urn:un:unece:uncefact:documentation:standard:CoreComponentType:2"
  xmlns:clm5ISO42173A="urn:un:unece:uncefact:codelist:standard:5:ISO42173A:2009-03-05"
  xmlns:cust="http://www.hm.com/POS/POSLog/CustomMetaData"
  xmlns:hmarts="http://www.hm.com/HMARTS/POSLog/5"
  xmlns:ids5ISO316612A="urn:un:unece:uncefact:identifierlist:standard:5:ISO316612A:SecondEdition2006VI-4"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <tns:TxnObjects>
    <tns:TxnObject>
      <tns:TxnData>
        <tns:TxnLog>
          <txnf:Transaction>
            <txnf:StoreOutlet>
              <txnf:OutletID>IN0704</artsOutletID>
            </txnf:StoreOutlet>
            <txnf:WorkstationID>08</txnf:WorkstationID>
            <txnf:BillNumber>4773</txnf:BillNumber>
            <txnf:BeginDateTime>2017-12-16T09:53:42</txnf:BeginDateTime>
            <txnf:ReceiptNumber>8088</txnf:ReceiptNumber>
            <txnf:ItemDetails>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>545396006176012</txnf:ItemID>
                  <txnf:Description>Jersey basic</txnf:Description>
                  <txnf:RegularSalesUnitPrice>6.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>1.39</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>545449004176008</txnf:ItemID>
                  <txnf:Description>Jersey basic</txnf:Description>
                  <txnf:RegularSalesUnitPrice>8.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>8.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:Total TotalType="TransactionGrandAmount" TypeCode="Sale">8.99</txnf:Total>
            </txnf:ItemDetails>
          </txnf:Transaction>
          <txnf:Transaction>
            <txnf:StoreOutlet>
              <artsOutletID>IN0704</artsOutletID>
            </txnf:StoreOutlet>
            <txnf:WorkstationID>08</txnf:WorkstationID>
            <txnf:BillNumber>4776</txnf:BillNumber>
            <txnf:BeginDateTime>2017-12-16T10:18:17</txnf:BeginDateTime>
            <txnf:ReceiptNumber>8089</txnf:ReceiptNumber>
            <txnf:ItemDetails>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>526562002176019</txnf:ItemID>
                  <txnf:Description>Trouser</txnf:Description>
                  <txnf:RegularSalesUnitPrice>14.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>14.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:Total TotalType="TransactionGrandAmount" TypeCode="Sale">14.99</txnf:Total>
            </txnf:ItemDetails>
          </txnf:Transaction>
          <txnf:Transaction>
            <txnf:StoreOutlet>
              <artsOutletID>IN0704</artsOutletID>
            </txnf:StoreOutlet>
            <txnf:WorkstationID>08</txnf:WorkstationID>
            <txnf:BillNumber>4777</txnf:BillNumber>
            <txnf:BeginDateTime>2017-12-16T10:19:02</txnf:BeginDateTime>
            <txnf:ReceiptNumber>8090</txnf:ReceiptNumber>
            <txnf:ItemDetails>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>577427004176009</txnf:ItemID>
                  <txnf:Description>Licence Knitwear &amp; Woven</txnf:Description>
                  <txnf:RegularSalesUnitPrice>12.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>12.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>506528001176008</txnf:ItemID>
                  <txnf:Description>Knitwear Girl</txnf:Description>
                  <txnf:RegularSalesUnitPrice>8.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>8.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>574056001176009</txnf:ItemID>
                  <txnf:Description>Licence Knitwear &amp; Woven</txnf:Description>
                  <txnf:RegularSalesUnitPrice>9.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>9.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:Total TotalType="TransactionGrandAmount" TypeCode="Sale">31.97</txnf:Total>
            </txnf:ItemDetails>
          </txnf:Transaction>
          <txnf:Transaction>
            <txnf:StoreOutlet>
              <artsOutletID>IN0704</artsOutletID>
            </txnf:StoreOutlet>
            <txnf:WorkstationID>08</txnf:WorkstationID>
            <txnf:BillNumber>4778</txnf:BillNumber>
            <txnf:BeginDateTime>2017-12-16T10:22:00</txnf:BeginDateTime>
            <txnf:ReceiptNumber>8091</txnf:ReceiptNumber>
            <txnf:ItemDetails>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>582178001187001</txnf:ItemID>
                  <txnf:Description>Small Acc Big Girl</txnf:Description>
                  <txnf:RegularSalesUnitPrice>2.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>2.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>305775024176011</txnf:ItemID>
                  <txnf:Description>Socks &amp; Tights Small Girl</txnf:Description>
                  <txnf:RegularSalesUnitPrice>5.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>5.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>293433009187011</txnf:ItemID>
                  <txnf:Description>Socks &amp; Tights Small Girl</txnf:Description>
                  <txnf:RegularSalesUnitPrice>7.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>7.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>546592001176014</txnf:ItemID>
                  <txnf:Description>Shirt</txnf:Description>
                  <txnf:RegularSalesUnitPrice>12.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>12.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>194902032176009</txnf:ItemID>
                  <txnf:Description>Jersey basic</txnf:Description>
                  <txnf:RegularSalesUnitPrice>5.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>5.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>402065025176009</txnf:ItemID>
                  <txnf:Description>Jersey basic</txnf:Description>
                  <txnf:RegularSalesUnitPrice>5.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>3.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>402065025176009</txnf:ItemID>
                  <txnf:Description>Jersey basic</txnf:Description>
                  <txnf:RegularSalesUnitPrice>5.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>3.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>402065020176009</txnf:ItemID>
                  <txnf:Description>Jersey basic</txnf:Description>
                  <txnf:RegularSalesUnitPrice>5.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>3.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:LineItem>
                <txnf:Sale>
                  <txnf:ItemID>194902032176009</txnf:ItemID>
                  <txnf:Description>Jersey basic</txnf:Description>
                  <txnf:RegularSalesUnitPrice>5.99</txnf:RegularSalesUnitPrice>
                  <txnf:ActualSalesUnitPrice>5.99</txnf:ActualSalesUnitPrice>
                  <txnf:Quantity>1</txnf:Quantity>
                </txnf:Sale>
              </txnf:LineItem>
              <txnf:Total TotalType="TransactionGrandAmount" TypeCode="Sale">47.92</txnf:Total>
            </txnf:ItemDetails>
          </txnf:Transaction>
        </tns:TxnLog>
      </tns:TxnData>
    </tns:TxnObject>
  </tns:TxnObjects>
</tns:TransactionData>

**Comment by BioQwer** [comment]
@Rahumathulla 
you have wrong xml
i copy your xml to idea 
![image](https://user-images.githubusercontent.com/5636129/48977710-9173dd00-f0b0-11e8-9c9d-f5e1351f0048.png)
see #331 i think it will helpfull for you

**Comment by HyukjinKwon** [comment]
Thanks, @BioQwer. Let me leave this closed.
