### ISSUE TITLE
How can I process  "&"/"<"  as <![CDATA[...&....<...]] instead of "&amp;" or "&lt;"

### ISSUE THREAD

**Issue by rgtv** [databricks/spark-xml#339]
How to save special character like "&"、"<" into CDATA?

**Comment by BioQwer** [comment]
Hello, @rgtv 
Can you add example of `xml` and code that you run?

**Comment by rgtv** [comment]
OK。My code is below：
```
val processDF = sparkSession.sql(
        s"""
           |select
           |  id as index_id,
           |  url as loc
           |from pp.t__data  limit 100
     """.stripMargin)
	 
processDF.repartition(5)
        .write.mode(SaveMode.Overwrite)
        .format("com.databricks.spark.xml")
        .option("rootTag", "urlset")
        .option("rowTag", "url")
        .save(save_path)
```
while the url filed may contains “&” for example “https://zhidao.baidu.com/search?lm=0**&**rn=10**&**pn=0”,then the save data become “https://zhidao.baidu.com/search?lm=0**&amp;**rn=10**&amp;**pn=0”。I wanna save this as “<![CDATA[https://zhidao.baidu.com/search?lm=0**&**rn=10**&**pn=0]]>”。
> Hello, @rgtv
> Can you add example of `xml` and code that you run?

**Comment by srowen** [comment]
You can't do that here, but, the escaped encoding of the string is perfectly valid, and an XML parser will read it back as you intended it to.
