### ISSUE TITLE
roottag inner body

### ISSUE THREAD

**Issue by EmilioOldenziel** [databricks/spark-xml#341]
I have a xml file with the following schema.
```
<items>
    <item>
        <subitem>hello></subitem>
         world
    </item>
    <item>
        <subitem>hello></subitem>
         world
    </item>
</items>
```

How do I get the `world` from each item?

**Comment by BioQwer** [comment]
see https://github.com/databricks/spark-xml/wiki/How-to-get-inner-field and this #331

**Comment by Minitour** [comment]
I am also having this issue where I need to read the `_VALUE` of the `rowTag`.

```xml
<objects>
      <object attr="atr">
            some string value
      </object>
</objects>
```
