### ISSUE TITLE
Nested element with same name as parent and attribute fails

### ISSUE THREAD

**Issue by jimenefe** [databricks/spark-xml#373]
Related to the following fix:

https://github.com/databricks/spark-xml/issues/160

If the nested elements contain attributes, this still fails. Modifying the test xml in `nested-element-with-name-of-parent.xml` to the following:

`<?xml version="1.0" encoding="UTF-8"?>
<people>
    <parent ID="1"><parent ID="1.1"><child>Child 1.1</child></parent><child>Child 1.2</child></parent>
    <parent ID="2"><parent ID="2.1"><child>Child 2.1</child></parent><child>Child 2.2</child></parent>
</people>`

Fails the test `"Nested element with same name as parent delineation"` in `XmlSuite`

**Comment by jimenefe** [comment]
NOTE: I have a fix for this already, will submit as soon as I can

**Comment by HyukjinKwon** [comment]
Hey, thanks for reporting this. Can you open a PR if that's ready? I think it's easier to check the issue and the change if that's already ready.

**Comment by jimenefe** [comment]
I will do, once I have it ready

**Comment by jimenefe** [comment]
Pull request: https://github.com/databricks/spark-xml/pull/374

**Comment by Sivauppari** [comment]
What is the artifactId and version of spark-xml which has this fix?

**Comment by srowen** [comment]
Tagged for 0.5.1 - it is not released

**Comment by jagadeesh477500** [comment]
what if my parent rowTag and child rowTag are same as below:
<Persons>
<Person ID="12345" ParentID="534343" type="good">  //Parent Row1
<Person ID="12589" type="goodOne">     //child row1
<Values>
....
</Values>
</Person>   //end of child row1
<Person ID="76475" type="goodOne">     //child row2
<Values>
....
</Values>
</Person>   //end of child row2
</Person>    //end of parent row1
</Persons>

When i parse this kind of xml , first two rowTags are skipped as _corrupt_record and getting null

**Comment by HyukjinKwon** [comment]
Can you try it against the current master? I think it's fixed.

**Comment by jondavidi** [comment]
> Tagged for 0.5.1 - it is not released

@srowen is there a timeframe for when 0.5.1 will be released with this fix?

**Comment by srowen** [comment]
Oh that is long since released. We are on 0.9.0.
