### ISSUE TITLE
&apos; (apostrophe) gets escaped futher to become &amp;apos;

### ISSUE THREAD

**Issue by krishnadasmallya** [databricks/spark-xml#377]
```
import spark.implicits._
val values = List("O'brien", "O&apos;brien","O&amp;pos;brien").toDF("name")
values.show
```
produces

---------------
|           name|
---------------
|        O'brien|
|   O&apos;brien|
|O&amp;pos;brien|

While if I do 

```
 values.write.format("com.databricks.spark.xml").option("rootTag", "names").option("rowTag", "name").mode("Overwrite").save("/user/mallyakr/test")
```
It would generate
```
<names>
    <name>
        <name>O'brien</name>
    </name>
    <name>
        <name>O&amp;apos;brien</name>
    </name>
    <name>
        <name>O&amp;amp;pos;brien</name>
    </name>
</names>
```

As [quoted here](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_xml_escape.html) these characters(&, ', ", <, >) needs to be escaped in the xml. But it is not handled here. Looks like `&` is getting string replaced in every case.

Am I missing some confs here to handle this better?

**Comment by srowen** [comment]
I don't think that's a bug. Quotes don't have to be escaped in XML except where used in quoted strings. At least, this output is generated by the built in JDK XML library.

**Comment by srowen** [comment]
This from the spec seems to confirm it: https://www.w3.org/TR/xml11/#syntax

**Comment by krishnadasmallya** [comment]
> This from the spec seems to confirm it: https://www.w3.org/TR/xml11/#syntax

@srowen  Thanks for the quick response, I may be overlooking few things here. Let me dig in further and see whats breaking my schema validation for the generated XML from spark-xml.
