### ISSUE TITLE
Support for encrypted XML file load or load decrypted files from memory

### ISSUE THREAD

**Issue by Sivauppari** [databricks/spark-xml#378]
Support for encrypted XML file load or load decrypted files from memory

1. Is there api support for loading pgp encrypted files into Data Frame? If not, is there api support to load decrypted XML files from memory instead of HDFS file path? 

Here is Sample Code : 

        DataFrame rootDF = sqlContext.read().format("com.databricks.spark.xml")
                .option("rowTag", "Search_Results")
                .load(getClass().getResource("/xml/*****_20181114.csv.out.pgp").getPath());

**Comment by srowen** [comment]
Here, what is an encrypted XML file?
Your example seems to show reading CSV. 
Why not decrypt it as a separate preprocessing step? Not sure any of that belongs in this library.

**Comment by Sivauppari** [comment]
decrypt can be separate processing step, however decrypted file will not be stored in HDFS, this library expects the file in HDFS. does this library support processing XML string or file which is in memory?

**Comment by srowen** [comment]
The processing in Spark happens in memory, and you can persist DataFrames in memory, yes.
