### ISSUE TITLE
Support for XML stream parsing

### ISSUE THREAD

**Issue by Sivauppari** [databricks/spark-xml#380]
Looks like current api does not support to load XML stream into data frame. 
load method only allows String argument (filename path). Is there api which takes input xml stream ?

   DataFrame rootDF = sqlContext.read().format("com.databricks.spark.xml")
            .option("rowTag", "Search_Results")
            .load(getClass().getResource("/xml/*****_20181114.csv.out").getPath());

**Comment by srowen** [comment]
You can load data on the driver however you want. You can parallelize that XML data across the cluster. You can then apply this library. None of Spark would operate directly on resources on the driver classpath, and this is no exception, but it is easy to write.
