### ISSUE TITLE
Read XML as String not File

### ISSUE THREAD

**Issue by mantovani** [databricks/spark-xml#382]
Hello,
I would like to read the XML from a string, not from a file. I'm doing this for JSON and it's trivial. But I'm having a bad time to do with XML.

Any suggestion ?

Thank you

**Comment by srowen** [comment]
Use `XmlReader.xmlRDD` to process an RDD or DataFrame of String

**Comment by mantovani** [comment]
Do you think that we suppose to have a standard API to read a file/string that's not ortogonal to the source ?

**Comment by srowen** [comment]
What do you mean? You can already read XML files directly from files. That's not orthogonal right?

**Comment by mantovani** [comment]
IMHO I think we should have an orthogonal interface to read from string as well, not just for file:

```
spark.read.json(Seq("foo").toDS)
spark.read.xml(Seq("foo").toDS)
```

**Comment by srowen** [comment]
That's, roughly, already what I posted above. Make an RDD from your Dataset/DataFrame and pass to the method I indicated.

**Comment by mantovani** [comment]
@srowen , I understood, thanks, it's perfect working.

`    val df = new XmlReader().xmlRdd(spark, spark.sparkContext.parallelize(Seq(string))).toDF
`

What I'm saying is for the enhancement, would be nice to have a standard way to read from string on the same way we do have for JSON, that's it.

**Comment by srowen** [comment]
You might be able to define a second implicit for `DataFrameReader` that accepts a Dataset of String, sure. Open a PR if you are up to it.
