### ISSUE TITLE
Allow row tag to select top level element in file

### ISSUE THREAD

**Issue by jenden** [databricks/spark-xml#383]
I have a large collection of XML data that contains many different types of records and I am not aware of all of the tags that exist. I would like to be able to load data without specifying a `rowTag` and capture the schema of the data similarly to what you can do by loading from JSON without specifying a schema. 

The source data is something like this:
```
# file 1 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:a xmlns:ns2="something">
  <a1>...</a1>
</ns2:a>

# file 2
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:a xmlns:ns3="something else">
  <a1>...</a1>
</ns3:a>

# file 2
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:b xmlns:ns2="something">
  <b1>...</b1>
</ns2:b>
```

I would like to see something like this after I read the data:

```
[
   Row(ns2:a=Row([@xmlns:ns2="something", a1="..."])), 
   Row(ns3:a:=Row([@xmlns:ns3="something else", a1="..."])), 
   Row(ns2:b=Row([@xmlns:ns2="something", b1="..."])),
]

**Comment by srowen** [comment]
I don't think you can do it here. The problem is that we're trying to convert XML, which doesn't have a tabular structure necessarily, to a tabular structure. This requires that the XML has some repeating element with a consistent structure. You could perhaps preprocess the files to wrap each body in a `<row>` tag of some kind, and then it would generally work.

**Comment by jenden** [comment]
JSON doesn't necessarily have a tabular structure either. But if you have multiple files each file can be considered it's own row or in new-line delimited JSON each line contains an object which becomes its own row. I can read arbitrary JSON files and spark can infer the schema. Fields which don't exist in a specific file are null.

Maybe a better way to have phrased the previous request is that I want to see this after a read:

```
[
   Row(ns2:a=Row([@xmlns:ns2="something", a1="..."]), ns3:a=null, ns2:b=null), 
   Row(ns2:a=null, ns3:a:=Row([@xmlns:ns3="something else", a1="..."]), ns2:b=null), 
   Row(ns2:a=null, ns3:a=Null, ns2:b=Row([@xmlns:ns2="something", b1="..."])),
]
```

**Comment by srowen** [comment]
Yeah, that's reasonable functionality too, to treat each file as a row. In that case, what if you read each file as a separate record, with spark.wholeTextFiles (need to find the exact method), and get a Dataset of String, and then process as in https://github.com/databricks/spark-xml/issues/383 ?

**Comment by jenden** [comment]
Is that a possibility? Right now I've been reading multiple xml files by matching against a glob pattern. Something like `df = spark.read.option(...).format('xml').load('my/path/*.xml')`. If I read a file as text, how would I parse the xml for each row? Looking for the xml equivalent of `pyspark.sql.functions.from_json`.

**Comment by srowen** [comment]
Yeah, instead you read them as `(filename, contents)` pairs with `sc.wholeTextFiles(...)`. Just keep the contents with `.values()` and then make that a Dataset with `.toDS()`. Then try the line in the PR I pointed to.

Honestly it's just off the top of my head but pretty sure something like this will work. At least, it's easy after `.values()` to `.map(contents => "<row>" + contents + "</row>")` if needed to wrap all your file contents in a tag each.

**Comment by jenden** [comment]
Yes - I will definitely give this a try.  Did you mean to post to another PR? #383 links back to this thread.

> Yeah, that's reasonable functionality too, to treat each file as a row. In that case, what if you read each file as a separate record, with spark.wholeTextFiles (need to find the exact method), and get a Dataset of String, and then process as in #383 ?

**Comment by srowen** [comment]
I don't think it needs a new PR. I am curious whether the approach works first.
