### ISSUE TITLE
withRowTag not working on spark-xml version upgrade

### ISSUE THREAD

**Issue by Kartik-RTP** [databricks/spark-xml#384]
Hi I am migrating my spark java application from spark 1.6 to spark 2.3 (including scala version upgrade from 2.10 to 2.11 for the libraries) . As a result , I have also upgraded the spark-xml version from 2.10_0.3.3 to 2.11_0.5.0 . 
However , the application is no longer able to correctly parse the xml structure and giving null values when given the schema.

So the message is of the format

`<?xml version="1.0" encoding="UTF-8" ?><TransactionRoot><Transaction_request_wire><clientid>123</clientid></Transaction_request_wire></TransactionRoot>
`
also, using the follwing schema

`StructType customSchema = new StructType(new StructField[]{ new StructField("clientid",Datatypes.StringType,Metadata.empty)});`

i am loading the xml strings in a `JavaRDD<String> rdd` and then calling

`(new XmlReader()).withRowTag("Transaction_request_wire").withSchema(customSchema).xmlRdd(sqlContext,rdd.rdd()).show();`

Here with spark 1.6 and spark-xml_2.10_0.3.3 , the values are correctly getting picked up , but the same code in spark 2.3 and spark-xml_2.11_0.5.0 gives null values for clientid field.

It seems that in spark 1.6 , parser is looking for the schema fields inside `<Transaction_request_wire>` ,
However in spark 2.3 , parser is looking inside  `<TransactionRoot>` for the schema columns.  Is there any option to revert it back to its original behaviour?

I am trying to take a look at the source code about how it is differing in parsing but i am unsuccessful till now , Please help!

**Comment by srowen** [comment]
It looks like your row tag is wrong. It needs to be "Transaction_request_wire", given your schema. That shouldn't have changed.

You'd also typically read the XML files directly with spark.read....xml(...), not parse as an RDD. Do you need to do that? you can read a Dataset of String, not an RDD.

Reopen with more details if that doesn't cover it.

**Comment by Kartik-RTP** [comment]
I am actually using it as part of spark streaming , so the input is a JavaRDD<String> . Hence  I am using the xmlRdd function. Also , I didn't get your point about wrong rowTag! I am not changing the rowTag. The same line of code is working in one version but not in other. Also , I am using the same rowTag that you have mentioned in your comments. Can you please clarify if I am misunderstanding your point!!

**Comment by srowen** [comment]
OK, make the RDD of String into a Dataset of String, and then try the approach at the bottom of https://github.com/databricks/spark-xml/issues/382

I wasn't reading your comment carefully; you're using the right row tag. The schema seems fine, and it works for me when I run it (albeit in Scala) in a local test.

I'm not sure what the difference is, but you should be using the newer Dataset/DataFrame APIs anywhere. Those work OK for me and is generally better anyway. You can still get those from RDDs.

**Comment by Kartik-RTP** [comment]
>
> I have looked at bottom of #382 and As per
https://github.com/databricks/spark-xml/issues/382#issuecomment-467640899

The usage of function looks similar to what I am using

Instead , if you are referring to
https://github.com/databricks/spark-xml/issues/382#issuecomment-467889589

Then here I am not sure what you exactly mean by defining an Implicit. Also
, I am not sure if Java provides the same implicits as Scala.

If possible , can you please provide some sample code for reference!

> .
>

**Comment by Kartik-RTP** [comment]
Also , while I will take a look at your suggestions ,  I would like to make
minimal changes in code while doing upgrade so as to avoid any side
effects. Hence , I would really appreciate if someone from your team can
also look into the different behaviors in parsing upon version upgrade

**Comment by srowen** [comment]
There's no team here; this isn't supported. It only works with Spark 2.3 anyway, and moving anything from 1.6 to 2.3 is going to need code changes.

I'm referring to `val df = new XmlReader().xmlRdd(spark, rdd)).toDF`; have you tried it? this is working for me. (I misspoke, you don't even need to make a `Dataset`)

**Comment by Kartik-RTP** [comment]
Ok, I will take a look at it . This one is without rowTag and without
schema .

Though I have previously tried without the schema and it is going to give
the Transaction_request_wire struct with relevant fields , post which I
created a view on it and then ran SQL like "select
transaction_request_wire.clientid as clientid from transaction"  to obtain
fields from struct, hence leading to extra code changes(I was looking to
avoid this approach)

Let me try once with what you suggested and come back with the update

**Comment by srowen** [comment]
If Transaction_request_wire is your row tag, then it's not part of the schema. The schema is based on its contents, so the schema is just clientid, as you have above. That is the schema that is inferred, too.

Your SQL query won't work, and shouldn't have ever worked, if that's your row tag. That _would_ be correct if Transaction is your row tag. I wonder if that was the difference
