### ISSUE TITLE
DataBricks Notebook (Spark xml) - java.lang.ClassNotFoundException: Failed to find data source: com.databricks.spark.xml. 

### ISSUE THREAD

**Issue by azurele** [databricks/spark-xml#385]
Hi, I am trying to use the spark-xml library and running into the ClassNotFoundException. I saw a couple of issues already opened for this and I tried using Version 2:10 of the library as it recommended but running into the same issue. 

Databricks Version details: 5.2 (includes Apache Spark 2.4.0, Scala 2.11)
Maven Library for Spark-XML : 2:10 

Sample Code: 
inputFile = "xxxx.xml"
df = (spark.read .format("com.databricks.spark.xml") .option("rowTag", "instrumentDatas") .load(inputFile
))
java.lang.ClassNotFoundException: Failed to find data source: com.databricks.spark.xml. Please find packages at http://spark.apache.org/third-party-projects.html

Appreciate any inputs to correct the issue.

**Comment by azurele** [comment]
Changing the format to "xml" in the below code has fixed the issue. 
df = (spark.read .format("com.databricks.spark.xml") .option("rowTag", "instrumentDatas") .load(inputFile
))

**Comment by mv1742** [comment]
I still have this issue. 
The repo says to install the package through 
`SPARK_HOME/bin/spark-shell --packages com.databricks:spark-xml_2.12:0.6.0`

but how to use this in the Databricks notebook? or Jupyter.
I've tried this in the notebook without any luck:
```
from os import environ
environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.databricks:spark-xml_2.11:0.6.0 pyspark-shell'
```

**Comment by srowen** [comment]
Not sure about Jupyter, but in Databricks you just add this as a Library and attach it to your cluster. In general you just need to add this as a dependency to your application so that it's available on the classpath for the JVM. It's not a Python package.

**Comment by mv1742** [comment]
thanks, but how do i add it as a library?

**Comment by sanketmote05** [comment]
Does anyone knows how to solves this in Jupyter?
