### ISSUE TITLE
scala spark.read.format("xml").load(files:_*) failed

### ISSUE THREAD

**Issue by liuzd123156** [databricks/spark-xml#386]
Hello,
   I want to load files by spark-sql&spark-xml.But the spark-sql&spark-xml can not support load(files:_*).Because the com.databricks.spark.xml.DefaultSource extend SchemaRelationProvider, not FileFormat.Can you give me some advice？
Thank you！

**Comment by srowen** [comment]
Yes, they take glob patterns like "*.xml". You can also read several sets of files and union them.

**Comment by liuzd123156** [comment]
> Yes, they take glob patterns like "*.xml". You can also read several sets of files and union them.

Thank you for your answer.If I have thousands of files will have performance problems？

**Comment by srowen** [comment]
Generally if there are performance problems, it happens when listing large directories of files on object stores like S3. You're better off reading fewer larger files if possible. Otherwise, no there's not much difference.

**Comment by liuzd123156** [comment]
> Generally if there are performance problems, it happens when listing large directories of files on object stores like S3. You're better off reading fewer larger files if possible. Otherwise, no there's not much difference.

Thank you very much！
