### ISSUE TITLE
spark-xml leads to strange xml content

### ISSUE THREAD

**Issue by rgtv** [databricks/spark-xml#387]
My spark version is spark-2.3.3.1,hadoop is Hadoop 2.9.1,the code is below:
`commodityBankDfTmp.repartition(1)
      .write.mode(SaveMode.Overwrite)
      .format("xml")
      .option("rootTag", "urlset")
      .option("rowTag", "url")
      .option("version", "2.0").
      save(save_baidu_bf_path)`
 I use spark-xml_2.11-0.5.0.jar to save my xml file and lead to the strange contents below:
```
<url>
        <sku_id>5656576575701595112</sku_id>



        <sku_name>abcd</sku_name>
        <city_code>00563000999</city_code>
    </url>
```

or 

```
<url>
        <sku_id>11111123101586423</sku_id>
        <sku_name>efg</sku_name>
        <city_code>0fgg00999</






city_code>
    </url>
```
or
```
    <url>
        <sku_id>





000000000104443271713</sku_id>
        <sku_name>kkf</sku_name>
        <city_code>0098701000999</city_code>
    </url>
```
or
```
    <url>
        <sku_id>





000000000104443271713</sku_id>
        <sku_name>kkf</sku_name>
        <city_code>0098701000999</city_code>
    </url>
```
There are a lot of empty lines,and the end close tag is broken.
So,how can I to fix this?

**Comment by srowen** [comment]
Yeah, I saw this too in https://github.com/databricks/spark-xml/issues/338 , with Hadoop 2.9, and I can't figure out why it happens. It's something to do with the buffer in the woodstox parser flushing, but even after stepping through the woodstox/Hadoop code, could not pinpoint why. Sorry, it's an open bug.
