### ISSUE TITLE
Incorrect schema inferred

### ISSUE THREAD

**Issue by tanvi-surana** [databricks/spark-xml#388]
Incorrect schema is being inferred.
For the xml 
`<request>
    <a>"test"
        <b>
            <c></c>
        </b>
    </a>
</request>`

Schema generated is -
root
 |-- a: string (nullable = true)
 |-- b: struct (nullable = true)
 |    |-- c: string (nullable = true)

However the expected schema is -
root
 |-- a: struct (nullable = true)
 |    |-- _VALUE: string (nullable = true)
 |    |-- b: struct (nullable = true)
 |    |    |-- c: string (nullable = true)

Can  you point us how to resolve this issue ?

**Comment by srowen** [comment]
Can you change your format? I'm not sure this type of mixed format is supported not. Ideally you'd have `<a><value>"test"</value><b><c></c></b></a>`

**Comment by hina1234** [comment]
There are different combinations of such types of xml in our project. Figuring out these combinations may not be possible. 
Since this is a valid use case, are there any chances of fixing it or if it is worth trying for us to contribute to spark-xml and fix it?

**Comment by srowen** [comment]
Your best bet is indeed to propose a fix. There are a few related issues here about mixed content in children. I think it's a little harder than it sounds, as this isn't the type of XML the library was really designed for. Still probably possible to implement

**Comment by srowen** [comment]
This is pretty much exactly the use case in https://github.com/databricks/spark-xml/issues/415 where we had some more discussion; see also https://github.com/databricks/spark-xml/pull/416 . Just closing this for now as a duplicate
