### ISSUE TITLE
Is there a Direct way to Convert all tags into Unique column names

### ISSUE THREAD

**Issue by server2245** [databricks/spark-xml#389]
Hi,

Is there a direct way to convert each XML tag into a Dataframe column dynamically considering attribute also ?.
For example, XML like below

```
<routes>
<route id=1>100</route>
<route id=2>200</route>
</routes>
```

above XML should give me columns as **route_id,route_value**

**Comment by srowen** [comment]
Sure just parse with route as your rowTag. It will generate an _id and _VALUE column with both values

**Comment by server2245** [comment]
> Sure just parse with route as your rowTag. It will generate an _id and _VALUE column with both values

Thanks. Could you please give me a sample code so it will be a god starting point for me?.

**Comment by srowen** [comment]
There's an example on the front page of the project: https://github.com/databricks/spark-xml/#conversion-from-xml-to-dataframe
