### ISSUE TITLE
Consider setting `mode` default to fastfail

### ISSUE THREAD

**Issue by blbradley** [databricks/spark-xml#390]
While working on a project, we discovered malformed XML late in delivery because of the default `mode` of `PERMISSIVE`.

I think it would be wise to consider having fastfail as the default. This would make users determine early in development what mode is acceptable for them.

**Comment by blbradley** [comment]
In addition, fastfail is similar to how Python's XML parser works by default. I'm not sure of other behavior from Spark supported languages.

**Comment by srowen** [comment]
It is certainly a reasonable position. I think the default is meant to match that of the CSV, JSON, etc readers in Spark, which default to permissive.
