### ISSUE TITLE
object xml is not a member of package com.databricks.spark

### ISSUE THREAD

**Issue by sakuraitabi2601** [databricks/spark-xml#391]
Hi All. I need to know how to setup by databricks / notebook to use xml.

I have the following error while import com.databricks.spark.xml._

notebook:2: error: object xml is not a member of package com.databricks.spark
import com.databricks.spark.xml._

actually how to install the package in databricks ?

**Comment by srowen** [comment]
You just add the library to your app like any other, but you do have to add it. In Databricks, add it as a Library in the workspace and attach it to your cluster.

**Comment by sakuraitabi2601** [comment]
how to add the library ? where is the sorce ? 

any detail steps?

**Comment by srowen** [comment]
https://github.com/databricks/spark-xml#scala-211
https://docs.databricks.com/user-guide/libraries.html#maven-libraries
