### ISSUE TITLE
How do I deal with duplicate xml tags?

### ISSUE THREAD

**Issue by miki1029** [databricks/spark-xml#395]
Hi.
I am very thankful to spark-xml.

However, I am having difficulty with handling duplicate tags.

```
<list>
  <element>a</element>
  <element>b</element>
  <element>c</element>
</list>
```

In this situation, I have always found element = "c".
The result I want is the first tag, element = "a".

Are there any related options?

Thanks

**Comment by srowen** [comment]
Array types should be supported. Are you specifying a schema, where element isn't an array?

**Comment by miki1029** [comment]
Oh, thank you.
I used StringType. However, it works well with ArrayType.
