### ISSUE TITLE
XML import: inferSchema = false is ignored

### ISSUE THREAD

**Issue by versusnja** [databricks/spark-xml#397]
Hi,

I want to stop inferring Schema and treat everything as string. `inferSchema` option is supposed to do exactly this. However, it doesn't have any effect.

```
from os import environ
environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.databricks:spark-xml_2.10:0.4.1 pyspark-shell'

spark = SparkSession.builder \
        .master("local[6]") \
        .appName("ipython-notebook") \
        .config("spark.sql.execution.arrow.enabled", "true") \
        .getOrCreate()

z = spark.read \
    .option("rowTag", "maintag") \
    .option('inferSchema', 'false') \
    .format('xml') \
    .load('data/sample.xml')
```

Schema:
```root
 |-- _CurrencyType: string (nullable = true)
 |-- _DistanceUnits: string (nullable = true)
 |-- _ResponseTime: long (nullable = true)        <-- LONG  !!! But must be string
 |-- _TransactionId: string (nullable = true)
 |-- _air: string (nullable = true)
```

What am I missing?

**Comment by versusnja** [comment]
Just in case, link https://github.com/databricks/spark-xml/commit/0ff88df9e3ab5fb9304f598aa1c05f8aba7a3817

**Comment by srowen** [comment]
Try `False` rather than `'false'` just to see if that's it.
What is the XML like?

**Comment by versusnja** [comment]
@srowen yes, I tried this. No effect.

Here's a super-basic XML: https://we.tl/t-KVI2EQDHal
```
<?xml version="1.0" encoding="utf-16"?>
<body>
    <response ResponseTime="2483" DistanceUnits="MI" CurrencyType="EUR"/>
</body>
```

and python script that infers `Long` from ResponseTime
```
z = spark.read \
    .format('xml') \
    .option('rowTag', "body") \
    .option('inferSchema', False) \
    .load('data/test.xml')
z.printSchema()
```

**Comment by versusnja** [comment]
Can it be so that it works in Scala API, but doesn't work in the pyspark API? Sounds unlikely...

**Comment by srowen** [comment]
I can't reproduce this -- but I do encounter a problem when including `encoding="utf-16"`. Try removing that, as I think that's incorrect (or was in my env, could be in yours).

**Comment by versusnja** [comment]
@srowen removing the encoding didn't help. See screenshot:
![image](https://user-images.githubusercontent.com/1716025/62288404-9c131d00-b45c-11e9-8b3e-6a460ae5291a.png)

And the environment of spark:
![image](https://user-images.githubusercontent.com/1716025/62288580-fca25a00-b45c-11e9-8619-9702c82004c2.png)

**Comment by srowen** [comment]
Oh, ha, I get it. I can't reproduce on `master` but can on 0.5.0. This is because `inferSchema` was only introduced after 0.5.0. It should work in the next release or you can build from master. https://github.com/databricks/spark-xml/commit/0ff88df9e3ab5fb9304f598aa1c05f8aba7a3817
