### ISSUE TITLE
Handling corrupt records

### ISSUE THREAD

**Issue by Supreme1977** [databricks/spark-xml#402]
I'm using spark-xml in my databricks project to read data that is stored in an XML nested structure. Files can be 10 MB or larger. Reading the files like this:
df = sqlContext.read.format("xml").options(rowTag=xmlAsdObject).load(xmlFilePath)
gives the expected result for most 'rows', but some of the rows get reported as _corrupt_record.
I don't know if there is a way to discover the reason why a row is treated as corrupt, but I suspect it is because these 'rows' are too big. I checked the XML of one of these corrupt items, and this was about 550.000 characters long.
I tried applying a custom schema for reading to exclude most of the data, but this does not help. Probably the library reads in all data and applies the schema afterwards. 

Is there a way to discover why a record is recognized as corrupt? Or is this already enough information to determine that the record is too big? And is it is too big, can I do anything to solve this or work around this?

Note: If needed I can supply my code and the xml file, but I prefer not to publish my xml file here

**Comment by srowen** [comment]
If you can switch logging to debug level, you should see more info in the logs about what failed. Note that the logs may be on your executor. But in fail-fast or drop-malformed mode you will get an exception or warning log respectively with the record. That may be very large! but I think it will log.

**Comment by Supreme1977** [comment]
Hi Sean,

Thanks for your suggestion. After some searching I found out how to do that. I used this info: https://kb.azuredatabricks.net/clusters/set-executor-log-level.html
I looked at the ‘stderr’ and ‘stdout’ logs, but didn’t find info that I can logically relate to the corrupt_record problem.
I can find logging about the file I’m reading in, so the logging seems to be working.
Can you tell me what I should look for specifically?

Kind regards,
Gerard Woudstra

**Comment by jagadeesh477500** [comment]
Try to print first row and check what is wrong I doubt nested xml

**Comment by srowen** [comment]
Try drop-malformed mode and look for "Dropping malformed line". Or use version 0.6.0 which has more logging in other modes: https://github.com/databricks/spark-xml/commit/a0a8b15d940bdc91eb7d6d24e8fdc60baf33a2a5

**Comment by Supreme1977** [comment]
Thank you for your suggestion to upgrade to v0.6. Apparently you guys fixed more than only the logging. I read the same file and no longer have a _corrupt_record column. This first record that gave me problems before now seems to be read correctly.

Looks like I don’t need the extra logging for now, but I’ll try that if I run into new corrupt record situations.

Regards,
Gerard

**Comment by srowen** [comment]
Good to hear. Yeah there were a few important fixes.
