### ISSUE TITLE
How do I add outer fields to parse results?

### ISSUE THREAD

**Issue by wds-job** [databricks/spark-xml#403]
If the XML data to be parsed is a field in the database, how do you implement it if you combine other fields with the results of the XML parsing?
![qu](https://user-images.githubusercontent.com/26320403/63137654-be369e80-c009-11e9-8358-7a523532b52c.png)

**Comment by srowen** [comment]
This isn't a use case for spark-xml. If you have a table with an XML column, simply parse the column with an XML parser and generate new columns from it. From there you can use Spark SQL to join other tables, etc.
