### ISSUE TITLE
Spark-xml (rootTag with attributes)

### ISSUE THREAD

**Issue by raucci2000** [databricks/spark-xml#404]
Hi folks!

I'm having issues to write an element into the root tag, so for instance:
`<EnvCad attribX=valueY> ` <-- this is the expected result, but for now all I've got was:
```
<EnvCad>
    <rowTag attribX=valueY> 
```
Is it possible to add elements into the root tag? 

I’ve alread read everthing about (spark-xml/sqlcontext/etc), however, I've never found about it.
https://github.com/databricks/spark-xml

Have you ever seen or done something like it?

**Comment by srowen** [comment]
This isn't explicitly supported. Really this library much more concerns the 'row tags'.

**Comment by raucci2000** [comment]
For example, is it possible to do it?
<root>
   <EnvCad attriX=valueX>
         <Cli attribY=valueY>
               <EncCli attribZ=valueZ>

If yes, how can I create it by StructType/StructField?

**Comment by srowen** [comment]
You can specify the schema of rowTags, but not things outside it. You can manually add XML around the XML that is generated, with some careful use of the text-based APIs in Spark.

**Comment by lucasarruda-ciandt** [comment]
why on earth I can't add simple attributes to the root tag? Now I'll have to manipulate the output files.. what a mess
