### ISSUE TITLE
spark-xml - StructType/StructField Nested

### ISSUE THREAD

**Issue by raucci2000** [databricks/spark-xml#407]
PHYTON CODE:
# 1 - EXECUTE QUERY
sqlDF = spark.sql("SELECT CnpjOgm,NmOgm,NrRms,SeqlRms,DtRms,TipCli,IdfcCli FROM  MY_TABLE")
rdd = sqlDF.collect()

# 2 - CREATE CUSTOM SCHEMA
```
custom_schema = StructType([StructField("EnvoCad", \
                              StructType([StructField("_CnpjOgm", LongType(), True), \
                                        StructField("_NmOgm", StringType(), True), \
                                        StructField("_NrRms", IntegerType(), True), \
                                        StructField("_SeqlRms", IntegerType(), True), \
                                        StructField("_DtRms", StringType(), True), \
                                        StructField("Cli", \
                                             StructType([StructField("_TipCli", IntegerType(), True), \
                                                         StructField("_IdfcCli", LongType(), True)]))]))])
```

# 3 - CREATE DATAFRAME WITH "CUSTOM SCHEMA" AND "RDD"
new_df = spark.createDataFrame(rdd,custom_schema)
new_df.printSchema()

# 4 - SAVE XML FILE
```
new_df.coalesce(1) \
      .write \
      .format('xml') \
      .options(attributePrefix="_") \
      .save('file:///home/my_user/xml/output.xml')
```

====================================================================================

RESULTS:
1 - EXECUTE QUERY RESULT:
+----------+----------------+--------+--------+----------+------+-------+
|   CnpjOgm|           NmOgm|   NrRms| SeqlRms|     DtRms|TipCli|IdfcCli|
+----------+----------------+--------+--------+----------+------+-------+
|-265264601|Enterprise 00001|    1526|73388359|2018-12-06|     1|     12|
|-265264601|Enterprise 00001|    1526|73388359|2018-12-06|     1|     12|
|-265264601|Enterprise 00001|    4321|72931215|2018-12-08|     1|     12|
|-265264601|Enterprise 00001|    1526|73388359|2018-12-06|     1|     12|
|-265264601|Enterprise 00001|46418316|72784522|2018-11-14|     1|     12|
|-265264601|Enterprise 00001|    1820|73989576|2018-12-22|     1|     12|
|-265264601|Enterprise 00001|    4321|72931215|2018-12-08|     1|     12|
+----------+----------------+--------+--------+----------+------+-------+

3 - CREATE DATAFRAME WITH "CUSTOM SCHEMA" AND "RDD" RESULT:
ValueError: Length of object (7) does not match with length of fields (1) 
 
=================================================================

For example, I need to generate the following xml output file:

```
<?xml version="1.0" encoding="UTF-8"?>
<EnvoCad CnpjOgm="-265264601" NmOgm="Enterprise 00001" NrRms="1526" SeqlRms="73388359" DtRms="2018-12-06">
    <Cli TipCli="1" IdfcCli="118873032"></Cli>
</EnvoCad>
```

**Comment by srowen** [comment]
Your XML schema has structs, but the result of your query does not.

**Comment by raucci2000** [comment]
Does my query need to be prepared to generate as nested as well?

**Comment by srowen** [comment]
Yes, you don't need to specify the schema. You do need a schema in the DataFrame that corresponds to what you want to output.

**Comment by raucci2000** [comment]
I got it. however, do you have some example to help me?
