### ISSUE TITLE
Vertical Tab in CDATA is not getting read

### ISSUE THREAD

**Issue by Magudeswaran-R** [databricks/spark-xml#408]
Hi Team,

I read that vertical tab is not a valid character in XML. But is there a way by which I could parse/ignore vertical tab(or any invalid character) coming as part of CDATA.

**Comment by srowen** [comment]
spark-xml is just looking for the start/end tags, and then uses an XML parser to parse the contents. If your XML is well-formed, it should be fine. Yes I think you'd have to use a CDATA element. From there you can do whatever you like with the text content afterwards.
