### ISSUE TITLE
New line character between xml tags/data 

### ISSUE THREAD

**Issue by a137705** [databricks/spark-xml#409]
The python code for creating xml

test_list =   [('Category A', 100, "This is category A"),
        ('Category B', 120, "This is category B"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C"),
        ('Category C', 150, "This is category C")]

schema = StructType([
    StructField('Category', StringType(), True),
    StructField('Count', IntegerType(), True),
    StructField('Description', StringType(), True)
])

df = spark.createDataFrame(spark.sparkContext.parallelize(test_list),schema)

df.repartition(1).write.mode("overwrite").format("xml").option("rootTag", rootTag).option("rowTag", rowTag).option("emptyValue","").option("nullValue", "").\
  save("/data/")

Generated xml

```
<CONTRACT_ACCOUNT_Set>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category B</Category>
        <Count>120</Count>
        <Description>This is category B</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</




Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category A</Category>
        <Count>100</Count>
        <Description>This is category A</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>



    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
    <CONTRACT_ACCOUNT_Record>
        <Category>Category C</Category>
        <Count>150</Count>
        <Description>This is category C</Description>
    </CONTRACT_ACCOUNT_Record>
</CONTRACT_ACCOUNT_Set>
```

It create blank new lines between tags and data  . Attached generated xml file

[part-00000.zip](https://github.com/databricks/spark-xml/files/3679821/part-00000.zip)

**Comment by srowen** [comment]
This is the same issue as https://github.com/databricks/spark-xml/issues/338 and unfortunately I have tried and failed to figure out why it happens or fix it. You can see more there.

**Comment by a137705** [comment]
@srowen Any work around  ?

**Comment by srowen** [comment]
As I say, no.
