### ISSUE TITLE
Processing Instructions Cause Failed Import

### ISSUE THREAD

**Issue by gmoore016** [databricks/spark-xml#411]
When importing XML containing [processing instructions](https://www.w3.org/TR/xml/#dt-pi), spark-xml yields no data. Consider this test case:
```xml
<foo>
<bar>
<?issue?>
lorem ipsum
</bar>
</foo>
```
When using `sql.read.format("xml").option("rowTag", "foo").load(filepath)` in the Python API, the above yields an empty dataframe. In contrast, running the same code with the `<?issue?>` removed appears to create a valid dataframe containing a "bar" column with one entry, "lorem ipsum". 

For reference, my current submission command is `spark-submit --packages com.databricks:spark-csv_2.11:1.5.0,com.databricks:spark-xml_2.11:0.6.0 script.py`.

At the moment, there doesn't appear to be a way to handle this other than manually removing all the processing instructions. Is there some way to ignore them and access the rest of the contents?

**Comment by HyukjinKwon** [comment]
Hm, I wonder how the processing instructions should be interpreted into Spark DataFrame.

**Comment by srowen** [comment]
Once the `<foo>` is found, the rest is parsed with an XML parser. I am guessing it doesn't like the processing instruction. Can it actually appear there in XML? hm, seems so. If anything it should be ignored of course. I don't know if/when I'll have time to look at it, but a debugger should quickly show what it is doing with them. maybe it's an easy fix to just ignore it.

**Comment by srowen** [comment]
I think https://github.com/databricks/spark-xml/pull/412 will fix this.
