### ISSUE TITLE
Data Loss happening when saving the dataframe as xml with spark 2.4 and spark-xml 0.6.0

### ISSUE THREAD

**Issue by codexIndore** [databricks/spark-xml#414]
We started experiencing this issue post migrating to spark-xml 0.6.0 on spark 2.4 cluster with scala 2.11
```
val df = sparkSession.read.parquet("s3n://someBucket/")
import com.databricks.spark.xml._
df.write
  .option("rootTag", "RecipientIdList")
  .option("rowTag", "recipientId")
  .mode("overwrite")
  .format("com.databricks.spark.xml")
  .save("s3n://SomeNewXmlBucket")
val xmlDf = sparkSession.read.option("rootTag", "RecipientIdList")
  .option("rowTag", "recipientId").format("xml").load("s3n://SomeNewXmlBucket")
xmlDf.count()
df.count()
```
The output we are seeing are 
res9: Long = 5553
res10: Long = 20394

We have been using this library without any issues with the spark-xml 0.4.1 version on spark 2.2 cluster with scala 2.11
But post-migration we started seeing this issue.

**Comment by codexIndore** [comment]
@srowen 
@HyukjinKwon 
Can one of you take a look into this as I see you are a major contributor to this repo or either confirm or deny if you are experiencing the same issue?

**Comment by srowen** [comment]
I think we'd have to have any info at all on the input and output. Like schema and a record that is written vs not written.

**Comment by srowen** [comment]
If I'm reading this right, you get _more_ records back than you wrote? That's weird, to be sure. We're sure there aren't old records in the bucket from a previous run?

**Comment by codexIndore** [comment]
@srowen 
That was the mistake in pasting, We are getting fewer records compared to what we write. I have updated the issue to reflect that.
I noticed that few tags are not closing correctly see the code below showing example of a bad tag.
```
        <LMemID>1123</LMemID>
        <LPoints>57</
LPoints>
       <name>"abc</name>
```

If I change this to 
``````
        <LMemID>1123</LMemID>
        <LPoints>57</LPoints>
       <name>"abc</name>
``````
The counts started matching.

**Comment by codexIndore** [comment]
Do you happen to know why this might be happening?

**Comment by srowen** [comment]
This is probably the same as https://github.com/databricks/spark-xml/issues/338 and I never figured it out after a lot of debugging. Does https://github.com/databricks/spark-xml/issues/338#issue-378532517 work around it?

**Comment by codexIndore** [comment]
@srowen 
I tried running by setting the system properties, but it doesn't work.

**Comment by srowen** [comment]
Hm, darn. I recall this bug and couldn't figure it out, because it seemed to happen in the STAX writer somewhere. It's actually easy to reproduce by setting the Hadoop dependency in the project to 2.9 or above and running tests. I can provide info on what I found when I debugged, but ultimately could not figure it out. It seemed like a problem outside the library

**Comment by srowen** [comment]
Another idea: try 1 partition? I recall that it had something to do with partition boundaries. Not ideal if it works, but maybe better than nothing. Also it doesn't seem to happen on Hadoop 2.8 or older; not sure if that is somehow an option to ensure your Spark cluster isn't on a later distro.

**Comment by srowen** [comment]
Have a look at https://github.com/databricks/spark-xml/pull/417 - after a fresh look, I found it without too much trouble

**Comment by codexIndore** [comment]
@srowen 
Awesome.
Can you also release this so that we can start consuming it?

**Comment by srowen** [comment]
Yes, just need to finish one other open issue. If you wanted to try right now you could build it locally and deploy.

**Comment by codexIndore** [comment]
@srowen
I was able to validate and the fix works 
The counts started matching.
Will really appreciate if you can release this fix so that we are unblocked.

**Comment by srowen** [comment]
Yeah, it's pretty important (and a relief to finally figure it out). I will probably resolve the other issue tomorrow, and if there are no objections, just roll an 0.7.0 release with a handful of fixes. CC @HyukjinKwon
