### ISSUE TITLE
Support specific xml path for duplicated tags

### ISSUE THREAD

**Issue by dtungbmw** [databricks/spark-xml#42]
Recently I found spark-xml library and it works well with our requirement. However, since we need to process more complex/nested xml file which has the case with same tag in different path. What will be the best practice to deal with this case? E.g., we have <protocols> under <configuration> as well as under <firewall>, I tried to set “protocols” as the rowTag, and the select function returns all the children under configuration and firewall. Do I need to split xml file first in order to select the exact xml path? I think it will be nice to be able to specify the XML tag path in the API.

e.g,

``` xml
...
<protocols>
    <configuration>
        <value>aaa</value>
    </configuration>
</protocols>
...
```

``` xml
...
<firewall>
    <configuration>
        <value>bbb</value>
    </configuration>
</firewall>
...
```

**Comment by HyukjinKwon** [comment]
@dtungbmw Thanks for your suggestion.

**Comment by srowen** [comment]
The easy thing is to parse it twice, looking for protocols and then firewall, and then union the results. It does mean two passes over the data, but ought to work fine.
