### ISSUE TITLE
Any help on how to call the new `from_xml` function using pyspark?

### ISSUE THREAD

**Issue by gpadavala** [databricks/spark-xml#430]

**Comment by srowen** [comment]
Not sure what you're looking for; there is no detail. There are examples in the README.

**Comment by gpadavala** [comment]
as my question said
"from_xml" is the function added in 0.8.0 => how to access this in pyspark

This is the scala sample in README
```
import com.databricks.spark.xml.functions.from_xml
import com.databricks.spark.xml.schema_of_xml
import spark.implicits._
val df = ... /// DataFrame with XML in column 'payload' 
val payloadSchema = schema_of_xml(df.select("payload").as[String])
val parsed = df.withColumn("parsed", from_xml($"payload", payloadSchema))
```

`from_xml` is not accessible in pyspark
so my question is if there is a way to do it in python??

**Comment by srowen** [comment]
Oh, no I don't believe you can access it in pyspark, not at the moment. There is no special python binding here, although the xml data source is usable from pyspark.

**Comment by gpadavala** [comment]
i tried to add the warapper similar to pyspark sql function wrappers

```
from pyspark.sql.column import Column

def from_xml(col, schema):
  scala_datatype = spark._jsparkSession.parseDataType(schema.json())
  jc = sc._jvm.com.databricks.spark.xml.functions.from_xml(col._jc if isinstance(col, Column) else col, scala_datatype)
  return Column(jc)

new_df = df.withColumn("parsed", from_xml(col('value'), schema))
```

but got the error :(
py4j.Py4JException: Method from_xml([class org.apache.spark.sql.Column, class org.apache.spark.sql.types.StructType]) does not exist

**Comment by srowen** [comment]
@HyukjinKwon might know more. That looks like the type of approach to use, yes. 
The method actually has a third argument, a map of XML options. I think you'd have to pass at least an empty map there.

**Comment by gpadavala** [comment]
i got it working with the below code :) (for anyone who comes searching in future (^_^))

```
def from_xml(col, schema, options={}):
  scala_datatype = spark._jsparkSession.parseDataType(schema.json())
  scala_options = sc._jvm.PythonUtils.toScalaMap(options)
  jc = sc._jvm.com.databricks.spark.xml.functions.from_xml(col._jc if isinstance(col, Column) else col, scala_datatype, scala_options)
  return Column(jc)
```

**Comment by srowen** [comment]
Oh that's good to know, thank you. I am not sure if we can/should also start publishing a python binding just for it. I suppose we can at least include this in docs or examples.

**Comment by HyukjinKwon** [comment]
Yeah, that should be the correct workaround. I am not sure about publishing a python binding just for it too.

In case of `schema_of_xml` it might be tricker. You could do something like:

```python
from pyspark.sql.types import _parse_datatype_json_string
from pysaprk.sql import SparkSession


def schema_of_xml(df, options={}):
    spark = SparkSession.builder.getOrCreate()
    scala_options = sc._jvm.PythonUtils.toScalaMap(options)
    jdataset = spark._wrapped._ssql_ctx.createDataset(
        df._jdf.rdd(),
        self._spark._jvm.Encoders.STRING())
    return _parse_datatype_json_string(
        getattr(sc._jvm.com.databricks.spark.xml, "MODULE$").schema_of_xml(jdataset, scala_options).json())
```

**Comment by HyukjinKwon** [comment]
There might be another possibility by leveraging SQL functionality. 

If somehow we can manage to add this function via `SimpleFunctionRegistry.registerFunction`, we can call the function via `expr("from_xml(col)")`.

I think we might be able to register `from_xml` function lazily via `spark.catalog.registerFunction(...)` although it's a bit hacky.

In this case, we should annotate `XmlDataToCatalyst` with `ExpressionDescription`  - there might be some more minor required changes as well.
`schema_of_xml`  would not be able to be registered since it doesn't use Expression and cannot be a SQL function.

**Comment by gpadavala** [comment]
thanks for the help :)

**Comment by 3mlabs** [comment]
Guys, Need help on the similar topic, It seems that gpadavala has successfully tested the from_xml code. we have been trying to type cast xml string to specified schema using below function- 

from pyspark.sql.column import Column, _to_java_column
from pyspark.sql.types import _parse_datatype_json_string
from pyspark.sql.types import *

def from_xml(col, schema, options={}):
  scala_datatype = spark._jsparkSession.parseDataType(schema.json())
  scala_options = sc._jvm.PythonUtils.toScalaMap(options)
  jc = sc._jvm.com.databricks.spark.xml.functions.from_xml(col._jc if isinstance(col, Column) else col, scala_datatype, scala_options)
  return Column(jc)

I have been trying below xml by converting it too dataframe -
data = '<POSLog><Transaction><RetailStoreID>48</RetailStoreID><WorkstationID>6</WorkstationID><SequenceNumber>73</SequenceNumber>       <BusinessDayDate>2014-09-30</BusinessDayDate><EndDateTime>2014-09-30T06:20:14</EndDateTime><CurrencyCode>USD</CurrencyCode></Transaction></POSLog>'

rdd1 = spark.sparkContext.parallelize([(123,data)])
df = rdd1.toDF(['id','value'])

schema = eval('StructType([StructField("BusinessDayDate",StringType(),True),StructField("CurrencyCode",StringType(),True),StructField("EndDateTime",StringType(),True),StructField("RetailStoreID",LongType(),True),StructField("SequenceNumber",LongType(),True),StructField("WorkstationID",LongType(),True)])')

and i am trying to typecast column using below command - 
df.select(ext_from_xml(df['value'],dataframe.schema, {"rowTag":"Transaction"}))

Above command works without any errors but gives me blank data frame column like below -
>>> new_df = df.select(from_xml(f.col('value'), schema, {"rowTag":"Transaction"}))
>>>
>>> new_df.show()
+------------------------+
|xmldatatocatalyst(value)|
+------------------------+
|                 [,,,,,]|
+------------------------+

We are not sure if we are using it in correct way, Appreciate if someone can help us. 

Thanks,
3m Labs.

**Comment by 3mlabs** [comment]
> i got it working with the below code :) (for anyone who comes searching in future (^_^))
> 
> ```
> def from_xml(col, schema, options={}):
>   scala_datatype = spark._jsparkSession.parseDataType(schema.json())
>   scala_options = sc._jvm.PythonUtils.toScalaMap(options)
>   jc = sc._jvm.com.databricks.spark.xml.functions.from_xml(col._jc if isinstance(col, Column) else col, scala_datatype, scala_options)
>   return Column(jc)
> ```

Hi gpadavala,

We have been trying to typecast the XML string. It seems you have successfully used the above function. we have tried below steps - 

Create dataframe and schema - 
data = '<POSLog><Transaction><RetailStoreID>48</RetailStoreID><WorkstationID>6</WorkstationID><SequenceNumber>73</SequenceNumber>       <BusinessDayDate>2014-09-30</BusinessDayDate><EndDateTime>2014-09-30T06:20:14</EndDateTime><CurrencyCode>USD</CurrencyCode></Transaction></POSLog>'

rdd1 = spark.sparkContext.parallelize([(123,data)])
df = rdd1.toDF(['id','value'])

schema = eval('StructType([StructField("BusinessDayDate",StringType(),True),StructField("CurrencyCode",StringType(),True),StructField("EndDateTime",StringType(),True),StructField("RetailStoreID",LongType(),True),StructField("SequenceNumber",LongType(),True),StructField("WorkstationID",LongType(),True)])')

from_xml function -
from pyspark.sql.column import Column, _to_java_column
from pyspark.sql.types import _parse_datatype_json_string
from pyspark.sql.types import *

def from_xml(col, schema, options={}):
  scala_datatype = spark._jsparkSession.parseDataType(schema.json())
  scala_options = sc._jvm.PythonUtils.toScalaMap(options)
  jc = sc._jvm.com.databricks.spark.xml.functions.from_xml(col._jc if isinstance(col, Column) else col, scala_datatype, scala_options)
  return Column(jc)

finally applied from_xml to dataframe -
new_df = df.select(ext_from_xml(df['value'], schema, {"rowTag":"Transaction"}))

The code gives a blank dataframe like below - 
>>> new_df.show()
+------------------------+
|xmldatatocatalyst(value)|
+------------------------+
|                 [,,,,,]|
+------------------------+

We have been stuck here for quite some time now. Appreciate if you guys can help us in any way.

Thanks,
3m Labs

**Comment by ravi129** [comment]
> Yeah, that should be the correct workaround. I am not sure about publishing a python binding just for it too.
> 
> In case of `schema_of_xml` it might be tricker. You could do something like:
> 
> ```python
> from pyspark.sql.types import _parse_datatype_json_string
> from pysaprk.sql import SparkSession
> 
> 
> def schema_of_xml(df, options={}):
>     spark = SparkSession.builder.getOrCreate()
>     scala_options = sc._jvm.PythonUtils.toScalaMap(options)
>     jdataset = spark._wrapped._ssql_ctx.createDataset(
>         df._jdf.rdd(),
>         self._spark._jvm.Encoders.STRING())
>     return _parse_datatype_json_string(
>         getattr(getattr(sc._jvm.com.databricks.spark.xml, "package$"), "MODULE$").schema_of_xml(jdataset, scala_options).json())
> ```

Hi

I have defined the 2 helper functions as suggested

from pyspark.sql.column import Column, _to_java_column
from pyspark.sql.types import _parse_datatype_json_string

def ext_from_xml(xml_column, schema, options={}):
    java_column = _to_java_column(xml_column.cast('string'))
    java_schema = spark._jsparkSession.parseDataType(schema.json())
    scala_map = spark._jvm.org.apache.spark.api.python.PythonUtils.toScalaMap(options)
    jc = spark._jvm.com.databricks.spark.xml.functions.from_xml(
        java_column, java_schema, scala_map)
    return Column(jc)

def ext_schema_of_xml_df(df, options={}):
    assert len(df.columns) == 1

    scala_options = spark._jvm.PythonUtils.toScalaMap(options)
    java_xml_module = getattr(getattr(
        spark._jvm.com.databricks.spark.xml, "package$"), "MODULE$")
    java_schema = java_xml_module.schema_of_xml_df(df._jdf, scala_options)
    return _parse_datatype_json_string(java_schema.json())

when I run the below code

df2 = df.select(ext_from_xml(col('payload'), schema))

I am getting below error:

TypeError                                 Traceback (most recent call last)
<command-38013870> in <module>
----> 1 df2 = df.select(ext_from_xml(col('payload'), schema))

<command-37961733> in ext_from_xml(xml_column, schema, options)
      7     scala_map = spark._jvm.org.apache.spark.api.python.PythonUtils.toScalaMap(options)
      8     jc = spark._jvm.com.databricks.spark.xml.functions.from_xml(
----> 9         java_column, java_schema, scala_map)
     10     return Column(jc)
     11 

TypeError: 'JavaPackage' object is not callable

I am running this in databricks notebook. Can you please help

**Comment by koleaby4** [comment]
> ```python
> self
> ```

at that point `self` is not declared?

**Comment by koleaby4** [comment]
> Yeah, that should be the correct workaround. I am not sure about publishing a python binding just for it too.
> 
> In case of `schema_of_xml` it might be tricker. You could do something like:
> 
> ```python
> from pyspark.sql.types import _parse_datatype_json_string
> from pysaprk.sql import SparkSession
> 
> 
> def schema_of_xml(df, options={}):
>     spark = SparkSession.builder.getOrCreate()
>     scala_options = sc._jvm.PythonUtils.toScalaMap(options)
>     jdataset = spark._wrapped._ssql_ctx.createDataset(
>         df._jdf.rdd(),
>         self._spark._jvm.Encoders.STRING())
>     return _parse_datatype_json_string(
>         getattr(getattr(sc._jvm.com.databricks.spark.xml, "package$"), "MODULE$").schema_of_xml(jdataset, scala_options).json())
> ```

in `self._spark._jvm.Encoders.STRING())` self is not declared?

**Comment by srowen** [comment]
@koleaby4 that's an object in the JVM, it's declared, what are you asking here? use the example in the README

**Comment by koleaby4** [comment]
> @koleaby4 that's an object in the JVM, it's declared, what are you asking here? use the example in the README

thanks for getting back to me, @srowen.

I got to this page just like  @gpadavala  and @3mlabs  - looking for a way to parse xml in columns using Python.
The solution mentioned in  [pyspark-notes](https://github.com/databricks/spark-xml#pyspark-notes) did not work by copy-pasting and it took me a while to get it working (I am a Python developer but at the moment I have little spark knowledge).

The fact that several people struggle in using the solution in the pyspark-notes makes me:
1. wonder why python functions were given different names compared to park ones?
2. think that docstrings with examples showing how to use `ext_from_xml` and `ext_schema_of_xml_df` could help?

Please take this as genuine feedback from someone who spent a full day trying to make this work on my project.

**Comment by srowen** [comment]
Eh, I'm not sure what's not working for you - you didn't say. Did copy-pasting that function and using it per the README not work? if so, I need to see what / why. AFAIK this is working, or at least is for all the people I've talked to.

What function's name are you talking about?
Docstring where? there is no python package here.

**Comment by koleaby4** [comment]
> Eh, I'm not sure what's not working for you - you didn't say. Did copy-pasting that function and using it per the README not work? if so, I need to see what / why. AFAIK this is working, or at least is for all the people I've talked to.
> 
> What function's name are you talking about? Docstring where? there is no python package here.

@srowen, all the questions in this ticket are related to people trying to figure out how to parse xml stored as strings in spark daraframes using Python. We found your github project and went through [Parsing Nested XML](https://github.com/databricks/spark-xml#parsing-nested-xml) documentation.

This functionality we need is described in [pyspark-notes](https://github.com/databricks/spark-xml#pyspark-notes).  The confuction comes from the fact that:
1. the Python functions' names (ext_from_xml, ext_schema_of_xml_df) differ from equivalent functions in Scala  (schema_of_xml, from_xml)
2. the Python functions provided in that section don't have examples / docstrings showing how to use them

I think if you update function names in pyspark-notes section to match those in Scala, that would help. Alternatively, you could add an example showing how to use those Python functions.

Hope this helps and thanks again.

**Comment by srowen** [comment]
I understand that, I'm trying to understand what is preventing people from using the existing solution.

You can name your python function whatever you want; you're defining it.
There isn't a docstring as this isn't source code in the project.

Are you just asking to add an example of calling it? it's just a method you call. It'd be one line, but sure.
Open a pull request with what you want to see.

But you said it didn't work, and I don't see info on that.

**Comment by abhimanyuZ** [comment]
I came across the same issue of calling from_xml() from pyspark. The code snippets mentioned above helped a lot.
I would like to build my comment on top of that.

Here is the wrapper:
```
from pyspark.sql.column import Column
from pyspark.sql import SparkSession
def from_xml(colx, schema, options={}):
    spark = SparkSession.builder.appName("xmlParser").config('spark.jars', 'jars/spark-xml_2.12-0.15.0.jar').getOrCreate()
    scala_datatype = spark._jsparkSession.parseDataType(schema.json())
    scala_options = spark.sparkContext._jvm.PythonUtils.toScalaMap(options)
    jc = spark.sparkContext._jvm.com.databricks.spark.xml.functions.from_xml(
        colx._jc if isinstance(colx, Column) else colx, scala_datatype, scala_options)
    return Column(jc)
```

and then you can call it like:
```
schema = StructType([
    ...
])
df.withColumn("parsed_xml", from_xml(col("xml_string"), schema))```

Make sure that your spark-xml jar file is available/configured properly.

That should do it!
