### ISSUE TITLE
facing java.java.lang.IllegalArgumentException.Failed to convert value 9999999909 (class of class java.lang.String) in type StructType(StructField

### ISSUE THREAD

**Issue by dude1141** [databricks/spark-xml#431]
I am receiving this error mentioned below while saving as XML, i am using spark data bricks XML spark-xml_2.11-0.7.0.jar. Request you to please suggest

I am reading data from hive using spark and creating data frames.

```

final_df= spark.sql("""select   _Dishtv,_Cid,_name,
        Channel,case when tune_type = 'true' then null else channeltune end as channeltune, Window from final""")
```

sample output
*******************
```
+-----------+---------+-----------+----------+----------+-------+------------------+---------+--------------+-----------+---------+----------------------------------------------------------------------------+-----------+-----------------+---------+-------------------+
|_Dishtv||windows|channel|tunetype|s_temp|h_null_indicator|
+-----------+---------+-----------+----------+----------+-------+------------------+---------+--------------+-----------+---------+----------------------------------------------------------------------------+-----------+-----------------+---------+-------------------+
|0181|[[08812, DIRECT, 01], [0851812, OOMR, 01], [08750151812, OOMR, 03]]|[[,,,,,,,]]|null             |[,,,,,,,]|true               |
+-----------+---------+-----------+----------+----------+-------+------------------+---------+--------------+-----------+---------+----------------------------------------------------------------------------+-----------+-----------------+---------+-------------------+
```
`final_df.write.mode("overwrite").option("rootTag","XX").option("rowTag", "abc").option("mode","PERMISSIVE").xml("abc")`

**Error:**
```
Caused by: java.lang.IllegalArgumentException: Failed to convert value 97659976554 (class of class java.lang.String) in type StructType(StructField(_Dishtv,StringType,true), StructField(
_chaneltunetypedate,IntegerType,true), StructField(_expiredtunedate,IntegerType,true)) to XML.
```

**Comment by srowen** [comment]
Can I see more of the stack trace, and the full schema of the DF? My guess is that something is parsing "97659976554" as an int but it's too big for an int.

**Comment by dude1141** [comment]
MainTV: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- _CId: string (nullable = true)
 |    |    |-- _sde: string (nullable = true)
 |    |    |-- _channelidentifier: string (nullable = true)
 |-- SDishTV: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- SubDishIP: struct (nullable = true)
 |    |    |    |-- _TTypeCode: string (nullable = true)
 |    |    |    |-- _EffeDate: integer (nullable = true)
 |    |    |    |-- _ExpDate: integer (nullable = true)|
 |    |    |-- _AId: string (nullable = true)
 |    |    |-- _City: string (nullable = true)
 |-- SSchanneltype: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- CustomerProt: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- Disneytv: struct (nullable = false)
 |    |    |    |    |    |-- _Effdte: date (nullable = true)
 |    |    |    |    |    |-- _Expate: date (nullable = true)
 |    |    |    |    |    |-- _PId: string (nullable = true)
 |    |    |    |    |    |-- _Tde: string (nullable = true)
 |    |    |    |    |-- _AId: long (nullable = true)
  |    |    |    |    |--_PId: string (nullable = true)
  |    |    |-- _CId: string (nullable = true)
 |    |    |-- _EfDate: date (nullable = true)
 |    |    |-- _ExDate: date (nullable = true)

**Comment by srowen** [comment]
What about the stack trace? I'm still not quite sure where it's happening in the code

**Comment by dude1141** [comment]
Job aborted due to stage failure: Task 146 in stage 291.0 failed 4 times, most recent failure: Lost task 146.3 in stage 291.0 (TID 25461,  com, executor 12): org.apache.spark.SparkException: Task failed while writing rows
    at org.apache.spark.internal.io.SparkHadoopWriter$.org$apache$spark$internal$io$SparkHadoopWriter$$executeTask(SparkHadoopWriter.scala:155)
    at org.apache.spark.internal.io.SparkHadoopWriter$$anonfun$3.apply(SparkHadoopWriter.scala:83)
    at org.apache.spark.internal.io.SparkHadoopWriter$$anonfun$3.apply(SparkHadoopWriter.scala:78)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:109)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Failed to convert value 13750238442 (class of class java.lang.String) in type StructType(StructField(_channeltune,StringType,true), StructField(_EffeDateMonth,StringType,true), StructField(_EffeDateYear,StringType,true), StructField(_EffDay,StringType,true), StructField(_ExpieMonth,StringType,true), StructField(_Expar,StringType,true), StructField(_ExpiDay,StringType,true)) to XML.
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$.writeElement$1(StaxXmlGenerator.scala:121)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$.com$databricks$spark$xml$parsers$StaxXmlGenerator$$writeChildElement$1(StaxXmlGenerator.scala:50)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$.com$databricks$spark$xml$parsers$StaxXmlGenerator$$writeChild$1(StaxXmlGenerator.scala:72)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$writeElement$1$3.apply(StaxXmlGenerator.scala:117)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$writeElement$1$3.apply(StaxXmlGenerator.scala:115)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$.writeElement$1(StaxXmlGenerator.scala:115)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$.com$databricks$spark$xml$parsers$StaxXmlGenerator$$writeChildElement$1(StaxXmlGenerator.scala:50)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$com$databricks$spark$xml$parsers$StaxXmlGenerator$$writeChild$1$2.apply(StaxXmlGenerator.scala:68)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$com$databricks$spark$xml$parsers$StaxXmlGenerator$$writeChild$1$2.apply(StaxXmlGenerator.scala:67)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$.com$databricks$spark$xml$parsers$StaxXmlGenerator$$writeChild$1(StaxXmlGenerator.scala:67)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$writeElement$1$3.apply(StaxXmlGenerator.scala:117)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$writeElement$1$3.apply(StaxXmlGenerator.scala:115)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$.writeElement$1(StaxXmlGenerator.scala:115)
    at com.databricks.spark.xml.parsers.StaxXmlGenerator$.apply(StaxXmlGenerator.scala:142)
    at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:103)
    at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:87)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
    at org.apache.spark.internal.io.SparkHadoopWriter$$anonfun$4.apply(SparkHadoopWriter.scala:129)
    at org.apache.spark.internal.io.SparkHadoopWriter$$anonfun$4.apply(SparkHadoopWriter.scala:127)
    at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1415)
    at org.apache.spark.internal.io.SparkHadoopWriter$.org$apache$spark$internal$io$SparkHadoopWriter$$executeTask(SparkHadoopWriter.scala:139)
    ... 8 more

Driver trace

**Comment by srowen** [comment]
Hm, there is some mismatch between the expected schema and actual values, which is weird, because the DF's schema has to be consistent with its contents.

You have columns named like "_Dishtv". spark-xml treats columns that start with "_" as XML attributes by default. I don't yet see how that could be the issue, but it would probably fail if one of your struct-valued cols started with "_".

The schema mentioned in the error doesn't seem to match part of the schema you printed above, nor the schema of the result in the original post up top. Is it possible to clarify exactly what you are running to get this? 

Is it possible to privately share a snippet of data that could be read/written to reproduce it?

**Comment by dude1141** [comment]
Actually I am creating a tag which contains attributes,so   I used select *, struct (_custid,_date) as sample from dataframe.
Is this correct  ?

**Comment by srowen** [comment]
OK, I understand. Can you be clearer about what you mean there? I'm trying to figure out if the problem is how you are defining the DataFrame. The error vs example above aren't consistent, so I'm having trouble understanding what the setup is.

Is there any simpler, fake example you can share that reproduces this?
I'm still guessing it's some column with a `_` prefix that isn't doing what you want it to.

**Comment by dude1141** [comment]
root
 |-- _abc: string (nullable = true)
 |-- _BDay: string (nullable = true)
 |-- _BMonth: string (nullable = true)
 |-- CDIer: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- _CId: string (nullable = true)
 |    |    |-- _Dode: string (nullable = [true)](url)
 |    |    |-- _Dier: string (nullable = true)
 |-- MMress: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- TPnt: struct (nullable = false)
 |    |    |    |-- _Tode: string (nullable = true)
 |    |    |    |-- _EffMonth: string (nullable = true)
 |    |    |    |-- _ExpMonth: string (nullable = true)
 |    |    |-- _Ane1: string (nullable = true)
 |    |    |-- _AId: string (nullable = true)
 |    |    |-- _City: string (nullable = true)
 |    |    |-- _Code: string (nullable = true)
 |    |    |-- _FCode: string (nullable = true)
 |-- BBBBBer: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- Bductt: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- Pct: struct (nullable = false)
 |    |    |    |    |    |-- _EfDate: date (nullable = true)
 |    |    |    |    |    |-- _ExpDate: date (nullable = true)
 |    |    |    |    |    |-- _Pd: string (nullable = true)
 |    |    |    |    |    |-- _PCode: string (nullable = true)
 |    |    |    |    |-- _Abc: string (nullable = true)
 |    |    |    |    |-- _ANumber: string (nullable = false)
 |    |    |    |    |-- _CId: string (nullable = true)
 |    |    |    |    |-- _AId: string (nullable = true)
 
 
 
![image](https://user-images.githubusercontent.com/48873398/73043472-387a1300-3e33-11ea-9540-d7c682e98ae1.png)




mple xml tree
```
</MMRESS>

-		<MMRESS AId="827" Ane1="185 MAT" City="SAINE" StateProvCode="A9" Pcod="09" Cde="US">

				<TPnt TCode="RESON"  EfeMonth="11" ExpMonth="02"/>

</MMRESS>
```

   ```
     val dataframe2=spark.sql("""
     select * ,MMRESS__ADDR_ as _Ane1,  MMRESS__ADDR_ as _AId,
   MMRESS__ADDR_ as _City , MMRESS__ADDR_  as _Code, MMRESS__ADDR_  as _FCode,
   struct(_TCode,_EffMonth,_ExpMonth) as TPnt from dataframe1 """)
   
  var MRESSDF1 = dataframe2.groupBy("MMRESS_PID").agg(collect_set(struct("TPnt","_Ane1","_AId","_City","_CCode","_FCode")).alias("MMRESS"))
 
```
 Actually I am creating a tag that contains attributes,so I used select *, struct (_Ane1,_Aid,......) as sample from dataframe.
Is this correct ?

sa

**Comment by srowen** [comment]
I'm still not clear here. The schema above is the schema for what? the names don't seem to match your XML sample or query. You are writing XML, but are you also reading from XML? I think I'd have to at least see a (redacted) example of the exact schema of the DF that is being written as XML, and how it is derived. A sample row of input would help too if possible, just to verify it matches what you are reading.

I can try to create something like this example locally, but I don't know if it would reproduce what you're doing.

**Comment by srowen** [comment]
Hm, I can't reproduce this so far, in attempting to replicate what you have. For example:

```
val schema = buildSchema(
      array("MMress",
        struct(
          struct("TPnt",
            field("_Tode"),
            field("_EffMonth"),
            field("_ExpMonth")),
          field("_Ane1"),
          field("_AId"),
          field("_City"),
          field("_Code"),
          field("_FCode"))))
    
    schema.printTreeString()

    val data = Row(Array(Row(Row("RESON", "11", "02"), "185 MAT", "827", "SAINE", "US", "09")))
    val df = spark.createDataFrame(spark.sparkContext.parallelize(Seq(data)), schema)
    df.show(truncate = false)
      
    df.write.mode("overwrite").option("rootTag", "root").option("rowTag", "row").xml("/tmp/abc.xml")
```

Shows schema:

```
root
 |-- MMress: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- TPnt: struct (nullable = true)
 |    |    |    |-- _Tode: string (nullable = true)
 |    |    |    |-- _EffMonth: string (nullable = true)
 |    |    |    |-- _ExpMonth: string (nullable = true)
 |    |    |-- _Ane1: string (nullable = true)
 |    |    |-- _AId: string (nullable = true)
 |    |    |-- _City: string (nullable = true)
 |    |    |-- _Code: string (nullable = true)
 |    |    |-- _FCode: string (nullable = true)
```

And writes out ...

```
<root>
    <row>
        <MMress Ane1="185 MAT" AId="827" City="SAINE" Code="US" FCode="09">
            <TPnt Tode="RESON" EffMonth="11" ExpMonth="02"></TPnt>
        </MMress>
    </row>

</root>
```

**Comment by dude1141** [comment]
emaild you

**Comment by srowen** [comment]
I'll leave these open to see if anyone encounters something similar. But to date we haven't been able to identify a reproduction or the source of the issue. FWIW, I threw together some test cases like this that seemed to work fine:

```
test("test issue 431") {
    val schema = buildSchema(
      field("foo"),
      field("_bar"),
      array("MMress",
        struct(
          array("TPnts",
            struct(
              field("_Tode"),
              field("_EffMonth"),
              field("_ExpMonth"))),
          field("_Ane1"),
          field("_AId"),
          field("_City"),
          field("_Code"),
          field("_FCode"))))
    
    schema.printTreeString()

    val data = Row("baz", "bing", 
      Array(Row(Array(Row("RESON", "11", "02")), "185 MAT", "827", "SAINE", "US", "09"),
            Row(Array(Row("RESON", "11", "02"), Row("RESON", "11", "02")),
              "185 MAT", "827", "SAINE", "US", "09"),
            null))
    val data2 = Row(null, null, null)
    val df = spark.createDataFrame(spark.sparkContext.parallelize(Seq(data, data2, data)), schema)
    df.show(truncate = false)
      
    df.repartition(1).write.mode("overwrite").
      option("rootTag", "root").option("rowTag", "row").xml("/tmp/abc.xml")
  }

  test("test issue 431 2") {
    val schema = buildSchema(
        array("Foo",
          struct(
            field("_bar"),
            field("_baz")
          )),
        array("MMress",
          struct(
            array("TPnts",
              struct(
                field("_Tode"),
                field("_EffMonth"),
                field("_ExpMonth"))),
            field("_Ane1"),
            field("_AId"),
            field("_City"),
            field("_Code"),
            field("_FCode"))))

    schema.printTreeString()
    
    val data = Row(
      Array(Row("123", "456"), Row("abc", "def")),
      Array(Row(Array(Row("RESON", "11", "02"), Row("RESON", "11", "02")),
        "185 MAT", "827", "SAINE", "US", "09")))
    
    val df = spark.createDataFrame(spark.sparkContext.parallelize(Seq(data)), schema)
    df.show(truncate = false)

    df.repartition(1).write.mode("overwrite").
      option("rootTag", "root").option("rowTag", "row").xml("/tmp/abc.xml")
  }
```

**Comment by dude1141** [comment]
when struct of elements is null i am receiving this error, for example here for some cid's  MMRESSis null ,i got that error for this id
please suggest how you are handling nulls for these issues

**Comment by giuseppeceravolo** [comment]
Hi! I guess I am getting this same error:

_Caused by: java.lang.IllegalArgumentException: Failed to convert value MyDescription (class of class java.lang.String) in type ArrayType(StructType(StructField(_ID,StringType,true),StructField(_Level,StringType,true)),true) to XML._

Please check out the code below.

```py
fake_file_df = spark \
    .sql(
        """SELECT
            CAST(STRUCT('ItemId' AS `_Type`, '123' AS `_VALUE`) AS STRUCT<_Type: STRING, _VALUE: STRING>) AS ItemID,
            CAST(STRUCT('UPC' AS `_Type`, '123' AS `_VALUE`) AS STRUCT<_Type: STRING, _VALUE: STRING>) AS UPC,
            CAST('' AS STRING) AS _SerialNumberFlag,
            CAST('MyDescription' AS STRING) AS Description,
            CAST(ARRAY(STRUCT(NULL AS `_ID`, NULL AS `_Level`)) AS ARRAY<STRUCT<_ID: STRING, _Level: STRING>>) AS MerchandiseHierarchy,
            CAST(ARRAY(STRUCT(NULL AS `_ValueTypeCode`, NULL AS `_VALUE`)) AS ARRAY<STRUCT<_ValueTypeCode: STRING, _Value: STRING>>) AS ItemPrice,
            CAST('' AS STRING) AS Color,
            CAST('' AS STRING) AS IntendedIndustry,
            CAST(STRUCT(NULL AS `Name`) AS STRUCT<Name: STRING>) AS Manufacturer,
            CAST(STRUCT(NULL AS `Season`) AS STRUCT<Season: STRING>) AS Marketing,
            CAST(STRUCT(NULL AS `_Name`) AS STRUCT<_Name: STRING>) AS BrandOwner,
            CAST(ARRAY(STRUCT('Attribute1' AS `_Name`, 'Value1' AS `_VALUE`)) AS ARRAY<STRUCT<_Name: STRING, AttributeValue: STRING>>) AS ItemAttribute_culinary,
            CAST(ARRAY(STRUCT(NULL AS `_Name`, ARRAY(ARRAY(STRUCT(NULL AS `AttributeCode`, NULL AS `AttributeValue`))) AS `_VALUE`)) AS ARRAY<STRUCT<_Name: STRING, _VALUE: ARRAY<ARRAY<STRUCT<AttributeCode: STRING, AttributeValue: STRING>>>>>) AS ItemAttribute_noculinary,
            CAST(STRUCT(STRUCT(NULL AS `_UnitOfMeasure`, NULL AS `_VALUE`) AS `Depth`, STRUCT(NULL AS `_UnitOfMeasure`, NULL AS `_VALUE`) AS `Height`, STRUCT(NULL AS `_UnitOfMeasure`, NULL AS `_VALUE`) AS `Width`, STRUCT(NULL AS `_UnitOfMeasure`, NULL AS `_VALUE`) AS `Diameter`) AS STRUCT<Depth: STRUCT<_UnitOfMeasure: STRING, _VALUE: STRING>, Height: STRUCT<_UnitOfMeasure: STRING, _VALUE: STRING>, Width: STRUCT<_UnitOfMeasure: STRING, _VALUE: STRING>, Diameter: STRUCT<_UnitOfMeasure: STRING, _VALUE: STRING>>) AS ItemMeasurements,
            CAST(STRUCT('GroupA' AS `TaxGroupID`, 'CodeA' AS `TaxExemptCode`, '1' AS `TaxAmount`) AS STRUCT<TaxGroupID: STRING, TaxExemptCode: STRING, TaxAmount: STRING>) AS TaxInformation,
            CAST('' AS STRING) AS ItemImageUrl,
            CAST(ARRAY(ARRAY(STRUCT(NULL AS `_action`, NULL AS `_franchiseeId`, NULL AS `_franchiseeName`))) AS ARRAY<ARRAY<STRUCT<_action: STRING, _franchiseeId: STRING, _franchiseeName: STRING>>>) AS ItemFranchisees,
            CAST('Add' AS STRING) AS _Action
        ;"""
    )
fake_file_df.display()

fake_file_df \
    .coalesce(1) \
    .write \
    .format('com.databricks.spark.xml') \
    .option('declaration', 'version="1.0" encoding="UTF-8"') \
    .option("nullValue", "") \
    .option('rootTag', "root_tag") \
    .option('rowTag', "row_tag") \
    .mode('overwrite') \
    .save(xml_folder_path)
```

Please find the full traceback attached.
[IllegalArgumentException.txt](https://github.com/databricks/spark-xml/files/12768974/IllegalArgumentException.txt)

**Comment by giuseppeceravolo** [comment]
I noticed that it works if I try to write all columns up to "Color" (excluded), namely:

```py
fake_file_df \
    .select(
        "ItemID",
        "UPC",
        "_SerialNumberFlag",
        "Description",
        "MerchandiseHierarchy",
        "ItemPrice"
    ) \
    .coalesce(1) \
    .write \
    .format('com.databricks.spark.xml') \
    .option('declaration', 'version="1.0" encoding="UTF-8"') \
    .option("nullValue", "") \
    .option('rootTag', "root_tag") \
    .option('rowTag', "row_tag") \
    .mode('overwrite') \
    .save(xml_folder_path)
```

This works, but as soon as I add "Color" to the .select() it throws the error above:

_Caused by: java.lang.IllegalArgumentException: Failed to convert value MyDescription (class of class java.lang.String) in type ArrayType(StructType(StructField(_ID,StringType,true),StructField(_Level,StringType,true)),true) to XML._

**Comment by giuseppeceravolo** [comment]
Hi @srowen I have found a workaround in the meantime: to put all string columns at the end of the DataFrame.
I know this might result in a longer plan, but it is the best I have got so far to avoid the error.
Please advice on any better solution!

```py
import pyspark.sql.functions as t

for struct_field in fake_file_df.schema.fields:
    if isinstance(struct_field.dataType, t.StringType):
        print(f"{struct_field.name = }")
        fake_file_df = fake_file_df \
            .selectExpr(
                *[col for col in fake_file_df.columns if col != struct_field.name],
                struct_field.name
            )
        print("\n")
```

This way I managed to write the following file (with the write code above):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root_tag>
    <row_tag SerialNumberFlag="" Action="Add">
        <ItemID Type="ItemId">123</ItemID>
        <UPC Type="UPC">123</UPC>
        <MerchandiseHierarchy ID="" Level=""/>
        <ItemPrice ValueTypeCode="" Value=""/>
        <Manufacturer>
            <Name></Name>
        </Manufacturer>
        <Marketing>
            <Season></Season>
        </Marketing>
        <BrandOwner Name=""/>
        <ItemAttribute_culinary Name="Attribute1">
            <AttributeValue>Value1</AttributeValue>
        </ItemAttribute_culinary>
        <ItemAttribute_noculinary Name="">
            <item>
                <AttributeCode></AttributeCode>
                <AttributeValue></AttributeValue>
            </item>
        </ItemAttribute_noculinary>
        <ItemMeasurements>
            <Depth UnitOfMeasure=""></Depth>
            <Height UnitOfMeasure=""></Height>
            <Width UnitOfMeasure=""></Width>
            <Diameter UnitOfMeasure=""></Diameter>
        </ItemMeasurements>
        <TaxInformation>
            <TaxGroupID>GroupA</TaxGroupID>
            <TaxExemptCode>CodeA</TaxExemptCode>
            <TaxAmount>1</TaxAmount>
        </TaxInformation>
        <ItemFranchisees>
            <item action="" franchiseeId="" franchiseeName=""/>
        </ItemFranchisees>
        <Description></Description>
        <Color>MyDescription</Color>
        <IntendedIndustry></IntendedIndustry>
        <ItemImageUrl></ItemImageUrl>
    </row_tag>

</root_tag>
```

**Comment by giuseppeceravolo** [comment]
Hi @srowen I just realized that my solution does not work, unfortunately.

As you can see from the output above, spark-xml wrote the content of the tag "Description" into the tag "Color".

```xml
...
        <Description></Description>
        <Color>MyDescription</Color>
...
```

And if I remove "Color" from the select, it will write "MyDescription" into the following string tag (e..g, "IntendedIndustry").

This is a quite blocking issue I am currently facing with my Client in Production.

Do you have any idea on how to fix it? Thanks!

**Comment by srowen** [comment]
This means your schema doesn't match your data for writing, or something along those lines. I don't know what your data looks like. This code has been ported to Apache Spark now anyway so won't be updated here

**Comment by giuseppeceravolo** [comment]
My data looks exactly like this 1-row "fake_file_df". I provide an end-to-end code snippet to test it out yourself and replicate this issue (*).

I am afraid I am not getting why my schema would not match my data since all I am doing is selecting 1 single row into a DataFrame and writing it as xml but it (1) either fails if string columns are in between non-string ones or (2) if I put all string columns at the end then I get a wrong xml.

So, who should I get in contact with to investigate this issue further and ask for support on spark-xml?

(*) Please find below the end-to-end code snippet that results into the error, namely the case (2) when I put all string columns at the end of the 1-row DataFrame but it mistakenly writes the content of one column into the tag right after it.
```py
fake_file_df = spark \
    .sql(
        """SELECT
            CAST(STRUCT('ItemId' AS `_Type`, '123' AS `_VALUE`) AS STRUCT<_Type: STRING, _VALUE: STRING>) AS ItemID,
            CAST(STRUCT('UPC' AS `_Type`, '123' AS `_VALUE`) AS STRUCT<_Type: STRING, _VALUE: STRING>) AS UPC,
            CAST(ARRAY(STRUCT(NULL AS `_ID`, NULL AS `_Level`)) AS ARRAY<STRUCT<_ID: STRING, _Level: STRING>>) AS MerchandiseHierarchy,
            CAST(ARRAY(STRUCT(NULL AS `_ValueTypeCode`, NULL AS `_VALUE`)) AS ARRAY<STRUCT<_ValueTypeCode: STRING, _Value: STRING>>) AS ItemPrice,
            CAST(STRUCT(NULL AS `Name`) AS STRUCT<Name: STRING>) AS Manufacturer,
            CAST(STRUCT(NULL AS `Season`) AS STRUCT<Season: STRING>) AS Marketing,
            CAST(STRUCT(NULL AS `_Name`) AS STRUCT<_Name: STRING>) AS BrandOwner,
            CAST(ARRAY(STRUCT('Attribute1' AS `_Name`, 'Value1' AS `_VALUE`)) AS ARRAY<STRUCT<_Name: STRING, AttributeValue: STRING>>) AS ItemAttribute_culinary,
            CAST(ARRAY(STRUCT(NULL AS `_Name`, ARRAY(ARRAY(STRUCT(NULL AS `AttributeCode`, NULL AS `AttributeValue`))) AS `_VALUE`)) AS ARRAY<STRUCT<_Name: STRING, _VALUE: ARRAY<ARRAY<STRUCT<AttributeCode: STRING, AttributeValue: STRING>>>>>) AS ItemAttribute_noculinary,
            CAST(STRUCT(STRUCT(NULL AS `_UnitOfMeasure`, NULL AS `_VALUE`) AS `Depth`, STRUCT(NULL AS `_UnitOfMeasure`, NULL AS `_VALUE`) AS `Height`, STRUCT(NULL AS `_UnitOfMeasure`, NULL AS `_VALUE`) AS `Width`, STRUCT(NULL AS `_UnitOfMeasure`, NULL AS `_VALUE`) AS `Diameter`) AS STRUCT<Depth: STRUCT<_UnitOfMeasure: STRING, _VALUE: STRING>, Height: STRUCT<_UnitOfMeasure: STRING, _VALUE: STRING>, Width: STRUCT<_UnitOfMeasure: STRING, _VALUE: STRING>, Diameter: STRUCT<_UnitOfMeasure: STRING, _VALUE: STRING>>) AS ItemMeasurements,
            CAST(STRUCT('GroupA' AS `TaxGroupID`, 'CodeA' AS `TaxExemptCode`, '1' AS `TaxAmount`) AS STRUCT<TaxGroupID: STRING, TaxExemptCode: STRING, TaxAmount: STRING>) AS TaxInformation,
            CAST('' AS STRING) AS ItemImageUrl,
            CAST(ARRAY(ARRAY(STRUCT(NULL AS `_action`, NULL AS `_franchiseeId`, NULL AS `_franchiseeName`))) AS ARRAY<ARRAY<STRUCT<_action: STRING, _franchiseeId: STRING, _franchiseeName: STRING>>>) AS ItemFranchisees,
            CAST('' AS STRING) AS _SerialNumberFlag,
            CAST('MyDescription' AS STRING) AS Description,
            CAST('' AS STRING) AS Color,
            CAST('' AS STRING) AS IntendedIndustry,
            CAST('Add' AS STRING) AS _Action
        ;"""
    )

fake_file_df \
    .coalesce(1) \
    .write \
    .format('com.databricks.spark.xml') \
    .option('declaration', 'version="1.0" encoding="UTF-8"') \
    .option("nullValue", "") \
    .option('rootTag', "root_tag") \
    .option('rowTag', "row_tag") \
    .mode('overwrite') \
    .save(xml_folder_path)
```

And the output is a wrong xml where "MyDescription" is writte inside the "Color" tag instead of the "Description" tag.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root_tag>
    <row_tag SerialNumberFlag="" Action="Add">
        <ItemID Type="ItemId">123</ItemID>
        <UPC Type="UPC">123</UPC>
        <MerchandiseHierarchy ID="" Level=""/>
        <ItemPrice ValueTypeCode="" Value=""/>
        <Manufacturer>
            <Name></Name>
        </Manufacturer>
        <Marketing>
            <Season></Season>
        </Marketing>
        <BrandOwner Name=""/>
        <ItemAttribute_culinary Name="Attribute1">
            <AttributeValue>Value1</AttributeValue>
        </ItemAttribute_culinary>
        <ItemAttribute_noculinary Name="">
            <item>
                <AttributeCode></AttributeCode>
                <AttributeValue></AttributeValue>
            </item>
        </ItemAttribute_noculinary>
        <ItemMeasurements>
            <Depth UnitOfMeasure=""></Depth>
            <Height UnitOfMeasure=""></Height>
            <Width UnitOfMeasure=""></Width>
            <Diameter UnitOfMeasure=""></Diameter>
        </ItemMeasurements>
        <TaxInformation>
            <TaxGroupID>GroupA</TaxGroupID>
            <TaxExemptCode>CodeA</TaxExemptCode>
            <TaxAmount>1</TaxAmount>
        </TaxInformation>
        <ItemImageUrl></ItemImageUrl>
        <ItemFranchisees>
            <item action="" franchiseeId="" franchiseeName=""/>
        </ItemFranchisees>
        <Description></Description>
        <Color>MyDescription</Color>
        <IntendedIndustry></IntendedIndustry>
    </row_tag>
</root_tag>
```

**Comment by srowen** [comment]
Hm yeah not sure what the problem is there. I won't be able to debug it, but if you figure out a solution, open a PR for Apache Spark to fix it.
