### ISSUE TITLE
rowValidationXSDPath is not working when using from_xml function

### ISSUE THREAD

**Issue by gpadavala** [databricks/spark-xml#432]
```
df = spark.read.load(
                path="books.xml",
                schema=schema,
                format="xml",
                rowTag='books',
                rowValidationXSDPath="books.xsd",
            )

```
I have used an invalid xml and it is properly loaded into _corrupt_record when using the `rowValidationXSDPath` directly 

But the same is not working when parsing the data from a column using the new "from_xml" function
```
df = df.withColumn("parsed", from_xml(col('value'), schema, {'rowValidationXSDPath': "books.xsd", "mode": "PERMISSIVE"}))
```

it just gets loaded normally

**Comment by srowen** [comment]
Yes you're right, it isn't currently checked. It can be. Your example highlights an issue that isn't directly related, but relevant: what would it mean to fail with "permissive" in this case? you'd get a result with a new column, but it won't match the schema you expect, and probably just doesn't make sense.

FailFast and DropMalformed make sense: you get an error or null.

What do you think about warning the user if "PERMISSIVE" is specified and consider it "DROPMALFORMED"?

**Comment by GeethanadhP** [comment]
Ignore the PERMISSIVE in my code, i added it just to see if it works if i add that option specifically, only then i checked the code and saw it was not implemented..

For my use case, i am streaming data from kafka which contains xml files, and i parse them write the stream out, 
I don't want to DROPMALFORMED records (as they have data too), 
and also not raise and error (as that would stop the streaming job)
Instead i want to have them put under the _corrupt_record, which will then be viewed and required action will be taken on those records

Logically speaking `_corrupt_record` is generated when reading from file system, i think it should have same functionality when reading from the memory too

**Comment by srowen** [comment]
Yeah DROPMALFORMED would just give you a null, not drop any rows - it wouldn't make sense to drop the whole row.

The problem I see is that you tell it to parse 'value' as some struct type, and you may not get that struct type back. You might get an extra column. That's OK if returning a whole DataFrame, whose schema spark-xml can define, but not so much when the user has asked for a particular schema.

There's another possible solution to your particular case: just map the XML field as an RDD[String] and apply spark-xml directly, as if on input files. It works that way too and the usual semantics apply.

**Comment by GeethanadhP** [comment]
yes the custom schema has _corrupt_record in it (right now its null for all rows except those with invalid xml)

I do have a solution using udf that does the validation

But just raised this ticket bcoz both `from_xml` and spark.read.xml both parse the xml and both takes "XmlOptions" object, so my assumption would be they both should work the same way :)

bcoz of that assumption i thought the `rowValidationXSDPath` is not at all working untill i checked reading from a file instead..
not sure if others will have same assumption or not

**Comment by srowen** [comment]
OK, adding XSD validation to from_xml is easy, so I can do that. One concern I had is that parsing the XSD is expensive, but, it already uses an internal cache, so shouldn't be a big deal.

The parse mode question isn't even that specific to the XSD question. It's just another way parsing can fail. But since it came up here I think we can also refine the semantics to make as much sense as possible:

- If parse mode is PERMISSIVE, and the corrupt record column was given in the schema, then use it as normal
  - ... otherwise, assume DROPMALFORMED
- If DROPMALFORMED, return a null column value on error
- If FAILFAST, of course fail on error

**Comment by GeethanadhP** [comment]
yaa seems fair to me :)

**Comment by srowen** [comment]
I will pursue this with the PR at #433
