### ISSUE TITLE
Maven repo path

### ISSUE THREAD

**Issue by Abhilash61360** [databricks/spark-xml#434]
Hi HyukjinKwon,

Tried reaching you on the email id i got from linkedin.

Could you please confirm the below Maven page is official page for anyone to download the corresponding jar file for this package please.

https://mvnrepository.com/artifact/com.databricks/spark-xml

Thanks,
Abhilash

**Comment by srowen** [comment]
Well, the artifacts are posted to Maven Central, the standard repo for Maven and many other tools. You don't generally download it via the web at all. But, Maven Central's web UI has the artifact at https://search.maven.org/search?q=a:spark-xml_2.12 

The site you mention is a third-party index of packages and points to the Maven Central copy, so yes it's fine, but that actually isn't Maven Central.

**Comment by Abhilash61360** [comment]
Thank you.
