### ISSUE TITLE
Feature request : Need an api to return StructType when xml-string is passed

### ISSUE THREAD

**Issue by RaoPisay** [databricks/spark-xml#443]
Struggling to find a direct api which gives StructType when xml-string is passed.
There is api present but that takes SparkSession which returns Dataset<row> and by using we need to do .schema(), Currently we are doing like below.
new XmlReader().withRowTag(rowTag).xmlRdd(spark_session, rdd));

**Comment by HyukjinKwon** [comment]
You could use `schema_of_xml` - https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/package.scala#L124-L126

**Comment by RaoPisay** [comment]
But the method 'schema_of_xml' takes 'Dataset[String]' as an argument.

**Comment by HyukjinKwon** [comment]
You can do `schema_of_xml(Seq("xml-string").toDS)`

**Comment by RaoPisay** [comment]
which scala version of Seq has toDS method?
https://www.scala-lang.org/api/current/scala/collection/Seq.html
I don't find it in the link above.

**Comment by HyukjinKwon** [comment]
Spark's implicit has it. You might have to do `import spark.implicits._`.

**Comment by RaoPisay** [comment]
Dear @HyukjinKwon, Thank you very much, I'm able to solve, I did a small reverse engineering and found what is happening under the hood.

> Dataset<String> ds = session.createDataset(Arrays.asList(xml_string), Encoders.STRING());
> StructType xmlStructType = InferSchema.infer(ds.rdd(), new XmlOptions());

**Comment by HyukjinKwon** [comment]
Oh you're using Java API. Sure that should be the right way.
