### ISSUE TITLE
Cannot access attribute values from a specific hierarchy in xml

### ISSUE THREAD

**Issue by smoshah** [databricks/spark-xml#452]
Hi,
I am working with xml structure something like below:
```
<flow>
    <request>
        <user>
            <id></id>
            <url></url>
    </request>
    <app_details>
        <id></id>
        <op></op>
        <seq></seq>
    </app_details>
    <service>
        <details></details>
        <app>
            <abc></abc>
            <abc></abc>
            <abc></abc>
            <xyz>
                <lmn></lmn>
            </xyz>
            <processing>
                <obj></obj>
                <data>
                    <bin id="123" cd="LXB" date="2020-06-05" fg="K" prod="WTC" del="false"/>
                    <bin id="909" cd="LXB" date="2020-04-05" fg="K" prod="WTC" del="false"/>
                </data>
            </processing>
        </app>
    </service>
</flow>
```

This is my python statement:
`spark.read.format('xml').option("rowTag", "app").option("attributePrefix","_Att_").load(xml_path)`

As long as my rowTag is at the level of '**app**' or lower like '**processing**' or '**data**' I can read the attribute values from **'bin'**. If I specify '**service**' or '**flow**' as my rowTag which are above '**app**', I get null for all attribute values in **'bin'**.
Any idea what can be the cause?

Thanks

**Comment by srowen** [comment]
There is an asymmetry in how tags with attributes are handled. Still I'd not expect to differ whether `processing` or `app` is the root. Are you sure there isn't some malformed XML or something in `app` elsewhere? `FAILFAST` mode would help pick that up. Or else can you supply something that reproduces it? this XML isn't well-formed even.

**Comment by smoshah** [comment]
Hi, thanks for the suggestion. I did try the `FAILFAST `mode and it failed on selecting data from dataframe. Stack trace showed an exception on trying to cast a null value as an integer. I couldn't find which field was it since it is a big xml document and stack trace had no mention of the exact field as well. I ended up setting `inferschema = false` and it seems to be working fine now.
