### ISSUE TITLE
Spark 3.0.0 SQL API - TEMPORARY TABLE fails

### ISSUE THREAD

**Issue by PhilippLange** [databricks/spark-xml#459]
Hi,

We have been using this Library for over a year now.
Today I was upgrading Spark from 2.4.5 (Scala 2.11) to 3.0.0 (Scala 2.12) and I'm running into an error when creating a temporary table through the SQL API.

Previously creating a temporary table through the SQL API worked fine like this:
```
CREATE TEMPORARY TABLE tb_tmp (...mySchema...)
USING com.databricks.spark.xml
OPTIONS (path "...myPath...", rowTag "...myRowTag...")
```

Now I'm running into the following exception:
`Error in SQL statement: IllegalArgumentException: 'path' must be specified for XML data.`

Thanks for having a look at this!

BR Philipp
[exception.txt](https://github.com/databricks/spark-xml/files/4798975/exception.txt)

**Comment by srowen** [comment]
I am pretty sure the options syntax is `path="...",` etc. It's possible Spark 3 is stricter about that. But this otherwise should work with Spark 3.

**Comment by PhilippLange** [comment]
The create works when I create the table without "TEMPORARY" in Spark 3.

**Comment by PhilippLange** [comment]
> I am pretty sure the options syntax is `path="...",` etc. It's possible Spark 3 is stricter about that. But this otherwise should work with Spark 3.

The create works when I create the table without "TEMPORARY" in Spark 3.

**Comment by srowen** [comment]
Hm no that's not it. I see we have tests that still succeed in Spark 3 without '='.
https://github.com/databricks/spark-xml/blob/665d2fe8202ed11d4994b0a7426aa5229081c227/src/test/scala/com/databricks/spark/xml/XmlSuite.scala#L260

The tests do `CREATE TEMPORARY VIEW`, but I added one with `CREATE TEMPORARY TABLE` now and it worked too. I'm curious if `VIEW` works for you? should be the right way to declare that anyway.
What version of spark-xml?

At the moment I can't reproduce.

**Comment by srowen** [comment]
Actually: can you use `LOCATION "..."` instead of `path` as an `OPTIONS` item? that seems to be more correct. It also looks like (at least according to the Spark 3 docs) that `CREATE TABLE` isn't meant to accept `TEMPORARY`, in favor of `CREATE TEMPORARY VIEW`. But then that doesn't accept options; it's defined as a query. but then it does work in the unit tests.

**Comment by PhilippLange** [comment]
I'm using spark-xml 0.9.0 for Scala 2.12.

As you suggested the CREATE TEMPORARY VIEW worked, thanks for the quick help / sorry for the confusion.

**Comment by srowen** [comment]
OK cool. Still not 100% clear why some of these things work - maybe supported unofficially. `LOCATION` may also be a better way to specify it, which also seems to work.
