### ISSUE TITLE
NoSuchMethodError when calling from_xml from PySpark

### ISSUE THREAD

**Issue by fcvr1010** [databricks/spark-xml#463]
Hi, I'm trying to use the `from_xml` function from PySpark as documented in the README but I run into the following issue:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o538.save.
: java.lang.NoSuchMethodError: com.databricks.spark.xml.parsers.StaxXmlParser$.parseColumn(Ljava/lang/String;Lorg/apache/spark/sql/types/StructType;Lcom/databricks/spark/xml/XmlOptions;)Lorg/apache/spark/sql/Row;
	at com.databricks.spark.xml.XmlDataToCatalyst.nullSafeEval(XmlDataToCatalyst.scala:45)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:393)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:389)
	at org.apache.spark.sql.catalyst.optimizer.ConstantFolding$$anonfun$apply$1$$anonfun$applyOrElse$1.applyOrElse(expressions.scala:52)
	at org.apache.spark.sql.catalyst.optimizer.ConstantFolding$$anonfun$apply$1$$anonfun$applyOrElse$1.applyOrElse(expressions.scala:45)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:256)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:256)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:255)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsDown$1.apply(QueryPlan.scala:83)
        [...]
```

I'm adding the library to the cluster by setting `"spark.jars.packages": "com.databricks:spark-xml_2.11:0.9.0"` in the configuration options.

I have also verified that, without the `spark.jars.packages`, `from_xml` is not found, so I guess there shouldn’t be another conflicting version of the library in the cluster.

To further check, I have run `print(dir(spark._jvm.com.databricks.spark.xml.parsers.StaxXmlParser))` from the driver and, indeed, I only obtained `['parse']` as a result. Something analogous happens for  `StaxXmlParserUtils`: several functions are returned by `dir(...)` but not all the available ones. Any idea about what could be the issue here? Thanks! 

Spark version is 2.4.0 and the python path is set as follows: `PYTHONPATH="${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.10.7-src.zip:${PYTHONPATH}"`

**Comment by srowen** [comment]
Hm, that is weird. The method was added in January so should be in the 0.9.0 version. No chance you have multiple copies of the library on your classpath? How are you calling from Pyspark, as in https://github.com/databricks/spark-xml#pyspark-notes ?

**Comment by fcvr1010** [comment]
Many thanks for the prompt feedback @srowen.

> How are you calling from Pyspark, as in https://github.com/databricks/spark-xml#pyspark-notes ?

Yes, I copied-pasted that code.

> No chance you have multiple copies of the library on your classpath?

I don't think so because if I remove the library from `"spark.jars.packages"` then not even `from_xml` is found (error is `JavaPackage object is not callable` right when defining `ext_from_xml`.

**Comment by fcvr1010** [comment]
Perhaps, to further exclude a conflicting version, I can try to run a standard `spark.read.format("xml").load(...)` without adding the library via `spark.jars.packages`. Let me do that.

**Comment by fcvr1010** [comment]
> Perhaps, to further exclude a conflicting version, I can try to run a standard `spark.read.format("xml").load(...)` without adding the library via `spark.jars.packages`. Let me do that.

Oops, that's actually the case, there is a 0.5.0 version lingering around. My apologies for the noise but I'm not fully in control of the cluster so I wasn't aware of this (plus the `from_xml` failure tricked me into believing there was no other library, initially).

Closing this. Thanks!

**Comment by srowen** [comment]
Ah OK, that makes a lot more sense then
