### ISSUE TITLE
Problem reading data from Azure blob

### ISSUE THREAD

**Issue by codelite1204** [databricks/spark-xml#466]
Hi!  Thank you all for the wonderful work that you've contributed to this package.

I'm trying to use the package to read from an Azure blob but I'm getting an error.  Here are the details...

file_path="wasbs://container_name@acct_name.blob.core.windows.net/*.xml" 
df = spark.read.format("xml").options(rowTag='rowTag').load(file_path, schema=schema)
Error:  AzureException: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Container container_name in account acct_name.blob.core.windows.net not found, and we can't create it using anoynomous credentials, and no credentials found for them in the configuration.

If it try to access the blob container using a file of different format, i.e. csv, the read works so I'm pretty sure that the container_name is there and that I can read from it.
file_path="wasbs://container_name@acct_name.blob.core.windows.net/*.csv" 
df = spark.read.format("csv").load(file_path, header=True, sep='|') ## this works and store the data in the dataframe

Appreciate your help in advance.  Thank you!

**Comment by srowen** [comment]
Hm, that's not going to be related to this library per se. It's an auth error from Azure. I don't know why it would be different from CSV though. This library just doesn't do anything that special to read data. I am not sure how you are supplying credentials or whether somehow this ends up not propagating, but I also don't have any reason to believe this is different w.r.t. file access
