### ISSUE TITLE
Load entire xml having multiple rowTags

### ISSUE THREAD

**Issue by Sumit2889** [databricks/spark-xml#478]
I'm trying to load the whole xml having multiple ```rowTag``` in pyspark. Is there any way to load the xml without mentioning ```rowTag```?

**Comment by Sumit2889** [comment]
I'm trying to load the whole xml having multiple rowTags in pyspark. Is there any way to load the xml without mentioning rowTags?

**Comment by srowen** [comment]
You have to specify a rowTag, so it knows what structure to parse as a row of the resulting DataFrame. You must have some repeating element like that in your XML right?
If you mean you have several different ones, no that's not possible. Presumably they have different structures, so can't be one DataFrame. You could read and union them I suppose, but would require also manipulating the schema.
