### ISSUE TITLE
Standardise Writer Formats

### ISSUE THREAD

**Issue by seddonm1** [databricks/spark-xml#485]
Hi,
When we did the work on https://github.com/databricks/spark-xml/pull/448 we should have also done the writing side to ensure the writer would conform with the spec.

We are currently (https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala#L79) relying on the default `java.sql.Timestamp` format (https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html#toString--) which does not define timezone properly.

I think it would be good to switch to a more deterministic format:

```scala
writer.writeCharacters(DateTimeFormatter.ISO_INSTANT.format(v.toInstant()))
```

**Comment by srowen** [comment]
Seems OK to me - certainly, if there is any standard representation of dates in XML (likely defined by XSD types) then we should follow that.

**Comment by seddonm1** [comment]
Ok. My reading of this https://www.w3.org/TR/xmlschema-2/#dateTime indicates that all dateTimes without a timezone are assumed to be UTC but currently the j`ava.sql.Timestamp` seems to output local time. I will raise a PR.
