### ISSUE TITLE
xs:choice element can't be null

### ISSUE THREAD

**Issue by trourance** [databricks/spark-xml#490]
When the schema is generated from a XSD using XSDToSchema, fields resulting from xs:element included in xs:choice have the `nullable` property set to `false`, unless attribute `MinOccurs == 0`.
IMO, this is a wrong assumption because the XML file will always have one element OR the other, and therefore one will be null.
Wouldn't it be more correct to set `nullable` as always `true` in those resulting fields ?

**Comment by srowen** [comment]
I think you're right - I'll take a look and can fix if so. I did 'fix' nullability to look at minOccurs recently, but may have added it in too many places.
