### ISSUE TITLE
ParseException: mismatched input ':' expecting {<EOF>

### ISSUE THREAD

**Issue by mzeidhassan** [databricks/spark-xml#500]
Hi Spark-xml team,

First, thanks for creating this.

I am working on an xml file, and here is the current schema:

```
root
 |-- _xml:lang: string (nullable = true)
 |-- seg: string (nullable = true)
```
and this is what I get when I df.show the dataframe:
+---------+--------------------+
|_xml:lang|                 seg|
+---------+--------------------+
|    EN-US|This is a standar...|
|    AR-EG|هذا أحد مكونات بر...|
|    EN-US|The installer wil...|
|    AR-EG|سيتم إنهاء المثبت...

When I run this code though:
`"df.filter('_xml:lang RLIKE "EN*"').select('seg').collect()"`

I get this error:

> ParseException                            Traceback (most recent call last)
> <ipython-input-458-eca2f29ecce3> in <module>
> ----> 1 df.filter('_xml:lang RLIKE "EN*"').select('seg').collect()
> 
> ~/.local/lib/python3.6/site-packages/pyspark/sql/dataframe.py in filter(self, condition)
>    1457         """
>    1458         if isinstance(condition, basestring):
> -> 1459             jdf = self._jdf.filter(condition)
>    1460         elif isinstance(condition, Column):
>    1461             jdf = self._jdf.filter(condition._jc)
> 
> ~/.local/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
>    1303         answer = self.gateway_client.send_command(command)
>    1304         return_value = get_return_value(
> -> 1305             answer, self.gateway_client, self.target_id, self.name)
>    1306 
>    1307         for temp_arg in temp_args:
> 
> ~/.local/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
>     132                 # Hide where the exception came from that shows a non-Pythonic
>     133                 # JVM exception message.
> --> 134                 raise_from(converted)
>     135             else:
>     136                 raise
> 
> ~/.local/lib/python3.6/site-packages/pyspark/sql/utils.py in raise_from(e)
> 
> ParseException: 
> mismatched input ':' expecting {<EOF>, '(', '.', '[', 'ADD', 'AFTER', 'ALL', 'ALTER', 'ANALYZE', 'AND', 'ANTI', 'ANY', 'ARCHIVE', 'ARRAY', 'AS', 'ASC', 'AT', 'AUTHORIZATION', 'BETWEEN', 'BOTH', 'BUCKET', 'BUCKETS', 'BY', 'CACHE', 'CASCADE', 'CASE', 'CAST', 'CHANGE', 'CHECK', 'CLEAR', 'CLUSTER', 'CLUSTERED', 'CODEGEN', 'COLLATE', 'COLLECTION', 'COLUMN', 'COLUMNS', 'COMMENT', 'COMMIT', 'COMPACT', 'COMPACTIONS', 'COMPUTE', 'CONCATENATE', 'CONSTRAINT', 'COST', 'CREATE', 'CROSS', 'CUBE', 'CURRENT', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'CURRENT_USER', 'DATA', 'DATABASE', DATABASES, 'DAY', 'DBPROPERTIES', 'DEFINED', 'DELETE', 'DELIMITED', 'DESC', 'DESCRIBE', 'DFS', 'DIRECTORIES', 'DIRECTORY', 'DISTINCT', 'DISTRIBUTE', 'DIV', 'DROP', 'ELSE', 'END', 'ESCAPE', 'ESCAPED', 'EXCEPT', 'EXCHANGE', 'EXISTS', 'EXPLAIN', 'EXPORT', 'EXTENDED', 'EXTERNAL', 'EXTRACT', 'FALSE', 'FETCH', 'FIELDS', 'FILTER', 'FILEFORMAT', 'FIRST', 'FOLLOWING', 'FOR', 'FOREIGN', 'FORMAT', 'FORMATTED', 'FROM', 'FULL', 'FUNCTION', 'FUNCTIONS', 'GLOBAL', 'GRANT', 'GROUP', 'GROUPING', 'HAVING', 'HOUR', 'IF', 'IGNORE', 'IMPORT', 'IN', 'INDEX', 'INDEXES', 'INNER', 'INPATH', 'INPUTFORMAT', 'INSERT', 'INTERSECT', 'INTERVAL', 'INTO', 'IS', 'ITEMS', 'JOIN', 'KEYS', 'LAST', 'LATERAL', 'LAZY', 'LEADING', 'LEFT', 'LIKE', 'LIMIT', 'LINES', 'LIST', 'LOAD', 'LOCAL', 'LOCATION', 'LOCK', 'LOCKS', 'LOGICAL', 'MACRO', 'MAP', 'MATCHED', 'MERGE', 'MINUTE', 'MONTH', 'MSCK', 'NAMESPACE', 'NAMESPACES', 'NATURAL', 'NO', NOT, 'NULL', 'NULLS', 'OF', 'ON', 'ONLY', 'OPTION', 'OPTIONS', 'OR', 'ORDER', 'OUT', 'OUTER', 'OUTPUTFORMAT', 'OVER', 'OVERLAPS', 'OVERLAY', 'OVERWRITE', 'PARTITION', 'PARTITIONED', 'PARTITIONS', 'PERCENT', 'PIVOT', 'PLACING', 'POSITION', 'PRECEDING', 'PRIMARY', 'PRINCIPALS', 'PROPERTIES', 'PURGE', 'QUERY', 'RANGE', 'RECORDREADER', 'RECORDWRITER', 'RECOVER', 'REDUCE', 'REFERENCES', 'REFRESH', 'RENAME', 'REPAIR', 'REPLACE', 'RESET', 'RESTRICT', 'REVOKE', 'RIGHT', RLIKE, 'ROLE', 'ROLES', 'ROLLBACK', 'ROLLUP', 'ROW', 'ROWS', 'SCHEMA', 'SECOND', 'SELECT', 'SEMI', 'SEPARATED', 'SERDE', 'SERDEPROPERTIES', 'SESSION_USER', 'SET', 'MINUS', 'SETS', 'SHOW', 'SKEWED', 'SOME', 'SORT', 'SORTED', 'START', 'STATISTICS', 'STORED', 'STRATIFY', 'STRUCT', 'SUBSTR', 'SUBSTRING', 'TABLE', 'TABLES', 'TABLESAMPLE', 'TBLPROPERTIES', TEMPORARY, 'TERMINATED', 'THEN', 'TO', 'TOUCH', 'TRAILING', 'TRANSACTION', 'TRANSACTIONS', 'TRANSFORM', 'TRIM', 'TRUE', 'TRUNCATE', 'TYPE', 'UNARCHIVE', 'UNBOUNDED', 'UNCACHE', 'UNION', 'UNIQUE', 'UNKNOWN', 'UNLOCK', 'UNSET', 'UPDATE', 'USE', 'USER', 'USING', 'VALUES', 'VIEW', 'VIEWS', 'WHEN', 'WHERE', 'WINDOW', 'WITH', 'YEAR', EQ, '<=>', '<>', '!=', '<', LTE, '>', GTE, '+', '-', '*', '/', '%', '&', '|', '||', '^', IDENTIFIER, BACKQUOTED_IDENTIFIER}(line 1, pos 4)
> 
> == SQL ==
> _xml:lang RLIKE "EN*"
> ----^^^

Any idea how to resolve this issue?
Thanks

**Comment by srowen** [comment]
Try putting the column name in back-tick quotes (not single or double quotes). I believe a colon is a reserved character in the SQL parser

**Comment by mzeidhassan** [comment]
Thank you so much @srowen 
This one seems to be working fine now. 

df.filter('`_xml:lang` RLIKE "EN"').select('seg').collect()

I appreciate your help.
