### ISSUE TITLE
Read RootTag Attributes, saving from using explode

### ISSUE THREAD

**Issue by hgarg1010** [databricks/spark-xml#503]
Please add this functionality in this library where RootTag Attributes can be read while parsing data of the row tag inside that root tag, this will prevent the use of expensive explode transformation causing straggling task in case of unevenly distributed data.

**Comment by srowen** [comment]
I'm not sure what you mean, can you provide an example? the root tag is not used during reading.

**Comment by hgarg1010** [comment]
Thanks for your fast reply.

I mean that when we read rowTag, its attributes are read, but I want the library to read rootTag's attribute as well and make a column having that same value of rootTag's attributes against all the rows.


For eg:

<library LIB_ID="101" LIB_Name="ABC">
    <book ID="1"/>
    <book ID="2"/>
</library>


df = spark.read.format('xml').option('rowTag','book').option('rootTag','library').option('inferSchema',True).load(path_of_file)

df.show()

Required DataFrame is:

_ID _LIB_ID _LIB_Name
1      101       ABC
2      101      ABC


Currently it won't read the rootTag attributes if I take book as rowTag, to accommodate the information I referred in required DataFrame I need to read the library as rowTag and then I have to explode the DataFrame column to generate the desired DataFrame.

Please provide this feature if possible.

**Comment by hgarg1010** [comment]
<library LIB_ID="101" LIB_Name="ABC">
   <book ID="1">
   <book ID="2">
</library>

**Comment by srowen** [comment]
rootTag has no effect on reading. It only affects how XML is written. The library by design only ever cares about rowTags. After all, where would you expect that single rootTag's attributes to go - which row?

Do you mean you just want rowTag = library? that would get the attributes, and books as an array.

**Comment by hgarg1010** [comment]
Yes, if I keep rowTag = library then book will be read as an Array, then I require the DataFrame to be broken at book level (meaning one book id should be on on row of DF), so for that I need to use the explode function, but as the data I am dealing with is unevenly distributed causing my task to keep on running state, for that I want the library to read the rootTag's attributes.



So when I keep rowTag = book and rootTag = library, then currently i will read only book's ID, but I require Library ID and nam e too, for that I need to put rowTag = Library,

then df will have

LIB_IB LIB_Name Column
101      ABC           [1,2]


so I have to then explode the above df to get


_ID _LIB_ID _LIB_Name
1 101 ABC
2 101 ABC


and explode is very expensive, causing some partitions to deal with lots of data (because of uneven distribution - nature of data), that's why I require this feature.

This will solve many people problems saving lots of time.

**Comment by srowen** [comment]
Again: rootTag is irrelevant here.
It doesn't make sense to make books as rows, but then need some values that are not part of any row.
You are doing it correctly: your rows are library elements. You have to explode if that's what you want to do.

**Comment by hgarg1010** [comment]
Yep, but I want to achieve that without using the explode function, that the whole point of this issue/requirement,

If I make rowTag ='book' and rootTag='library' and if a new feature which can read rootTag's attribute data then we don't require explode.

**Comment by srowen** [comment]
You can't - it does not make sense semantically. Please read my replies above again as to why.
