### ISSUE TITLE
RowTag and feed specification

### ISSUE THREAD

**Issue by MartinTrubelik** [databricks/spark-xml#509]
Is it possible to detect w3 feed specification via spark-xml or spark?

I want to use rowTag `item` when using `RSS` type and `entry` when using `Atom`.

https://validator.w3.org/feed/docs/

**Comment by srowen** [comment]
Is the feed XML? sure you can parse it then. You'd have to parse different XML files differently, so you may need to read the RSS and Atom feeds separately if they are different types of XML. After transforming them into a common representation, you can union the DataFrames. Is that all you're after?

**Comment by MartinTrubelik** [comment]
Thank you for fast response. I'm working on a product application and I'd like to import products from an XML feed to a database. Merchants are using RSS or Atom specification. Perhaps I can create an document with XML first, check (somehow) root tag or xmlns attribute and then create the dataframe when I know which rowTag I should use. 

So, I don't want to union the dataFrames, because those XML files are parsed separately.

**Comment by srowen** [comment]
OK, you wouldn't know ahead of time? then sure.
You can process them separately sure, if you like.
