### ISSUE TITLE
When reading a XML file i am not getting all the rows and some columns show incorrect values.

### ISSUE THREAD

**Issue by KevSpally-collab** [databricks/spark-xml#525]
I am trying to read a xml file 3.9 GB. The file can be found [here](https://www.gleif.org/en/lei-data/gleif-concatenated-file/download-the-concatenated-file). 

So when i am reading the xml:
`df = spark.read.format('xml').options("rowTag", "lei:LEIRecord").load("20210223-gleif-concatenated-file-lei2.xml")`

It seems to work within acceptables run times. But when i validate the data in Databricks i see that the column "lei:EntityLegalFormCode" is showing incorrect values. 

For example the LEI record with ID: 029200013A5N6ZD0F605
Shows the value "8888" for the column "lei:EntityLegalFormCode", but if i check the https://api.gleif.org/api/v1/lei-records/:id API the value should be "9999".

There also should be 1,813,360 rows but when i do a:
`df.count()`

I see 1221475 rows.

So it seems the data is incomplete and incorrect.

I dont receive any errors or warning, so i am a little lost on how to solve this.

The steps are easy to reproduce, i shared all the information to reproduce.
Any help on this is appreciated.

**Comment by KevSpally-collab** [comment]
solved this issue

**Comment by srowen** [comment]
Interesting, what was the issue? I might guess there is a corrupted XML file somewhere or something

**Comment by KevSpally-collab** [comment]
well issue was on my side, in my azure data factory pipeline i was extracting old data from 2018(was using old value in my parameters) and comparing that with data from 2021.
