### ISSUE TITLE
Allow ignoring namespaces when detecting rows

### ISSUE THREAD

**Issue by m-orchard** [databricks/spark-xml#529]
Hi,

I believe this is a follow-on from https://github.com/databricks/spark-xml/issues/168.

As I understand, by using `ignoreNamespace` it's possible to have namespace prefixes removed from parsed column names, but it's [not yet possible to match row tags irrespective of their prefix(es)](https://github.com/databricks/spark-xml/issues/168#issuecomment-739425677).

In our use case, we have a large number of XML files that follow the same schema, but we don't know if they use the same prefix for that schema in every file, nor do we necessarily have a fixed set of prefixes that we expect. The files themselves can be quite large, and so we'd like to avoid any kind of preprocessing to remove or align the prefixes.

Ideally, we'd like to be able to use the `ignoreNamespace` option, or a similar option, to allow us to parse rows from all files in question for the same `rowTag`, no matter what prefix  is used local to each file.

It was mentioned on the previous issue that is may not be trivial - it looks like the way rows are matched currently is [character by character](https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/XmlInputFormat.scala#L203), and so I suspect it might be necessary to keep reference to the current start tag being checked until the end of the tag name or the end of its prefix, before beginning to decide if it matches the specified row tag. (I'm keen to find out if my understanding is correct here!)

Thanks,

Michael

**Comment by srowen** [comment]
That's right, it's a valid feature but just tricky to implement in the current code, so I hadn't bothered before. Yes I think you have to save each start tag you read in full and then decide at the end whether it matches. Not that hard just takes some care to get right.

**Comment by m-orchard** [comment]
Got it, thanks for the response! Hopefully we can find some time to help out with this.

**Comment by srowen** [comment]
I looked into this. On the one hand, it's not too hard to look ahead in the stream with a BufferedReader and correctly ignore the namespace. On the other hand, the trick here is that this low-level logic is quite sensitive to respecting where partition splits end (which may not be the end of the file) and so you can see there's some tricky logic to know exactly how much of the file has been consumed. Buffering complicates this a lot, and there's already some logic to subtract out what the InputStreamReader may have read but not consumed. I suppose we can do the same with some hacks for the BufferedReader too, but it's getting messy! I'm trying to think of other ways to do it - read ahead without knowing whether you're looking at a namespace or not

**Comment by m-orchard** [comment]
I see - I did see some discussion about the file split and mention of it in code, but I didn't quite wrap my head around how it was being handled. I'll try to get a better understanding and have a think too.

**Comment by molok** [comment]
@srowen this issue was marked as completed, so is `ignoreNamespace` supposed to work for `rowTag` too?

**Comment by srowen** [comment]
I've forgotten, but I don't think so. I probably just closed it. You're welcome to test it!

**Comment by molok** [comment]
I'm asking because it doesn't seem to work. It's an annoying issue because we are pretty much forced to preprocess all the XML files to strip the namespaces. IMHO it would be useful to keep the issue open.
