### ISSUE TITLE
How to parse XML with XSD using spark-xml package?

### ISSUE THREAD

**Issue by ungalVicky** [databricks/spark-xml#530]
Hi Team,
I am trying to parse simple XML by supplying XSD schema.  Using the approach given here.

https://github.com/databricks/spark-xml#xsd-support

### XML is here:
```
<?xml version="1.0"?>  
<beginnersbook>
 <to>My Readers</to>
 <from>Chaitanya</from>
 <subject>A Message to my readers</subject>
 <message>Welcome to beginnersbook.com</message>
</beginnersbook>

```

### XSD is here:
```
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.beginnersbook.com"
xmlns="https://www.beginnersbook.com"
elementFormDefault="qualified">

<xs:element name="beginnersbook">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="to" type="xs:string"/>
      <xs:element name="from" type="xs:string"/>
      <xs:element name="subject" type="xs:string"/>
      <xs:element name="message" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

```

I am trying to read this XSD and trying to build schema like below.

`import com.databricks.spark.xml.util.XSDToSchema`
`import java.nio.file.Paths`
`val schemaParsed = XSDToSchema.read(Paths.get("<local_linux_path>/sample_file.xsd"))`
`print(schema)`

Here  schema successfully parsed.
Next I am reading XML file like below.

`val df = spark.read.format("com.databricks.spark.xml").schema(schemaParsed).load("<hdfs_path>/sample_file.xml")`

After this step I can display schema of Dataframe using df.printSchema() , But content is coming as empty if I am giving df.show()

Please guide me where I am doing wrong here.
Actual XML and XSD attached for your reference as well.

Thanks in advance.
[sample_file.zip](https://github.com/databricks/spark-xml/files/6383922/sample_file.zip)

**Comment by srowen** [comment]
You are not specifying a rowTag as "beginnersbook". That's almost certainly it.
You probably do not need the XSD for the schema in this case. It will infer something simple like this.

**Comment by ungalVicky** [comment]
I have mentioned rowTag as "beginnersbook" but job failed with null pointer exception...

Can you please provide one simple workign example with this approach??
It will be really helpful for me..

**Comment by srowen** [comment]
That isn't shown above - you're sure? how are you actually calling it and what is the error in full?

**Comment by ungalVicky** [comment]
@srowen Yes.. Even i tried giving with rootTag and rowTag with schema generated using "com.databricks.spark.xml.util.XSDToSchema".

In both the cases df.show() is failing with nullpointerexception.

Please find the how i am calling it and error in the attached PDF.
[Error.pdf.pdf](https://github.com/databricks/spark-xml/files/6386680/Error.pdf.pdf)

Just check from your side whether are you able to read a simple XML using the schema generated using XSDToSchema.

Thanks.

**Comment by srowen** [comment]
rootTag is only relevant for writing.

The problem is that the schema in your XSD says your rowTags have a single nested element called "beginnersbook", but, actually that _is_ your rowTag. You could change the XSD to express that (not sure how), or just access the nested schema for this element and pass that as your schema:

`.schema(schema("beginnersbook").dataType.asInstanceOf[StructType])`

But you don't need an XSD here. It will correctly infer the schema of your example directly.

**Comment by NonStopProgrammer** [comment]
@srowen thanks. It worked.
