### ISSUE TITLE
spark.databricks.queryWatchdog.maxQueryTasks exceeded

### ISSUE THREAD

**Issue by skanthb** [databricks/spark-xml#531]
Hi,

I have a requirement to read thousands of small xml files from azure adls. Currently we have 1,041,620 files and when tried to read them using below script, it fails.  

xml_header_tag_df = spark.read \
          .format("xml") \
          .option("rowTag","tag_hdr") \
          .option("inferSchema", "false") \
          .option("rowValidationXSDPath",xsd_file_name) \
          .load(input_files_path + "*.xml")

Error:

org.apache.spark.SparkException: The query is not executed because it tries to launch 1041620 tasks in a single stage, while the maximum allowed tasks one query can launch is 100000; this limit can be modified with configuration parameter &#34;spark.databricks.queryWatchdog.maxQueryTasks&#34;.

How can we resolve this? Is it advisable to increase maxQueryTasks value?

Thanks,
Sri

**Comment by srowen** [comment]
Yikes, that's a lot of files! In an extreme case like this, it may be better to ask Spark to read the contents of the files as individual rows with `wholeTextFiles`. That gives a Dataset of Strings. You can read this at a lower level with the `XmlReader` class. However that kind of requires that every file's contents is a single row, and nothing more. Is that true of your data? then it's an efficient solution. Otherwise... yeah this is hard. You'd have to try concatenating the files first.

**Comment by skanthb** [comment]
What I tried was to disable the query watchdog and ran the above command and it took  21.76 minutes. 

spark.conf.set("spark.databricks.queryWatchdog.enabled", "false")

https://docs.databricks.com/spark/latest/spark-sql/query-watchdog.html#when-should-you-disable-query-watchdog

As per the above article it recommends to disable if it's part of ETL workload. But this ran 1,041,620 tasks :D. Any suggestions? I'm guessing looping through the files will run for even more time.

Env ran in:
Databricks runtime ver: 7.3 LTS
worker: Standard_E8_v3 (64gb mem, 8 cores, 2DBU) (min 1, max 10)
driver type: Standard_E8_v3 (64gb mem, 8 cores, 2DBU)

Details for Stage 13550 (Attempt 0)
Total Time Across All Tasks: 8.2 h
Locality Level Summary: Process local: 1041620
Input Size / Records: 2.9 GiB / 1041520
Associated Job Ids: 7977 

![xml job](https://user-images.githubusercontent.com/17520646/116628393-05b7a800-a91d-11eb-8af7-a1c85dd1736c.PNG)

**Comment by srowen** [comment]
A million tasks is pretty extreme. It may work, but not ideal. See the comment above.

The only other thing I can think of is to tell the Hadoop InputFormat to try to put many files into one partition. You could try setting `mapred.min.split.size` (via `spark.hadoop.mapred.min.split.size`) to some large value, the size of 100s of your small files, and see if that induces it to put many files into a partition.

**Comment by skanthb** [comment]
Thanks a lot, @srowen for your responses.

I tried setting the below configuration at the notebook level and ran the command again. However, it did not reduce the tasks.

spark.conf.set("mapred.min.split.size", "256000000"); 
spark.conf.set("mapred.max.split.size", "256000000");

Did i miss anything ? 

Thanks again for introducing this setting to me. After you mentioned it, i did see a similar article on Databricks knowledge base (which is trying to do the opposite of what i want).

https://kb.databricks.com/execution/increase-tasks-per-stage.html

![xml jobc2](https://user-images.githubusercontent.com/17520646/116635147-fe4bcb00-a92b-11eb-9148-b5f7d4bd3340.PNG)
![xml job 3](https://user-images.githubusercontent.com/17520646/116635148-fee46180-a92b-11eb-9259-4770f575e095.PNG)


Best,
Sri

**Comment by srowen** [comment]
As I say, in Spark it's probably `spark.hadoop.mapred.min.split.size`. You do not want to set a max split size in any event.
