### ISSUE TITLE
weird behaviour when there is a ">" at the end of RowTag

### ISSUE THREAD

**Issue by kduvekot-wehkamp-nl** [databricks/spark-xml#532]
By accident I had pasted the Row element name in my configuration with the trailing ">"
```python
    df = (spark.read.format('xml')
         .options(rowTag='RowElement>')
         .load(file_location)
     )
```
It resulted in a valid dataframe with a schema that was expected from the data.
however when I displayed the resulting dataframe it only had 7 rows instead of the 408238 rows I was expecting
the rows were roughtly 58k apart .. so must be some "long line parsing" artifact.

so maybe its good to "sanitize" or "validate" the rowTag option to not include any XML restricted chars

**Comment by srowen** [comment]
Yeah it can't have the angle bracket. If it does it will probably read the closing bracket as part of the tag, then keep searching for the next angle bracket to close it, which would mean it skips some random data. Maybe I should have it throw an error in this case

**Comment by kduvekot-wehkamp-nl** [comment]
Cool .. thanks for the quick solution 👍
