### ISSUE TITLE
possibility to extract data from the "header" part of the xml when using the rowTag option

### ISSUE THREAD

**Issue by kduvekot-wehkamp-nl** [databricks/spark-xml#533]
I have a fairly large XML document that contains over 400k "rows" .. but also some "header" data in the XML part before the rows start. This data is interesting to have in the resulting dataframe but you can't get to that data currently

would it be possible to have an way of adding data from the "header" part as "static" row values?

otherwise I need to parse the XML document twice and join the resulting dataframes.

**Comment by srowen** [comment]
No, it won't read anything outside the row tag. It wouldn't be conceptually tied to a row.

You could possibly read it separately and figure out which rows it applies to.

You could try reading the entire doc, where your 'rows' would become an array inside each row, and the header would be another struct. But that could result in huge amounts of data being read.

You could imagine reading the each whole XML doc as a string column, chopping out the row data from the header manually, then applying this library twice to parse them separately. It might work; I haven't thought through whether that's any more efficient than just reading the whole doc as a 'row'.
