### ISSUE TITLE
how to use "standard Hadoop globbing expressions"

### ISSUE THREAD

**Issue by kduvekot-wehkamp-nl** [databricks/spark-xml#535]
I have problems using the "standard globbing" when using this spark datasource

I have taken the example books.xml file and stored in the following structure:
```
    /path/to/data/for/spark-xml/
    /path/to/data/for/spark-xml/year=2021
    /path/to/data/for/spark-xml/year=2021/month=04
    /path/to/data/for/spark-xml/year=2021/month=04/day=29
    /path/to/data/for/spark-xml/year=2021/month=04/day=29/books.xml
    /path/to/data/for/spark-xml/year=2021/month=04/day=30
    /path/to/data/for/spark-xml/year=2021/month=04/day=30/books.xml
    /path/to/data/for/spark-xml/year=2021/month=05
    /path/to/data/for/spark-xml/year=2021/month=05/day=01
    /path/to/data/for/spark-xml/year=2021/month=05/day=01/books.xml
    /path/to/data/for/spark-xml/year=2021/month=05/day=02
    /path/to/data/for/spark-xml/year=2021/month=05/day=02/books.xml
```

I try to read this data on databricks (DBR 8.2) using the following code:

```python
from pyspark.sql.types import *

customSchema = StructType([
    StructField("_id", StringType(), True),
    StructField("author", StringType(), True),
    StructField("description", StringType(), True),
    StructField("genre", StringType(), True),
    StructField("price", DoubleType(), True),
    StructField("publish_date", StringType(), True),
    StructField("title", StringType(), True)])

df = (spark.read
       .format('xml')
       .option('rowTag', 'book')
       .option('path', '/path/to/data/for/spark-xml/')
       .schema(customSchema)
       .load(pathGlobFilter="*.xml")
     )
```
that is giving an OK (probably due to "lazy loading")

but when I want to display the data I get :

`FileNotFoundException: Can't open /databricks-shard-id/0/path/to/data/for/spark-xml/year=2021 because it is a directory`

I tried to "fix" that by adding that `pathGlobFilter` in the load() but that did not help.

Any pointers on how to read XML files stored in such a structure?

The end goal is to periodically run a streaming job (with .trigger(once=True) ) on this location to process any new xml files that are stored there into a raw/bronze data table for further processing/parsing/enrichment etc

**Comment by srowen** [comment]
It uses a standard HadoopInputFormat under the hood, so I think globs work, but the syntax is more like `foo/**/**/*.xml` I believe. Does that work?

**Comment by kduvekot-wehkamp-nl** [comment]
that does give results .. but it doesn't include the partition columns `year`, `month` and `day` in the resulting dataframe.

**Comment by srowen** [comment]
Oh I see. Hm, I'm not sure if that will work, as the input format treats this as fundamentally just text. I'm not sure if it will process this as a "PARTITIONED BY" 'column' in the way that other input formats could. Like in https://spark.apache.org/docs/latest/sql-data-sources-parquet.html try setting `basePath` as an `.option`? that would be set to the root of the partitioned data

**Comment by kduvekot-wehkamp-nl** [comment]
same error as before
```python
    df = (spark.read
           .format('xml')
           .option('rowTag', 'book')
           .option('path', '/path/to/data/for/spark-xml/')
           .option('basePath', '/path/to/data/for/spark-xml/')
           .schema(customSchema)
           .load()
         )
```

**Comment by srowen** [comment]
I think your path still has to be the glob expression

**Comment by kduvekot-wehkamp-nl** [comment]
no difference ... still no partition columns

**Comment by kduvekot-wehkamp-nl** [comment]
mmm also "readStream" is not supported apparently .. so that is an other stopper ...

**Comment by srowen** [comment]
Yeah, I didn't think it would work. You could manage to manually list the dir, parse their partition info, read the subdirs individually, and add the partition columns, then union. Messy and doesn't scale super well but would work.

Yes streaming doesn't work directly because it doesn't implement DSv2. However you can stream sources as text and then parse the text as XML with this library. It's not much harder but more steps.

**Comment by kduvekot-wehkamp-nl** [comment]
Any pointers for that? I was looking to see how I can get a full file into a dataframe column with the filename ... But most things I try failed (trying to use wholeTextFile .. and fileStream )

**Comment by srowen** [comment]
wholeTextFiles gives you the file name and the contents as text. You can then use the methods here to parse that column of text as XML. The only catch is that it will assume that each whole XML file is one row, rather than any subset of it.

**Comment by JCZuurmond** [comment]
Hi @srowen, I am also looking to read partitions like other file formats do. Seeing the discussion, this is not possible ATM. or, is there a work around found? If not, is this not possible at all or just a feature to implement?

**Comment by srowen** [comment]
I'm not sure of any workaround. It may depend on extending DSv2
