### ISSUE TITLE
Tags are misaligned while writing as xml using pyspark dataframes

### ISSUE THREAD

**Issue by suganya301** [databricks/spark-xml#537]
Tags are misaligned while writing as xml using pyspark dataframes.

options = {"rootTag": "document","rowTag": "book"}
xml_jar_format = "com.databricks.spark.xml"
hdfs_path = "hdfs_path"
save_mode = "overwrite"
dataframe.coalesce(1).write.mode(save_mode).options(**xml_options).save(hdfs_path,format=xml_format)

![image](https://user-images.githubusercontent.com/39955399/118430733-0ec7b800-b718-11eb-81fc-b35b554c90e8.png)
![image](https://user-images.githubusercontent.com/39955399/118430761-2141f180-b718-11eb-871c-c5f6dc651b6f.png)

**Comment by srowen** [comment]
What version are you using? that sort of looks like a problem that was fixed a while ago.
I'm looking at the output of some test cases and they don't have that problem.

**Comment by suganya301** [comment]
I’m using 0.6.0. Later i tried 0.12.0, seems misalignment is fixed, but Nested columns are getting created as one single column in unix.but windows side looks fine. For example:  Tag  -  country.state.city is  getting created as <country_state_city>aa</country_state_city> instead of 
<country><state<city>aa</city></state</country>

**Comment by srowen** [comment]
OK, right. Use the latest.
I'm not sure what you mean about nested columns. Could you open a separate issue with more detail?
