### ISSUE TITLE
Add option to read xml as flat data.

### ISSUE THREAD

**Issue by aestela-brighthealthplan** [databricks/spark-xml#538]
Hello! This is a feature request.

It would be amazing if there was an option to flatten nested data like what is shown here https://www.linkedin.com/pulse/flattening-nested-data-jsonxml-using-apache-spark-saikrishna-pujari/?articleId=6680102264994066432. It's a shame losing the names when nested structures are stored in an array. For our use case, keeping the naming is much more convenient. 

.option("flatData", true)

**Comment by srowen** [comment]
From this, I don't understand the semantics. You can always `explode` an array column. What are you looking for?

**Comment by aestela-brighthealthplan** [comment]
That link I shared is doing a little more than exploding, but flattening the nested data so that the entire structure from a given root (or rowTag) becomes one row. This seems like a nice feature to include as an option for this library. Just for your consideration :)

**Comment by srowen** [comment]
Why would you not just do this with DataFrame operations downstream? Seems quite orthogonal to parsing the XML

**Comment by aestela-brighthealthplan** [comment]
My thinking was that flattening structured data might be such a common use case that it's basically a necessary step after, strictly speaking, parsing XML. And flattening nicely (beyond simply exploding) is just non-trivial enough it would be nice to standardize/consolidate. If you haven't gotten that feedback before and I'm wrong in thinking it's a main use case, then consider me the odd one out!

**Comment by srowen** [comment]
OK, I think that any subsequent flattening is use-case-specific, and is already accommodated by existing Spark APIs to further transform the data. I don't think there is one common semantic for flattening (which columns?) that makes sense to expose.
