### ISSUE TITLE
object xml is not a member of package com.databricks.spark

### ISSUE THREAD

**Issue by stikoson** [databricks/spark-xml#546]
Hi,

the problem described in [https://github.com/databricks/spark-xml/issues/391]
still exists when using a Databricks notebook. 

HyukjinKwon:spark-xml:0.1.1-s_2.11 is installed to the cluster still spark-xml
is not getting imported.

Please note there is no option to select the Scala 2.12 version when installing the package through Databricks Workspace.

**Comment by srowen** [comment]
That is an extremely old version. You want to just install from maven now, not spark-packages. 0.12.0 is the latest, and exists for 2.12 https://search.maven.org/artifact/com.databricks/spark-xml_2.12/0.12.0/jar
