### ISSUE TITLE
databricks 8.3 incompatibility

### ISSUE THREAD

**Issue by grusin** [databricks/spark-xml#549]
i've just noticed that spark-xml (com.databricks:spark-xml_2.12:0.12.0) stopped working on databricks 8.3. it works without a problem up to and including 8.2

the error I am getting while trying to open XML file is this:

java.lang.AbstractMethodError: Method com/databricks/spark/xml/XmlDataToCatalyst.child()Lorg/apache/spark/sql/catalyst/trees/TreeNode; is abstract

I am aware that this might be databricks bug, not this project's bug, hence if someone could help me triage this it would be awesome.

code snippet (databricks notebook code) reproducing issue is attached

[xml parsing error.zip](https://github.com/databricks/spark-xml/files/6770452/xml.parsing.error.zip)

**Comment by srowen** [comment]
Hm. I see that oo. This piece of code does hook into catalyst, which is internal, so, possible that there is some variance between OSS and modifications in Databricks Spark. However I looked at the immediate source code in Databricks and don't see differences from OSS, so not sure what's going on.

Do you have access to Databricks support to file a ticket? If not I can. It may be that the library has to change somehow but I'm not sure.

**Comment by grusin** [comment]
I probably have access to dbr support ticket system, but I dont know how to use it :P if you could help in that regard it would be great.

**Comment by srowen** [comment]
Word from inside is that this is indeed an inadvertent binary compatibility problem in 8.3. It will be fixed soon - not sure if it's 8.4 but seems like it's already in the release pipe. I'll close this as not directly related to spark-xml itself.
