### ISSUE TITLE
Surface XSD errors to dataframe

### ISSUE THREAD

**Issue by renepajta** [databricks/spark-xml#551]
With spark-xml library and with PERMISSIVE option, we are able to perform record-by-record validation quickly. It filters entire record as Invalid record and store in _corrupted_record column by default. 

In addition to this, is it possible to get also XSD error as additional column?

**Comment by srowen** [comment]
Hm, I don't really want to complicate the API a lot more for this. Maybe, but how about just revalidating the content with the XSD?

**Comment by renepajta** [comment]
@srowen the thing is, then I need to loop through every single record and evaluate with other XSD package either in Python or Scala. 

Is it too much effort to surface XSD errors as additional option in XML reader?

**Comment by srowen** [comment]
It's not that hard but I'm thinking of consistency - maybe then it becomes surprising that the parse error isn't exposed for different non XSD failures, which is more common. Other data sources don't do this. It's a few lines of code to validate too

**Comment by renepajta** [comment]
I understand. Then let's keep it consistent and we will run extra code to get parser errors.
