### ISSUE TITLE
Facing Ambiguous reference exception for duplicate tags in xml

### ISSUE THREAD

**Issue by mksuren** [databricks/spark-xml#552]
Hi

I am working on an XML flattening task and using the "0.12.0" databricks spark-xml library.
Code is failing for duplicate XML tags (eComStringAttributeValuePairList) with the attribute (attributeName) eg
	<supplierDataNotification>
			<avpList>
				<eComStringAttributeValuePairList attributeName="supStatus">A</eComStringAttributeValuePairList>
				<ecomStringAttributeValuePairList attributeName="shipMethod">SM</ecomStringAttributeValuePairList>
			</avpList>
	</supplierDataNotification>

Exception 
Exception message:Ambiguous reference to fields StructField(eComStringAttributeValuePairList,StructType(StructField(VLU,StringType,true), StructField(_attributeName,StringType,true)),true), StructField(ecomStringAttributeValuePairList,StructType(StructField(VLU,StringType,true), StructField(_attributeName,StringType,true)),true); line 1 pos 0
org.apache.spark.sql.AnalysisException: Ambiguous reference to fields StructField(eComStringAttributeValuePairList,StructType(StructField(VLU,StringType,true), StructField(_attributeName,StringType,true)),true), StructField(ecomStringAttributeValuePairList,StructType(StructField(VLU,StringType,true), StructField(_attributeName,StringType,true)),true); line 1 pos 0
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.findField(complexTypeExtractors.scala:88)
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:53)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq$$anonfun$7.apply(package.scala:244)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq$$anonfun$7.apply(package.scala:243)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)

Please provide the solution/suggestion for it

Thanks
Surender

**Comment by mksuren** [comment]
Sample XML
	<supplierDataNotification>
			<avpList>
				<eComStringAttributeValuePairList attributeName="supStatus">A</eComStringAttributeValuePairList>
				<ecomStringAttributeValuePairList attributeName="shipMethod">SM</ecomStringAttributeValuePairList>
			</avpList>
	</supplierDataNotification>

**Comment by mksuren** [comment]
<avpList>
   <eComStringAttributeValuePairList   attributeName=”shipMethod”>SM</eComStringAttributeValuePairList>
  <eComStringAttributeValuePairList   attributeName=”paymentMethod”>WT</eComStringAttributeValuePairList>
  <eComStringAttributeValuePairList   attributeName=”settlementCode”>N</eComStringAttributeValuePairList>
</avpList>

**Comment by mksuren** [comment]
<avpList>
   <eComStringAttributeValuePairList   attributeName=”shipMethod”>SM</eComStringAttributeValuePairList>
  <eComStringAttributeValuePairList   attributeName=”paymentMethod”>WT</eComStringAttributeValuePairList>
  <eComStringAttributeValuePairList   attributeName=”settlementCode”>N</eComStringAttributeValuePairList>
</avpList>

**Comment by mksuren** [comment]
`<avpList>
   <eComStringAttributeValuePairList   attributeName=”shipMethod”>SM</eComStringAttributeValuePairList>
  <eComStringAttributeValuePairList   attributeName=”paymentMethod”>WT</eComStringAttributeValuePairList>
  <eComStringAttributeValuePairList   attributeName=”settlementCode”>N</eComStringAttributeValuePairList>
</avpList>`

**Comment by srowen** [comment]
That should work as an array-valued element. What's your schema?

**Comment by mksuren** [comment]
`********************Sample XML *********************
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<supplierDataNotificationMessage >
	<supplierDataNotification>
		<creationDateTime>2008-11-15T22:22:58</creationDateTime>
		<documentStatusCode>ORIGINAL</documentStatusCode>
		<documentActionCode>ADD</documentActionCode>
		<lastUpdateDateTime>2002-11-05T13:31:03+05:30</lastUpdateDateTime>
		<revisionNumber>201</revisionNumber>
		<documentEffectiveDate>
			<date>2002-06-24+05:30</date>
			<time>20:26:29+05:30</time>
		</documentEffectiveDate>
		<avpList>
			<eComStringAttributeValuePairList attributeName="family">LEAD</eComStringAttributeValuePairList>
		</avpList>
		<supplierDataNotificationIdentification>
			<entityIdentification>supplier</entityIdentification>
		</supplierDataNotificationIdentification>
		<supplier>
			<avpList>
				<eComStringAttributeValuePairList attributeName="supStatus">A</eComStringAttributeValuePairList>
				<ecomStringAttributeValuePairList attributeName="shipMethod">SM</ecomStringAttributeValuePairList>
				<ecomStringAttributeValuePairList attributeName="paymentMethod">WT</ecomStringAttributeValuePairList>
			</avpList>
		</supplier>
	</supplierDataNotification>
</supplierDataNotificationMessage>

******************* XSD of above xml *************************
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="supplierDataNotificationMessage">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="supplierDataNotification">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:dateTime" name="creationDateTime"/>
              <xs:element type="xs:string" name="documentStatusCode"/>
              <xs:element type="xs:string" name="documentActionCode"/>
              <xs:element type="xs:dateTime" name="lastUpdateDateTime"/>
              <xs:element type="xs:short" name="revisionNumber"/>
              <xs:element name="documentEffectiveDate">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:date" name="date"/>
                    <xs:element type="xs:time" name="time"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="avpList">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="eComStringAttributeValuePairList">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="attributeName"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="supplierDataNotificationIdentification">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="entityIdentification"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="supplier">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="avpList">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="eComStringAttributeValuePairList">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="attributeName"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="ecomStringAttributeValuePairList" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="attributeName" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>`

**Comment by mksuren** [comment]
Hi Srowen,

Thanks for reply. Please find the attached sample XML, XSD and parsing code.
`
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<supplierDataNotificationMessage >
	<supplierDataNotification>
		<creationDateTime>2008-11-15T22:22:58</creationDateTime>
		<documentStatusCode>ORIGINAL</documentStatusCode>
		<documentActionCode>ADD</documentActionCode>
		<lastUpdateDateTime>2002-11-05T13:31:03+05:30</lastUpdateDateTime>
		<revisionNumber>201</revisionNumber>
		<documentEffectiveDate>
			<date>2002-06-24+05:30</date>
			<time>20:26:29+05:30</time>
		</documentEffectiveDate>
		<avpList>
			<eComStringAttributeValuePairList attributeName="family">LEAD</eComStringAttributeValuePairList>
		</avpList>
		<supplierDataNotificationIdentification>
			<entityIdentification>supplier</entityIdentification>
		</supplierDataNotificationIdentification>
		<supplier>
			<avpList>
				<eComStringAttributeValuePairList attributeName="supStatus">A</eComStringAttributeValuePairList>
				<ecomStringAttributeValuePairList attributeName="shipMethod">SM</ecomStringAttributeValuePairList>
				<ecomStringAttributeValuePairList attributeName="paymentMethod">WT</ecomStringAttributeValuePairList>
			</avpList>
		</supplier>
	</supplierDataNotification>
</supplierDataNotificationMessage>`

XSD of above XML 

`<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="supplierDataNotificationMessage">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="supplierDataNotification">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:dateTime" name="creationDateTime"/>
              <xs:element type="xs:string" name="documentStatusCode"/>
              <xs:element type="xs:string" name="documentActionCode"/>
              <xs:element type="xs:dateTime" name="lastUpdateDateTime"/>
              <xs:element type="xs:short" name="revisionNumber"/>
              <xs:element name="documentEffectiveDate">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:date" name="date"/>
                    <xs:element type="xs:time" name="time"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="avpList">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="eComStringAttributeValuePairList">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="attributeName"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="supplierDataNotificationIdentification">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="entityIdentification"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="supplier">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="avpList">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="eComStringAttributeValuePairList">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="attributeName"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="ecomStringAttributeValuePairList" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="attributeName" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>`

XML Flattening code

`   val fields = df.schema.fields
    val fieldNames = fields.map(x => x.name)
    val length = fields.length
	println("Start parsing XML")
    for(i <- 0 to fields.length-1){
      val field = fields(i)
      val fieldtype = field.dataType
      val fieldName = field.name
			val fieldMetadataInfo = field.metadata

			println("fieldName ----  "+fieldName)
			println("metadata ----  "+fieldMetadataInfo)

      fieldtype match {
        case arrayType: ArrayType =>
          val newfieldNames = fieldNames.filter(_!=fieldName) ++ Array("explode_outer(".concat(fieldName).concat(") as ").concat(fieldName))
          val explodedDf = df.selectExpr(newfieldNames:_*)
          return flattenRecursive(explodedDf)
        case structType: StructType =>
          val newfieldNames = fieldNames.filter(_!= fieldName) ++ 
          										structType.fieldNames.map(childname => fieldName.concat(".").concat(childname)
          																																		.concat(" as ")
          																																		.concat(fieldName).concat("_").concat(childname))
         	val explodedf = df.selectExpr(newfieldNames:_*)
          return flattenRecursive(explodedf)
        case _ =>
      }
    }
`

Exception raised 
Exception message:Ambiguous reference to fields StructField(eComStringAttributeValuePairList,StringType,true), StructField(ecomStringAttributeValuePairList,ArrayType(StringType,true),true); line 1 pos 0
org.apache.spark.sql.AnalysisException: Ambiguous reference to fields StructField(eComStringAttributeValuePairList,StringType,true), StructField(ecomStringAttributeValuePairList,ArrayType(StringType,true),true); line 1 pos 0
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.findField(complexTypeExtractors.scala:88)
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:53)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq$$anonfun$7.apply(package.scala:244)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq$$anonfun$7.apply(package.scala:243)

**Comment by mksuren** [comment]
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<supplierDataNotificationMessage >
	<supplierDataNotification>
		<creationDateTime>2008-11-15T22:22:58</creationDateTime>
		<documentStatusCode>ORIGINAL</documentStatusCode>
		<documentActionCode>ADD</documentActionCode>
		<lastUpdateDateTime>2002-11-05T13:31:03+05:30</lastUpdateDateTime>
		<revisionNumber>201</revisionNumber>
		<documentEffectiveDate>
			<date>2002-06-24+05:30</date>
			<time>20:26:29+05:30</time>
		</documentEffectiveDate>
		<avpList>
			<eComStringAttributeValuePairList attributeName="family">LEAD</eComStringAttributeValuePairList>
		</avpList>
		<supplierDataNotificationIdentification>
			<entityIdentification>supplier</entityIdentification>
		</supplierDataNotificationIdentification>
		<supplier>
			<avpList>
				<eComStringAttributeValuePairList attributeName="supStatus">A</eComStringAttributeValuePairList>
				<ecomStringAttributeValuePairList attributeName="shipMethod">SM</ecomStringAttributeValuePairList>
				<ecomStringAttributeValuePairList attributeName="paymentMethod">WT</ecomStringAttributeValuePairList>
			</avpList>
		</supplier>
	</supplierDataNotification>
</supplierDataNotificationMessage>`

**Comment by srowen** [comment]
Sorry no I mean what is the Spark schema you use to parse this? I think the schema is wrong. Not XML schema.

**Comment by mksuren** [comment]
`root
 |-- supplierDataNotification: struct (nullable = true)
 |    |-- creationDateTime: timestamp (nullable = true)
 |    |-- documentActionCode: string (nullable = true)
 |    |-- documentEffectiveDate: struct (nullable = true)
 |    |    |-- date: date (nullable = true)
 |    |    |-- time: string (nullable = true)
 |    |-- documentStatusCode: string (nullable = true)
 |    |-- lastUpdateDateTime: timestamp (nullable = true)
 |    |-- revisionNumber: long (nullable = true)
 |    |-- supplier: struct (nullable = true)
 |    |    |-- avpList: struct (nullable = true)
 |    |    |    |-- eComStringAttributeValuePairList: string (nullable = true)
 |    |    |    |-- ecomStringAttributeValuePairList: array (nullable = true)
 |    |    |    |    |-- element: string (containsNull = true)
 |    |-- supplierDataNotificationIdentification: struct (nullable = true)
 |    |    |-- entityIdentification: string (nullable = true)`

**Comment by mksuren** [comment]
root
 |-- supplierDataNotification: struct (nullable = true)
 |    |-- creationDateTime: timestamp (nullable = true)
 |    |-- documentActionCode: string (nullable = true)
 |    |-- documentEffectiveDate: struct (nullable = true)
 |    |    |-- date: date (nullable = true)
 |    |    |-- time: string (nullable = true)
 |    |-- documentStatusCode: string (nullable = true)
 |    |-- lastUpdateDateTime: timestamp (nullable = true)
 |    |-- revisionNumber: long (nullable = true)
 |    |-- supplier: struct (nullable = true)
 |    |    |-- avpList: struct (nullable = true)
 |    |    |    |-- eComStringAttributeValuePairList: string (nullable = true)
 |    |    |    |-- ecomStringAttributeValuePairList: array (nullable = true)
 |    |    |    |    |-- element: string (containsNull = true)
 |    |-- supplierDataNotificationIdentification: struct (nullable = true)
 |    |    |-- entityIdentification: string (nullable = true)

**Comment by mksuren** [comment]
ok Srowen

root
 |-- supplierDataNotification: struct (nullable = true)
 |    |-- creationDateTime: timestamp (nullable = true)
 |    |-- documentActionCode: string (nullable = true)
 |    |-- documentEffectiveDate: struct (nullable = true)
 |    |    |-- date: date (nullable = true)
 |    |    |-- time: string (nullable = true)
 |    |-- documentStatusCode: string (nullable = true)
 |    |-- lastUpdateDateTime: timestamp (nullable = true)
 |    |-- revisionNumber: long (nullable = true)
 |    |-- supplier: struct (nullable = true)
 |    |    |-- avpList: struct (nullable = true)
 |    |    |    |-- eComStringAttributeValuePairList: string (nullable = true)
 |    |    |    |-- ecomStringAttributeValuePairList: array (nullable = true)
 |    |    |    |    |-- element: string (containsNull = true)
 |    |-- supplierDataNotificationIdentification: struct (nullable = true)
 |    |    |-- entityIdentification: string (nullable = true)

**Comment by srowen** [comment]
Oh I see the issue: it's `eComStringAttributeValuePairList` vs `ecomStringAttributeValuePairList` - note the capitalization difference. I think the fields are case insensitive in Spark, but these are being inferred as different fields. Can you fix the XML? that's probably the most robust answer. But there's an open question here whether the schema inference is wrong to be case-sensitive in a case like this - Spark isn't (I think) but XML is, and this is treating XML tags as Spark field names.

**Comment by mksuren** [comment]
Thanks a lot, Srowen for identifying the issue. It helped me to fix the issue.
Correct me if I am wrong, these kinds of silly types can traverse and break the core application code as Spark fields are case sensitive.
Can we have any validator sitting in front to validate the xml based on our custom logic and then allow data to move further down the application. In case Spark provides anythign for that? or if we need to write our own what will be best way.

**Comment by srowen** [comment]
It's the reverse - XML is case sensitive. If two fields differ by case in the user's input, they are not the same field. Is it valid to treat them as the same?

**Comment by mksuren** [comment]
Yes, you are right XML is case sensitive. XML fields will come in the same format. 

Now I am facing another issue, When I am trying to flatten the XML, which contains fields with attributeName, it returns an array.  Due to that, I am not able to fetch the correct value corresponding to the attributeName. 

Sample xml 
` <avpList>
    <eComStringAttributeValuePairList  attributeName=”shipMethod”>SM</eComStringAttributeValuePairList>
  <eComStringAttributeValuePairList  attributeName=”paymentMethod”>WT</eComStringAttributeValuePairList>
  <eComStringAttributeValuePairList  attributeName=”settlementCode”>N</eComStringAttributeValuePairList>
  </avpList>`


I want map type functionality(key-value pair) for attributeName - VALUE. so that I can fetch the value corresponding to attributeName.
like -  
      shipMethod - SM
      paymentMethod - WT
      settlementCode - N 

Schema 

`root
 |-- StandardBusinessDocumentHeader: struct (nullable = true)
 |    |-- BusinessScope: struct (nullable = true)
 |    |    |-- Scope: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- Identifier: string (nullable = true)
 |    |    |    |    |-- Type: string (nullable = true)
 |    |-- DocumentIdentification: struct (nullable = true)
 |    |    |-- CreationDateAndTime: timestamp (nullable = true)
 |    |    |-- InstanceIdentifier: string (nullable = true)
 |    |    |-- Standard: string (nullable = true)
 |    |    |-- Type: string (nullable = true)
 |    |    |-- TypeVersion: double (nullable = true)
 |    |-- HeaderVersion: double (nullable = true)
 |    |-- Receiver: struct (nullable = true)
 |    |    |-- ContactInformation: struct (nullable = true)
 |    |    |    |-- Contact: long (nullable = true)
 |    |    |    |-- EmailAddress: string (nullable = true)
 |    |    |    |-- FaxNumber: long (nullable = true)
 |    |    |    |-- TelephoneNumber: long (nullable = true)
 |    |    |-- Identifier: string (nullable = true)
 |    |-- Sender: struct (nullable = true)
 |    |    |-- ContactInformation: struct (nullable = true)
 |    |    |    |-- Contact: long (nullable = true)
 |    |    |    |-- EmailAddress: string (nullable = true)
 |    |    |    |-- FaxNumber: long (nullable = true)
 |    |    |    |-- TelephoneNumber: long (nullable = true)
 |    |    |-- Identifier: string (nullable = true)
 |-- _stan: string (nullable = true)
 |-- _urn: string (nullable = true)
 |-- supplierDataNotification: struct (nullable = true)
 |    |-- avpList: struct (nullable = true)
 |    |    |-- eComStringAttributeValuePairList: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |    |    |-- _attributeName: string (nullable = true)
 |    |-- creationDateTime: timestamp (nullable = true)
 |    |-- documentActionCode: string (nullable = true)
 |    |-- documentEffectiveDate: struct (nullable = true)
 |    |    |-- date: date (nullable = true)
 |    |    |-- time: string (nullable = true)
 |    |-- documentStatusCode: string (nullable = true)
 |    |-- lastUpdateDateTime: timestamp (nullable = true)
 |    |-- revisionNumber: long (nullable = true)
 |    |-- supplier: struct (nullable = true)
 |    |    |-- address: struct (nullable = true)
 |    |    |    |-- city: string (nullable = true)
 |    |    |    |-- cityCode: long (nullable = true)
 |    |    |    |-- countryCode: long (nullable = true)
 |    |    |    |-- countyCode: long (nullable = true)
 |    |    |    |-- crossStreet: string (nullable = true)
 |    |    |    |-- currencyOfPartyCode: string (nullable = true)
 |    |    |    |-- languageOfThePartyCode: string (nullable = true)
 |    |    |    |-- name: string (nullable = true)
 |    |    |    |-- pOBoxNumber: long (nullable = true)
 |    |    |    |-- postalCode: long (nullable = true)
 |    |    |    |-- provinceCode: long (nullable = true)
 |    |    |    |-- state: string (nullable = true)
 |    |    |    |-- streetAddressOne: string (nullable = true)
 |    |    |    |-- streetAddressTwo: string (nullable = true)
 |    |    |-- avpList: struct (nullable = true)
 |    |    |    |-- eComStringAttributeValuePairList: array (nullable = true)
 |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |    |    |    |-- _attributeName: string (nullable = true)
 |    |    |-- financialInstitutionInformation: struct (nullable = true)
 |    |    |    |-- additionalFinancialInformation: struct (nullable = true)
 |    |    |    |    |-- description: string (nullable = true)
 |    |-- supplierDataNotificationIdentification: struct (nullable = true)
 |    |    |-- entityIdentification: string (nullable = true)`

**Comment by mksuren** [comment]
Yes, you are right XML is case sensitive. XML fields will come in the same format.

Now I am facing another issue, When I am trying to flatten the XML, which contains fields with attributeName, it returns an array. Due to that, I am not able to fetch the correct value corresponding to the attributeName.

Sample xml

`<avpList> <eComStringAttributeValuePairList attributeName=”shipMethod”>SM</eComStringAttributeValuePairList> <eComStringAttributeValuePairList attributeName=”paymentMethod”>WT</eComStringAttributeValuePairList> <eComStringAttributeValuePairList attributeName=”settlementCode”>N</eComStringAttributeValuePairList> </avpList>`

I want map type functionality(key-value pair) for attributeName - VALUE. so that I can fetch the value corresponding to attributeName.
like -
shipMethod - SM
paymentMethod - WT
settlementCode - N

Schema

root
 |-- StandardBusinessDocumentHeader: struct (nullable = true)
 |    |-- BusinessScope: struct (nullable = true)
 |    |    |-- Scope: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- Identifier: string (nullable = true)
 |    |    |    |    |-- Type: string (nullable = true)
 |    |-- DocumentIdentification: struct (nullable = true)
 |    |    |-- CreationDateAndTime: timestamp (nullable = true)
 |    |    |-- InstanceIdentifier: string (nullable = true)
 |    |    |-- Standard: string (nullable = true)
 |    |    |-- Type: string (nullable = true)
 |    |    |-- TypeVersion: double (nullable = true)
 |    |-- HeaderVersion: double (nullable = true)
 |    |-- Receiver: struct (nullable = true)
 |    |    |-- ContactInformation: struct (nullable = true)
 |    |    |    |-- Contact: long (nullable = true)
 |    |    |    |-- EmailAddress: string (nullable = true)
 |    |    |    |-- FaxNumber: long (nullable = true)
 |    |    |    |-- TelephoneNumber: long (nullable = true)
 |    |    |-- Identifier: string (nullable = true)
 |    |-- Sender: struct (nullable = true)
 |    |    |-- ContactInformation: struct (nullable = true)
 |    |    |    |-- Contact: long (nullable = true)
 |    |    |    |-- EmailAddress: string (nullable = true)
 |    |    |    |-- FaxNumber: long (nullable = true)
 |    |    |    |-- TelephoneNumber: long (nullable = true)
 |    |    |-- Identifier: string (nullable = true)
 |-- _stan: string (nullable = true)
 |-- _urn: string (nullable = true)
 |-- supplierDataNotification: struct (nullable = true)
 |    |-- avpList: struct (nullable = true)
 |    |    |-- eComStringAttributeValuePairList: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |    |    |-- _attributeName: string (nullable = true)
 |    |-- creationDateTime: timestamp (nullable = true)
 |    |-- documentActionCode: string (nullable = true)
 |    |-- documentEffectiveDate: struct (nullable = true)
 |    |    |-- date: date (nullable = true)
 |    |    |-- time: string (nullable = true)
 |    |-- documentStatusCode: string (nullable = true)
 |    |-- lastUpdateDateTime: timestamp (nullable = true)
 |    |-- revisionNumber: long (nullable = true)
 |    |-- supplier: struct (nullable = true)
 |    |    |-- address: struct (nullable = true)
 |    |    |    |-- city: string (nullable = true)
 |    |    |    |-- cityCode: long (nullable = true)
 |    |    |    |-- countryCode: long (nullable = true)
 |    |    |    |-- countyCode: long (nullable = true)
 |    |    |    |-- crossStreet: string (nullable = true)
 |    |    |    |-- currencyOfPartyCode: string (nullable = true)
 |    |    |    |-- languageOfThePartyCode: string (nullable = true)
 |    |    |    |-- name: string (nullable = true)
 |    |    |    |-- pOBoxNumber: long (nullable = true)
 |    |    |    |-- postalCode: long (nullable = true)
 |    |    |    |-- provinceCode: long (nullable = true)
 |    |    |    |-- state: string (nullable = true)
 |    |    |    |-- streetAddressOne: string (nullable = true)
 |    |    |    |-- streetAddressTwo: string (nullable = true)
 |    |    |-- avpList: struct (nullable = true)
 |    |    |    |-- eComStringAttributeValuePairList: array (nullable = true)
 |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |-- _VALUE: string (nullable = true)
 |    |    |    |    |    |-- _attributeName: string (nullable = true)
 |    |    |-- financialInstitutionInformation: struct (nullable = true)
 |    |    |    |-- additionalFinancialInformation: struct (nullable = true)
 |    |    |    |    |-- description: string (nullable = true)
 |    |-- supplierDataNotificationIdentification: struct (nullable = true)
 |    |    |-- entityIdentification: string (nullable = true)

**Comment by srowen** [comment]
I'm not sure what you mean - `eComStringAttributeValuePairList` is repeated, so it must be array-valued (an array of structs). You can further manipulate the dataframe however you want, but that's not a function of spark-xml
