### ISSUE TITLE
Typo  in scala doc XmlDataFrameReader and XmlDataFrameWriter classes

### ISSUE THREAD

**Issue by wassimtrifi** [databricks/spark-xml#555]
We need to change  `avro` format by `xml` in both  descriptions of classes _XmlDataFrameWriter_ and  _XmlDataFrameReader_
[Xml](https://github.com/databricks/spark-xml/blob/ccbb866b166ee30e2289cd15126f6be8946ec8b0/src/main/scala/com/databricks/spark/xml/package.scala#L94) object.

```scala 
 /**
   * Adds a method, `xml`, to DataFrameWriter that allows you to write avro files using
   * the DataFileWriter
   */
  implicit class XmlDataFrameWriter[T](writer: DataFrameWriter[T]) {
....
```

```scala
  /**
   * Adds a method, `xml`, to DataFrameReader that allows you to read avro files using
   * the DataFileReader
   */
  implicit class XmlDataFrameReader(reader: DataFrameReader) {
....
```

**Comment by srowen** [comment]
Oops, you can guess where this was copied from years ago. If you want to open a PR, go ahead, otherwise I will tomorrow.
