### ISSUE TITLE
Py4JJavaError: An error occurred while calling o352.load.

### ISSUE THREAD

**Issue by vnteleah** [databricks/spark-xml#572]
I'm having issues when I try to parse books.xml

My tools:
Python 3.6.3
Spark 2.4.3

Setting up spark:
spark = SparkSession\
        .builder\
        .config('com.databricks:spark-xml_2.12:0.14.0')\
        .getOrCreate()

I even tried using:
spark = SparkSession\
        .builder\
        .config('spark.jars.packages')\
        .getOrCreate()

Parsing:
df = spark.read.format('xml')\
                .options(rowTag = 'book')\
                .load('books.xml')

Attached is the error message I receive when I try to parse the book.xml file you provided.

What might be causing this issue?
![issue1](https://user-images.githubusercontent.com/85556933/148554511-ad57d3a7-30f9-4f2e-8396-ff72fcb74f75.JPG)

**Comment by srowen** [comment]
It looks like you have not added the spark-xml library. .config('com.databricks:spark-xml_2.12:0.14.0') is not how you add dependences

**Comment by vnteleah** [comment]
How do I add the spark-xml library to my spark session then?

**Comment by srowen** [comment]
I don't think you can add them after startup. You would need to put it on the path before startup. I'm not sure, does the %configure magic work in Jupyter?  I thnk that might be specific to this Spark distribution: https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-jupyter-notebook-use-external-packages
