### ISSUE TITLE
How to read XSD file into pyspark schema.

### ISSUE THREAD

**Issue by avinashgbhosale** [databricks/spark-xml#575]
I am trying to read XSD file into pyspark schema but not able to achieve. This package does not export the class XSDToSchema

**Comment by srowen** [comment]
It is Scala-only, yes, but you can call simple methods from Python with: https://github.com/databricks/spark-xml#pyspark-notes

**Comment by bama-chi** [comment]
Hello @srowen  could you provide an example for XSDToSchema method in python please ?
