### ISSUE TITLE
NoClassDefFoundError: scala/$less$colon$less

### ISSUE THREAD

**Issue by carlosg-m** [databricks/spark-xml#576]
```
val df = spark.read.format("com.databricks.spark.xml").load("dbfs:/FileStore/example.xml")
# NoClassDefFoundError: scala/$less$colon$less
# Caused by: ClassNotFoundException: scala.$less$colon$less
```
Spark 3.2.1
Scala 2.12

**Comment by srowen** [comment]
You are probably using a Scala 2.11 build of the project. Use _2.12

**Comment by sanyam-dev** [comment]
I'm using java and I face similar issue, what should I do?

**Comment by srowen** [comment]
Same answer. You need to match library scala version to the scala version that your Spark uses.
