### ISSUE TITLE
maxRecordsPerFile

### ISSUE THREAD

**Issue by vstoyanoff** [databricks/spark-xml#584]
Hey there!

Thank you very much for this package! I was wondering if the `maxRecordsPerFile` can be applied or if it is only applicable to the build-in formats?

Thanks!

**Comment by srowen** [comment]
Hm, I haven't tried it, but I imagine it will work. Under the hood it uses code paths very similar to Spark's JSON support.

**Comment by vstoyanoff** [comment]
@srowen thanks for the quick response. I tried using the option but it doesn't work. How would you apply it? Maybe I am adding it wrong.

**Comment by vstoyanoff** [comment]
@srowen I also have a more specific question if you don't mind answering. We are using Glue job to generate sitemaps (XML files) of a large website from our data. Currently, this is achieved by using `.toLocalIterator` and going through the items and writing them. I would imagine that `spark-xml` will do the job faster and more efficiently. Am I right?
Sorry if this question seems noob, but I've been working with Spark for the past month only and don't understand everything. Thanks!

**Comment by srowen** [comment]
Yes, though Spark by nature writes a file per task. You can .repartition(1) just before writing to get 1 file

**Comment by vstoyanoff** [comment]
What if the data is very large? Wouldn't this potentially cause OOM? Also the `maxRecordsPerFile` is not working - for the ones that are looking for this here.

**Comment by srowen** [comment]
No, shouldn't be a memory problem. You may lose parallelism if you do this. Depends on how your job works. You could stitch together N XML files after the fact. Or do sitemaps just let you provide N XML files to begin with?

**Comment by vstoyanoff** [comment]
I actually need to generate several files (that's why I was wondering if `maxRecordsPerFile` will work) since I need to put no more than 8000 records in a file. So I reached out to spark-xml for parallel generation of those files. I found out that `toLocalIterator` slows down the process a lot. The job runs for around 2:30h and from what I saw at least 50% of the time it spends on iterating over the products and writing files.

**Comment by srowen** [comment]
No, don't use toLocalIterator. Use .repartition(N).write.format("xml").save(...)

**Comment by neontty** [comment]
Hi I just wanted to bring up that I would also highly benefit from a maxRecordsPerFile option. Would the fix be to rewrite the output part to inherit from OutputWriter more like json does? https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/json/JsonOutputWriter.scala
