### ISSUE TITLE
Spark-xml How to read repeated sub tags under rowtag

### ISSUE THREAD

**Issue by lanmACode** [databricks/spark-xml#586]
<FILEDS>
	<FILED TYPE="int4(10)" id="1">id</FILED>
	<FILED TYPE="varchar(255)" id="2">name</FILED>
	<FILED TYPE="date(13)" id="3">update_time</FILED>
</FILEDS>

option("rowTag", "FILEDS") How to read label values and attribute values under fileds
Error reporting information：Compiling "GeneratedClass": Two non-abstract methods "public int scala.collection.TraversableOnce.size()" have the same parameter types, declaring type and return type

**Comment by srowen** [comment]
I don't understand what this is asking
