### ISSUE TITLE
How to use XSDToSchema in Python?

### ISSUE THREAD

**Issue by sumitgsh** [databricks/spark-xml#587]
Not able to figure it out how to use it ,Would love to know from u all, as I need to use in my Project to improve the read time from the XML dataset..

**Comment by srowen** [comment]
You can't call it from Python; using py4j might let you call the method but it has JVM objects in the return value, not sure it'd be easy to parse

**Comment by sumitgsh** [comment]
@srowen Thank U for ur help..

**Comment by HyukjinKwon** [comment]
BTW, we're discussing about porting spark-xml into Apache Spark. Once it gets ported, Python API would be available too.
