### ISSUE TITLE
Support for writing DTD/declaration.

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#59]
Currently this library produces indented XML files without DTD/declaration.

Maybe it should write a DTD/declaration as default or support an option to write this.

**Comment by srowen** [comment]
I personally think it's reasonable to consider writing the xml header, as it's kinda required. We can generate a DTD but I'm not sure that is widely used now compared to an XML schema. And an XML schema, not sure how widely used that is either. I'd close this in favor of https://github.com/databricks/spark-xml/issues/278 but if there's a good case for XML schemas this should be reopened.
