### ISSUE TITLE
Write an xml element value with escape characters as it is in the input text

### ISSUE THREAD

**Issue by DipeshV** [databricks/spark-xml#611]
Hello,

I am using this connector to write the data to the xml format as below

<root-tag>
    <row-tag>
             <name>Dipesh Vora
             <text>&#x2022;pim_mandatory_Action_string_mv:Antall stangdeler&#xB6;&#x2022;pim_mandatory</text>
   </row-tag>
</root-tag>

But after the write operation is finished, i get the xml content like below,

<root-tag>
    <row-tag>
             <name>Dipesh Vora
             <text>&amp;#x2022;pim_mandatory_Action_string_mv:Antall stangdeler&amp;#xB6;&amp;#x2022;pim_mandatory</text>
   </row-tag>
</root-tag>

It is replacing & with &amp; as I think is is escaping the '&' char.

Is there any configuration or wprk around available which can help me to write it without escaping the special characters.

**Comment by DipeshV** [comment]
So when the text in xml is something like A & B, it is written as A &amp; B.
I don't need it that way and so it should just write it from dataframe as A & B.

**Comment by srowen** [comment]
But it has to be written this way in XML to be valid XML

**Comment by DipeshV** [comment]
I tried many examples with online validators and it gives me valid xml,

<product Name="&#x2022;pim_mandatory"  countryCode="fi" languageCode="fi-FI"/>

I just need to write the texts strictly in this format only.

Can you please suggest me how to do it ?
