### ISSUE TITLE
Encoding not working with UTF-16/32 (not UTF-16LE/BE or UTF-32LE/BE).

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#62]
Since UTF-16/32 has BOM bytes ahead, BOM bytes should be handled because `XmlRecordReader` reads record between `startTag` and `endTag`, which are also encoded with BOM when the given encoding is UTF-16/32.

So, it ends up with trying to find `startTag` and `endTag` including BOM bytes for every record, which will not find any because DOM bytes only exist in the head of data.

I think I better do not support the, but just mention in documentation maybe.

**Comment by srowen** [comment]
I thought maybe recent changes to reading the XML as chars would resolve it, but it doesn't. A UTF-16 with a BOM still fails if the encoding is specified as UTF-16BE.

**Comment by dmvieira** [comment]
But do you know a workaround?

**Comment by HyukjinKwon** [comment]
It's kind of tricky to fix. It's not currently supported in Apache Spark's JSON datasource as well.

**Comment by lyncher33** [comment]
I can confirm that this is definitely an issue for me which is currently preventing my from using the library at all.  I have a large (>15GB) file that is encoded as UCS-2 LE BOM which my understanding is the same as UTF-16LE.  Regardless, the library will not read the file with this encoding (i.e. option charset='utf-16').  As a workaround I have attempted to re-encode my file to UTF-8 before loading with spark-xml library but it doesn't work either.  The workaround works with smaller files, but not the larger one.  Please advise if this is something easily fixable.  Thanks.
