### ISSUE TITLE
read multiple XML file. and get file name as metadata

### ISSUE THREAD

**Issue by writetoarun** [databricks/spark-xml#628]
I am trying to read multiple XML files into a spark data frame and trying to get the file name of XML into the data frame using the below statement

spark.read.format("com.databricks.spark.xml").option("rowTag","row").load("/raw/Batch/////").select("*", "_metadata")

but get an error _metadata not found

**Comment by srowen** [comment]
I am not sure what you're referring to. What is _metadata?

**Comment by srowen** [comment]
Oh, that might be a property of DSv2 or something, or specific to Databricks. Don't think that exists for this data source
