### ISSUE TITLE
Problem with extra line breaks inside tags during writing XML file

### ISSUE THREAD

**Issue by VladIsLuve** [databricks/spark-xml#656]
Hi. I have a problem with writing XML file. In the resulting file there are some additional line breaks inside tags. They can look like this:
```
        <tag>content</
tag>
```
or like this
```
        <
tag>content</tag>
```
My software info: Spark 2.4.0, spark-xml_2.11-0.5.0

**Comment by srowen** [comment]
That sounds like an issue that was fixed a long time ago - you have a very old version! use 0.16.0
