### ISSUE TITLE
Failed to find data source: xml.

### ISSUE THREAD

**Issue by luisenriqueramos1977** [databricks/spark-xml#661]
In my databrick project, i installed the java file  spark_xml_2_12_0_13_0.jar
and when running the command:

df1=spark.read.format('xml').option('rowTag',tag_to_extract).load(input_xml_file)

I get the error:
org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find data source: xml. Please find packages at `https://spark.apache.org/third-party-projects.html`.

runtime:
11.3

Any recommendation?

Luis Ramos

**Comment by srowen** [comment]
I am not sure what that JAR is, but chances are it's wrong.
You don't install libraries this way in Databricks. Install a "Maven" library and use the coordinates `com.databricks:spark-xml_2.12:0.16.0`

**Comment by luisenriqueramos1977** [comment]
Thanks for your answer.

I instalado the librará you mentioned, and had same issue.

Luis Ramos.

**Comment by srowen** [comment]
It works fine for me on Databricks, I'm not sure what might be different. Check that the library has actually installed in the cluster UI.
