### ISSUE TITLE
Convert xml to dataframe based on pyspark - using rowValidationXSDPath

### ISSUE THREAD

**Issue by yu-tracy** [databricks/spark-xml#669]
Hi,

I want to read [books.xml](https://raw.githubusercontent.com/databricks/spark-xml/master/src/test/resources/books.xml) based on XSD schema, the following shows what I did.

XSD schema
![Screenshot 2023-11-08 at 16 06 39](https://github.com/databricks/spark-xml/assets/100492995/734b0b81-3e77-4234-ac0f-ae85baa97416)

Python code
`spark.read.format("xml").options(rowValidationXSDPath='books_schema.xsd').options(rowTag='catalog').load(books_path).show()`

The result I got is 
![Screenshot 2023-11-08 at 15 59 22](https://github.com/databricks/spark-xml/assets/100492995/235b0732-f944-4b67-9cb7-d24bb87a8e95)

But it is not actually what I want, I expect to get like the following
![Screenshot 2023-11-08 at 16 00 15](https://github.com/databricks/spark-xml/assets/100492995/2d8d93da-1fe0-4460-a027-eec4bd8a927f)

I am not sure if my XSD schema is wrong, could you please help me to check it? Thank you!

And about the field `rowValidationXSDPath`, `README.md` shows `The XSD does not otherwise affect the schema provided, or inferred.` if it means, even though I provide xsd file, paser still infers schema, and xsd is only used for validation? :)

**Comment by srowen** [comment]
Note that the XSD here does not control the schema of the output. It is
only there for validation.

The result is expected as your schema defines a result with multiple cols
so it must be a struct. You can select book.* to pull up all the cols. This
is not related to XML .

**Comment by yu-tracy** [comment]
Thanks for your reply!
I would like my result directly shows multiple cols
![Screenshot 2023-11-09 at 09 51 07](https://github.com/databricks/spark-xml/assets/100492995/e4a73ff6-8f3d-44ff-b5a4-22a589c44b59)
instead of using `select book.*` to pull up all the cols. If that means I should change my XSD schema?

**Comment by srowen** [comment]
The XSD is unrelated to this.
You can set your rowTag to book, is that all you need ?

**Comment by yu-tracy** [comment]
If I let `rowTag` be `book`, I will get `_corrupt_record`. I am confused about it, sorry...
![Screenshot 2023-11-09 at 14 34 14](https://github.com/databricks/spark-xml/assets/100492995/beb7802f-8f79-4a52-9ea2-c9f81357c169)
