### ISSUE TITLE
Remove New Line coming in between records during spark write dataframe to XML

### ISSUE THREAD

**Issue by avinashpandu** [databricks/spark-xml#676]
Hi, 
When writing the following dataframe to XML , I am seeing new blank lines inserting in between the ROWS.
+--------------------+--------------------+--------------+----------+----------+--------------+------+----------+-------------+--------------------+------------------+------------------+
|PORTFOLIO_MANAGER_ID|EFFECTIVE_START_DATE|DATA_SOURCE_ID| LAST_NAME|FIRST_NAME|MIDDLE_INITIAL|SUFFIX|SHORT_NAME|QUALIFICATION|           BIOGRAPHY|SOURCE_SYSTEM_CODE|EFFECTIVE_END_DATE|
+--------------------+--------------------+--------------+----------+----------+--------------+------+----------+-------------+--------------------+------------------+------------------+
|               10247|          2019-09-30|           100| McPherson|   Heather|          null|  null|      null|         null|&nbsp;&nbsp;&nbsp...|           MA_1066|        9999-12-31|
|                4574|          2018-08-31|           100|     Mordy|     James|            N.|  null|      null|         null|~~~~~~~~~~~~~~<di...|             MA_68|        9999-12-31|
|                4249|          2018-08-31|           100|Lakonishok| Dr. Josef|          null|  null|      null|         null|<p>&#9632; <stron...|            MA_209|        9999-12-31|
+--------------------+--------------------+--------------+----------+----------+--------------+------+----------+-------------+--------------------+------------------+------------------+
**XML**

<T_REF_PORTFOLIO_MANAGER_RECS>
    <T_REF_PORTFOLIO_MANAGER>
        <PORTFOLIO_MANAGER_ID>10247</PORTFOLIO_MANAGER_ID>
        <EFFECTIVE_START_DATE>2019-09-30</EFFECTIVE_START_DATE>
        <DATA_SOURCE_ID>100</DATA_SOURCE_ID>
        <LAST_NAME>McPherson</LAST_NAME>
        <FIRST_NAME>Heather</FIRST_NAME>
        <BIOGRAPHY>&amp;nbsp;&amp;nbsp;&amp;nbsp; &lt;p>Heather McPherson joined as co-portfolio manager of the strategy in 2015. Ms. McPherson has been with the firm since 2002 and served as associate portfolio manager for the US Mid-Cap Value Equity Strategy from 2005 through 2014.&lt;/p>&amp;nbsp;&lt;/p></BIOGRAPHY>
        <SOURCE_SYSTEM_CODE>MA_1066</SOURCE_SYSTEM_CODE>
        <EFFECTIVE_END_DATE>9999-12-31</EFFECTIVE_END_DATE>
    </T_REF_PORTFOLIO_MANAGER>

    <T_REF_PORTFOLIO_MANAGER>
        <PORTFOLIO_MANAGER_ID>4574</PORTFOLIO_MANAGER_ID>
        <EFFECTIVE_START_DATE>2018-08-31</EFFECTIVE_START_DATE>
        <DATA_SOURCE_ID>100</DATA_SOURCE_ID>
        <LAST_NAME>Mordy</LAST_NAME>
        <FIRST_NAME>James</FIRST_NAME>
        <MIDDLE_INITIAL>N.</MIDDLE_INITIAL>
        <BIOGRAPHY>~~~~~~~~~~~~~~&lt;div>~~&lt;p>&amp;#9632;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; &lt;b>James~N. Mordy&lt;/b>is a Senior Managing Director and portfolio manager at~Wellington Management. �Mr. Mordy received a B.A. from Stanford University and~an M.B.A. from the Wharton School of The University of Pennsylvania.&lt;/p>~~&lt;/div>~~&lt;/body>~~&lt;/html>~</BIOGRAPHY>
        <SOURCE_SYSTEM_CODE>MA_68</SOURCE_SYSTEM_CODE>
        <EFFECTIVE_END_DATE>9999-12-31</EFFECTIVE_END_DATE>
    </T_REF_PORTFOLIO_MANAGER>

    <T_REF_PORTFOLIO_MANAGER>
        <PORTFOLIO_MANAGER_ID>4249</PORTFOLIO_MANAGER_ID>
        <EFFECTIVE_START_DATE>2018-08-31</EFFECTIVE_START_DATE>
        <DATA_SOURCE_ID>100</DATA_SOURCE_ID>
        <LAST_NAME>Lakonishok</LAST_NAME>
        <FIRST_NAME>Dr. Josef</FIRST_NAME>
        <BIOGRAPHY>&lt;p>&amp;#9632; &lt;strong>Dr. Josef Lakonishok&lt;/strong>, is chief executive officer and founding partner of LSV Asset Management and Portfolio Manager&lt;/p>&lt;p>for the Fund. He received a B.A. in Economics and Statistics from Tel Aviv University in 1970 and an M.B.A. from Tel Aviv&lt;/p>&lt;p>University in 1972. Dr. Lakonishok earned a PhD in Business Administration in 1976 from Cornell University.&lt;/p></BIOGRAPHY>
        <SOURCE_SYSTEM_CODE>MA_209</SOURCE_SYSTEM_CODE>
        <EFFECTIVE_END_DATE>9999-12-31</EFFECTIVE_END_DATE>
    </T_REF_PORTFOLIO_MANAGER>

</T_REF_PORTFOLIO_MANAGER_RECS>

**Issue1 **

Blank Empty Line created between Row Tags- 
    </T_REF_PORTFOLIO_MANAGER>

    <T_REF_PORTFOLIO_MANAGER>

**Issue 2**
< is getting converted to &lt ;
& is getting converted to &amp ;
But, XML Writer is not converting > to "&gt"; ( please refer the BIOGRAPHY tag )

Can you please help me understand this? Thank you!

**Comment by srowen** [comment]
I don't think either of those are problems. An extra newline has no meaning between tags, and, you don't need to escape close tags as they are not opened.

Both of these behaviors are not from this library, but from the standard javax.xml.stream writer.

This library is not maintained anymore either, being part of Spark now.

**Comment by avinashpandu** [comment]
Thank you. Regarding Issue 2, there is an open < tag and it got converted to &lt ; 
the same is not happening for >.
why is that ?

**Comment by srowen** [comment]
I presume because there is no need to escape a close tag if there is no open tag. You can see the code in StaxXmlGenerator that just uses the JDK's XML writer to do all this, so this is behavior of the standard library, I assume. https://github.com/databricks/spark-xml/blob/3b40ef48bce114fa9f1f4d96ae500d74dac0ea91/src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala#L22

What is the issue?

**Comment by avinashpandu** [comment]
I understand your comment Sean. Thank you!

But the string is as follows :
<p>Gregory<div><p></p
This converting to:
&lt ;p>Gregory&lt :div>&lt ;p>&lt; /p


I need all the > to be escaped during XML Write.

**Comment by srowen** [comment]
Why?
But, again: this would be behavior of the standard JDK writer. I don't know if it's controllable.
If it is, you'd have to open a PR against Spark, not this library.
But I don't know if there is a reason to do this.
