### ISSUE TITLE
Getting Multi Generator issue while flattening the XML file

### ISSUE THREAD

**Issue by a-sameer18** [databricks/spark-xml#682]
Hi,
I am getting Multi Generator issue while flattening the XML file using PySpark(Python).

XML is having 2 Arrays at same level.

XML: Test9.txt
Code: Spark-xml_Flatten.text
  
Please help.
Thanks,
Sam
[Test9.txt](https://github.com/databricks/spark-xml/files/15112327/Test9.txt)
[Spark-xml_Flatten.txt](https://github.com/databricks/spark-xml/files/15112328/Spark-xml_Flatten.txt)

**Comment by srowen** [comment]
I'm not sure what you're reporting, but multiple arrays are fine. You can't explode on two array cols though. This has nothing to do with spark-xml though.
