### ISSUE TITLE
Value field appears null inside the tag

### ISSUE THREAD

**Issue by anilkulkarni87** [databricks/spark-xml#691]
**XML**

```
<custom-fields>
<custom-field field-id="description" xml:lang="en-US">This is nice to have</custom-field>
            <custom-field field-id="category" xml:lang="en-US">
                <value>Fun</value>
            </custom-field>
<custom-fields>
```

**Databricks spark code:**

```
# Define the file path
xml_file_path = "filepath/custom_fields.xml"

# Load XML into a DataFrame
df = spark.read.format("xml").option("rowTag", "custom-field").option("rootTag", "custom-fields").option("valueTag", "child_name").load(xml_file_path)

# Show the schema to inspect the structure
df.printSchema()

display(df)
```

**Result:**
![image](https://github.com/user-attachments/assets/eb3bb542-abe9-493f-93a1-7eecfad65571)

**Issue:**
The value "This is nice to have" is not showing up.

**Comment by srowen** [comment]
That doesn't look like the output from the example XML (where does "Coats and Jackets" come from?) Do you have the actual example?

I don't think this can really work though as the resulting column can't be both string and struct. Some kind of 'union' struct is conceivable but not going to happen. This isn't really 'tabular' XML

**Comment by anilkulkarni87** [comment]
@srowen  Update the value of Fun in my example with "Coats and Jackets".
Failed to take an updated screenshot. 

```
<custom-fields>
<custom-field field-id="description" xml:lang="en-US">This is nice to have</custom-field>
            <custom-field field-id="category" xml:lang="en-US">
                <value>Coats and Jackets</value>
            </custom-field>
<custom-fields>
```

**Comment by anilkulkarni87** [comment]
When I use the below xml:

```
<custom-fields>
<custom-field field-id="description" xml:lang="en-US">This is nice to have</custom-field>
<custom-fields>
```

```
# Define the file path
xml_file_path = "filepath/file.xml"

# Load XML into a DataFrame
df = spark.read.format("xml").option("rowTag", "custom-field").option("rootTag", "custom-fields").load(xml_file_path)

# Show the schema to inspect the structure
df.printSchema()

display(df)
```


Result:
![image](https://github.com/user-attachments/assets/a07a346b-c309-4ea7-a037-19c5fa89425c)

**Comment by srowen** [comment]
The first example is not going to be supported - it doesn't quite make sense that two rows have different schemas, in a table.
The second example is "as intended" in that there are no child elements in the rowTag (though attributes map to columns) so no additional columns. There's a long story in a previous issue about why this kind of makes more sense than adding a _value column, which is what you get in some other cases where such an element is a child of the rowTag.

At this point, not going to change behavior in the library, as it's moved to Spark anyway.
