### ISSUE TITLE
Dynamic update of XML files into folder when I read xmls files by batch with 'com.databricks.spark.xml' format

### ISSUE THREAD

**Issue by cporrasn** [databricks/spark-xml#693]
Hello! I have questions about reading Xmls using the function:

df = sql_context.read \
.format('com.databricks.spark.xml') \
.option("rowTag", rowTag) \
.option("charset", encoding) \
.load(path)

The path corresponds to a folder, where the read incorporates all the data loaded in batches into the df.

However, if after performing this reading, another file is added or deleted in that path, I have noticed that the data in the df is updated, and even the list of files obtained using the command: df.withColumn("source_file", input_file_name()).select("source_file").distinct().rdd.map(lambda row: row.source_file).collect(), is also updated.

This doesn't happen if I read csv files, which I imagine is because I'm using the com.databricks.spark.xml module for the xml, and the csv is different.

So I think that until the spark job finishes completely, any update in the path folder will affect the dfs that I have as temporary views.

I'm using spark 3.4.1.

I would need to please know if there is a way to stop this behavior to have more control over the data that I'm actually reading and processing.

Thank you very much

**Comment by srowen** [comment]
The result is not defined in this case. You do not want to add data to the path you are reading; this has always been true in Spark for this reason.
Do you just want to cache() the result once after readig and materialize it? 
But the real answer is: do not do this.

**Comment by cporrasn** [comment]
I would like to know if I understood correctly.
What you mean is that in a spark context, from the time of load() to the time of write() in delta for example, there should not be an update of files in the folder?

I have tested and the following happens, if from the load to the write, there are changes in the source files, when I do the write to delta, the delta tables are saved with the last file update that was done, which for now is correct.

However, if after that, I want to know which files were actually processed, I get the files with the code that I showed you above, but when I do a collect, if the files folder is updated again, then that collect gives me the last update that does not necessarily correspond to what was saved in delta.

So my question is if there is any way to avoid this problem, even if it is not with spark itself, but something else.

Thank you very much for your answer!

**Comment by srowen** [comment]
No, I'm saying you should never plan to change the files you are reading. They are assumed to be immutable. Behavior becomes undefined if not (what if part? all? of the RDD needs to be recreated? what state is your data in?)

If you are trying to process a dir of files that updates, you need Spark Streaming, and this is the wrong setup.
