### ISSUE TITLE
Classes probably shouldn't be in org.apache.spark.* and org.apache.hadoop.* namespaces

### ISSUE THREAD

**Issue by rxin** [databricks/spark-xml#7]
If this is library going to exist as a package outside of Spark then its classes should probably not be under the org.apache.spark and org.apache.hadoop namespaces. Making these changes would make it easier to spot where this library depends on internal Spark + Hadoop functionality.

Link from https://github.com/HyukjinKwon/spark-xml/issues/4

**Comment by JoshRosen** [comment]
Fixed in #9.
