### ISSUE TITLE
Reading XML files should remove tags

### ISSUE THREAD

**Issue by Tooa** [databricks/spark-xml#71]
Hi, 
this library fits perfectly to my need of parsing pseudo Wikipedia dumps. However, I have a small problem and I'm not sure, if this is actually an issue. Consider the following input format:
```
<documents>
    <article title="A">
        Multiline text
    </article>
    <article title="B">
        ... 
    </article>
    ...
</documents>
``` 

The code to parse such an input file looks like this (according to your example):
```
val input = {
      sc.hadoopConfiguration.set(XmlInputFormat.START_TAG_KEY, "<article>")
      sc.hadoopConfiguration.set(XmlInputFormat.END_TAG_KEY, "</article>")
      sc.hadoopConfiguration.set(XmlInputFormat.ENCODING_KEY, "utf-8")
      val records = sc.newAPIHadoopFile(config.inFile, classOf[XmlInputFormat],classOf[LongWritable],classOf[Text])
      records
    }
input.saveAsTextFile(config.outFile)
```

However, the output still contains the xml tags:

```
(283,<article title="A">
Multiline text
</article>)
```

Is this a feature or an issue? In my case, I don't need these tags. 

Best Uli

**Comment by HyukjinKwon** [comment]
@Tooa Thanks for having interests into this.
How about trying [XmlInpuFormat](https://github.com/apache/mahout/blob/ad84344e4055b1e6adff5779339a33fa29e1265d/examples/src/main/java/org/apache/mahout/classifier/bayes/XmlInputFormat.java) at Mahout?

This XmlInputFormat is basically and initially copied from that and I modified to adapt to Spark datasource.

If you are planing to use this for DataFrame, then I recommand to just perform a filter after loading but if you arw hitting a case just to use XmlInputFormat, you might better use that in Mahout. Although that does not support to read compressed files and different encodings, it looks that more fits to you needs.

**Comment by HyukjinKwon** [comment]
I re-read and tought another possible case. If you meant reading a XML files that includes attributes but you want to exclude attributes, then yoy might want to try to load the XML with the `excludeAttributes' option to read it without attributes and try to save that. This library does not support to filter at input format level.

**Comment by Tooa** [comment]
Hi,
thanks for you quick reply. I would like to have the output like: `(283,Multiline text)`

Copied the the [Mahout](https://github.com/apache/mahout/blob/ad84344e4055b1e6adff5779339a33fa29e1265d/examples/src/main/java/org/apache/mahout/classifier/bayes/XmlInputFormat.java)  `XmlInputFormat` to my project and tried it:

```
import org.apache.hadoop.io.Text
import org.apache.hadoop.io.LongWritable
import org.apache.hadoop.conf.Configuration
import scala_utilities.XmlInputFormat;
val hadoopConf = new Configuration()
      conf.set(XmlInputFormat.START_TAG_KEY, "<article>")
      conf.set(XmlInputFormat.END_TAG_KEY, "</article>") 
      val records = sc.newAPIHadoopFile(config.inFile, classOf[XmlInputFormat], classOf[LongWritable], classOf[Text], hadoopConf)
```
```
error: inferred type arguments [org.apache.hadoop.io.LongWritable,org.apache.hadoop.io.Text,scala_utilities.XmlInputFormat] do not conform to method newAPIHadoopFile's type parameter bounds [K,V,F <: org.apache.hadoop.mapreduce.InputFormat[K,V]]
[ERROR]       val records = sc.newAPIHadoopFile(config.inFile, classOf[XmlInputFormat], classOf[LongWritable], classOf[Text], hadoopCo
```

Any ideas?

**Comment by HyukjinKwon** [comment]
Oh, I hit the similar issue before. Maybe this is because of `newAPIHadoopFile`. The Mahout's inputformat is the old Hadoop API as far as I remember. 

Can you try this with `hadoopFile` one Hadoop old API?

**Comment by Tooa** [comment]
Yes your are right. This way it works:

```
val hadoopConf = new JobConf()
hadoopConf.set("mapreduce.input.fileinputformat.inputdir", config.inFile)
hadoopConf.set(XmlInputFormatNew.START_TAG_KEY, "<article>")
hadoopConf.set(XmlInputFormatNew.END_TAG_KEY, "</article>") 
val records = sc.hadoopRDD(hadoopConf, classOf[XmlInputFormat], classOf[LongWritable], classOf[Text])
```

The reader seems to work only without XML attributes. So, the input format needs to look like this `<article> ... </article>`. However, the output still looks like `(256,<article> ... </article>`. I just need the text within these text. If you remove `buffer.write(startTag);` you can remove the start tag. Need to figure out, how to remove the endTag. 

BTW, there is also a modified version written from the authors of [Advanced Analytics with Spark: Patterns for Learning from Data at Scale](https://github.com/sryza/aas/blob/master/common/src/main/java/com/cloudera/datascience/common/XmlInputFormat.java). Working example:

```
@transient val hadoopConf = new Configuration()
hadoopConf.set(XmlInputFormatNew.START_TAG_KEY, "<article>")
hadoopConf.set(XmlInputFormatNew.END_TAG_KEY, "</article>") 
      
val records = sc.newAPIHadoopFile(config.inFile, classOf[XmlInputFormat], classOf[LongWritable], classOf[Text], hadoopConf)```

**Comment by HyukjinKwon** [comment]
I am going to close this. Please feel free to reopen if you think it is not solved.
