### ISSUE TITLE
Slow performance for reading XML due to the XML library and not optimized logics.

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#84]
Sameer Farooqui said:

> I'm reading the wikipedia file like this:
> 
> ```scala
> val wiki001DF = sqlContext.read
>     .format("com.databricks.spark.xml")
>     .option("rowTag", "page")
>     .load("/mnt/wikipedia-readonly/en_wikipedia/enwiki-20160204-pages-articles-multistream.xml")
> ```
> 
> When reading the 54 GB XML file, I noticed that on a Spark cluster with 15 Executors (4 cores on each), it took 40 minutes to read the file (about 839 tasks). Each task is running for about 2 minutes. I found that very slow/long.
> 
> I then took some thread dumps on the Executors and noticed that a lot of time is being spent in the xerces XML parsing library:
> 
> ```
> com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanName(XMLEntityScanner.java:716)
> com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(XMLDocumentFragmentScannerImpl.java:1844)
> com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3067)
> com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
> com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerlmpl.java:117)
> com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:558)
> com.sun.xml.internal.stream.XMLEventReaderImpl.peek(XMLEventReaderImpl.java:276)
> com.databricks.spark.xml.parsers.StaxXmlParserUtils$.readDataFully(StaxXmlParserUtils.scala:29)
> ```

Although this issue sounds a bit broad, I think I should create this as a remainder. It looks there are two things to deal with.

- Better XML library.
- Optimization for parsing logic.

**Comment by HyukjinKwon** [comment]
Let me close this for now because as I said it is a bit broad and also the PR I submitted for this was pretty much successful in terms of performance improvement.

**Comment by Green-Angry-Bird** [comment]
I'm wondering if anyone else is experiencing issues with smaller files... I have a file that is 660 bytes which is taking about a minute to parse (worst-case). Server is not loaded and is only processing about 5 in parallel.
