### ISSUE TITLE
Can't collect DataFrame with empty fields read with specified schema

### ISSUE THREAD

**Issue by larsbkrogvig** [databricks/spark-xml#94]
I am having problems working with a DataFrame I loaded with a specified schema. 

The problem looks related to the fix for #80, and could be the same as #93 as it produces the same error in some cases. (I think it is [this one](https://issues.apache.org/jira/browse/SPARK-12624))

For the record I am using `pyspark`.

### Short version
I can't `collect()` a certain DataFrame with missing values in it that I have read with a specified schema, and i get `ArrayIndexOutOfBoundsException` when trying to do certain operations with it.

### Very long version
I have two files, File1 and File2:
File1
```
<row>
    <a>A</a>
    <b>
        <c>C</c>
    </b>
</row>
```
File2
```
<row>
    <a>A</a>
    <b>
    </b>
</row>
```
When I infer schemas from the two files separately I get this:
File1
```
root
 |-- a: string (nullable = true)
 |-- b: struct (nullable = true)
 |    |-- c: string (nullable = true)
```
and File2
```
root
 |-- a: string (nullable = true)
 |-- b: string (nullable = true)
```
As expected `b` is a `struct` in File1 and a `string` in File2. When I infer the schema from both files at the same time I get this schema:
```
root
 |-- a: string (nullable = true)
 |-- b: struct (nullable = true)
 |    |-- #VALUE: string (nullable = true)
 |    |-- c: string (nullable = true)
```
At first I was surprised to see the `#VALUE` field in `b`. After thinking about it I think it makes sense, since `b` is a `string` in File2 and if a string value exists there it must go somewhere. However, I'm not interested in the `#VALUE` field and I want to use the schema from File1 on both files. 

**This is where the problems start**

I save the first schema and specify it when reading both files again to a DataFrame `df`. I use `treatEmptyValuesAsNulls=True` and expect `c` to be `null` in the row from File2. When I try to use `df` I get errors.
The schema looks correct:
```
root
 |-- a: string (nullable = true)
 |-- b: struct (nullable = true)
 |    |-- c: string (nullable = true)
```
And I can have a look at the contents with `df.show()`:
```
+---+---+
|  a|  b|
+---+---+
|  A|[C]|
|  A| []|
+---+---+
```
This looks ok, but i would expect to see `[null]` and not `[]` in the second row. I think that is the cause of the following problem: Running `df.collect()` yields the nasty error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../spark/python/pyspark/sql/dataframe.py", line 281, in collect
    return list(_load_from_socket(port, BatchedSerializer(PickleSerializer())))
  File ".../spark/python/pyspark/rdd.py", line 142, in _load_from_socket
    for item in serializer.load_stream(rf):
  File ".../spark/python/pyspark/serializers.py", line 139, in load_stream
    yield self._read_with_length(stream)
  File ".../spark/python/pyspark/serializers.py", line 164, in _read_with_length
    return self.loads(obj)
  File ".../spark/python/pyspark/serializers.py", line 422, in loads
    return pickle.loads(obj)
  File ".../spark/python/pyspark/sql/types.py", line 1159, in <lambda>
    return lambda *a: dataType.fromInternal(a)
  File ".../spark/python/pyspark/sql/types.py", line 568, in fromInternal
    return _create_row(self.names, values)
  File ".../spark/python/pyspark/sql/types.py", line 1163, in _create_row
    row = Row(*values)
  File ".../spark/python/pyspark/sql/types.py", line 1210, in __new__
    raise ValueError("No args or kwargs")
ValueError: (ValueError('No args or kwargs',), <function <lambda> at 0x10670ab18>, ())
```
When I for example try `df.groupBy('b').count().show()` i get this:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.genericGet(rows.scala:227)
```

I think the problem is that the parser can't see that `c` is empty when `b` is empty.

For now I think I can work around this issue by using `#VALUE` in my schema.

**Comment by HyukjinKwon** [comment]
@larsbkrogvig Thanks! I will look into this as well.

**Comment by HyukjinKwon** [comment]
@larsbkrogvig Yes, you were right. I believe the PR I just submitted will fix this issue as well.

**Comment by larsbkrogvig** [comment]
@HyukjinKwon I merged the PR locally and it solved my problem. Thanks!

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/spark-xml/pull/95.
