### ISSUE TITLE
Duplicate "value" fields

### ISSUE THREAD

**Issue by PatrikTrestik** [databricks/spark-xml#98]
Inferred schema contains duplicate "#VALUE" fields. 
Test XML structure:
`<root><a attr="abc">123</a></root>`
`<root><a >456</a></root>`
`<root><a >789</a></root>`
`<root><a >900</a></root>`

Produced schema:
`root`
` |-- a: struct (nullable = true)`
` |    |-- #VALUE: long (nullable = true)`
` |    |-- #VALUE: long (nullable = true)`
` |    |-- #VALUE: long (nullable = true)`
` |    |-- #VALUE: long (nullable = true)`
` |    |-- @attr: string (nullable = true)`

I found out that it is caused by InferSchema, compatibleType(StructType, DataType) code which is not reducing by field name.
I managed to fix it, but because I'm lame in scala and spark I'm not committing it. Please review.

Here is my code fragment:

        case (StructType(fields), dt: DataType) =>
          val safeFields = (fields :+ StructField(options.valueTag, dt, nullable = true)).groupBy(field => field.name).map {
            case (name, fieldTypes) =>
              val dataType = fieldTypes.view.map(_.dataType).reduce(compatibleType(options))
              StructField(name, dataType, nullable = true)
          }
          StructType(safeFields.toSeq.sortBy(_.name))
          

        case (dt: DataType, StructType(fields)) =>
          val safeFields = (fields :+ StructField(options.valueTag, dt, nullable = true)).groupBy(field => field.name).map {
            case (name, fieldTypes) =>
              val dataType = fieldTypes.view.map(_.dataType).reduce(compatibleType(options))
              StructField(name, dataType, nullable = true)
          }
          StructType(safeFields.toSeq.sortBy(_.name))

**Comment by HyukjinKwon** [comment]
Oh yes I realised this problem during fixing another bug. This PR https://github.com/databricks/spark-xml/pull/96 should fix this problem.

**Comment by HyukjinKwon** [comment]
This must be fixed in #96. @PatrikTrestik Would you maybe confirm if this is fixed?

**Comment by PatrikTrestik** [comment]
I'll confirm the fix on Monday when I'm back at PC.


Dne 8. března 2016 5:03:39 AM Hyukjin Kwon <notifications@github.com> napsal:

**Comment by HyukjinKwon** [comment]
@PatrikTrestik Thanks! Please reopen if this is still happening.
